#!/usr/bin/env python3
"""
R3, step 7 (Д.R3.7, the user 8.10, (а)): the currency of a formed country -- an event with a choice.

A country forms (on_country_formed: the same country, a new tag). If it has a CB and a currency law, and a currency
law lists the new tag in its can_enact (GER -> mark, ITA -> lira, CAN -> the Canadian dollar) and is not in force, the
event ld_currency_formed.1 offers it: introduce the historical currency (a reform) or keep the old one.

The reform (zz_ef_cf_reform, root = the reforming country, var:zz_ef_cf_target = flag:<new>):
  * the parity: E&F's introduction_of_<new> (09_introduction_building_lvl.txt) -- the middle of its range for the
    country's standard (silver / gold); another standard -- the parity stays;
  * the old currency held by the CBs (stockpiling_<old>_state_1 of every state) -> the new one, at the old parity /
    the new (the metal value kept) -- only if no other country issues the old one any more;
  * the law of the new currency (its on_activate sets var:zz_ef_cur), then the parity.
Our accounts are in the engine's money (Д.1) and do not change; the CB table's last-week stocks (zz_ef_cbfx_p_<cur>)
are not moved -- that week's change of the two currencies shows the reform.

Generated (fork «E&F: Ledgerdemain», via ld_gen, by entry keys):
  common/scripted_effects/ld_currency_formed.txt -- zz_ef_cf_find, zz_ef_cf_parity, zz_ef_cf_take_old, zz_ef_cf_put_new,
      zz_ef_cf_activate
  common/customizable_localization/ld_currency_formed_loc.txt -- zz_ef_cf_target_name
Handwritten: zz_ef_cf_reform (the same file), the event (events/ld_currency_formed_events.txt), its localization,
the call (on_actions/ld_new_country_immediate_init.txt).
Reads the fork's common/laws/01_ef_currency_type.txt and common/scripted_effects/09_introduction_building_lvl.txt.

Usage:
    python3 tools/regen_ef_currency_formed.py [--check]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_curdata  # noqa: E402
import ld_gen  # noqa: E402

INTRO = os.path.join(ld_gen.FORK, "common", "scripted_effects", "09_introduction_building_lvl.txt")
OUT_FX = "common/scripted_effects/zz_ef_currency_formed.txt"
OUT_LOC = "common/customizable_localization/zz_ef_currency_formed_loc.txt"

HEAD = ("# GENERATED by tools/regen_ef_currency_formed.py -- do not edit by hand (except zz_ef_cf_reform).\n"
        "# (Д.R3.7) the currency of a formed country -- see the generator's docstring.\n")


def laws():
    """[(cur, [tags], enabled)] in the file's order."""
    out = []
    for cur, body in ld_curdata.laws():
        ce = re.search(r"can_enact = \{(.*?)\n    \}", body, re.S)
        tags = re.findall(r"c:(\w+) \?= this", ce.group(1)) if ce else []
        out.append((cur, tags, "always = no" not in body))
    return out


def block_end(lines, i):
    depth, started = 0, False
    for j in range(i, len(lines)):
        for ch in lines[j].split("#", 1)[0]:
            if ch == "{":
                depth += 1
                started = True
            elif ch == "}":
                depth -= 1
        if started and depth == 0:
            return j
    raise ValueError(i)


def parities():
    """{cur: {"silver": x, "gold": y}} -- the middle of E&F's money_value_target_1 range per standard."""
    lines = open(INTRO, encoding="utf-8-sig").read().split("\n")
    out = {}
    for i, l in enumerate(lines):
        m = re.match(r"^introduction_of_(\w+) = \{", l)
        if not m:
            continue
        std, got = None, {}
        for j in range(i, block_end(lines, i) + 1):
            s = lines[j].split("#", 1)[0]
            ms = re.search(r"activate_law = law_type:law_(gold|silver)_standard", s)
            if ms:
                std = ms.group(1)
            if "name = money_value_target_1" in s and std and std not in got:
                v = lines[j + 1].split("#", 1)[0]
                mv = re.search(r"value = \{\s*([0-9.]+)\s+([0-9.]+)\s*\}", v) or re.search(r"value = ([0-9.]+)", v)
                if mv:
                    nums = [float(x) for x in mv.groups()]
                    got[std] = round(sum(nums) / len(nums), 4)
        out[m.group(1)] = got
    return out


def num(x):
    return ("%g" % x)


def effects(lw, par):
    out = [HEAD]
    targets = [(c, t) for c, t, en in lw if en and t]
    out.append("# Country scope (the formed country): var:zz_ef_cf_target = flag:<cur> -- the enabled currency law that lists\n"
               "# this tag and is not in force; no such law -- no variable.\n"
               "zz_ef_cf_find = {\n"
               "\tif = { limit = { has_variable = zz_ef_cf_target } remove_variable = zz_ef_cf_target }\n")
    for i, (c, tags) in enumerate(targets):
        kw = "if" if i == 0 else "else_if"
        tg = " ".join(f"c:{t} ?= this" for t in tags)
        out.append(f"\t{kw} = {{ limit = {{ OR = {{ {tg} }} NOT = {{ has_law = law_type:law_{c}_currency }} }} "
                   f"set_variable = {{ name = zz_ef_cf_target value = flag:{c} }} }}\n")
    out.append("}\n")
    out.append("# The new parity (var:zz_ef_cf_par_new, set to the old one before): E&F's introduction range, its middle, for\n"
               "# the country's standard.\n"
               "zz_ef_cf_parity = {\n")
    first = True
    for c, tags in targets:
        p = par.get(c, {})
        br = []
        if "silver" in p:
            br.append(f"if = {{ limit = {{ has_law = law_type:law_silver_standard }} set_variable = {{ name = zz_ef_cf_par_new value = {num(p['silver'])} }} }}")
        if "gold" in p:
            kw = "else_if" if br else "if"
            br.append(f"{kw} = {{ limit = {{ OR = {{ has_law = law_type:law_gold_standard has_law = law_type:law_gold_exchange_standard }} }} "
                      f"set_variable = {{ name = zz_ef_cf_par_new value = {num(p['gold'])} }} }}")
        if not br:
            continue
        kw = "if" if first else "else_if"
        first = False
        out.append(f"\t{kw} = {{ limit = {{ var:zz_ef_cf_target = flag:{c} }} {' '.join(br)} }}\n")
    out.append("}\n")
    allc = [c for c, t, en in lw]
    out.append("# Root = the reforming country (scope:zz_cf_issuer), still on its old law: the old currency held in every state\n"
               "# -> var:zz_ef_cf_units of the state, in new units (x var:zz_ef_cf_ratio = the old parity / the new); the stock\n"
               "# to 0. Not when another country issues the old currency too.\n"
               "zz_ef_cf_take_old = {\n")
    for i, c in enumerate(allc):
        kw = "if" if i == 0 else "else_if"
        out.append(f"\t{kw} = {{ limit = {{ has_law = law_type:law_{c}_currency NOT = {{ any_country = {{ NOT = {{ this = scope:zz_cf_issuer }} "
                   f"has_law = law_type:law_{c}_currency }} }} }} every_country = {{ every_scope_state = {{ limit = {{ has_variable = stockpiling_{c}_state_1 }} "
                   f"set_variable = {{ name = zz_ef_cf_units value = {{ value = var:stockpiling_{c}_state_1 multiply = scope:zz_cf_issuer.var:zz_ef_cf_ratio }} }} "
                   f"set_variable = {{ name = stockpiling_{c}_state_1 value = 0 }} }} }} }}\n")
    out.append("}\n")
    out.append("# var:zz_ef_cf_units of every state -> the new currency's stock (var:zz_ef_cf_target of root).\n"
               "zz_ef_cf_put_new = {\n")
    for i, (c, tags) in enumerate(targets):
        kw = "if" if i == 0 else "else_if"
        out.append(f"\t{kw} = {{ limit = {{ var:zz_ef_cf_target = flag:{c} }} every_country = {{ every_scope_state = {{ limit = {{ has_variable = zz_ef_cf_units }} "
                   f"if = {{ limit = {{ NOT = {{ has_variable = stockpiling_{c}_state_1 }} }} set_variable = {{ name = stockpiling_{c}_state_1 value = 0 }} }} "
                   f"change_variable = {{ name = stockpiling_{c}_state_1 add = var:zz_ef_cf_units }} remove_variable = zz_ef_cf_units }} }} }}\n")
    out.append("}\n")
    out.append("# The law of the new currency (its on_activate sets var:zz_ef_cur).\n"
               "zz_ef_cf_activate = {\n")
    for i, (c, tags) in enumerate(targets):
        kw = "if" if i == 0 else "else_if"
        out.append(f"\t{kw} = {{ limit = {{ var:zz_ef_cf_target = flag:{c} }} activate_law = law_type:law_{c}_currency }}\n")
    out.append("}\n")
    return "".join(out)


def loc(lw):
    out = [HEAD, "# The name of var:zz_ef_cf_target (the keys of currency_name).\n",
           "zz_ef_cf_target_name = {\n\ttype = country\n\tlog_loc_errors = no\n"]
    for c, tags, en in lw:
        if en and tags:
            out.append(f"\ttext = {{\n\t\ttrigger = {{ var:zz_ef_cf_target ?= flag:{c} }}\n\t\tlocalization_key = {c}\n\t}}\n")
    out.append("}\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--dump", help="write the full output into this directory (a new file's first version)")
    a = ap.parse_args()
    lw = laws()
    par = parities()
    fx, lc = effects(lw, par), loc(lw)
    if a.dump:
        for rel, text in ((OUT_FX, fx), (OUT_LOC, lc)):
            p = os.path.join(a.dump, ld_gen.fork_rel(rel))
            os.makedirs(os.path.dirname(p), exist_ok=True)
            open(p, "w", encoding="utf-8").write(text)
        return
    ld_gen.emit(OUT_FX, fx)
    ld_gen.emit(OUT_LOC, lc)
    ld_gen.report("regen_ef_currency_formed")


if __name__ == "__main__":
    main()
