#!/usr/bin/env python3
"""
В2.4 (decided 4.10, М.10 а; 5.10): E&F's reset_law_event_currency (01_economic_scripted_effects.txt) -- the currency's
reset after a crisis (extreme_weak_currency_solution, the CB's bankruptcy, E&F's button) -- zeroes the central bank's
metal (gold_state_1 / silver_state_1 of the capital, 95 currency laws x 2 = 190 edits): the metal went into nothing,
and introduction_new_currency then gave it back from nothing. Both are off now: this re-issue drops the zeroing (the
rest of E&F's body as is: the currency count, government_loan, the pool's private bank funds, the stock); the
introduction side is wrapped in scripted_effects/zz_ef_currency_intro_metal.txt.

Writes _ef/ef hotfix 1.13/common/scripted_effects/zz_ef_currency_reset_keep_metal.txt
(key-level REPLACE_OR_CREATE: regenerate after an E&F update; the counts are asserted).

Usage:
    py tools/regen_ef_currency_reset_keep_metal.py [--check]
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))
SRC = res(r"..\..\vic3_mods_out\E&F\common\scripted_effects\01_economic_scripted_effects.txt")
OUT = res(r"..\_ef\ef hotfix 1.13\common\scripted_effects\zz_ef_currency_reset_keep_metal.txt")
NAME = "reset_law_event_currency"
ZERO = re.compile(r"\n[ \t]*set_variable = \{\s*name = (gold|silver)_state_1\s*value = 0\s*\}")


def match(text, i):
    d = 0
    for j in range(i, len(text)):
        d += {"{": 1, "}": -1}.get(text[j], 0)
        if d == 0:
            return j
    raise AssertionError


def build():
    t = open(SRC, encoding="utf-8-sig").read()
    m = re.search(rf"^[ \t]*{NAME} = \{{", t, re.M)
    assert m, f"{NAME} not found"
    i = t.index("{", m.start())
    body = t[i + 1:match(t, i)]
    body, n = ZERO.subn("", body)
    assert n == 190, f"zeroing edits: {n}, expected 190 (E&F changed)"
    assert "gold_state_1" not in body and "silver_state_1" not in body
    out = ("# GENERATED by tools/regen_ef_currency_reset_keep_metal.py -- do not edit by hand.\n"
           "# В2.4 (5.10): E&F's reset_law_event_currency without the zeroing of the CB's metal (190 edits) -- see the\n"
           "# generator's docstring.\n"
           "# !! MAINTENANCE !! Key-level REPLACE_OR_CREATE of E&F's effect: regenerate after an E&F update.\n\n"
           f"REPLACE_OR_CREATE:{NAME} = {{{body}}}\n")
    assert out.count("{") == out.count("}")
    return out


def main():
    out = build()
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8-sig").read() if os.path.exists(OUT) else ""
        print("ok" if cur == out else "DIFFERS", OUT)
        sys.exit(0 if cur == out else 1)
    with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write(out)
    print("ok", OUT)


if __name__ == "__main__":
    main()
