# -*- coding: utf-8 -*-
"""Builds addon-VC out of its pair compatches (plus one solo VC-internal-bug
fix), and checks the result.

Rule the hard way round (section 8 of the working notes): the assembly is built
FROM the compatches, never by editing the previous assembly. An old assembly is
behind on every file rename, and once it is you can no longer tell a renamed file
from a deleted one. So: work out the target file list, move everything that is
not in it into _to_delete/, copy the target list in, then verify coverage
byte-for-byte.

VC.5 (VC x PSC) and VC.6 (VC x PBE) are `noneed` -- confirmed 26.08.2026, no
compatch file exists for either, so they contribute nothing here. That leaves
four real pairs (TGR, E&F, Morgenroete, Kuromi's AI) plus one folder that isn't
a pair at all: `_vc/vc joi_flavor_chi29 done` disables a VC-internal event bug
(joi_flavor_chi.29 creates migrant pops with Standard of Living 100, wrecking
the receiving state's economy) -- same shape as `_tgr/tgr taxpanel fix done`,
a solo fix for the block's own base mod, not a compatibility issue with
anything else. See that folder's README for the bug and why it's disabled
rather than data-fixed.

One wrinkle beyond addon1 (HC + GoB + MoH): three of the four pair compatches
here restore different fields of the SAME 99 buy_packages records (wealth_1..
wealth_99). Copied in as three separate files they would sort so TGR's full
REPLACE_OR_CREATE loads last and silently wipes E&F's and Morgenroete's
injections again -- the typical assembly conflict from section 8. So those
three source files are excluded from the copy here and folded instead into one
addon-only file, common/buy_packages/zzzz_addon_vc_buy_packages.txt, generated
fresh by tools/regen_addon_vc.py every time this script runs (never stale,
never a separate command to remember).

Usage:
    python3 build_addon_vc.py --repo <path to vic3_mods> [--check]
"""
import argparse, os, shutil, filecmp, sys, re, json, collections

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3lib import read, brace_balance
import regen_addon_vc

PAIRS = ['_vc/tgr+vc done',
         '_vc/ef+vc done',
         '_vc/morg+vc done',
         '_vc/kai+vc done',
         '_vc/vc joi_flavor_chi29 done']
ADDON = '__addon/addon vc'

# Source files folded into one addon-only merge instead of being copied verbatim
# -- see the module docstring and tools/regen_addon_vc.py. Value is the written
# explanation section 8 requires for every non-zero coverage deviation.
MERGED_INTO = {
    '_vc/tgr+vc done/common/buy_packages/zz_vc_tgr_buy_packages.txt':
        'folded into common/buy_packages/zzzz_addon_vc_buy_packages.txt together with '
        "ef+vc's and morg+vc's copies of this record -- three separate files would sort "
        "with this one (a full REPLACE_OR_CREATE) loading last and wiping the other two's "
        'injections. See tools/regen_addon_vc.py.',
    '_vc/ef+vc done/common/buy_packages/zz_vc_ef_buy_packages.txt':
        'folded into common/buy_packages/zzzz_addon_vc_buy_packages.txt, same reason as '
        "tgr+vc's copy above.",
    '_vc/morg+vc done/common/buy_packages/zz_vc_morg_buy_packages.txt':
        'folded into common/buy_packages/zzzz_addon_vc_buy_packages.txt, same reason as '
        "tgr+vc's copy above.",
}

# Files that belong to the addon and to no single compatch. Each one needs a
# reason (section 8) -- and must also be kept out of the stale-file sweep below,
# since it is never present in the PAIRS source list to protect it from that.
ADDON_ONLY = {
    'common/buy_packages/zzzz_addon_vc_buy_packages.txt':
        'merge of the three buy_packages compatches above -- generated by '
        'tools/regen_addon_vc.py, run automatically as part of this script',
}

SKIP = {'.metadata', 'thumbnail.png'}
SKIP_SUFFIX = ('.md', '.xlsx')

# Repeated top-level keys the internal check would otherwise flag. Each one needs
# a reason here, not a silent exception (section 8).
DECLARED_DUPS = {
    ('common/history/countries', 'COUNTRIES'):
        'container key, additive across files -- one per country file, same as vanilla '
        '(same declared exception as addon1, tools/addon1_metadata.py)',
    ('common/static_modifiers', 'base_values'):
        "zz_vc_tgr_base_values.txt (TGR pair) and zz_vc_ef_static_modifiers.txt (E&F "
        'pair) both INJECT: into base_values on disjoint field names (TGR: loan '
        'interest, bureaucracy/authority/influence, officer/soldier political '
        'strength, company construction efficiency, trade advantage; E&F: an icon and '
        'country_minting_add) -- additive, not a conflict. See _vc/tgr+vc done and '
        '_vc/ef+vc done READMEs.',
}


def walk(base):
    out = {}
    for r, ds, fs in os.walk(base):
        ds[:] = [d for d in ds if d not in ('_to_delete',)]
        for f in fs:
            p = os.path.join(r, f)
            rel = os.path.relpath(p, base).replace('\\', '/')
            if rel.split('/')[0] in SKIP or rel in SKIP:
                continue
            if rel.endswith(SKIP_SUFFIX):
                continue
            out[rel] = p
    return out


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument('--repo', required=True)
    ap.add_argument('--check', action='store_true', help='verify only, change nothing')
    a = ap.parse_args(argv)
    addon = os.path.join(a.repo, ADDON)

    # ---- regenerate the one addon-only file first -----------------------------
    merge_text, merge_n, merge_ef, merge_morg = regen_addon_vc.build(a.repo)
    merge_out = os.path.join(a.repo, regen_addon_vc.OUT)
    if not a.check:
        from vic3lib import write as _write
        _write(merge_out, merge_text)
        print('regenerated %s (%d records, E&F on %d, Morgenrote on %d)'
              % (regen_addon_vc.OUT, merge_n, merge_ef, merge_morg))

    # ---- target list ------------------------------------------------------------
    target, owner = {}, {}
    merged_sources = collections.defaultdict(list)  # pair -> [rel paths folded away]
    for pair in PAIRS:
        for rel, src in walk(os.path.join(a.repo, pair)).items():
            full_key = pair + '/' + rel
            if full_key in MERGED_INTO:
                merged_sources[pair].append(rel)
                continue
            if rel in target:
                raise SystemExit('two compatches ship %s (%s and %s) -- needs an '
                                 'addon-only merge file' % (rel, owner[rel], pair))
            target[rel], owner[rel] = src, pair

    # ---- copy ---------------------------------------------------------------
    if not a.check:
        have = walk(addon) if os.path.isdir(addon) else {}
        protect = set(target) | set(ADDON_ONLY)
        stale = sorted(set(have) - protect)
        if stale:
            dump = os.path.join(addon, '_to_delete', 'rebuild_%s' % _today())
            for rel in stale:
                dst = os.path.join(dump, rel)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.move(have[rel], dst)   # rm is not permitted on the mount
            print('moved %d stale file(s) to %s' % (len(stale), dump))
        for rel, src in target.items():
            dst = os.path.join(addon, rel)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copyfile(src, dst)
        print('copied %d file(s) into %s' % (len(target), ADDON))

    # ---- coverage -----------------------------------------------------------
    print('\n--- coverage (every compatch file, byte for byte, or an explained deviation) ---')
    bad = 0
    for pair in PAIRS:
        files = walk(os.path.join(a.repo, pair))
        missing = [r for r in files if not os.path.exists(os.path.join(addon, r))]
        differ = [r for r in files
                  if r not in missing and not filecmp.cmp(files[r], os.path.join(addon, r), shallow=False)]
        explained = [r for r in missing if (pair + '/' + r) in MERGED_INTO]
        real_missing = [r for r in missing if r not in explained]
        print('  %-16s %2d files, %d missing, %d different, %d folded into the merge'
              % (pair.split('/')[-1], len(files), len(real_missing), len(differ), len(explained)))
        for r in real_missing + differ:
            print('      ! ' + r)
        for r in explained:
            print('      (expected) %s -- %s' % (r, MERGED_INTO[pair + '/' + r]))
        bad += len(real_missing) + len(differ)
    extra = sorted(set(walk(addon)) - set(target))
    print('  addon-only files: %d' % len(extra))
    for r in extra:
        if r in ADDON_ONLY:
            print('      declared: %s -- %s' % (r, ADDON_ONLY[r]))
        else:
            print('      ! %s is in the addon but in no compatch and not declared' % r)
            bad += 1

    # ---- internal checks ----------------------------------------------------
    print('\n--- checks ---')
    files = walk(addon)
    print('  files: %d' % len(files))
    imbalance = [(r, brace_balance(read(p))) for r, p in files.items()
                 if r.endswith('.txt') and brace_balance(read(p))]
    print('  brace balance: %s' % ('ok' if not imbalance else imbalance))
    bad += len(imbalance)

    enc = []
    for r, p in files.items():
        raw = open(p, 'rb').read()
        has_bom = raw[:3] == b'\xEF\xBB\xBF'
        txt = raw[3:].decode('utf-8') if has_bom else raw.decode('utf-8')
        needs = any(ord(c) > 127 for line in txt.split('\n') for c in line.split('#')[0])
        if needs and not has_bom:
            enc.append(r)
    print('  encodings: %s' % ('ok' if not enc else 'missing BOM in %s' % enc))
    bad += len(enc)

    dup = collections.defaultdict(list)
    for r, p in files.items():
        if not r.startswith('common/') or not r.endswith('.txt'):
            continue
        cat = os.path.dirname(r)
        for m in re.finditer(r'(?m)^(?:[A-Z_]+:)?([a-zA-Z_][a-zA-Z_0-9]*)\s*=\s*\{', read(p)):
            dup[(cat, m.group(1))].append(r)
    dups = {k: v for k, v in dup.items() if len(v) > 1}
    declared, real = [], {}
    for k, v in dups.items():
        why = DECLARED_DUPS.get(k)
        (declared.append((k, why)) if why else real.__setitem__(k, v))
    print('  duplicate top-level keys inside the addon: %s'
          % ('none beyond the %d declared' % len(declared) if not real else real))
    for k, why in sorted(declared):
        print('      declared: %s/%s -- %s' % (k[0], k[1], why))
    bad += len(real)

    loc = collections.defaultdict(list)
    for r, p in files.items():
        if not r.startswith('localization/'):
            continue
        lang = r.split('/')[1]
        for m in re.finditer(r'(?m)^\s*([A-Za-z_][\w.]*):\d*\s+"', read(p)):
            loc[(lang, m.group(1))].append(r)
    ldups = {k: v for k, v in loc.items() if len(v) > 1}
    print('  localization: %d keys, duplicates per language: %s'
          % (len(loc), 'none' if not ldups else ldups))
    bad += len(ldups)

    goods = [r for r in files if r.startswith('common/goods/')]
    print('  goods files in the addon: %d (nothing added, so the 128 ceiling is unchanged '
          'at 74)' % len(goods))

    print('\n%s' % ('ALL CHECKS PASS' if not bad else '%d PROBLEM(S)' % bad))
    return 1 if bad else 0


def _today():
    import datetime
    return datetime.date.today().isoformat()


if __name__ == '__main__':
    sys.exit(main())
