"""Комментарии форка — только актуальное (Д.R3б.6, правило `CLAUDE.md` форка «Комментарии в коде»).

    python tools/ld_comment_clean.py [--write] [--files <glob>] [--show N]

Меняет только текст комментариев (токены `#…` разбора `ld_pdx`), код — нет (сверка `ld_pdx.norm` без комментариев до
и после, иначе файл не пишется):
- старые имена файлов `zz_ef_X.txt` / `zz_pb_ef_X.txt` → нынешние `ld_X.txt` / `ld_pb_X.txt` (если такой файл в форке есть);
- история в скобках — даты (`5.10`, `2026-09-24`), прогоны (`r1007_180243`, `run 15`), «was», «night», «the user …»;
- метки шагов в начале комментария (`R1а.4:`, `EF.48 item 5:`, `В2.1 (2.10):`, `П.8:`, `UI.7:`, `stage 2, step 8:` …);
  ссылки на решения этапов (`Д.R2.7`) остаются;
- строка `# (was …)` целиком.
Файлы с шапкой «GENERATED» пропускаются — их комментарии правятся в генераторе; `--generated` — те же правки и в
них (после той же правки строк генераторов: `ld_gen` сверяет записи без комментариев и комментарии сам не переносит).
Без `--write` — только счёт и примеры.
"""
import argparse
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ld_pdx  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
FORK = os.path.normpath(os.path.join(HERE, "..", "..", "Economic-and-Financial-Ledgerdemain-Mod"))

DATE = r"(?<![\d.])(?:[1-9]|[12]\d|3[01])\.(?:0?9|10)(?:\.2026)?(?![\d.])|2026-\d\d-\d\d"
HISTWORD = r"r1[01]\d{2}_\d{6}|\brun \d+\b|\bruns? r\d|\bwas\b|\bWas\b|\bnight\b|\bthe user\b|\bevening\b|\bmorning\b|" + DATE
PAREN = re.compile(r"\s*\((?:[^()]|\([^()]*\))*?(?:" + HISTWORD + r")(?:[^()]|\([^()]*\))*?\)")
TAG = (r"(?:R\d{1,2}[а-яa-z]?(?:\.\d+)?|EF\.\d+[a-z]?|В\d(?:\.\d+)*|П\.\d+[а-яa-z]?|Е\.\d+|UI\.\d+|Д\d\.\d+[а-яa-z]?|ФК\d|"
       r"М(?:\.\d+)?|STR\.\d+|СТР\.\d+|Н\.\d+|D\.\d+|Хвост R1|stage \d+|step \d+|steps [\d, ]+|night \d+|item \d+|items [\d\-, ]+|v\d)")
LEAD = re.compile(r"^(#+\s*)(?:" + TAG + r"(?:[ ,/]+(?:" + TAG + r"))*)\s*(\((?:[^()]|\([^()]*\))*\))?\s*(?:[:,]|--)\s+")
DEC = re.compile(r"Д\.R[0-9а-яa-z]+\.\d+")
WAS_LINE = re.compile(r"^#+\s*\((?:was|Was)\b[^)]*\)\s*$")


def files_map():
    have = {}
    for p in glob.glob(os.path.join(FORK, "common", "**", "*.txt"), recursive=True):
        have.setdefault(os.path.basename(p), p)
    for p in glob.glob(os.path.join(FORK, "gui", "**", "*.gui"), recursive=True):
        have.setdefault(os.path.basename(p), p)
    return have


HAVE = None


def rename(m):
    name = m.group(0)
    base = re.sub(r"^zz_pb_ef_", "ld_pb_", re.sub(r"^zz_ef_", "ld_", name))
    return base if base in HAVE else name


def clean(c):
    """Текст одного комментария (с `#`) → новый текст (пустая строка — убрать)."""
    if WAS_LINE.match(c):
        return ""
    s = re.sub(r"\b(?:zz_pb_ef|zz_ef)_[A-Za-z0-9_]+\.(?:txt|gui)\b", rename, c)
    m = LEAD.match(s)
    if m:
        keep = DEC.findall(m.group(0))
        s = m.group(1) + (f"({', '.join(keep)}) " if keep else "") + s[m.end():]
    s = PAREN.sub(lambda mm: " (" + ", ".join(DEC.findall(mm.group(0))) + ")" if DEC.search(mm.group(0)) else "", s)
    if s == c:
        return c
    s = re.sub(r"[ \t]+([,.;:])", r"\1", s)
    s = re.sub(r"[ \t]+$", "", s)
    if re.fullmatch(r"#+\s*", s):
        return ""
    return s


def process(text):
    out, pos, n = [], 0, 0
    for t in ld_pdx.TOKEN.finditer(text):
        if not t.group(0).startswith("#"):
            continue
        new = clean(t.group(0))
        if new == t.group(0):
            continue
        n += 1
        a, b = t.start(), t.end()
        if new == "":
            ls = text.rfind("\n", 0, a) + 1
            if text[ls:a].strip() == "":
                a = ls
                if b < len(text) and text[b] == "\n":
                    b += 1
            else:
                while a > ls and text[a - 1] in " \t":
                    a -= 1
        out.append(text[pos:a])
        out.append(new)
        pos = b
    out.append(text[pos:])
    return "".join(out), n


def main():
    global HAVE
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--files", default=None)
    ap.add_argument("--show", type=int, default=0)
    ap.add_argument("--generated", action="store_true", help="и файлы «GENERATED» (после той же правки строк генераторов)")
    a = ap.parse_args()
    HAVE = files_map()
    pats = [a.files] if a.files else ["common/**/*.txt", "events/**/*.txt", "gui/**/*.gui"]
    tot, files, shown = 0, 0, 0
    for pat in pats:
        for p in sorted(glob.glob(os.path.join(FORK, pat), recursive=True)):
            text, bom, eol = ld_pdx.read(p)
            if "GENERATED by" in text[:300] and not a.generated:
                continue
            new, n = process(text)
            if not n:
                continue
            if ld_pdx.norm(re.sub(r"#[^\n]*", "", new)) != ld_pdx.norm(re.sub(r"#[^\n]*", "", text)):
                print("КОД ИЗМЕНИЛСЯ — пропуск:", os.path.relpath(p, FORK))
                continue
            tot += n
            files += 1
            if a.show and shown < a.show:
                ol, nl = text.split("\n"), new.split("\n")
                import difflib
                for d in difflib.unified_diff(ol, nl, lineterm="", n=0):
                    if d.startswith(("-", "+")) and not d.startswith(("---", "+++")) and shown < a.show:
                        print(d[:200])
                        shown += 1
            if a.write:
                ld_pdx.write(p, new, bom=bom, eol=eol)
    print(f"комментариев изменено {tot} в {files} файлах" + ("" if a.write else " (без --write)"))


if __name__ == "__main__":
    main()
