# -*- coding: utf-8 -*-
"""
regen_greys_megapack.py -- builds the Grey's x megapack `no t&r` compatch in
`_greys/greys+megapack done`.

Pair GR.17. Not a raw mod-vs-mod pair like the others: the "no t&r" megapack
already merges TGR x PSC x KAI x E&F x Morgenroete x PBE into single winning
bodies, and grey_usu (loading after the whole Grey's pack, i.e. after the
megapack) then silently drops content from two of those merged bodies with
full-body TRY_REPLACE:s. `content_holes.py --only builds` is what catches this
class of gap -- pair_matrix.py only compares blocks in the `order` chain, and
the megapack is a *build*, not a block.

Of the 7 keys `content_holes.py` reports under "МЕГАПАК x USU", 5 are already
closed elsewhere: `building_construction_sector` and the four
`pm_*_buildings` construction methods are fixed by `_greys/greys+psc done`
(GR.2), which loads after the whole Grey's pack and so wins outright
regardless of what the megapack itself carries on that record. The two left:

  * `building_airport` -- grey_usu's TRY_REPLACE: (`zMoG_USU_MR_airports.txt`,
    "Respecified purely so that the auto-expand rules are properly managed")
    drops the two groups E&F x Morgenroete wired onto it: `pmg_market_liquidity`
    + `pmg_private_ownership_manufacture_stock`.
  * `building_dubois_national_park` -- grey_usu's TRY_REPLACE:
    (`zMoG_USU_MR_nat_park.txt`) drops `pmg_market_liquidity` only -- this
    building is `can_build_private = { always = no }` in both the megapack's
    body and grey_usu's, so it was never a stock candidate, only liquidity.

**Mutually exclusive with `_greys/greys+llwa done` on `building_airport`.**
That compatch (GR.9/GR.16) restores the SAME two E&F groups on the same
record, plus addon-LLWA's own three -- it is the right fix when addon-LLWA is
installed. This compatch is for players who run the megapack + Grey's pack
WITHOUT addon-LLWA. Installing both would TRY_INJECT: the two E&F groups onto
`building_airport` twice. Pick one:
  * using addon-LLWA  -> `_greys/greys+llwa done` (5 groups)
  * not using it       -> this compatch (2 groups)
`building_dubois_national_park` has no such overlap -- addon-LLWA does not
touch it -- so it is always safe to install this compatch's file for that
record alone.

Usage:
    python3 regen_greys_megapack.py            # write the compatch
    python3 regen_greys_megapack.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

MEGAPACK = res("../__megapacks/megapack no t&r")
USU = res("../../vic3_mods_out/grey_add_alot_of_things/grey_usu")
OUT = res("../_greys/greys+megapack done")

MEGAPACK_SRC = os.path.join(MEGAPACK, "common/buildings/zz_ef_mr_buildings_inject.txt")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's x megapack `no t&r` compatch (GR.17) -- {what}
# Generated by tools/regen_greys_megapack.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: ... -> megapack `no t&r` -> ... -> Grey's pack -> THIS.
# NOT for players using addon-LLWA on building_airport -- see the module
# docstring and the README: use _greys/greys+llwa done instead for that
# record, or you double-inject the two E&F groups onto it.
# Why this file exists: {why}
"""

# (key, grey_usu file, grey_usu prefix)
BUILDINGS = [
    ("building_airport", os.path.join(USU, "common/buildings/zMoG_USU_MR_airports.txt"), "TRY_REPLACE:"),
    ("building_dubois_national_park", os.path.join(USU, "common/buildings/zMoG_USU_MR_nat_park.txt"), "TRY_REPLACE:"),
]


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_buildings():
    mega_text = V.read(MEGAPACK_SRC)
    records, notes = [], []
    for key, usu_file, prefix in BUILDINGS:
        _decl, mega_body = V.entry(mega_text, key, "TRY_INJECT:")
        groups_block = V.sub(mega_body, "production_method_groups")
        assert groups_block, f"{key}: megapack's own TRY_INJECT: no longer carries production_method_groups"
        groups = groups_block.strip("{} \n\t").split()
        assert groups, f"{key}: megapack's own TRY_INJECT: injects an empty group list"

        assert os.path.isfile(usu_file), f"{usu_file} is gone -- grey_usu renamed a file, re-check GR.17"
        usu_text = V.read(usu_file)
        _decl, usu_body = V.entry(usu_text, key, prefix)
        have = V.sub(usu_body, "production_method_groups") or ""
        missing = [g for g in groups if g not in have]
        assert missing, (
            f"{key}: {os.path.basename(usu_file)} already lists {groups} -- grey_usu fixed it, "
            f"drop this building from BUILDINGS")
        assert missing == groups, (
            f"{key}: {os.path.basename(usu_file)} lists some but not all of {groups} -- "
            f"re-read the body by hand")

        notes.append(f"#   {key:30} loses {groups} to {os.path.basename(usu_file)}")
        records.append(
            f"TRY_INJECT:{key} = {{\n\tproduction_method_groups = {{\n"
            + "".join(f"\t\t{g}\n" for g in groups)
            + "\t}\n}"
        )

    text = ("# what each building loses and to whose body:\n" + "\n".join(notes) + "\n\n"
            + "\n\n".join(records))
    write("common/buildings/zz_greys_megapack_buildings_inject.txt", text,
          "restore E&F x Morgenroete's groups on two buildings grey_usu re-declares whole",
          "the megapack already carries E&F x Morgenroete's own TRY_INJECT: of these groups "
          "(from ef+morg done, folded into the megapack build). grey_usu's TRY_REPLACE: of "
          "both records loads after the whole Grey's pack and does not name either group, so "
          "both buildings drop out of E&F's liquidity/stock system silently. "
          "building_construction_sector and the four pm_*_buildings construction methods, "
          "the other 5 of content_holes.py's 7 reported keys here, are NOT in this file -- "
          "`_greys/greys+psc done` (GR.2) already restores them and wins outright, loading "
          "after the whole Grey's pack same as this file. building_airport is mutually "
          "exclusive with `_greys/greys+llwa done` -- see the module docstring.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        import re as _re
        doubled = _re.findall(r"^[A-Z_]+:[A-Z_]+:", text, _re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        empty_colon = _re.findall(r"^[A-Z_]+::", text, _re.M)
        if empty_colon:
            print(f"  FAIL {rel}: {len(empty_colon)} bad '::' prefix(es), e.g. {empty_colon[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = _re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_megapack.py -> {OUT}")
    for name, fn in (("buildings", build_buildings),):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current megapack / Grey's sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
