#!/usr/bin/env python3
"""
Е.6 (5.10, Д.3) -- the bond tables in "Budget -> Finances": who holds our bonds and whose bonds we hold.

Why this exists
---------------
E&F's two blocks -- "Investments in foreign debt" (gold_lent_to_foreign_countries) and "Foreign gold lent
against our debt" (gold_lent_to_us) -- list only the human player's own purchases (seller_country_general_N,
total_bond_value_N); the bonds the AI buys for a country (ai_buy_bond_1..10: ai_seller_country_general_N,
ai_total_bond_value_N) and the private banks' bonds (ai_privat_bank_*_1..25) were in lists hidden by EF.30
(an E&F check failing every frame). The user (4.10) saw "one Portugal 4.40M" while Britain held ~20M of bonds.

What this does
--------------
A scripted GUI zz_ef_bonds_update (root = the player) fills two global lists of countries:
  zz_ef_bt_in_list  -- who holds OUR bonds: other countries' treasuries (their slots naming us as the seller)
                       and their private banks (bank slots whose seller list has us);
  zz_ef_bt_out_list -- whose bonds WE hold: the sellers of our treasury's slots and of our banks' slots.
Per row (variables on the listed country): treasury sum (engine money, as E&F's purchase price), its yearly
rate and interest a week; banks' sum (in gold -- E&F values the banks' bonds in gold), rate, interest a week.
gui/ld_cb_rate_panel.gui (hand-written) puts a button and the two tables under E&F's headers.

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys): common/scripted_guis/ld_bond_tables.txt,
common/script_values/ld_bond_tables_values.txt, localization/{english,russian}/ld_bond_tables_l_*.yml.
Reads nothing.
Usage: python3 tools/regen_ef_bond_tables.py [--check]
"""
from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

# hotfix paths; ld_gen writes into the fork (ld_bond_tables.txt, ld_bond_tables_values.txt, ld_bond_tables_l_*.yml)
OUT_SG = "common/scripted_guis/zz_ef_bond_tables.txt"
OUT_SV = "common/script_values/zz_ef_bond_tables_values.txt"
LANGS = ["english", "russian", "braz_por", "french", "german", "japanese",
         "korean", "polish", "simp_chinese", "spanish", "turkish"]
N_STATE = 10   # ai_buy_bond_1..10 and the player's slots 1..10
N_BANK = 25    # ai_privat_bank_*_1..25
VARS = ["zz_ef_bt_t_amt", "zz_ef_bt_t_week", "zz_ef_bt_b_amt", "zz_ef_bt_b_year",
        "zz_ef_bto_t_amt", "zz_ef_bto_t_week", "zz_ef_bto_b_amt", "zz_ef_bto_b_year"]  # in / out rows


def state_slot(n: int, seller: str) -> str:
    """Treasury slot n of the scope country (the holder) bought from `seller`: E&F's AI slot and the player's."""
    return (f"\t\t\tif = {{ limit = {{ has_variable = ai_buy_bond_{n}_on var:ai_buy_bond_{n}_on = 1 "
            f"has_variable = ai_seller_country_general_{n} var:ai_seller_country_general_{n} = {seller} "
            f"has_variable = ai_total_bond_value_{n} }}\n"
            f"\t\t\t\tchange_variable = {{ name = zz_ef_bt_t_amt add = var:ai_total_bond_value_{n} }}\n"
            f"\t\t\t\tchange_variable = {{ name = zz_ef_bt_t_week add = {{ value = var:ai_interest_per_month_calculated_{n} multiply = 0.25 }} }}\n"
            f"\t\t\t}}\n"
            f"\t\t\tif = {{ limit = {{ has_variable = total_bond_value_{n} var:total_bond_value_{n} > 0 "
            f"has_variable = seller_country_general_{n} var:seller_country_general_{n} = {seller} }}\n"
            f"\t\t\t\tchange_variable = {{ name = zz_ef_bt_t_amt add = var:total_bond_value_{n} }}\n"
            f"\t\t\t\tchange_variable = {{ name = zz_ef_bt_t_week add = {{ value = var:interest_per_month_calculated_{n} multiply = 0.25 }} }}\n"
            f"\t\t\t}}\n")


def sgui() -> str:
    out = ["# GENERATED by tools/regen_ef_bond_tables.py -- do not edit by hand.\n"
           "# who holds our bonds (zz_ef_bt_in_list) and whose bonds we hold (zz_ef_bt_out_list).\n"
           "# Rows: variables on the listed country -- treasury sum (money), interest a week; banks' sum (gold), interest\n"
           "# a year (gold). Filled when the player opens the table (button in Budget -> Finances).\n"
           "zz_ef_bonds_update = {\n\teffect = {\n\t\tsave_scope_as = bt_root\n"
           "\t\tclear_global_variable_list = zz_ef_bt_in_list\n\t\tclear_global_variable_list = zz_ef_bt_out_list\n"
           "\t\tclear_global_variable_list = zz_ef_bt_in_tmp\n\t\tclear_global_variable_list = zz_ef_bt_out_tmp\n"
           "\t\t# the banks' sums are gold: the player's gold per unit of money, for the order\n"
           "\t\tset_global_variable = { name = zz_ef_bt_gpm value = zz_ef_clr_gold_per_money }\n"
           "\t\tevery_country = {\n"]
    for v in VARS:
        out.append(f"\t\t\tset_variable = {{ name = {v} value = 0 }}\n")
    out.append("\t\t}\n")
    # 1. who holds ours
    out.append("\t\t# 1. other countries holding our bonds: their treasury slots naming us, their banks' slots with us\n"
               "\t\tevery_country = {\n\t\t\tlimit = { NOT = { this = scope:bt_root } }\n")
    for n in range(1, N_STATE + 1):
        out.append(state_slot(n, "scope:bt_root"))
    for m in range(1, N_BANK + 1):
        out.append(f"\t\t\tif = {{ limit = {{ has_variable = ai_privat_bank_bond_value_{m} var:ai_privat_bank_bond_value_{m} > 0 "
                   f"is_target_in_variable_list = {{ name = ai_privat_bank_seller_country_general_{m} target = scope:bt_root }} }}\n"
                   f"\t\t\t\tchange_variable = {{ name = zz_ef_bt_b_amt add = var:ai_privat_bank_bond_value_{m} }}\n"
                   f"\t\t\t\tif = {{ limit = {{ has_variable = ai_privat_bank_interest_calculated_{m} }} "
                   f"change_variable = {{ name = zz_ef_bt_b_year add = var:ai_privat_bank_interest_calculated_{m} }} }}\n"
                   f"\t\t\t}}\n")
    out.append("\t\t\tif = { limit = { OR = { var:zz_ef_bt_t_amt > 0 var:zz_ef_bt_b_amt > 0 } } "
               "add_to_global_variable_list = { name = zz_ef_bt_in_tmp target = this } }\n\t\t}\n")
    # 2. whose we hold: our slots, the sum goes on the seller (the listed country)
    out.append("\t\t# 2. our bonds of other countries: each of our slots adds to its seller's row\n")
    for n in range(1, N_STATE + 1):
        out.append(f"\t\tif = {{ limit = {{ has_variable = ai_buy_bond_{n}_on var:ai_buy_bond_{n}_on = 1 "
                   f"has_variable = ai_seller_country_general_{n} has_variable = ai_total_bond_value_{n} }}\n"
                   f"\t\t\tvar:ai_seller_country_general_{n} = {{\n"
                   f"\t\t\t\tchange_variable = {{ name = zz_ef_bto_t_amt add = scope:bt_root.var:ai_total_bond_value_{n} }}\n"
                   f"\t\t\t\tchange_variable = {{ name = zz_ef_bto_t_week add = {{ value = scope:bt_root.var:ai_interest_per_month_calculated_{n} multiply = 0.25 }} }}\n"
                   f"\t\t\t\tif = {{ limit = {{ NOT = {{ is_target_in_global_variable_list = {{ name = zz_ef_bt_out_tmp target = this }} }} }} add_to_global_variable_list = {{ name = zz_ef_bt_out_tmp target = this }} }}\n"
                   f"\t\t\t}}\n\t\t}}\n"
                   f"\t\tif = {{ limit = {{ has_variable = seller_country_general_{n} has_variable = total_bond_value_{n} var:total_bond_value_{n} > 0 }}\n"
                   f"\t\t\tvar:seller_country_general_{n} = {{\n"
                   f"\t\t\t\tchange_variable = {{ name = zz_ef_bto_t_amt add = scope:bt_root.var:total_bond_value_{n} }}\n"
                   f"\t\t\t\tchange_variable = {{ name = zz_ef_bto_t_week add = {{ value = scope:bt_root.var:interest_per_month_calculated_{n} multiply = 0.25 }} }}\n"
                   f"\t\t\t\tif = {{ limit = {{ NOT = {{ is_target_in_global_variable_list = {{ name = zz_ef_bt_out_tmp target = this }} }} }} add_to_global_variable_list = {{ name = zz_ef_bt_out_tmp target = this }} }}\n"
                   f"\t\t\t}}\n\t\t}}\n")
    for m in range(1, N_BANK + 1):
        out.append(f"\t\tif = {{ limit = {{ has_variable = ai_privat_bank_bond_value_{m} var:ai_privat_bank_bond_value_{m} > 0 }}\n"
                   # night check (run ext2): the slot's seller list held Britain itself for Britain's banks --
                   # our own bonds are not "other countries'"
                   f"\t\t\trandom_in_list = {{\n\t\t\t\tvariable = ai_privat_bank_seller_country_general_{m}\n"
                   f"\t\t\t\tlimit = {{ NOT = {{ this = scope:bt_root }} }}\n"
                   f"\t\t\t\tchange_variable = {{ name = zz_ef_bto_b_amt add = scope:bt_root.var:ai_privat_bank_bond_value_{m} }}\n"
                   f"\t\t\t\tif = {{ limit = {{ scope:bt_root = {{ has_variable = ai_privat_bank_interest_calculated_{m} }} }} "
                   f"change_variable = {{ name = zz_ef_bto_b_year add = scope:bt_root.var:ai_privat_bank_interest_calculated_{m} }} }}\n"
                   f"\t\t\t\tif = {{ limit = {{ NOT = {{ is_target_in_global_variable_list = {{ name = zz_ef_bt_out_tmp target = this }} }} }} add_to_global_variable_list = {{ name = zz_ef_bt_out_tmp target = this }} }}\n"
                   f"\t\t\t}}\n\t\t}}\n")
    # night check (run ext2): the biggest first -- treasury (money) + banks (gold / the player's gold per money)
    for k in ("in", "out"):
        out.append(f"\t\tordered_in_global_list = {{ variable = zz_ef_bt_{k}_tmp order_by = zz_ef_bt_{k}_key max = 1000 "
                   f"check_range_bounds = no add_to_global_variable_list = {{ name = zz_ef_bt_{k}_list target = this }} }}\n")
    out.append("\t}\n}\n")
    return "".join(out)


LOC = {
    "russian": {
        "zz_ef_bt_button": "Показать",
        "zz_ef_bt_button_tt": "Собрать таблицу облигаций (на сегодня).",
        "zz_ef_bt_in_title": "Кто держит наши облигации (наш долг)",
        "zz_ef_bt_out_title": "Наши облигации других стран (казна и банки)",
        "zz_ef_bt_head": "#grey Страна: казна — сумма, ставка в год, проценты в неделю; банки — сумма в золоте, проценты в год#!",
        "zz_ef_bt_t_row": "казна [Scope.GetCountry.MakeScope.Var('zz_ef_bt_t_amt').GetValue|D] ¤, ставка "
                          "[Scope.GetCountry.MakeScope.ScriptValue('zz_ef_bt_t_rate')|%1], в неделю "
                          "[Scope.GetCountry.MakeScope.Var('zz_ef_bt_t_week').GetValue|D] ¤",
        "zz_ef_bt_b_row": "банки [Scope.GetCountry.MakeScope.Var('zz_ef_bt_b_amt').GetValue|D] @gold!, в год "
                          "[Scope.GetCountry.MakeScope.Var('zz_ef_bt_b_year').GetValue|D] @gold!",
        "zz_ef_bto_t_row": "казна [Scope.GetCountry.MakeScope.Var('zz_ef_bto_t_amt').GetValue|D] ¤, ставка "
                          "[Scope.GetCountry.MakeScope.ScriptValue('zz_ef_bto_t_rate')|%1], в неделю "
                          "[Scope.GetCountry.MakeScope.Var('zz_ef_bto_t_week').GetValue|D] ¤",
        "zz_ef_bto_b_row": "банки [Scope.GetCountry.MakeScope.Var('zz_ef_bto_b_amt').GetValue|D] @gold!, в год "
                          "[Scope.GetCountry.MakeScope.Var('zz_ef_bto_b_year').GetValue|D] @gold!",
        "zz_ef_bt_empty": "#grey (нет — или нажмите «Показать»)#!",
    },
    "english": {
        "zz_ef_bt_button": "Show",
        "zz_ef_bt_button_tt": "Fill the bond table (as of today).",
        "zz_ef_bt_in_title": "Who holds our bonds (our debt)",
        "zz_ef_bt_out_title": "Our bonds of other countries (treasury and banks)",
        "zz_ef_bt_head": "#grey Country: treasury — sum, yearly rate, interest a week; banks — sum in gold, interest a year#!",
        "zz_ef_bt_t_row": "treasury [Scope.GetCountry.MakeScope.Var('zz_ef_bt_t_amt').GetValue|D] ¤, rate "
                          "[Scope.GetCountry.MakeScope.ScriptValue('zz_ef_bt_t_rate')|%1], a week "
                          "[Scope.GetCountry.MakeScope.Var('zz_ef_bt_t_week').GetValue|D] ¤",
        "zz_ef_bt_b_row": "banks [Scope.GetCountry.MakeScope.Var('zz_ef_bt_b_amt').GetValue|D] @gold!, a year "
                          "[Scope.GetCountry.MakeScope.Var('zz_ef_bt_b_year').GetValue|D] @gold!",
        "zz_ef_bto_t_row": "treasury [Scope.GetCountry.MakeScope.Var('zz_ef_bto_t_amt').GetValue|D] ¤, rate "
                          "[Scope.GetCountry.MakeScope.ScriptValue('zz_ef_bto_t_rate')|%1], a week "
                          "[Scope.GetCountry.MakeScope.Var('zz_ef_bto_t_week').GetValue|D] ¤",
        "zz_ef_bto_b_row": "banks [Scope.GetCountry.MakeScope.Var('zz_ef_bto_b_amt').GetValue|D] @gold!, a year "
                          "[Scope.GetCountry.MakeScope.Var('zz_ef_bto_b_year').GetValue|D] @gold!",
        "zz_ef_bt_empty": "#grey (none — or press 'Show')#!",
    },
}
# the treasury's sums are E&F's purchase prices in the engine's money; the player's currency symbol
CUR = "[GetPlayer.GetCustom('currency_symbol')]"

SV = """
# the rows' order -- treasury sum (money) + banks' sum (gold) in the player's money
zz_ef_bt_in_key = {
	value = 0
	if = { limit = { has_variable = zz_ef_bt_t_amt } add = var:zz_ef_bt_t_amt }
	if = {
		limit = { has_variable = zz_ef_bt_b_amt has_global_variable = zz_ef_bt_gpm global_var:zz_ef_bt_gpm > 0 }
		add = { value = var:zz_ef_bt_b_amt divide = global_var:zz_ef_bt_gpm }
	}
}
zz_ef_bt_out_key = {
	value = 0
	if = { limit = { has_variable = zz_ef_bto_t_amt } add = var:zz_ef_bto_t_amt }
	if = {
		limit = { has_variable = zz_ef_bto_b_amt has_global_variable = zz_ef_bt_gpm global_var:zz_ef_bt_gpm > 0 }
		add = { value = var:zz_ef_bto_b_amt divide = global_var:zz_ef_bt_gpm }
	}
}
# the row's yearly rate on the treasury's bonds (interest a week x 52 / sum)
zz_ef_bt_t_rate = {
	value = 0
	if = {
		limit = { has_variable = zz_ef_bt_t_amt var:zz_ef_bt_t_amt > 0 has_variable = zz_ef_bt_t_week }
		value = var:zz_ef_bt_t_week
		multiply = 52
		divide = var:zz_ef_bt_t_amt
	}
}
zz_ef_bto_t_rate = {
	value = 0
	if = {
		limit = { has_variable = zz_ef_bto_t_amt var:zz_ef_bto_t_amt > 0 has_variable = zz_ef_bto_t_week }
		value = var:zz_ef_bto_t_week
		multiply = 52
		divide = var:zz_ef_bto_t_amt
	}
}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    text = sgui()
    assert text.count("{") == text.count("}")
    ld_gen.emit(OUT_SG, text)
    ld_gen.emit(OUT_SV, "# GENERATED by tools/regen_ef_bond_tables.py -- do not edit by hand.\n" + SV)
    for lang in LANGS:
        d = LOC["russian" if lang == "russian" else "english"]
        lines = [f"l_{lang}:\n"] + [f' {k}:0 "{v.replace("¤", CUR)}"\n' for k, v in d.items()]
        ld_gen.emit(f"localization/{lang}/zz_ef_bond_tables_l_{lang}.yml", "".join(lines))
    ld_gen.report("regen_ef_bond_tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
