#!/usr/bin/env python3
"""
EF.48, В5.1 (decided 2.10): the government's loan from the central bank -- step 0.5% of GDP, cap 50%.

E&F (scripted_guis/00_financial_scripted_guis.txt:2237): debt_issued_relative_GDP_increase / _reduce move
var:debt_issued_relative_GDP_percentage by 5% of GDP with no upper bound, and set_debt_issued ("take")
adds GDP x that share to the treasury and to the debt to the CB (var:credit_at_central_bank) -- the
player could take any number of 5%-of-GDP loans. Now: step 0.5%, the share between 0.5% and 50%, and
"take" is valid only while the debt to the CB after the loan stays within 50% of GDP. The foreign bond
slots (5 for the player, 10 for the AI) stay.

E&F shows the share as |%| (whole percent): its text key debt_issued_relative_GDP_2 is re-issued with
|%1 in every language (localization/<lang>/replace/), E&F's wording kept.

Writes (_ef/ef hotfix 1.13/): common/scripted_guis/zz_ef_cb_loan.txt,
localization/<lang>/replace/zz_ef_cb_loan_replace_l_<lang>.yml

Usage:
    py tools/regen_ef_cb_loan.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))
EF = res(r"..\..\vic3_mods_out\E&F")
HOTFIX = res(r"..\_ef\ef hotfix 1.13")
LANGS = ["english", "russian", "braz_por", "french", "german", "japanese",
         "korean", "polish", "simp_chinese", "spanish", "turkish"]

STEP = 0.005
SHARE_MAX = 0.5
DEBT_CAP = 0.5

GUIS = f"""# GENERATED by tools/regen_ef_cb_loan.py -- do not edit by hand.
# EF.48, В5.1 (2.10): the loan from the central bank -- step {STEP:.1%} of GDP, at most {DEBT_CAP:.0%} of
# GDP of debt to the CB. !! MAINTENANCE !! key-level REPLACE_OR_CREATE of E&F's three scripted guis
# (00_financial_scripted_guis.txt): redo after an E&F update.

REPLACE_OR_CREATE:debt_issued_relative_GDP_increase = {{
	is_shown = {{
	}}
	is_valid = {{
		custom_tooltip = {{
			text = zz_ef_loan_tt_share_max
			var:debt_issued_relative_GDP_percentage < {SHARE_MAX - STEP / 2}
		}}
	}}
	effect = {{
		change_variable = {{
			name = debt_issued_relative_GDP_percentage
			add = {STEP}
		}}
		if = {{
			limit = {{ var:debt_issued_relative_GDP_percentage > {SHARE_MAX} }}
			set_variable = {{ name = debt_issued_relative_GDP_percentage value = {SHARE_MAX} }}
		}}
	}}
}}
REPLACE_OR_CREATE:debt_issued_relative_GDP_reduce = {{
	is_shown = {{
	}}
	is_valid = {{
		custom_tooltip = {{
			text = zz_ef_loan_tt_share_min
			var:debt_issued_relative_GDP_percentage > {STEP * 1.5}
		}}
	}}
	effect = {{
		change_variable = {{
			name = debt_issued_relative_GDP_percentage
			subtract = {STEP}
		}}
		if = {{
			limit = {{ var:debt_issued_relative_GDP_percentage < {STEP} }}
			set_variable = {{ name = debt_issued_relative_GDP_percentage value = {STEP} }}
		}}
	}}
}}
REPLACE_OR_CREATE:set_debt_issued = {{
	is_valid = {{
		custom_tooltip = {{
			text = zz_ef_loan_tt_cap
			zz_ef_cb_loan_after_to_gdp <= {DEBT_CAP}
		}}
	}}
	# E&F's "take" button has no enabled = IsValid binding: the cap is checked in the effect too
	effect = {{
		if = {{
			limit = {{ zz_ef_cb_loan_after_to_gdp <= {DEBT_CAP} }}
			change_variable = {{
				name = credit_at_central_bank
				add = debt_issued_relative_GDP
			}}
			add_treasury = {{
				add = debt_issued_relative_GDP
			}}
			every_scope_state = {{
				if = {{
					limit = {{
						has_modifier = financial_center_historic_place
					}}
					change_variable = {{
						name = stockpiling_bond_var_state_1
						add = owner.bond_creation_by_debt
					}}
				}}
			}}
			change_variable = {{
				name = government_loan
				add = debt_issued_relative_GDP_in_currency
			}}
			credit_at_central_bank_interest_per_week = yes
		}}
	}}
}}
"""

VALUES = f"""# GENERATED by tools/regen_ef_cb_loan.py -- do not edit by hand.
# EF.48, В5.1 (2.10): the debt to the CB after one more loan, a share of GDP (the cap of set_debt_issued).
zz_ef_cb_loan_after_to_gdp = {{
	value = 0
	if = {{ limit = {{ has_variable = credit_at_central_bank }} value = var:credit_at_central_bank }}
	add = debt_issued_relative_GDP
	divide = {{
		value = gdp_var
		min = 1
	}}
}}
zz_ef_cb_loan_now_to_gdp = {{
	value = 0
	if = {{ limit = {{ has_variable = credit_at_central_bank }} value = var:credit_at_central_bank }}
	divide = {{
		value = gdp_var
		min = 1
	}}
}}
"""

NOW = "[GetPlayer.MakeScope.ScriptValue('zz_ef_cb_loan_now_to_gdp')|%1]"
AFTER = "[GetPlayer.MakeScope.ScriptValue('zz_ef_cb_loan_after_to_gdp')|%1]"
TEXTS = {
    "russian": {
        "zz_ef_loan_tt_share_max": f"Доля займа не выше {SHARE_MAX:.0%} ВВП",
        "zz_ef_loan_tt_share_min": f"Доля займа не ниже {STEP:.1%} ВВП",
        "zz_ef_loan_tt_cap": f"Долг центробанку после займа — не больше {DEBT_CAP:.0%} ВВП (сейчас {NOW}, после займа {AFTER})",
    },
    "english": {
        "zz_ef_loan_tt_share_max": f"Loan at most {SHARE_MAX:.0%} of GDP",
        "zz_ef_loan_tt_share_min": f"Loan at least {STEP:.1%} of GDP",
        "zz_ef_loan_tt_cap": f"Debt to the central bank after the loan at most {DEBT_CAP:.0%} of GDP (now {NOW}, after {AFTER})",
    },
}

KEY = "debt_issued_relative_GDP_2"


def ef_text(lang):
    d = os.path.join(EF, "localization", lang)
    for fn in sorted(os.listdir(d)):
        t = open(os.path.join(d, fn), encoding="utf-8-sig").read()
        m = re.search(rf'^\s*{KEY}:\d* "(.*)"\s*$', t, re.M)
        if m:
            return m.group(1)
    raise AssertionError(lang)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write(text)
    print("ok", path)


def main():
    write(os.path.join(HOTFIX, "common", "scripted_guis", "zz_ef_cb_loan.txt"), GUIS)
    write(os.path.join(HOTFIX, "common", "script_values", "zz_ef_cb_loan_values.txt"), VALUES)
    for lang in LANGS:
        src = ef_text(lang)
        old = "[GetPlayer.MakeScope.Var('debt_issued_relative_GDP_percentage').GetValue|%|]"
        assert old in src, lang
        new = src.replace(old, "[GetPlayer.MakeScope.Var('debt_issued_relative_GDP_percentage').GetValue|%1]")
        tx = TEXTS.get(lang, TEXTS["english"])
        lines = [f"l_{lang}:\n", " # GENERATED by tools/regen_ef_cb_loan.py -- do not edit by hand.\n",
                 " # EF.48, В5.1: E&F's loan share with one decimal (step 0.5% of GDP); the loan's limits.\n",
                 f' {KEY}:0 "{new}"\n']
        lines += [f' {k}:0 "{v}"\n' for k, v in tx.items()]
        write(os.path.join(HOTFIX, "localization", lang, "replace", f"zz_ef_cb_loan_replace_l_{lang}.yml"), "".join(lines))


if __name__ == "__main__":
    main()
