#!/usr/bin/env python3
"""
П.6 (the user, 4.10, decisions В.2 / В.3): the world clearing of payments with abroad.

Was (Hume, EF.48 item 6): each country's CB metal moved by its own net flow with abroad (zz_ef_ext_net_week)
with nobody on the other side -- the world's metal was not conserved, it piled up at the big exporters
(night 4.10: Britain x9, Russia x10) and Qing lost all. В2.1 (zz_ef_rc_step, monthly) swapped part of the
exporters' metal for the importers' currency pair by pair on top of it.

Now one clearing house for the world (global variables), in gold:
  * a country with a net OUTFLOW pays it in full into the clearing house: the share in metal by trust in its
    currency (zz_ef_clr_metal_share: 100% at strength to the reference < 0.75, 30% at >= 1.25, linear between),
    at most the metal its CB holds; the rest in its own currency (units of its money, E&F's
    stockpiling_<currency> scale). Fiat: currency only.
  * a country with a net INFLOW takes its inflow x the clearing ratio, at most what the house holds, as an equal
    slice of everything in it: metal into its CB, each foreign currency into its CB's stock
    (stockpiling_<currency>_state_1 on the CB capital state); its own currency coming home is redeemed
    (taken out of the house, a debt abroad gone).
  * the ratio: the countries' weekly steps are spread over the month (no common weekly tick), so the house
    works in windows of 7 days (global var zz_ef_clr_window, days = 7): at a window's start the ratio = what the
    house holds / the inflows claimed during the window before (at most 2); with world payments = world claims
    it is 1. Metal and currency only move between the CBs and the house: nothing appears from nowhere.

П.8 (В.5): E&F's table "currency in the trade balance" (its trade reserve, zeroed by В2.1 -- empty) shows the CB's
foreign currency by currency instead: units, in money, in gold, the week's change (zz_ef_cbfx_*; the list is
filled by our scripted GUI zz_ef_cbfx_update, the table re-issued by tools/regen_ef_economy_panel_gui.py).

Writes (_ef/ef hotfix 1.13/):
  common/scripted_effects/zz_ef_clearing.txt, common/script_values/zz_ef_clearing_values.txt,
  common/scripted_guis/zz_ef_cbfx.txt, localization/<lang>/zz_ef_cbfx_l_<lang>.yml

Usage:
    py tools/regen_ef_clearing.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from regen_ef_reserve_trade import currencies, chain  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
HOTFIX = os.path.normpath(os.path.join(HERE, r"..\_ef\ef hotfix 1.13\common"))
OUT_EFF = os.path.join(HOTFIX, "scripted_effects", "zz_ef_clearing.txt")
OUT_SV = os.path.join(HOTFIX, "script_values", "zz_ef_clearing_values.txt")
OUT_SG = os.path.join(HOTFIX, "scripted_guis", "zz_ef_cbfx.txt")
LOC_DIR = os.path.normpath(os.path.join(HOTFIX, "..", "localization"))
# Е.2: E&F's private banks with a currency stock (global_var:stockpiling_<currency>_company_<bank>_fixe)
BANKS = ["BancaCommercialeItaliana", "BankHSBC", "BankIBC", "BankJPMorgan", "Bankenverein", "BanqueDeParisEtDesPaysBas",
         "DeNederlandscheBank", "DeutscheBank", "Mitsubishiexchangehousebank", "Rothschild_Bank_aus", "Rothschild_Bank_fra",
         "Rothschild_Bank_gbr", "Rothschild_Bank_ger", "Rothschild_Bank_ita", "RotterdamscheBankvereeniging", "amsterdamschebank"]
LANGS = ["english", "russian", "braz_por", "french", "german", "japanese",
         "korean", "polish", "simp_chinese", "spanish", "turkish"]

HEAD = ("# GENERATED by tools/regen_ef_clearing.py -- do not edit by hand.\n"
        "# П.6 (4.10): the world clearing of payments with abroad -- see the generator's docstring.\n")

STEP = """
# The window of the clearing house (7 days): at its start the ratio for the claims of the window.
zz_ef_clr_window_roll = {
	if = {
		limit = { NOT = { has_global_variable = zz_ef_clr_window } }
		set_global_variable = { name = zz_ef_clr_window value = yes days = 7 }
		if = {
			limit = { NOT = { has_global_variable = zz_ef_clr_in_acc } }
			set_global_variable = { name = zz_ef_clr_in_acc value = 0 }
		}
		if = {
			limit = { NOT = { has_global_variable = zz_ef_clr_out_acc } }
			set_global_variable = { name = zz_ef_clr_out_acc value = 0 }
		}
		# П.6а (runs clr1, clr2): the world's net flows do not add up to zero (trade at different markets'
		# prices, countries without a CB), so both sides are scaled. Receivers take at most what the house holds
		# against last window's claims (up to 1.5); payers pay the share that keeps the house near twice a
		# window's claims: min(1, (2 x claims - held) / payments). On random flows (in = out) a receiver gets
		# ~0.8-0.9 of its inflow and the house stays bounded; was: receivers 20% (clr1), the house 187M (clr2).
		set_global_variable = { name = zz_ef_clr_ratio value = 1 }
		set_global_variable = { name = zz_ef_clr_pay_ratio value = 1 }
		if = {
			limit = { global_var:zz_ef_clr_in_acc > 0 }
			set_global_variable = {
				name = zz_ef_clr_ratio
				value = {
					value = zz_ef_clr_pot_value
					divide = global_var:zz_ef_clr_in_acc
					max = zz_ef_clr_take_max
					min = 0
				}
			}
		}
		if = {
			limit = { global_var:zz_ef_clr_out_acc > 0 }
			set_global_variable = {
				name = zz_ef_clr_pay_ratio
				value = {
					value = global_var:zz_ef_clr_in_acc
					multiply = zz_ef_clr_pot_target
					subtract = zz_ef_clr_pot_value
					divide = global_var:zz_ef_clr_out_acc
					max = 1
					min = 0
				}
			}
		}
		# the window just closed, for the tooltip
		set_global_variable = { name = zz_ef_clr_in_last value = global_var:zz_ef_clr_in_acc }
		set_global_variable = { name = zz_ef_clr_out_last value = global_var:zz_ef_clr_out_acc }
		set_global_variable = { name = zz_ef_clr_in_acc value = 0 }
		set_global_variable = { name = zz_ef_clr_out_acc value = 0 }
	}
}

# COUNTRY scope, from zz_ef_cb_hume_step: the week's net flow var:zz_ef_f_ext_net settled through the house.
# Leaves var:zz_ef_f_hume (the CB's metal, native, + in / - out), var:zz_ef_f_clr_cur_out (own currency paid,
# money), var:zz_ef_f_clr_fx_in (foreign currency received, gold), var:zz_ef_f_clr_own_back (own currency
# redeemed, money).
zz_ef_clr_step = {
	set_variable = { name = zz_ef_f_hume value = 0 }
	set_variable = { name = zz_ef_f_clr_cur_out value = 0 }
	set_variable = { name = zz_ef_f_clr_fx_in value = 0 }
	set_variable = { name = zz_ef_f_clr_own_back value = 0 }
	if = {
		limit = {
			has_modifier = has_central_bank
			zz_ef_clr_gold_per_money > 0
			any_scope_state = {
				has_modifier = central_bank_historic_place
				is_capital = yes
			}
		}
		zz_ef_clr_window_roll = yes
		if = {
			limit = { var:zz_ef_f_ext_net < 0 }
			zz_ef_clr_pay = yes
		}
		else_if = {
			limit = { var:zz_ef_f_ext_net > 0 }
			zz_ef_clr_receive = yes
		}
	}
	# П.6а (run clr3): a country without a CB pays its outflow too -- in its currency only (no metal reserves);
	# it takes nothing (no CB to hold it). Its payments were counted as the receivers' inflow (subjects' tribute,
	# the East India Company -> Britain's diplomatic pacts +112K a week) with nothing paid into the house:
	# receivers got 15-40% of their claims. A subject on its overlord's currency pays in that currency, which
	# comes home to the overlord and is redeemed -- nothing out of nothing.
	else_if = {
		limit = {
			NOT = { has_modifier = has_central_bank }
			zz_ef_rc_currency_value > 0.0002
			var:zz_ef_f_ext_net < 0
		}
		zz_ef_clr_window_roll = yes
		zz_ef_clr_pay = yes
	}
}

zz_ef_clr_pay = {
	# the whole outflow in gold
	set_variable = {
		name = zz_ef_clr_due
		value = {
			value = var:zz_ef_f_ext_net
			multiply = -1
			multiply = zz_ef_clr_gold_per_money
		}
	}
	# the world's claims see the whole outflow; the payment is its share (П.6а)
	change_global_variable = { name = zz_ef_clr_out_acc add = var:zz_ef_clr_due }
	change_variable = { name = zz_ef_clr_due multiply = zz_ef_clr_pay_ratio_v }
	# the metal part, native (fiat: none), at most the CB's metal
	set_variable = { name = zz_ef_clr_metal value = 0 }
	if = {
		limit = {
			has_modifier = has_central_bank
			OR = {
				has_law = law_type:law_gold_standard
				has_law = law_type:law_silver_standard
				has_law = law_type:law_bimetallism_standard
			}
			has_variable = money_value_target_1
			var:money_value_target_1 > 0
		}
		set_variable = {
			name = zz_ef_clr_metal
			value = {
				value = var:zz_ef_f_ext_net
				multiply = -1
				multiply = var:money_value_target_1
				multiply = zz_ef_clr_metal_share
				multiply = zz_ef_clr_pay_ratio_v
				max = zz_ef_cb_metal
				min = 0
			}
		}
	}
	every_scope_state = {
		limit = {
			has_modifier = central_bank_historic_place
			is_capital = yes
		}
		if = {
			limit = { owner = { has_law = law_type:law_silver_standard } }
			if = {
				limit = { NOT = { has_variable = silver_state_1 } }
				set_variable = { name = silver_state_1 value = 0 }
			}
			change_variable = { name = silver_state_1 subtract = owner.var:zz_ef_clr_metal }
		}
		else = {
			if = {
				limit = { NOT = { has_variable = gold_state_1 } }
				set_variable = { name = gold_state_1 value = 0 }
			}
			change_variable = { name = gold_state_1 subtract = owner.var:zz_ef_clr_metal }
		}
	}
	set_variable = { name = zz_ef_f_hume value = var:zz_ef_clr_metal }
	change_variable = { name = zz_ef_f_hume multiply = -1 }
	# the metal in gold into the house
	set_variable = { name = zz_ef_clr_mgold value = var:zz_ef_clr_metal }
	if = {
		limit = { has_law = law_type:law_silver_standard }
		change_variable = { name = zz_ef_clr_mgold multiply = silver_to_gold_rate }
	}
	if = {
		limit = { NOT = { has_global_variable = zz_ef_clr_gold } }
		set_global_variable = { name = zz_ef_clr_gold value = 0 }
	}
	change_global_variable = { name = zz_ef_clr_gold add = var:zz_ef_clr_mgold }
	# the rest in the own currency, units of its money at E&F's value in gold
	set_variable = { name = zz_ef_clr_units value = 0 }
	if = {
		limit = {
			zz_ef_rc_currency_value > 0.0002
			var:zz_ef_clr_due > var:zz_ef_clr_mgold
		}
		set_variable = { name = zz_ef_clr_units value = var:zz_ef_clr_due }
		change_variable = { name = zz_ef_clr_units subtract = var:zz_ef_clr_mgold }
		change_variable = { name = zz_ef_clr_units divide = zz_ef_rc_currency_value }
		zz_ef_clr_put_own = yes
	}
	set_variable = { name = zz_ef_f_clr_cur_out value = var:zz_ef_clr_units }
	remove_variable = zz_ef_clr_due
	remove_variable = zz_ef_clr_metal
	remove_variable = zz_ef_clr_mgold
	remove_variable = zz_ef_clr_units
}

zz_ef_clr_receive = {
	set_variable = {
		name = zz_ef_clr_claim
		value = {
			value = var:zz_ef_f_ext_net
			multiply = zz_ef_clr_gold_per_money
		}
	}
	change_global_variable = { name = zz_ef_clr_in_acc add = var:zz_ef_clr_claim }
	set_variable = { name = zz_ef_clr_pot value = zz_ef_clr_pot_value }
	if = {
		limit = { var:zz_ef_clr_pot > 0 }
		# the slice of everything in the house
		set_variable = {
			name = zz_ef_clr_g
			value = {
				value = var:zz_ef_clr_claim
				multiply = global_var:zz_ef_clr_ratio
				divide = var:zz_ef_clr_pot
				max = 1
				min = 0
			}
		}
		# metal: gold from the house, native into the CB
		set_variable = { name = zz_ef_clr_mgold value = 0 }
		if = {
			limit = { has_global_variable = zz_ef_clr_gold }
			set_variable = {
				name = zz_ef_clr_mgold
				value = {
					value = global_var:zz_ef_clr_gold
					multiply = var:zz_ef_clr_g
					min = 0
				}
			}
			change_global_variable = { name = zz_ef_clr_gold subtract = var:zz_ef_clr_mgold }
		}
		set_variable = { name = zz_ef_f_hume value = var:zz_ef_clr_mgold }
		if = {
			limit = { has_law = law_type:law_silver_standard }
			change_variable = { name = zz_ef_f_hume multiply = gold_to_silver_rate }
		}
		every_scope_state = {
			limit = {
				has_modifier = central_bank_historic_place
				is_capital = yes
			}
			if = {
				limit = { owner = { has_law = law_type:law_silver_standard } }
				if = {
					limit = { NOT = { has_variable = silver_state_1 } }
					set_variable = { name = silver_state_1 value = 0 }
				}
				change_variable = { name = silver_state_1 add = owner.var:zz_ef_f_hume }
			}
			else = {
				if = {
					limit = { NOT = { has_variable = gold_state_1 } }
					set_variable = { name = gold_state_1 value = 0 }
				}
				change_variable = { name = gold_state_1 add = owner.var:zz_ef_f_hume }
			}
			save_scope_as = clr_cb
		}
		# currencies
		save_scope_as = clr_rcv
		zz_ef_clr_take_all = yes
		remove_variable = zz_ef_clr_g
		remove_variable = zz_ef_clr_mgold
	}
	remove_variable = zz_ef_clr_claim
	remove_variable = zz_ef_clr_pot
}
"""


def effects(cur):
    out = [HEAD, STEP]
    out.append("\n# The payer's own currency into the house: var:zz_ef_clr_units of its money.\n"
               "zz_ef_clr_put_own = {\n")
    out.append(chain(cur, lambda c: (
        f"if = {{ limit = {{ NOT = {{ has_global_variable = zz_ef_clr_c_{c} }} }} "
        f"set_global_variable = {{ name = zz_ef_clr_c_{c} value = 0 }} }} "
        f"change_global_variable = {{ name = zz_ef_clr_c_{c} add = var:zz_ef_clr_units }}")))
    out.append("}\n")
    out.append("\n# scope:clr_rcv (the receiver), var:zz_ef_clr_g = its slice: each currency of the house -- its own\n"
               "# redeemed, a foreign one into its CB's stock (scope:clr_cb).\n"
               "zz_ef_clr_take_all = {\n")
    for c in cur:
        out.append(
            f"\tif = {{\n"
            f"\t\tlimit = {{ has_global_variable = zz_ef_clr_c_{c} global_var:zz_ef_clr_c_{c} > 0 }}\n"
            f"\t\tset_variable = {{ name = zz_ef_clr_u value = {{ value = global_var:zz_ef_clr_c_{c} multiply = var:zz_ef_clr_g }} }}\n"
            f"\t\tchange_global_variable = {{ name = zz_ef_clr_c_{c} subtract = var:zz_ef_clr_u }}\n"
            f"\t\tif = {{\n"
            f"\t\t\tlimit = {{ has_law = law_type:law_{c}_currency }}\n"
            f"\t\t\tchange_variable = {{ name = zz_ef_f_clr_own_back add = var:zz_ef_clr_u }}\n"
            f"\t\t}}\n"
            f"\t\telse = {{\n"
            f"\t\t\tscope:clr_cb = {{\n"
            f"\t\t\t\tif = {{ limit = {{ NOT = {{ has_variable = stockpiling_{c}_state_1 }} }} set_variable = {{ name = stockpiling_{c}_state_1 value = 0 }} }}\n"
            f"\t\t\t\tchange_variable = {{ name = stockpiling_{c}_state_1 add = scope:clr_rcv.var:zz_ef_clr_u }}\n"
            f"\t\t\t}}\n"
            f"\t\t\tchange_variable = {{ name = zz_ef_f_clr_fx_in add = {{ value = var:zz_ef_clr_u multiply = money_value_{c} }} }}\n"
            f"\t\t}}\n"
            f"\t\tremove_variable = zz_ef_clr_u\n"
            f"\t}}\n")
    out.append("}\n")
    out.append("\n# П.8: the week's change of each foreign currency in the CB (country vars zz_ef_cbfx_d_<c>), from the\n"
               "# money model's weekly step.\n"
               "zz_ef_cbfx_week_step = {\n")
    for c in cur:
        out.append(f"\tif = {{ limit = {{ OR = {{ zz_ef_cbfx_{c} > 0 has_variable = zz_ef_cbfx_p_{c} }} }} "
                   f"set_variable = {{ name = zz_ef_cbfx_d_{c} value = zz_ef_cbfx_{c} }} "
                   f"if = {{ limit = {{ has_variable = zz_ef_cbfx_p_{c} }} change_variable = {{ name = zz_ef_cbfx_d_{c} subtract = var:zz_ef_cbfx_p_{c} }} }} "
                   f"set_variable = {{ name = zz_ef_cbfx_p_{c} value = zz_ef_cbfx_{c} }} }}\n")
    out.append("}\n")
    return "".join(out)


VALUES = """
# В.3 (the user, 4.10): the payer's metal share by trust in its currency -- its strength against the reference
# (zz_ef_currency_strength): 100% under 0.75, 30% at 1.25 and over, linear between.
zz_ef_clr_metal_share_low = 0.75
zz_ef_clr_metal_share_high = 1.25
zz_ef_clr_metal_share_min = 0.3
zz_ef_clr_metal_share = {
	value = zz_ef_currency_strength
	subtract = zz_ef_clr_metal_share_low
	divide = {
		value = zz_ef_clr_metal_share_high
		subtract = zz_ef_clr_metal_share_low
	}
	multiply = {
		value = 1
		subtract = zz_ef_clr_metal_share_min
	}
	multiply = -1
	add = 1
	max = 1
	min = zz_ef_clr_metal_share_min
}
# Gold a unit of the scope country's money pays / claims abroad: at the parity under a metal standard (as Hume
# settled), else E&F's value of its currency in gold.
zz_ef_clr_gold_per_money = {
	value = zz_ef_rc_currency_value
	if = {
		limit = {
			OR = {
				has_law = law_type:law_gold_standard
				has_law = law_type:law_silver_standard
				has_law = law_type:law_bimetallism_standard
			}
			has_variable = money_value_target_1
			var:money_value_target_1 > 0
		}
		value = var:money_value_target_1
		if = {
			limit = { has_law = law_type:law_silver_standard }
			multiply = silver_to_gold_rate
		}
	}
	min = 0
}
# The week's results (0 if unset), for the cards and the log.
zz_ef_v_f_clr_cur_out = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_clr_cur_out } value = var:zz_ef_f_clr_cur_out }
}
zz_ef_v_f_clr_fx_in = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_clr_fx_in } value = var:zz_ef_f_clr_fx_in }
}
zz_ef_v_f_clr_own_back = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_clr_own_back } value = var:zz_ef_f_clr_own_back }
}
# the foreign currency received, in the receiver's money (gold / its gold a unit)
zz_ef_v_f_clr_fx_in_money = {
	value = 0
	if = {
		limit = { zz_ef_clr_gold_per_money > 0 }
		value = zz_ef_v_f_clr_fx_in
		divide = zz_ef_clr_gold_per_money
	}
}
# П.6а: the house's limits -- receivers take at most 1.5 of their claim; payers keep the house near 2 windows' claims
zz_ef_clr_take_max = 1.5
zz_ef_clr_pot_target = 2
zz_ef_clr_pay_ratio_v = {
	value = 1
	if = { limit = { has_global_variable = zz_ef_clr_pay_ratio } value = global_var:zz_ef_clr_pay_ratio }
}
# this receiver's clearing, in money (the abroad card's reserve assets, П.17): metal at the parity, currency
zz_ef_v_f_clr_metal_money = {
	value = 0
	if = {
		limit = { has_variable = zz_ef_f_hume has_variable = money_value_target_1 var:money_value_target_1 > 0 }
		value = var:zz_ef_f_hume
		divide = zz_ef_cb_valuation
	}
}
zz_ef_v_f_clr_fx_money = {
	value = 0
	if = {
		limit = { zz_ef_clr_gold_per_money > 0 }
		value = zz_ef_v_f_clr_fx_in
		divide = zz_ef_clr_gold_per_money
	}
	subtract = zz_ef_v_f_clr_cur_out
	add = zz_ef_v_f_clr_own_back
}
# the reserves' change by the clearing and what the clearing did not settle this week (the BoP's errors and omissions)
zz_ef_v_f_clr_reserves_money = {
	value = zz_ef_v_f_clr_metal_money
	add = zz_ef_v_f_clr_fx_money
}
zz_ef_v_f_clr_unsettled = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_ext_net } value = var:zz_ef_f_ext_net }
	subtract = zz_ef_v_f_clr_reserves_money
}
zz_ef_clr_ratio_v = {
	value = 1
	if = { limit = { has_global_variable = zz_ef_clr_ratio } value = global_var:zz_ef_clr_ratio }
}
# the window just closed (world inflows claimed / payments made, gold), for the tooltip
zz_ef_clr_in_last_v = {
	value = 0
	if = { limit = { has_global_variable = zz_ef_clr_in_last } value = global_var:zz_ef_clr_in_last }
}
zz_ef_clr_out_last_v = {
	value = 0
	if = { limit = { has_global_variable = zz_ef_clr_out_last } value = global_var:zz_ef_clr_out_last }
}
# for the monthly log: 1 for a customs union member that settles with the market owner (В3.3)
zz_ef_cu_member_v = {
	value = 0
	if = { limit = { zz_ef_cu_member = yes } value = 1 }
}
# Е.1: the amount of the player's currency on a holder (zz_ef_holders_update), for ordering the list
zz_ef_holds_pc_v = {
	value = 0
	if = { limit = { has_variable = zz_ef_holds_pc } value = var:zz_ef_holds_pc }
}
zz_ef_clr_gold_v = {
	value = 0
	if = { limit = { has_global_variable = zz_ef_clr_gold } value = global_var:zz_ef_clr_gold }
}
"""


def values(cur):
    out = [HEAD, VALUES]
    out.append("# Everything the house holds, in gold: metal + each currency at E&F's value.\n"
               "zz_ef_clr_pot_value = {\n\tvalue = zz_ef_clr_gold_v\n")
    for c in cur:
        out.append(f"\tif = {{ limit = {{ has_global_variable = zz_ef_clr_c_{c} }} add = {{ value = global_var:zz_ef_clr_c_{c} "
                   f"multiply = money_value_{c} min = 0 }} }}\n")
    out.append("\tmin = 0\n}\n")
    out.append("# The scope country's own currency waiting in the house (its money): a debt abroad, as zz_ef_fx_liab.\n"
               "zz_ef_clr_own_in_pot = {\n\tvalue = 0\n")
    out.append(chain(cur, lambda c: f"if = {{ limit = {{ has_global_variable = zz_ef_clr_c_{c} }} value = global_var:zz_ef_clr_c_{c} }}"))
    out.append("\tmin = 0\n}\n")
    out.append("\n# Е.2 (5.10): the scope country's currency held by each of E&F's private banks (its arbitrage stock,\n"
               "# global_var:stockpiling_<currency>_company_<bank>_fixe), in units of the scope country's money.\n")
    for b in BANKS:
        out.append(f"zz_ef_bank_holds_{b} = {{\n\tvalue = 0\n")
        out.append(chain(cur, lambda c: f"if = {{ limit = {{ has_global_variable = stockpiling_{c}_company_{b}_fixe }} "
                                        f"value = global_var:stockpiling_{c}_company_{b}_fixe }}"))
        out.append("\tmin = 0\n}\n")
    out.append("\n# П.8: the CB's stock of each foreign currency (the capital CB state, as the clearing and В2.1 keep it):\n"
               "# units, in gold (E&F's value), in the holder's money, the week's change.\n")
    for c in cur:
        out.append(f"zz_ef_cbfx_{c} = {{ value = 0 capital = {{ if = {{ limit = {{ has_variable = stockpiling_{c}_state_1 }} "
                   f"add = var:stockpiling_{c}_state_1 }} }} min = 0 }}\n"
                   f"zz_ef_cbfx_{c}_gold = {{ value = zz_ef_cbfx_{c} multiply = money_value_{c} }}\n"
                   f"zz_ef_cbfx_{c}_money = {{ value = 0 if = {{ limit = {{ zz_ef_clr_gold_per_money > 0 }} "
                   f"value = zz_ef_cbfx_{c}_gold divide = zz_ef_clr_gold_per_money }} }}\n"
                   f"zz_ef_cbfx_{c}_d = {{ value = 0 if = {{ limit = {{ has_variable = zz_ef_cbfx_d_{c} }} value = var:zz_ef_cbfx_d_{c} }} }}\n")
    return "".join(out)


def sguis(cur):
    out = [HEAD, "# П.8: the CB's foreign currencies for E&F's table (global list zz_ef_cbfx_list of E&F's currency scopes).\n"
           "zz_ef_cbfx_update = {\n\teffect = {\n\t\tclear_global_variable_list = zz_ef_cbfx_list\n"]
    for c in cur:
        out.append(f"\t\tif = {{ limit = {{ zz_ef_cbfx_{c} > 0 NOT = {{ has_law = law_type:law_{c}_currency }} }} "
                   f"add_to_global_variable_list = {{ name = zz_ef_cbfx_list target = global_var:currency_import_export_value_{c}_03 }} }}\n")
    out.append("\t}\n}\n")
    # П.16: the same list sorted by the stock's value in gold, the biggest first (selection: the largest not yet
    # listed, again and again)
    out.append("\n# П.16 (4.10): E&F's table sorted by value in gold, the biggest first.\n"
               "zz_ef_cbfx_update_sorted = {\n\teffect = {\n\t\tclear_global_variable_list = zz_ef_cbfx_list\n"
               "\t\tset_variable = { name = zz_ef_cbfx_n value = 0 }\n")
    for c in cur:
        out.append(f"\t\tif = {{ limit = {{ zz_ef_cbfx_{c}_gold > 0 NOT = {{ has_law = law_type:law_{c}_currency }} }} "
                   f"change_variable = {{ name = zz_ef_cbfx_n add = 1 }} set_variable = {{ name = zz_ef_cbfx_left_{c} value = yes }} }}\n")
    out.append("\t\twhile = {\n\t\t\tlimit = { var:zz_ef_cbfx_n > 0 }\n"
               "\t\t\tset_variable = { name = zz_ef_cbfx_max value = -1 }\n")
    for c in cur:
        out.append(f"\t\t\tif = {{ limit = {{ has_variable = zz_ef_cbfx_left_{c} zz_ef_cbfx_{c}_gold > var:zz_ef_cbfx_max }} "
                   f"set_variable = {{ name = zz_ef_cbfx_max value = zz_ef_cbfx_{c}_gold }} }}\n")
    out.append("\t\t\tset_variable = { name = zz_ef_cbfx_done value = no }\n")
    for c in cur:
        out.append(f"\t\t\tif = {{ limit = {{ var:zz_ef_cbfx_done = no has_variable = zz_ef_cbfx_left_{c} zz_ef_cbfx_{c}_gold >= var:zz_ef_cbfx_max }} "
                   f"add_to_global_variable_list = {{ name = zz_ef_cbfx_list target = global_var:currency_import_export_value_{c}_03 }} "
                   f"remove_variable = zz_ef_cbfx_left_{c} set_variable = {{ name = zz_ef_cbfx_done value = yes }} }}\n")
    out.append("\t\t\tchange_variable = { name = zz_ef_cbfx_n subtract = 1 }\n\t\t}\n"
               "\t\tremove_variable = zz_ef_cbfx_n\n\t\tremove_variable = zz_ef_cbfx_max\n\t\tremove_variable = zz_ef_cbfx_done\n"
               "\t}\n}\n")
    # П.18: who holds our currency -- the other CBs' stocks of the player's currency, for a pie chart
    out.append("\n# П.18 (4.10): the other CBs holding the player's currency (global list zz_ef_holders_list; the amount\n"
               "# in the player's money on each holder, var:zz_ef_holds_pc), for the pie chart in the trade balance.\n"
               "# Е.1 (5.10): biggest holder first -- the amounts are set first, then ordered_country fills the list.\n"
               "zz_ef_holders_update = {\n\teffect = {\n\t\tclear_global_variable_list = zz_ef_holders_list\n"
               "\t\tsave_scope_as = holders_root\n"
               "\t\tevery_country = { limit = { has_variable = zz_ef_holds_pc } remove_variable = zz_ef_holds_pc }\n")
    for i, c in enumerate(cur):
        kw = "if" if i == 0 else "else_if"
        out.append(f"\t\t{kw} = {{ limit = {{ has_law = law_type:law_{c}_currency }} every_country = {{ limit = {{ NOT = {{ this = scope:holders_root }} "
                   f"NOT = {{ has_law = law_type:law_{c}_currency }} has_modifier = has_central_bank capital = {{ has_variable = stockpiling_{c}_state_1 "
                   f"var:stockpiling_{c}_state_1 > 0 }} }} set_variable = {{ name = zz_ef_holds_pc value = capital.var:stockpiling_{c}_state_1 }} }} }}\n")
    out.append("\t\tordered_country = { limit = { has_variable = zz_ef_holds_pc } order_by = zz_ef_holds_pc_v max = 1000 check_range_bounds = no "
               "add_to_global_variable_list = { name = zz_ef_holders_list target = this } }\n")
    # Е.2: the private banks holding our currency (zz_ef_bank_holders_list of company scopes, var:zz_ef_bank_holds_pc on
    # each), the biggest first -- the banks sit in different countries, so a selection like zz_ef_cbfx_update_sorted
    out.append("\t\t# Е.2 (5.10): E&F's private banks holding our currency, the biggest first\n"
               "\t\tclear_global_variable_list = zz_ef_bank_holders_list\n"
               "\t\tset_variable = { name = zz_ef_bh_n value = 0 }\n")
    for b in BANKS:
        out.append(f"\t\tset_variable = {{ name = zz_ef_bh_{b} value = zz_ef_bank_holds_{b} }}\n"
                   f"\t\tif = {{ limit = {{ var:zz_ef_bh_{b} > 0 }} change_variable = {{ name = zz_ef_bh_n add = 1 }} }}\n")
    out.append("\t\twhile = {\n\t\t\tlimit = { var:zz_ef_bh_n > 0 }\n\t\t\tset_variable = { name = zz_ef_bh_max value = 0 }\n")
    for b in BANKS:
        out.append(f"\t\t\tif = {{ limit = {{ var:zz_ef_bh_{b} > var:zz_ef_bh_max }} set_variable = {{ name = zz_ef_bh_max value = var:zz_ef_bh_{b} }} }}\n")
    out.append("\t\t\tset_variable = { name = zz_ef_bh_done value = no }\n")
    for b in BANKS:
        out.append(f"\t\t\tif = {{ limit = {{ var:zz_ef_bh_done = no var:zz_ef_bh_{b} > 0 var:zz_ef_bh_{b} >= var:zz_ef_bh_max }} "
                   f"every_country = {{ limit = {{ has_company = company_type:company_{b} }} every_company = {{ limit = {{ "
                   f"is_company_type = company_type:company_{b} }} set_variable = {{ name = zz_ef_bank_holds_pc value = scope:holders_root.var:zz_ef_bh_{b} }} "
                   f"add_to_global_variable_list = {{ name = zz_ef_bank_holders_list target = this }} }} }} "
                   f"set_variable = {{ name = zz_ef_bh_{b} value = 0 }} set_variable = {{ name = zz_ef_bh_done value = yes }} }}\n")
    out.append("\t\t\tchange_variable = { name = zz_ef_bh_n subtract = 1 }\n\t\t}\n"
               "\t\tremove_variable = zz_ef_bh_n\n\t\tremove_variable = zz_ef_bh_max\n\t\tremove_variable = zz_ef_bh_done\n")
    for b in BANKS:
        out.append(f"\t\tremove_variable = zz_ef_bh_{b}\n")
    out.append("\t}\n}\n")
    return "".join(out)


def write_loc(cur):
    for lang in LANGS:
        ru = lang == "russian"
        w = "за неделю" if ru else "a week"
        sv = lambda n: f"[GetPlayer.MakeScope.ScriptValue('{n}')"
        lines = [f"l_{lang}:\n",
                 ' zz_ef_ep_cbfx_title:0 "%s"\n' % ("Резервы ЦБ по валютам" if ru else "CB reserves by currency"),
                 ' zz_ef_ep_cbfx_tt:0 "%s"\n' % (
                     "Чужая валюта в резервах ЦБ (мировой клиринг): количество, в наших деньгах, в золоте и изменение "
                     "за неделю. В подсказке денежной массы она в счёте «Заграница» и учтена в покрытии." if ru else
                     "Foreign currency in the CB's reserves (the world clearing): units, in our money, in gold and the "
                     "week's change. In the money supply tooltip it is in the 'Abroad' account and counts in the cover.")]
        for c in cur:
            lines.append(f' {c}_03_zz_cbfx_units:0 "#v {sv("zz_ef_cbfx_" + c)}|D]#! @{c}!"\n')
            lines.append(f' {c}_03_zz_cbfx_money:0 "{sv("zz_ef_cbfx_" + c + "_money")}|D] [GetPlayer.GetCustom(\'currency_symbol\')]"\n')
            lines.append(f' {c}_03_zz_cbfx_gold:0 "{sv("zz_ef_cbfx_" + c + "_gold")}|D] @gold! ({sv("zz_ef_cbfx_" + c + "_d")}|+D] {w})"\n')
        p = os.path.join(LOC_DIR, lang, f"zz_ef_cbfx_l_{lang}.yml")
        with open(p, "w", encoding="utf-8-sig", newline="\n") as f:
            f.write("".join(lines))


def main():
    cur = currencies()
    write_loc(cur)
    for path, text in ((OUT_EFF, effects(cur)), (OUT_SV, values(cur)), (OUT_SG, sguis(cur))):
        assert text.count("{") == text.count("}"), path
        with open(path, "w", encoding="utf-8-sig", newline="\n") as f:
            f.write(text)
        print("ok", len(cur), "currencies ->", path)


if __name__ == "__main__":
    main()
