#!/usr/bin/env python3
"""
В5.5 (decided by the user 5.10; with EF.37, Ф.10): a bond is a part of the engine's government debt.

The engine's debt (principal) is the treasury's loan from its own economy: the interest goes to the pops whose
privately owned cash reserves back the loans (vanilla concept_budget_interest_desc; the nationally owned part lowers
the government dividends). The engine takes and repays it alone. E&F's treasury bonds (ai_buy_bond_1..10: the buyer's
treasury pays the price, the seller gets nothing; the buyer's interest is E&F's income modifier from nobody, since
Е.5 / Д.2 the seller paid it as an expense line; at maturity the buyer gets the price back from nobody) become a
record of WHO HOLDS A PART of the seller's principal:

  1. purchase  -- the price goes into the seller's bank pool (not its treasury), at most the seller's principal minus
                  the parts already held; the rest goes back to the buyer's treasury;
  2. interest  -- the seller pays the engine as usual; the holder gets (its part / principal) x the week's interest
                  (the bridge's GetInterestPayment, var:zz_ef_g_ipay), out of the seller's pool (the pool took the
                  price: it sold part of its claim). E&F's income modifier and our Д.2 expense line go;
  3. repayment -- the engine repays alone; the principal under the parts held -> each holder gets the difference back
                  from the seller's pool; E&F's maturity -> the part is bought back from the seller's pool (E&F's
                  payout from nobody removed);
  4. default   -- the principal falls by more than half in a week while the country is in default (in_default): the
                  parts over it are written off, nobody pays; a fast repayment out of default is bought back (5.10 evening).
Weekly, in the money model's step: the holder walks its 10 slots; the seller's side is summed in var:zz_ef_bl_acc_*
and rolled into var:zz_ef_f_bl_* at its own step (at most a week late). The bond tables (Е.6) -- later.

Private banks' bonds (В1.6, the user 5.10 evening: "as В5.5"): E&F's ai_privat_bank_bond_N / _renforcement (25 slots on
the buyer country, var:ai_privat_bank_bond_value_N, the seller in its list ai_privat_bank_seller_country_general_N) took
the price out of the buyer's pool and gave the seller nothing -- run s1e: one-off flows without a counterpart of
6-16M a month (Britain 1837.1, 1838.1; Qing 1837.8). The ledger watches each slot weekly: a rise of E&F's value is a
purchase -- the part (at most the seller's room) into the seller's pool, the rest back to the buyer's pool and off
E&F's value (its interest scaled with it); the principal under the parts -> the part bought back from the seller's
pool into the buyer's; E&F dropping the value (its seller gone) -- written off. The banks' yearly interest stays as
Ф.2 pays it (the issuer's treasury, bf28108). The parts count in the seller's var:zz_ef_bl_held with the treasury's.

A rise with no seller found in E&F's list goes back whole (run s1g: Britain 1838.1, 1.95M unpaired; log line EFP).

Only existing debt (the user 5.10 evening): E&F picks the seller by its own remaining_debt; the treasury's
ai_buy_bond_1..10, the banks' seller list central_bank_debt_variable_list and ai_privat_bank_bond_N_renforcement also
require room in the seller's engine debt (zz_ef_bl_room > 0) -- was: almost every purchase went back to the buyer
(run s1b: principal 0 everywhere).

Writes (via ld_gen, by entry keys, into the fork «E&F: Ledgerdemain»):
  common/scripted_effects/ld_bond_ledger.txt          -- the ledger (generated slots);
  common/script_values/ld_bond_ledger_values.txt      -- its script values.
The changes of E&F's own effects (ai_buy_bond_N / central_bank_debt_variable_list / ai_privat_bank_bond_N_renforcement
with the room test zz_ef_bl_room > 0; ai_bond_maturity_N without the payout; interest_per_month_from_foreign_debt_investment)
are in E&F's bodies; the generator does not read E&F.

Usage:
    py tools/regen_ef_bond_ledger.py [--check]    # --check: exit 1 if the fork files differ
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

OUT_LEDGER = "common/scripted_effects/zz_ef_bond_ledger.txt"        # пути хотфикса; ld_gen пишет в форк (ld_*)
OUT_VALUES = "common/script_values/zz_ef_bond_ledger_values.txt"
SLOTS = range(1, 11)
PB_SLOTS = range(1, 26)
HEAD = "# GENERATED by tools/regen_ef_bond_ledger.py -- do not edit by hand.\n"


def slot(n):
    return f"""
# treasury slot {n}: E&F's purchase ai_buy_bond_{n} (ai_buy_bond_{n}_on / ai_seller_country_general_{n} /
# ai_total_bond_value_{n}) -> the register, the slot freed for E&F's next purchase
zz_ef_bl_slot_{n} = {{
	if = {{
		limit = {{
			has_variable = ai_buy_bond_{n}_on
			var:ai_buy_bond_{n}_on = 1
			has_variable = ai_seller_country_general_{n}
			has_variable = ai_total_bond_value_{n}
			exists = var:ai_seller_country_general_{n}
			var:ai_seller_country_general_{n} = {{ is_country_type = recognized }}
		}}
		var:ai_seller_country_general_{n} = {{ save_scope_as = zz_ef_bl_seller }}
		set_variable = {{ name = zz_ef_bl_x value = var:ai_total_bond_value_{n} }}
		zz_ef_bl_register = {{ H = tr FB = bl INTO = treasury }}
		zz_ef_bl_slot_free = {{ N = {n} }}
	}}
}}
"""


def pb_slot(n):
    return f"""
# private banks' slot {n}: E&F's purchase ai_privat_bank_bond_{n} / _renforcement (ai_privat_bank_bond_value_{n}, the
# seller from its list ai_privat_bank_seller_country_general_{n}) -> the register; E&F's value back to 0
zz_ef_pb_slot_{n} = {{
	if = {{
		limit = {{
			has_variable = ai_privat_bank_bond_value_{n}
			var:ai_privat_bank_bond_value_{n} > 0
		}}
		set_variable = {{ name = zz_ef_bl_x value = var:ai_privat_bank_bond_value_{n} }}
		if = {{
			limit = {{ has_variable_list = ai_privat_bank_seller_country_general_{n} }}
			random_in_list = {{
				variable = ai_privat_bank_seller_country_general_{n}
				limit = {{ is_country_type = recognized }}
				save_scope_as = zz_ef_pbsel_{n}
			}}
		}}
		if = {{
			limit = {{ exists = scope:zz_ef_pbsel_{n} }}
			scope:zz_ef_pbsel_{n} = {{ save_scope_as = zz_ef_bl_seller }}
			zz_ef_bl_register = {{ H = bk FB = pb INTO = pool }}
		}}
		else = {{
			zz_ef_pb_no_seller = yes
		}}
		set_variable = {{ name = ai_privat_bank_bond_value_{n} value = 0 }}
		if = {{ limit = {{ has_variable = ai_privat_bank_interest_calculated_{n} }} set_variable = {{ name = ai_privat_bank_interest_calculated_{n} value = 0 }} }}
	}}
}}
"""


def ledger():
    slots = "".join(slot(n) for n in SLOTS)
    calls = "".join(f"\tzz_ef_bl_slot_{n} = yes\n" for n in SLOTS)
    calls += "\t# private banks (В1.6)\n" + "".join(f"\tzz_ef_pb_slot_{n} = yes\n" for n in PB_SLOTS)
    pslots = "".join(pb_slot(n) for n in PB_SLOTS)
    frees = "".join(f"\t\t\tset_variable = {{ name = {v}_$N$ value = 0 }}\n" for v in (
        "ai_buy_bond", "ai_interest_purchasing", "ai_bond_quantity", "ai_quantity_purchasing",
        "ai_selle_bond_maturity_yers_time", "ai_interest_calculated", "ai_total_bond_value",
        "ai_interest_at_term_calculated", "ai_interest_per_month_calculated", "ai_selle_bond_maturity_yers"))
    frees = frees.replace("name = ai_buy_bond_$N$ value", "name = ai_buy_bond_$N$_on value")
    return HEAD + f"""# В5.5 (5.10), R8б.2: bonds as parts of the seller's engine debt, held in the register of claims -- see the
# generator's docstring. Values: script_values/ld_bond_ledger_values.txt (generated with this file).

# Country scope, weekly (zz_ef_money_model_step): the seller's side first (roll last week's sums, the ratio of the
# principal to the parts held abroad), then as a holder: E&F's new purchases into the register, then every holding.
zz_ef_bond_ledger_step = {{
	# --- as a seller ---
	zz_ef_bl_roll = {{ F = sold }}
	zz_ef_bl_roll = {{ F = int_out }}
	zz_ef_bl_roll = {{ F = redeem }}
	zz_ef_bl_roll = {{ F = woff }}
	set_variable = {{ name = zz_ef_bl_ratio value = 1 }}
	if = {{ limit = {{ has_variable = zz_ef_bl_woff_now }} remove_variable = zz_ef_bl_woff_now }}
	if = {{
		limit = {{
			zz_ef_bl_held_v > 0
			zz_ef_bl_principal < zz_ef_bl_held_v
		}}
		set_variable = {{ name = zz_ef_bl_ratio value = {{ value = zz_ef_bl_principal divide = zz_ef_bl_held_v }} }}
		# default: the principal more than halved in a week IN DEFAULT -> the parts over it are written off; a repayment
		# is bought back from the pool, only the engine's default (in_default) writes off
		if = {{
			limit = {{
				has_variable = zz_ef_bl_prev_principal
				zz_ef_bl_principal < zz_ef_bl_half_prev
				in_default = yes
			}}
			set_variable = {{ name = zz_ef_bl_woff_now value = yes }}
		}}
	}}
	set_variable = {{ name = zz_ef_bl_prev_principal value = zz_ef_bl_principal }}
	# --- as a holder ---
	set_variable = {{ name = zz_ef_f_bl_buy value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_refund value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_int_in value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_back value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_lost value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_int_short value = 0 }}
	set_variable = {{ name = zz_ef_f_pb_buy value = 0 }}
	set_variable = {{ name = zz_ef_f_pb_refund value = 0 }}
	set_variable = {{ name = zz_ef_f_pb_back value = 0 }}
	set_variable = {{ name = zz_ef_f_pb_int_in value = 0 }}
{calls}	zz_ef_bl_hold_map = {{ H = tr FB = bl INTO = treasury }}
	zz_ef_bl_hold_map = {{ H = bk FB = pb INTO = pool }}
	if = {{
		limit = {{
			OR = {{
				zz_ef_log_country = yes
				zz_ef_bl_held_v > 0
				zz_ef_bl_parts > 0
				zz_ef_bank_bonds > 0
			}}
		}}
		if = {{ limit = {{ zz_ef_logs_on = yes }} debug_log = "EFB|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|principal [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_bl_principal')|0]|held [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_bl_held_v')|0]|ratio [THIS.GetCountry.MakeScope.Var('zz_ef_bl_ratio').GetValue|3]|ipay [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_g_ipay')|0]|sold [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_sold')|0]|int_out [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_int_out')|0]|redeem [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_redeem')|0]|woff [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_woff')|0]|parts [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_treasury_bonds')|0]|buy [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_buy').GetValue|0]|refund [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_refund').GetValue|0]|int_in [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_int_in').GetValue|0]|back [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_back').GetValue|0]|lost [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_lost').GetValue|0]|pb_buy [THIS.GetCountry.MakeScope.Var('zz_ef_f_pb_buy').GetValue|0]|pb_refund [THIS.GetCountry.MakeScope.Var('zz_ef_f_pb_refund').GetValue|0]|pb_back [THIS.GetCountry.MakeScope.Var('zz_ef_f_pb_back').GetValue|0]|pb_int [THIS.GetCountry.MakeScope.Var('zz_ef_f_pb_int_in').GetValue|0]|pbonds [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_bank_bonds')|0]" }}
	}}
}}

# var:zz_ef_f_bl_$F$ = var:zz_ef_bl_acc_$F$ (summed by the holders since our last step); the sum restarts.
zz_ef_bl_roll = {{
	set_variable = {{ name = zz_ef_f_bl_$F$ value = 0 }}
	if = {{
		limit = {{ has_variable = zz_ef_bl_acc_$F$ }}
		set_variable = {{ name = zz_ef_f_bl_$F$ value = var:zz_ef_bl_acc_$F$ }}
	}}
	set_variable = {{ name = zz_ef_bl_acc_$F$ value = 0 }}
}}

# Holder scope: a purchase of var:zz_ef_bl_x from scope:zz_ef_bl_seller. The part is at most the seller's room
# (principal - the parts held abroad); the rest back where it came from ($INTO$: treasury | pool); the part -- a claim
# in our map zz_ef_rq_$H$_b, its price into the seller's pool (its banks sold a part of their claim on the engine's debt).
zz_ef_bl_register = {{
	set_variable = {{ name = zz_ef_bl_y value = var:zz_ef_bl_x }}
	change_variable = {{ name = zz_ef_bl_y subtract = scope:zz_ef_bl_seller.zz_ef_bl_room }}
	if = {{
		limit = {{ var:zz_ef_bl_y > 0 }}
		change_variable = {{ name = zz_ef_bl_x subtract = var:zz_ef_bl_y }}
		set_variable = {{ name = zz_ef_bl_z value = var:zz_ef_bl_x }}
		set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_bl_y }}
		zz_ef_bl_into_$INTO$ = yes
		change_variable = {{ name = zz_ef_f_$FB$_refund add = var:zz_ef_bl_y }}
		set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_bl_z }}
		remove_variable = zz_ef_bl_z
	}}
	if = {{
		limit = {{ var:zz_ef_bl_x > 0 }}
		change_variable = {{ name = zz_ef_f_$FB$_buy add = var:zz_ef_bl_x }}
		zz_ef_rq_add = {{ H = $H$ K = b D = scope:zz_ef_bl_seller V = var:zz_ef_bl_x }}
		scope:zz_ef_bl_seller = {{
			zz_ef_bl_acc_add = {{ F = sold V = root.var:zz_ef_bl_x }}
			add_investment_pool = root.var:zz_ef_bl_x
			zz_ef_bl_seller_capital = {{ V = root.var:zz_ef_bl_x }}
		}}
	}}
	remove_variable = zz_ef_bl_x
	remove_variable = zz_ef_bl_y
}}

# Holder scope, E&F's treasury slot $N$ taken into the register: the slot free again (as E&F's maturity leaves it).
zz_ef_bl_slot_free = {{
{frees.replace(chr(9)*3, chr(9))}}}

# Holder scope, a private banks' purchase with no seller in E&F's list (run s1g: Britain 1838.1, 1.95M): no debt to
# hold a part of -- back to our pool (only existing debt is bought).
zz_ef_pb_no_seller = {{
	add_investment_pool = var:zz_ef_bl_x
	change_variable = {{ name = zz_ef_f_pb_refund add = var:zz_ef_bl_x }}
	if = {{ limit = {{ zz_ef_logs_on = yes }} debug_log = "EFP|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|no_seller [THIS.GetCountry.MakeScope.Var('zz_ef_bl_x').GetValue|0]" }}
	remove_variable = zz_ef_bl_x
}}

# Holder scope: every holding of our map zz_ef_rq_$H$_b (the keys listed first, zz_ef_rq_keys_take) -- zz_ef_bl_hold_one.
zz_ef_bl_hold_map = {{
	if = {{
		limit = {{ has_variable_map = zz_ef_rq_$H$_b }}
		zz_ef_rq_keys_take = {{ MAP = zz_ef_rq_$H$_b }}
		save_temporary_scope_as = zz_ef_bl_hd
		every_in_list = {{
			variable = zz_ef_rq_keys
			save_scope_as = zz_ef_bl_seller
			scope:zz_ef_bl_hd = {{ zz_ef_bl_hold_one = {{ H = $H$ FB = $FB$ INTO = $INTO$ }} }}
		}}
		clear_variable_list = zz_ef_rq_keys
	}}
}}

# Holder scope, our part of scope:zz_ef_bl_seller's debt (map zz_ef_rq_$H$_b), weekly:
#   1. the seller's principal under the parts held abroad (its var:zz_ef_bl_ratio < 1) -> our part cut by (1 - ratio):
#      bought back from its pool, or written off in its default;
#   2. maturity -- the part is repaid evenly over zz_ef_bl_term_weeks (E&F's slots: 5 or 10 years), from its pool;
#   3. the week's interest on what is left, at the seller's rate (zz_ef_bl_int_per_part), from its pool.
# A seller no longer recognized (decentralized) -- the part written off.
zz_ef_bl_hold_one = {{
	zz_ef_rq_get = {{ MAP = zz_ef_rq_$H$_b D = scope:zz_ef_bl_seller }}
	if = {{
		limit = {{ NOT = {{ scope:zz_ef_bl_seller = {{ is_country_type = recognized }} }} }}
		set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_rq_h }}
		zz_ef_rq_add = {{ H = $H$ K = b D = scope:zz_ef_bl_seller V = {{ value = var:zz_ef_bl_x multiply = -1 }} }}
		change_variable = {{ name = zz_ef_f_bl_lost add = var:zz_ef_bl_x }}
		zz_ef_bl_woff_$INTO$ = yes
	}}
	else = {{
		if = {{
			limit = {{
				scope:zz_ef_bl_seller = {{
					has_variable = zz_ef_bl_ratio
					var:zz_ef_bl_ratio < 1
				}}
			}}
			set_variable = {{ name = zz_ef_bl_x value = {{ value = var:zz_ef_rq_h multiply = {{ value = 1 subtract = scope:zz_ef_bl_seller.var:zz_ef_bl_ratio }} }} }}
			zz_ef_rq_add = {{ H = $H$ K = b D = scope:zz_ef_bl_seller V = {{ value = var:zz_ef_bl_x multiply = -1 }} }}
			change_variable = {{ name = zz_ef_rq_h subtract = var:zz_ef_bl_x }}
			if = {{
				limit = {{ scope:zz_ef_bl_seller = {{ has_variable = zz_ef_bl_woff_now }} }}
				change_variable = {{ name = zz_ef_f_bl_lost add = var:zz_ef_bl_x }}
				scope:zz_ef_bl_seller = {{ zz_ef_bl_acc_add = {{ F = woff V = root.var:zz_ef_bl_x }} }}
				zz_ef_bl_woff_$INTO$ = yes
			}}
			else = {{
				zz_ef_bl_pay = {{ F = redeem TO = zz_ef_f_$FB$_back SHORT = zz_ef_f_bl_lost INTO = $INTO$ }}
			}}
		}}
		set_variable = {{
			name = zz_ef_bl_x
			value = {{
				value = var:zz_ef_rq_h
				divide = zz_ef_bl_term_weeks
				multiply = zz_ef_step_weeks_v
				max = var:zz_ef_rq_h
			}}
		}}
		if = {{
			limit = {{ var:zz_ef_bl_x > 0 }}
			zz_ef_rq_add = {{ H = $H$ K = b D = scope:zz_ef_bl_seller V = {{ value = var:zz_ef_bl_x multiply = -1 }} }}
			change_variable = {{ name = zz_ef_rq_h subtract = var:zz_ef_bl_x }}
			zz_ef_bl_pay = {{ F = redeem TO = zz_ef_f_$FB$_back SHORT = zz_ef_f_bl_lost INTO = $INTO$ }}
		}}
		set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_rq_h }}
		change_variable = {{ name = zz_ef_bl_x multiply = scope:zz_ef_bl_seller.zz_ef_bl_int_per_part }}
		# R1а.4: a holder's step after a gap -- the interest of the weeks its step covers
		change_variable = {{ name = zz_ef_bl_x multiply = zz_ef_step_weeks_v }}
		if = {{
			limit = {{ var:zz_ef_bl_x > 0 }}
			zz_ef_bl_pay = {{ F = int_out TO = zz_ef_f_$FB$_int_in SHORT = zz_ef_f_bl_int_short INTO = $INTO$ }}
			zz_ef_bl_icap_$INTO$ = yes
		}}
	}}
	if = {{ limit = {{ has_variable = zz_ef_bl_x }} remove_variable = zz_ef_bl_x }}
}}

# Holder scope: var:zz_ef_bl_x into our treasury (marked for the treasury's reconciliation, R1б В5) or our pool.
zz_ef_bl_into_treasury = {{
	add_treasury = var:zz_ef_bl_x
	zz_ef_tr_mark = {{ V = var:zz_ef_bl_x }}
}}
zz_ef_bl_into_pool = {{ add_investment_pool = var:zz_ef_bl_x }}
# the private banks' parts are in their book (zz_ef_bank_bonds): a part written off and the interest paid go to their
# capital; the treasury's parts are not in the banks' book
zz_ef_bl_woff_pool = {{ change_variable = {{ name = zz_ef_bank_capital subtract = var:zz_ef_bl_x }} }}
zz_ef_bl_woff_treasury = {{ }}
zz_ef_bl_icap_pool = {{ change_variable = {{ name = zz_ef_bank_capital add = var:zz_ef_bl_x }} }}
zz_ef_bl_icap_treasury = {{ }}

# Holder scope: var:zz_ef_bl_x from scope:zz_ef_bl_seller's pool (at most what it holds) to our treasury ($INTO$ =
# treasury) or our pool (pool, private banks); the seller sums it under $F$, we under var:$TO$; what its pool could not
# pay -- under var:$SHORT$. var:zz_ef_bl_x is left as paid.
zz_ef_bl_pay = {{
	set_variable = {{ name = zz_ef_bl_x0 value = var:zz_ef_bl_x }}
	change_variable = {{ name = $SHORT$ add = var:zz_ef_bl_x }}
	set_variable = {{
		name = zz_ef_bl_x
		value = {{
			value = var:zz_ef_bl_x
			max = {{
				value = scope:zz_ef_bl_seller.investment_pool
				min = 0
			}}
			min = 0
		}}
	}}
	scope:zz_ef_bl_seller = {{
		add_investment_pool = {{
			value = root.var:zz_ef_bl_x
			multiply = -1
		}}
		# R2, step 7: paid by the seller's banks (their capital)
		zz_ef_bl_seller_capital_out = {{ V = root.var:zz_ef_bl_x }}
		zz_ef_bl_acc_add = {{ F = $F$ V = root.var:zz_ef_bl_x }}
	}}
	zz_ef_bl_into_$INTO$ = yes
	change_variable = {{ name = $TO$ add = var:zz_ef_bl_x }}
	change_variable = {{ name = $SHORT$ subtract = var:zz_ef_bl_x }}
	# R2, step 7: the unpaid part
	set_variable = {{ name = zz_ef_bl_s value = var:zz_ef_bl_x0 }}
	change_variable = {{ name = zz_ef_bl_s subtract = var:zz_ef_bl_x }}
	if = {{ limit = {{ var:zz_ef_bl_s > 0 }} zz_ef_bl_short_$INTO$ = yes }}
	remove_variable = zz_ef_bl_s
	remove_variable = zz_ef_bl_x0
}}

# R2, step 7 (8.10): the seller's pool moves for its bonds (a sale, interest and repayments to the holders) are its
# banks' capital (the pool backs the engine's debt; the treasury pays the engine's interest as before) -- not «прочее».
zz_ef_bl_seller_capital = {{
	zz_ef_registry_init = yes
	change_variable = {{ name = zz_ef_bank_capital add = $V$ }}
}}
zz_ef_bl_seller_capital_out = {{
	zz_ef_registry_init = yes
	change_variable = {{ name = zz_ef_bank_capital subtract = $V$ }}
}}
# Holder scope, what the seller could not pay (var:zz_ef_bl_s): the private banks' part is in their book -- a loss of
# their capital; the treasury's parts are not in the banks' book.
zz_ef_bl_short_pool = {{ change_variable = {{ name = zz_ef_bank_capital subtract = var:zz_ef_bl_s }} }}
zz_ef_bl_short_treasury = {{ }}

# Seller scope: var:zz_ef_bl_acc_$F$ += $V$.
zz_ef_bl_acc_add = {{
	if = {{ limit = {{ NOT = {{ has_variable = zz_ef_bl_acc_$F$ }} }} set_variable = {{ name = zz_ef_bl_acc_$F$ value = 0 }} }}
	change_variable = {{ name = zz_ef_bl_acc_$F$ add = $V$ }}
}}
{slots}{pslots}"""


def values():
    vf = "".join(f"zz_ef_v_f_bl_{k} = {{\n\tvalue = 0\n\tif = {{ limit = {{ has_variable = zz_ef_f_bl_{k} }} value = var:zz_ef_f_bl_{k} }}\n}}\n"
                 for k in ("sold", "int_out", "redeem", "woff", "buy", "refund", "int_in", "back", "lost", "int_short"))
    vf += "".join(f"zz_ef_v_f_pb_{k} = {{\n\tvalue = 0\n\tif = {{ limit = {{ has_variable = zz_ef_f_pb_{k} }} value = var:zz_ef_f_pb_{k} }}\n}}\n"
                  for k in ("buy", "refund", "back", "int_in"))
    return HEAD + f"""# В5.5 (5.10), R8б.2: values of the bond ledger (scripted_effects/ld_bond_ledger.txt) -- see the generator's docstring.

# the engine's debt
zz_ef_bl_principal = {{
	value = principal
	min = 0
}}
zz_ef_bl_half_prev = {{
	value = 0
	if = {{ limit = {{ has_variable = zz_ef_bl_prev_principal }} value = var:zz_ef_bl_prev_principal }}
	multiply = 0.5
}}
# the parts of our principal held abroad -- our bonds in the holders' maps (the register's total, ld_claims.txt)
zz_ef_bl_held_v = {{
	value = zz_ef_rq_out_b_v
	min = 0
}}
# room for new parts
zz_ef_bl_room = {{
	value = zz_ef_bl_principal
	subtract = zz_ef_bl_held_v
	min = 0
}}
# the week's interest per unit of principal (the bridge's GetInterestPayment / principal)
zz_ef_bl_int_per_part = {{
	value = 0
	if = {{
		limit = {{ zz_ef_bl_principal > 0 }}
		value = zz_ef_v_g_ipay
		divide = zz_ef_bl_principal
		min = 0
		max = 0.01
	}}
}}
# a part is repaid evenly over this many weeks (E&F's slots were 5 or 10 years -- 7.5 on average)
zz_ef_bl_term_weeks = 390
# our parts of other countries' debt: the treasury's (replaces E&F's prices in zz_ef_treasury_bonds) and the private
# banks' (zz_ef_bank_bonds) -- the totals of our maps
zz_ef_bl_parts = {{
	value = 0
	if = {{ limit = {{ has_variable = zz_ef_rq_tot_tr_b }} value = var:zz_ef_rq_tot_tr_b }}
	min = 0
}}
zz_ef_bl_bank_parts = {{
	value = 0
	if = {{ limit = {{ has_variable = zz_ef_rq_tot_bk_b }} value = var:zz_ef_rq_tot_bk_b }}
	min = 0
}}
# the week's results (0 if unset)
{vf}"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    for path, text in ((OUT_LEDGER, ledger()), (OUT_VALUES, values())):
        assert text.count("{") == text.count("}"), path
        ld_gen.emit(path, text)
    ld_gen.report("regen_ef_bond_ledger")


if __name__ == "__main__":
    main()
