# -*- coding: utf-8 -*-
"""
regen_greys_ef.py -- builds the Grey's x E&F+hotfix compatch in `_greys/greys+ef done`.

Pair GR.5 of the Grey's addon. 24 shared keys, and they fall into three groups:

1. Six vanilla buildings E&F wires into its economy with `INJECT:` of
   `pmg_market_liquidity` + `pmg_private_ownership_*_stock`, and which the
   Grey's pack later re-declares with FULL bodies (`REPLACE_OR_CREATE:` /
   `REPLACE:`). A full body wins over an earlier INJECT, so the two E&F groups
   are gone -- silently, nothing in error.log. Five of them are fixed here.
   `building_railway` is NOT: USU turns it into a station and moves the actual
   line to `building_usu_railway_line`, and the body that has to win there is
   the merged one from the LLWA addon (GR.9 / GR.16 / GR.17). Fixing it here
   would mean two compatches REPLACE-ing one record.

2. Fourteen `pm_company_headquarter_*`. Three mods rewrite all fourteen in a
   row: TGR (`REPLACE_OR_CREATE:`, adds `state_modifiers`), E&F (`REPLACE:`,
   only `building_modifiers` -- it cuts HQ employment from vanilla's 50/level
   to ~10), USU (`REPLACE_OR_CREATE:`, its own rebalance back to 50/level).
   USU loads last, so E&F's cut is gone. Decision 27.08.2026: E&F's scale
   wins, USU's structure stays -- this file re-issues USU's own body with
   E&F's `building_modifiers` block put back into it. TGR's `state_modifiers`
   are carried too: USU never names that sub-block, so whether it survives
   depends on the still-unresolved REPLACE-semantics question in the rules,
   and a full body that names it is correct under both readings.

3. Three companies and `NEconomy` -- checked, nothing to fix, see the README.

4. GR.15: four buildings USU adds that are brand-new content nobody else in the
   set is aware of -- building_river_port, ppp_building_power_grid,
   usu_building_hydro_power_plant, usu_building_public_green, all
   `ownership_type = self`. E&F's stock/liquidity machinery is a hand-written
   whitelist that predates them -- same class of gap as `_llwa/llwa+ef done`
   and `_ef/ef+morg done`. All four get manufacture_stock; see
   build_new_buildings() for the reasoning per building. A fifth new USU
   building, building_usu_railway_line, already got railroad_stock in
   `_greys/greys+llwa done` (folded in there because the LLWA merge on that
   record had to happen in one place) and is not repeated here.

Usage:
    python3 regen_greys_ef.py            # write the compatch
    python3 regen_greys_ef.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

EF = res("../../vic3_mods_out/E&F")
TGR = res("../../vic3_mods_out/TheGreatRevision")
GREYS = res("../../vic3_mods_out/grey_add_alot_of_things")
USU_PM = os.path.join(GREYS, "grey_usu/common/production_methods/yMoG_USU_owners_tax_pms.txt")
EF_HQ = os.path.join(EF, "common/production_methods/11_ef_private_infrastructure.txt")
TGR_HQ = os.path.join(TGR, "common/production_methods/TGR_TRADE_private_infrastructure_investors.txt")
OUT = res("../_greys/greys+ef done")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's x E&F+hotfix compatch -- {what}
# Generated by tools/regen_greys_ef.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: TGR -> ... -> E&F -> E&F Hotfix -> ... -> Grey's pack -> THIS.
# Why this file exists: {why}
"""

# Five of the six buildings of GR.5. building_railway is deliberately absent --
# see the module docstring and the README.
BUILDINGS = [
    ("building_food_industry", "grey_food/common/buildings/mog_food_industry.txt"),
    ("building_livestock_ranch", "grey_food_2_ranch/common/buildings/mog_ranch.txt"),
    ("building_port", "grey_usu/common/buildings/yMoG_USU_ports_coastal.txt"),
    ("building_power_plant", "grey_usu/common/buildings/yMoG_USU_PPP_power_plant.txt"),
    ("building_trade_center", "grey_usu/common/buildings/yMoG_USU_trade_center.txt"),
]

# GR.15: four buildings USU adds that are brand-new content, all
# `ownership_type = self`, checked live to be on nobody's radar but USU's own
# (no other mod in the set names any of the four anywhere). Stock type is
# manufacture_stock for all four -- see build_new_buildings() docstring below
# for the per-building reasoning. building_usu_railway_line, GR.15's fifth new
# building, already got railroad_stock in `_greys/greys+llwa done` and is not
# here.
NEW_BUILDINGS = [
    ("building_river_port", "grey_usu/common/buildings/yMoG_USU_ports_river.txt"),
    ("ppp_building_power_grid", "grey_usu/common/buildings/yMoG_USU_PPP_power_grid.txt"),
    ("usu_building_hydro_power_plant", "grey_usu/common/buildings/yMoG_USU_PPP_power_plant.txt"),
    ("usu_building_public_green", "grey_usu/common/buildings/yMoG_USU_public_green.txt"),
]
NEW_BUILDINGS_STOCK = "manufacture_stock"
NEW_BUILDINGS_EFFECT = "greys_ef_new_buildings_production_stocks"
EF_PMG = os.path.join(EF, "common/production_method_groups/01_ef_industry.txt")
EF_SWITCH = os.path.join(EF, "common/scripted_effects/01_financial_scripted_effects.txt")
EF_PM_INDUSTRY = os.path.join(EF, "common/production_methods/01_ef_industry.txt")

SWITCH_BLOCK_TMPL = """\t\t# %(key)s (%(stock)s)
\t\tif = {
\t\t\tlimit = {
\t\t\t\thas_building = %(key)s
\t\t\t\tb:%(key)s = {
\t\t\t\t\tprivate_ownership_fraction > 0.5
\t\t\t\t}
\t\t\t\tis_production_method_active = {
\t\t\t\t\tbuilding_type = %(key)s
\t\t\t\t\tproduction_method = %(pm_no)s
\t\t\t\t}
\t\t\t}
\t\t\tactivate_production_method = {
\t\t\t\tbuilding_type = %(key)s
\t\t\t\tproduction_method = %(pm_yes)s
\t\t\t}
\t\t}
\t\tif = {
\t\t\tlimit = {
\t\t\t\thas_building = %(key)s
\t\t\t\tb:%(key)s = {
\t\t\t\t\tprivate_ownership_fraction <= 0.5
\t\t\t\t}
\t\t\t\tis_production_method_active = {
\t\t\t\t\tbuilding_type = %(key)s
\t\t\t\t\tproduction_method = %(pm_yes)s
\t\t\t\t}
\t\t\t}
\t\t\tactivate_production_method = {
\t\t\t\tbuilding_type = %(key)s
\t\t\t\tproduction_method = %(pm_no)s
\t\t\t}
\t\t}"""

INJECT_TMPL = """TRY_INJECT:%(key)s = {
\tproduction_method_groups = {
\t\tpmg_market_liquidity
\t\tpmg_private_ownership_%(stock)s
\t}
}"""


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def ef_groups(key: str) -> tuple[str, list[str]]:
    """The PM groups E&F INJECTs into `key`, read out of E&F itself."""
    bdir = os.path.join(EF, "common/buildings")
    for fn in sorted(os.listdir(bdir), key=lambda s: s.encode()):
        if not fn.endswith(".txt"):
            continue
        text = V.read(os.path.join(bdir, fn))
        try:
            _, body = V.entry(text, key, "INJECT:")
        except KeyError:
            continue
        block = V.sub(body, "production_method_groups")
        assert block, f"E&F INJECT:{key} in {fn} no longer carries production_method_groups"
        groups = [g for g in re.sub(r"#.*", "", block).strip("{} \n\t").split()]
        assert groups, f"E&F INJECT:{key} in {fn} injects an empty group list"
        return fn, groups
    raise AssertionError(f"E&F no longer INJECTs {key} anywhere in common/buildings -- re-check GR.5")


def build_buildings_inject():
    records, notes = [], []
    for key, rel in BUILDINGS:
        src, groups = ef_groups(key)
        winner = os.path.join(GREYS, rel)
        assert os.path.isfile(winner), f"{rel} is gone -- the Grey's pack renamed a file, re-check GR.5"
        wtext = V.read(winner)
        decl, wbody = V.entry(wtext, key)
        prefix = decl.split(":")[0] + ":" if ":" in decl.split("=")[0] else "(bare)"
        have = V.sub(wbody, "production_method_groups") or ""
        missing = [g for g in groups if g not in have]
        assert missing, (
            f"{key}: {rel} already lists {groups} -- the Grey's author fixed it, "
            f"drop this building from BUILDINGS")
        assert missing == groups, (
            f"{key}: {rel} lists some but not all of {groups} -- re-read the body by hand")
        notes.append(f"#   {key:26} {prefix:20} {os.path.basename(rel):34} <- {src}")
        records.append(
            f"TRY_INJECT:{key} = {{\n\tproduction_method_groups = {{\n"
            + "".join(f"\t\t{g}\n" for g in groups)
            + "\t}\n}"
        )
    text = ("# what each building loses and to whose body:\n" + "\n".join(notes) + "\n\n"
            + "\n\n".join(records))
    write("common/buildings/zz_greys_ef_buildings_inject.txt", text,
          "put E&F's liquidity/stock groups back on five buildings the Grey's pack re-declares",
          "E&F adds its two financial PM groups with INJECT:. Five buildings are then "
          "re-declared with full bodies by grey_food / grey_food_2_ranch / grey_usu, which "
          "load later, and a full body wins over an earlier INJECT -- so the groups are gone "
          "and those buildings drop out of E&F's economy entirely (no liquidity, no stock, "
          "no private-ownership switching), with nothing in error.log. TRY_INJECT: so a "
          "building renamed in a future Grey's version does not spam the log. "
          "building_railway is NOT here on purpose: its body has to be merged with the LLWA "
          "addon's (GR.9 / GR.16 / GR.17), and two compatches must not REPLACE one record.")


def build_company_hq():
    ef_text, usu_text, tgr_text = V.read(EF_HQ), V.read(USU_PM), V.read(TGR_HQ)
    keys = [m.group(2) for m in re.finditer(
        r"(?m)^([A-Z_]+:)?(pm_company_headquarter[a-z_0-9]*)\s*=\s*\{", ef_text)]
    assert len(keys) == 14, f"E&F now rewrites {len(keys)} HQ methods, not 14 -- re-read GR.5"
    records = []
    for key in keys:
        _, ef_body = V.entry(ef_text, key, "REPLACE:")
        ef_subs = V.sub_names(ef_body)
        assert ef_subs == ["building_modifiers"], (
            f"{key}: E&F now also names {[s for s in ef_subs if s != 'building_modifiers']} -- "
            f"this merge only knows how to carry building_modifiers")
        _, usu_body = V.entry(usu_text, key, "REPLACE_OR_CREATE:")
        usu_subs = V.sub_names(usu_body)
        assert "building_modifiers" in usu_subs, f"{key}: USU's body has no building_modifiers"
        assert "state_modifiers" not in usu_subs, (
            f"{key}: USU now names state_modifiers too -- it collides with TGR's, merge by hand")
        merged = V.replace_sub(usu_body, "building_modifiers", V.sub(ef_body, "building_modifiers"))
        tgr_sm = V.sub(V.entry(tgr_text, key, "REPLACE_OR_CREATE:")[1], "state_modifiers")
        assert tgr_sm, f"{key}: TGR no longer carries state_modifiers -- re-check, GR.7 depends on it"
        merged = merged.rstrip() + "\n\n\t# TGR's layer, carried so a full body cannot drop it:\n" \
                 + "\tstate_modifiers = " + tgr_sm.strip() + "\n"
        records.append(f"REPLACE_OR_CREATE:{key} = {{{merged}}}")
    text = ("# 14 methods, all three layers in one body:\n"
            "#   structure, textures, gates, employment split  -- grey_usu (loads last)\n"
            "#   building_modifiers (E&F's HQ employment cut)  -- E&F, verbatim\n"
            "#   state_modifiers (trade capacity, tax capacity) -- TGR, verbatim\n\n"
            + "\n\n".join(records))
    write("common/production_methods/zz_greys_ef_company_hq.txt", text,
          "restore E&F's company-HQ employment on top of USU's HQ bodies",
          "vanilla employs 50 pops per HQ level; E&F cuts that to ~10 with a REPLACE: that "
          "names building_modifiers and nothing else; USU rebalances the same block back to "
          "50 and loads last, so E&F's cut disappears. Decision 27.08.2026: E&F's scale wins, "
          "USU's structure (its shopkeeper split, its share math, its gates) stays. TGR's "
          "state_modifiers block is carried in the same body on purpose -- USU never names it, "
          "so whether it survives today depends on the unresolved REPLACE-semantics question "
          "in the rules; naming it here is correct under both readings.")



def build_new_buildings():
    """GR.15: wire USU's four brand-new self-owned buildings into E&F's economy.

    Same four-file shape as `_ef/ef+morg done` / `_llwa/llwa+ef done`: an
    inject of the two PM groups, a yearly switch effect, an on_action hook,
    and a game-start init -- because unlike the five buildings in
    build_buildings_inject() above, E&F has never heard of these four at all
    (they are not vanilla, not on its hand-written whitelist), so there is no
    existing switch to piggyback on.

    Stock type, manufacture_stock for all four:
      * building_river_port, ppp_building_power_grid,
        usu_building_hydro_power_plant -- direct analogues of E&F's own
        building_port / building_power_plant (already manufacture_stock).
      * usu_building_public_green -- not an obvious fit by name, but its
        production methods (usu_pmg_public_space_management /
        usu_pmg_public_parklands) carry real building_modifiers:
        goods_output_services / goods_output_transportation and real
        employment (laborers, clerks, shopkeepers, bureaucrats). It is a
        production building like any other -- the same reasoning `ef+morg
        done` already applies to Morgenroete's Opera, instrument workshops
        and Manzoni publishing (also manufacture_stock). E&F has no separate
        civic-amenity stock type, and nothing amenity-only appears in its own
        49-building list either.
    """
    pmg_text = V.read(EF_PMG)
    for g in ("pmg_market_liquidity", "pmg_private_ownership_" + NEW_BUILDINGS_STOCK):
        V.entry(pmg_text, g)  # raises KeyError if E&F stopped defining it

    pm_text = V.read(EF_PM_INDUSTRY)
    pm_no = "pm_no_private_ownership_" + NEW_BUILDINGS_STOCK
    pm_yes = "pm_private_ownership_majority_" + NEW_BUILDINGS_STOCK
    for pm in (pm_no, pm_yes):
        V.entry(pm_text, pm)

    switch_guard = V.read(EF_SWITCH)
    for key, _rel in NEW_BUILDINGS:
        assert "building_type = " + key not in switch_guard, (
            f"{key}: E&F's own private_ownership_production_stocks already switches it -- "
            f"this compatch's own switch would double it, re-check GR.15 before running")

    inject_records = []
    for key, rel in NEW_BUILDINGS:
        src_path = os.path.join(GREYS, rel)
        text = V.read(src_path)
        _decl, body = V.entry(text, key)
        have = V.sub(body, "production_method_groups") or ""
        assert "pmg_market_liquidity" not in have and (
            "pmg_private_ownership_" + NEW_BUILDINGS_STOCK not in have), (
            f"{key}: {rel} already carries E&F's groups -- the Grey's author added support, "
            f"drop this building from NEW_BUILDINGS")
        assert "ownership_type = self" in body, (
            f"{key}: {rel} is no longer ownership_type = self -- it can't be privately owned, "
            f"re-check GR.15")
        inject_records.append(INJECT_TMPL % {"key": key, "stock": NEW_BUILDINGS_STOCK})

    write("common/buildings/zz_greys_ef_new_buildings_inject.txt",
          "\n\n".join(inject_records),
          "add E&F's financial PM groups to four brand-new USU buildings (GR.15)",
          "grey_usu adds building_river_port, ppp_building_power_grid, "
          "usu_building_hydro_power_plant and usu_building_public_green, all "
          "ownership_type = self -- none on E&F's hand-written whitelist (it predates "
          "them, same class of gap as LLWA's six buildings and Morgenroete's private "
          "ones). All four get manufacture_stock: river port and power plant/grid are "
          "direct analogues of E&F's own building_port / building_power_plant; "
          "usu_building_public_green produces real goods_output (services/"
          "transportation) with real employment, same as Morgenroete's Opera / "
          "instrument workshops in ef+morg done -- E&F has no separate civic-amenity "
          "stock type. building_usu_railway_line, GR.15's fifth new building, already "
          "got railroad_stock in greys+llwa done and is not repeated here.")

    switch_blocks = [
        SWITCH_BLOCK_TMPL % {"key": key, "stock": NEW_BUILDINGS_STOCK, "pm_no": pm_no, "pm_yes": pm_yes}
        for key, _rel in NEW_BUILDINGS
    ]
    switch_text = (NEW_BUILDINGS_EFFECT + " = {\n\tevery_scope_state = {\n\n"
                   + "\n\n".join(switch_blocks) + "\n\t}\n}")
    write("common/scripted_effects/zz_greys_ef_new_buildings_stocks.txt", switch_text,
          "yearly private-ownership -> stock switch for the four new USU buildings (GR.15)",
          "same shape as E&F's own private_ownership_production_stocks and the mr_/llwa_ "
          "variants in ef+morg done / llwa+ef done -- E&F's switch only lists vanilla/E&F "
          "buildings, so these four need their own. Wired in additively (see the "
          "on_action and history/global files here), overrides nothing of E&F's.")

    on_action_text = (
        "on_yearly_pulse_country = {\n"
        "\ton_actions = {\n"
        "\t\tzz_greys_ef_new_buildings_on_yearly_pulse_country\n"
        "\t}\n"
        "}\n\n"
        "zz_greys_ef_new_buildings_on_yearly_pulse_country = {\n"
        "\teffect = {\n"
        "\t\t" + NEW_BUILDINGS_EFFECT + " = yes\n"
        "\t}\n"
        "}"
    )
    write("common/on_actions/zz_greys_ef_new_buildings_on_actions.txt", on_action_text,
          "hook the four-building stock switch into the yearly pulse",
          "on_actions are additive across mods -- overrides nothing from E&F or anyone "
          "else also appending to on_yearly_pulse_country.")

    init_text = (
        "GLOBAL = {\n"
        "\tevery_country = {\n"
        "\t\t" + NEW_BUILDINGS_EFFECT + " = yes\n"
        "\t}\n"
        "}"
    )
    write("common/history/global/zz_greys_ef_new_buildings_init.txt", init_text,
          "initialise the four new stock production methods at game start",
          "on_yearly_pulse_country only fires a year after start -- same fix E&F uses "
          "for its own buildings and ef+morg done / llwa+ef done use for theirs. GLOBAL "
          "blocks stack across mods, overrides nothing.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        empty_colon = re.findall(r"^[A-Z_]+::", text, re.M)
        if empty_colon:
            print(f"  FAIL {rel}: {len(empty_colon)} bad '::' prefix(es), e.g. {empty_colon[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_ef.py -> {OUT}")
    for name, fn in (("buildings inject", build_buildings_inject),
                     ("company HQ methods", build_company_hq),
                     ("new buildings (GR.15)", build_new_buildings)):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current Grey's / E&F / TGR sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
