#!/usr/bin/env python3
"""
Д2.30 / Д2.31 (the user, 6.10 day): a country's currency held by other CBs lies as deposits in ITS banks.

Was: the clearing paid an outflow partly in the payer's own currency (the reference 70%, В1); the engine had already
taken the importers' money, so that currency left the payer's M2 for good -- the holders' stocks
(stockpiling_<currency>_state_1 on their CB capitals) only grew. Run r1006_154528: 21.6M pounds abroad by 1838.3,
Britain's M2 41 -> 36M, prices -10% a year, GDP -9%.

Now (Д2.30, (a)): the issuer's banks hold it. Weekly, at the receiver after the clearing, the change of
zz_ef_fx_liab_all (our currency held by other CBs + waiting in the clearing house) is put into / drawn out of the
issuer's investment pool (var:zz_ef_f_nr_dep, + in / - out, at most the pool on the way out); var:zz_ef_nr_dep = the
deposits held. Every channel counts: the clearing, our currency coming home, E&F's forex, a crisis redemption.

Д2.31 (the start): E&F's history gives CBs foreign currency in its own scale, and the start rescaled each holder's
stock by the HOLDER's factor -- Belgian francs abroad 8.4M against Belgium's M2 3.2M (60M in week 1), the same for
Sardinia, Sweden, Norway, Finland. Now the holders' factor is not applied (zz_ef_money_model.txt); the issuer cuts its
currency held abroad to zz_ef_fx_start_cap (5%) of its money, every holder in proportion -- at its first step
against the money expected (zz_ef_rescale_money), and again when the deposits start (after the week-12 recount,
against M2). What is kept starts as deposits in its banks (the first week's change = the whole stock).

Д2.33 (the user, 6.10 day, after run r1006_162423: Britain's deficit 0.15 -> 0.6M a week, pounds abroad 66% of GDP,
nothing closing it): (a) the issuer's banks pay the holders interest at the deposit rate -- weekly every holder's
stock x (1 + zz_ef_deposit_rate / 52), credited as more deposits (the pool unchanged, the banks' liabilities up:
var:zz_ef_f_nr_int); (b) the holders spend the currency on the issuer's goods -- the engine's lever, an export
advantage for the issuer by its currency held abroad: static modifier zz_ef_fx_holders_demand (+1% per unit),
multiplier = zz_ef_fx_holders_demand_m (+1 per 3% of GDP held abroad, at most 20). More exports -> an inflow in the
clearing -> the holders pay with its own currency coming home, the debt falls by itself.

The issuer: a country with a CB outside an overlord's currency zone (zz_ef_nr_issuer) -- a zone member shares the
overlord's zz_ef_fx_liab and must not count it twice.

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys): common/scripted_effects/ld_nr_deposits.txt,
common/script_values/ld_nr_deposits_values.txt, common/scripted_triggers/ld_nr_deposits_triggers.txt,
common/static_modifiers/ld_fx_holders_demand.txt (localization by hand). Reads the currencies from zz_ef_fx_liab's
branches (the fork's common/script_values/ld_reserve_trade_values.txt).

Usage:
    python3 tools/regen_ef_nr_deposits.py [--check]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

SRC = os.path.join(ld_gen.FORK, "common", "script_values", "ld_reserve_trade_values.txt")
# hotfix paths; ld_gen writes into the fork (ld_nr_deposits*.txt, ld_fx_holders_demand.txt)
OUT_EFF = "common/scripted_effects/zz_ef_nr_deposits.txt"
OUT_SV = "common/script_values/zz_ef_nr_deposits_values.txt"
OUT_TR = "common/scripted_triggers/zz_ef_nr_deposits_triggers.txt"
OUT_SM = "common/static_modifiers/zz_ef_fx_holders_demand.txt"

HEAD = ("# GENERATED by tools/regen_ef_nr_deposits.py -- do not edit by hand.\n"
        "# Д2.30 / Д2.31 (6.10): our currency held by other CBs = deposits in our banks; the start's foreign\n"
        "# currency cut to 5% of the issuer's money -- see the generator's docstring.\n")


def currencies():
    text = open(SRC, encoding="utf-8-sig").read()
    block = text[text.index("\nzz_ef_fx_liab = {"):]
    block = block[:block.index("\n}\n")]
    cur = re.findall(r"has_law = law_type:law_([a-z_]+)_currency \}", block)
    cur = list(dict.fromkeys(cur))
    assert len(cur) >= 90, len(cur)
    return cur


def trim_chain(cur, var="zz_ef_fxt_k"):
    out = []
    for i, c in enumerate(cur):
        kw = "if" if i == 0 else "else_if"
        out.append(
            f"\t\t\t{kw} = {{ limit = {{ has_law = law_type:law_{c}_currency }} every_country = {{ limit = {{ "
            f"NOT = {{ this = scope:zz_fxt_issuer }} NOT = {{ has_law = law_type:law_{c}_currency }} "
            f"has_modifier = has_central_bank }} capital = {{ if = {{ limit = {{ has_variable = stockpiling_{c}_state_1 }} "
            f"change_variable = {{ name = stockpiling_{c}_state_1 multiply = scope:zz_fxt_issuer.var:{var} }} }} }} }} }}\n")
    return "".join(out)


def effects(cur):
    return HEAD + """
# COUNTRY scope (the issuer). Our currency held by other CBs cut to zz_ef_fx_start_cap x $BASE$ (a script value: the
# money), every holder's stock in proportion. Log EFN|trim.
zz_ef_fx_liab_trim = {
	if = {
		limit = { zz_ef_nr_issuer = yes }
		save_scope_as = zz_fxt_issuer
		set_variable = { name = zz_ef_fxt_liab value = zz_ef_fx_liab }
		set_variable = { name = zz_ef_fxt_cap value = $BASE$ }
		change_variable = { name = zz_ef_fxt_cap multiply = zz_ef_fx_start_cap }
		set_variable = { name = zz_ef_fxt_k value = 1 }
		if = {
			limit = {
				var:zz_ef_fxt_liab > 0
				var:zz_ef_fxt_liab > var:zz_ef_fxt_cap
			}
			set_variable = { name = zz_ef_fxt_k value = var:zz_ef_fxt_cap }
			change_variable = { name = zz_ef_fxt_k divide = var:zz_ef_fxt_liab }
""" + trim_chain(cur) + """		}
		if = { limit = { zz_ef_logs_on = yes } debug_log = "EFN|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|trim|liab [THIS.GetCountry.MakeScope.Var('zz_ef_fxt_liab').GetValue|0]|cap [THIS.GetCountry.MakeScope.Var('zz_ef_fxt_cap').GetValue|0]|k [THIS.GetCountry.MakeScope.Var('zz_ef_fxt_k').GetValue|4]|after [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_fx_liab')|0]" }
	}
}

# COUNTRY scope, weekly at the receiver after the clearing (zz_ef_cb_hume_step). The deposits start once the start is
# over (no week-12 recount pending): the stock cut against M2, then the whole of it comes in as deposits.
zz_ef_nr_dep_step = {
	set_variable = { name = zz_ef_f_nr_dep value = 0 }
	if = {
		limit = {
			zz_ef_nr_issuer = yes
			NOT = { has_variable = zz_ef_nr_started }
			has_variable = zz_ef_parity_version
			NOT = { has_variable = zz_ef_metal_rescale_due }
		}
		zz_ef_fx_liab_trim = { BASE = zz_ef_agg_m2 }
		set_variable = { name = zz_ef_nr_started value = yes }
		set_variable = { name = zz_ef_nr_dep value = 0 }
	}
	if = {
		limit = {
			zz_ef_nr_issuer = yes
			has_variable = zz_ef_nr_started
		}
		# Д2.33 (a): interest to the holders at the deposit rate, credited as more deposits (the pool unchanged)
		set_variable = { name = zz_ef_f_nr_int value = 0 }
		set_variable = { name = zz_ef_nri_liab value = zz_ef_fx_liab }
		if = {
			limit = {
				var:zz_ef_nri_liab > 0
				zz_ef_nr_int_week > 0
			}
			set_variable = { name = zz_ef_f_nr_int value = zz_ef_nr_int_week }
			set_variable = { name = zz_ef_nri_k value = var:zz_ef_f_nr_int }
			change_variable = { name = zz_ef_nri_k divide = var:zz_ef_nri_liab }
			change_variable = { name = zz_ef_nri_k add = 1 }
			save_scope_as = zz_fxt_issuer
""" + trim_chain(cur, "zz_ef_nri_k") + """			set_variable = { name = zz_ef_nr_dep value = zz_ef_nr_dep_v }
			change_variable = { name = zz_ef_nr_dep add = var:zz_ef_f_nr_int }
		}
		# the holders' stock is final for the week here (the interest above was its last change): one pass of
		# zz_ef_fx_liab_all, read by the deposits below and by zz_ef_fx_holders_demand_m
		set_variable = { name = zz_ef_t_liab_all value = zz_ef_fx_liab_all }
		set_variable = { name = zz_ef_f_nr_dep value = var:zz_ef_t_liab_all }
		change_variable = { name = zz_ef_f_nr_dep subtract = zz_ef_nr_dep_v }
		# withdrawn: at most what the pool holds; the rest waits for next week
		if = {
			limit = { var:zz_ef_f_nr_dep < 0 }
			set_variable = {
				name = zz_ef_f_nr_dep
				value = {
					value = var:zz_ef_f_nr_dep
					min = {
						value = investment_pool
						min = 0
						multiply = -1
					}
				}
			}
		}
		add_investment_pool = var:zz_ef_f_nr_dep
		set_variable = { name = zz_ef_nr_dep value = zz_ef_nr_dep_v }
		change_variable = { name = zz_ef_nr_dep add = var:zz_ef_f_nr_dep }
	}
	# Д2.33 (b): the holders' demand for the issuer's goods -- an export advantage by its currency held abroad
	if = {
		limit = { has_modifier = zz_ef_fx_holders_demand }
		remove_modifier = zz_ef_fx_holders_demand
	}
	if = {
		limit = {
			zz_ef_nr_issuer = yes
			has_variable = zz_ef_nr_started
			zz_ef_fx_holders_demand_m > 0
		}
		add_modifier = {
			name = zz_ef_fx_holders_demand
			multiplier = zz_ef_fx_holders_demand_m
		}
	}
}
"""


def values():
    return HEAD + """
# Д2.31: the start's foreign holdings of a currency, at most this share of the issuer's money
zz_ef_fx_start_cap = 0.05

# the deposits of other CBs in our banks (our currency they hold), money
zz_ef_nr_dep_v = {
	value = 0
	if = { limit = { has_variable = zz_ef_nr_dep } value = var:zz_ef_nr_dep }
}
# put into (+) / drawn out of (-) the pool this receiver / last window
zz_ef_v_f_nr_dep = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_nr_dep } value = var:zz_ef_f_nr_dep }
}
zz_ef_v_w_nr_dep = {
	value = 0
	if = { limit = { has_variable = zz_ef_w_nr_dep } value = var:zz_ef_w_nr_dep }
}

# Д2.33 (a): the week's interest to the holders: the deposits x the deposit rate / 52
zz_ef_nr_int_week = {
	value = zz_ef_nr_dep_v
	multiply = zz_ef_deposit_rate
	divide = 52
	min = 0
}
zz_ef_v_f_nr_int = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_nr_int } value = var:zz_ef_f_nr_int }
}
# Д2.33 (b): the export advantage's multiplier, +1 (= +1%) per 3% of GDP held abroad, at most 20
# (only inside zz_ef_nr_dep_step, after zz_ef_t_liab_all is set: the same guards as the step's second block)
zz_ef_fx_holders_demand_m = {
	value = 0
	if = {
		limit = {
			has_variable = zz_ef_t_liab_all
			zz_ef_raw_gdp > 0
		}
		value = var:zz_ef_t_liab_all
		divide = zz_ef_raw_gdp
		multiply = 100
		divide = 3
	}
	max = 20
	min = 0
}
"""


def triggers():
    return HEAD + """
# The issuer of its currency: a CB, not a member of an overlord's currency zone (В3.2)
zz_ef_nr_issuer = {
	has_modifier = has_central_bank
	NOT = { has_variable = zz_ef_cur_zone }
}
"""


def modifiers():
    return HEAD + """
# Д2.33 (b): the holders of our currency spend it on our goods -- +1% export advantage per unit; the multiplier
# zz_ef_fx_holders_demand_m (script_values/zz_ef_nr_deposits_values.txt), set weekly by zz_ef_nr_dep_step
zz_ef_fx_holders_demand = {
	icon = gfx/interface/icons/timed_modifier_icons/strong_currency.dds
	state_export_advantage_mult = 0.01
}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    cur = currencies()
    for path, text in ((OUT_EFF, effects(cur)), (OUT_SV, values()), (OUT_TR, triggers()), (OUT_SM, modifiers())):
        ld_gen.emit(path, text)
    ld_gen.report("regen_ef_nr_deposits")


if __name__ == "__main__":
    main()
