"""
regen_llwa_morg_ef.py -- builds the LLWA+Morgenroete-compatch x E&F fix in
`_llwa/llwa+morg+ef done`.

Not one of the three LLWA.1-3 pairs. Found while re-checking the finished
addon (user question: "I don't see Morgenroete files"). The plan's LLWA.4
calls LLWA x Morgenroete `noneed`/"closed by the author's own compach"
(`_llwa/llwa+morg out`, id xyz.1230james.LLWA_morgenrote_compatch) -- true
at the raw-mod level (pair_matrix.py: 1 shared key, additive, noneed), but
the author's compach itself introduces a NEW loss the matrix can't see,
because `tools/blocks.json`'s "LLWA" block is raw-mod-only and never
measures this third-party compach at all.

`_llwa/llwa+morg out/common/buildings/zz_LLWAMR_buildings.txt` bare-redefines
building_railway and building_airport -- full bodies, no prefix, reconciling
LLWA's and Morgenroete's own production_method_groups by hand. It does NOT
declare E&F as a dependency (checked its own metadata.json: only Locomotion
and Morgenroete). Two groups E&F contributes via plain INJECT: earlier in
the chain get silently dropped as a result:

  * building_railway: E&F's own `ef_11_private_infrastructure.txt` --
    `INJECT:building_railway = { production_method_groups = {
    pmg_market_liquidity pmg_private_ownership_railroad_stock } }`.
  * building_airport: the closed E&F x Morgenroete pair, folded into the
    megapack -- `zz_ef_mr_buildings_inject.txt` --
    `TRY_INJECT:building_airport = { production_method_groups = {
    pmg_market_liquidity pmg_private_ownership_manufacture_stock } }`.

This matches, almost exactly, the in-game finding already on record in the
rules file (section 3): "в панели железной дороги остаются три группы
вместо девяти -- ни pmg_market_liquidity от E&F...". That passage names
"LLWA и его компачи" collectively, not raw LLWA alone -- this generator is
that finding's fix.

What this does NOT fix, on purpose: `llwa+morg out`'s building_airport also
completely drops Morgenroete's OWN aviation redesign (pmg_base_building_airport,
pmg_cargo_airport, pmg_tourism_airport from Morgenroete's own
mr_sports_civil_aviation_buildings.txt) in favour of LLWA's own air PM
groups. That is not an additive INJECT silently eaten by a bare override --
it is two mods each proposing a full, mutually-exclusive redesign of the
same building, and the author's compach already made a choice between them.
Second-guessing which design should win is not this addon's job (rules
file: "не чинить чужой замысел, не разобравшись") -- left as an open item,
see README.

Both restorations use the SAME technique as regen_llwa_tgr.py/regen_llwa_vc.py:
read the current full body from `llwa+morg out` live, append the missing
list items to the existing production_method_groups sub-block, REPLACE_OR_CREATE:
the whole record. Not blind INJECT: -- E&F's groups must NOT already be
present (guards against double-counting if a user runs addon-LLWA without
`llwa+morg out`, where raw LLWA already leaves E&F's INJECT untouched, or if
the author's compach is updated to include them itself).

Usage:
    python3 regen_llwa_morg_ef.py            # write the compatch
    python3 regen_llwa_morg_ef.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

MORG_OUT = res("../_llwa/llwa+morg out")
EF = res("../../vic3_mods_out/E&F")
MEGAPACK = res("../__megapacks/megapack no t&r")
OUT = res("../_llwa/llwa+morg+ef done")

HEADER = """# LLWA+Morgenroete compatch x E&F fix -- {what}
# Generated by tools/regen_llwa_morg_ef.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: E&F -> ... -> Morgenroete -> ... -> LLWA -> llwa+morg out -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}


def block(lines: list[str], i: int) -> tuple[list[str], int]:
    depth = 0
    started = False
    for j in range(i, len(lines)):
        code = lines[j].split("#", 1)[0]
        depth += code.count("{") - code.count("}")
        if "{" in code:
            started = True
        if started and depth <= 0:
            return lines[i:j + 1], j + 1
    return lines[i:], len(lines)


def record(path: str, key: str, prefix: str | None = None) -> list[str] | None:
    lines = read_lines(path)
    pat_prefix = re.escape(prefix) if prefix else r"(?:[A-Z_]+:)?"
    pat = re.compile(r"^" + pat_prefix + re.escape(key) + r"\s*=\s*\{")
    for i, raw in enumerate(lines):
        if pat.match(raw.split("#", 1)[0].lstrip("﻿")):
            body, _ = block(lines, i)
            body[0] = re.sub(r"^﻿?(?:[A-Z_]+:)?", "", body[0])
            return body
    return None


def top_subblocks(body: list[str]) -> dict[str, tuple[int, int]]:
    out: dict[str, tuple[int, int]] = {}
    depth = 0
    i = 0
    n = len(body)
    while i < n:
        code = body[i].split("#", 1)[0]
        if i == 0:
            depth += code.count("{") - code.count("}")
            i += 1
            continue
        if depth == 1:
            m = re.match(r"^\s*([A-Za-z0-9_]+)\s*=\s*\{", code)
            if m:
                sub, j = block(body, i)
                out[m.group(1)] = (i, j - 1)
                depth += sum(c.count("{") - c.count("}") for c in
                             [x.split("#", 1)[0] for x in body[i:j]])
                i = j
                continue
        depth += code.count("{") - code.count("}")
        i += 1
    return out


def list_items(body: list[str], name: str) -> list[str]:
    """Bare identifiers inside a depth-1 `name = { a b c }` list block."""
    subs = top_subblocks(body)
    lo, hi = subs[name]
    items = []
    for l in body[lo + 1:hi]:
        code = l.split("#", 1)[0].strip()
        if code:
            items.append(code)
    return items


def append_to_list(body: list[str], name: str, new_items: list[str], tag: str) -> list[str]:
    subs = top_subblocks(body)
    lo, hi = subs[name]
    out = list(body)
    insertion = ["\t\t" + it + "  # " + tag for it in new_items]
    out = out[:hi] + insertion + out[hi:]
    return out


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_buildings():
    morg_f = os.path.join(MORG_OUT, "common/buildings/zz_LLWAMR_buildings.txt")
    ef_f = os.path.join(EF, "common/buildings/ef_11_private_infrastructure.txt")
    mp_f = os.path.join(MEGAPACK, "common/buildings/zz_ef_mr_buildings_inject.txt")
    for f, name in ((morg_f, "llwa+morg out's zz_LLWAMR_buildings.txt"),
                    (ef_f, "E&F's ef_11_private_infrastructure.txt"),
                    (mp_f, "the megapack's zz_ef_mr_buildings_inject.txt")):
        assert os.path.isfile(f), f"{name} not found -- did a source move or get renamed?"

    out_records: list[str] = []

    # -- building_railway: add back E&F's own INJECT -----------------------
    rail_body = record(morg_f, "building_railway")
    assert rail_body, "llwa+morg out no longer bare-defines building_railway -- re-check"
    rail_current = list_items(rail_body, "production_method_groups")
    assert "pmg_market_liquidity" not in rail_current, (
        "llwa+morg out's building_railway already has pmg_market_liquidity -- "
        "E&F's group may no longer be silently dropped, re-check before running this")

    ef_inject = record(ef_f, "building_railway", prefix="INJECT:")
    assert ef_inject, "E&F no longer INJECTs building_railway -- re-check"
    ef_rail_items = list_items(ef_inject, "production_method_groups")
    assert set(ef_rail_items) == {"pmg_market_liquidity", "pmg_private_ownership_railroad_stock"}, (
        f"E&F's building_railway INJECT no longer contains exactly the expected two "
        f"groups, got {ef_rail_items!r} -- re-check the merge")

    new_rail = append_to_list(rail_body, "production_method_groups", ef_rail_items, "E&F")
    out_records.append("REPLACE_OR_CREATE:" + "\n".join(new_rail))

    # -- building_airport: add back E&F's contribution via the closed ------
    # -- E&F x Morgenroete pair (folded into the megapack) ------------------
    air_body = record(morg_f, "building_airport")
    assert air_body, "llwa+morg out no longer bare-defines building_airport -- re-check"
    air_current = list_items(air_body, "production_method_groups")
    assert "pmg_market_liquidity" not in air_current, (
        "llwa+morg out's building_airport already has pmg_market_liquidity -- "
        "E&F's group may no longer be silently dropped, re-check before running this")

    mp_inject = record(mp_f, "building_airport", prefix="TRY_INJECT:")
    assert mp_inject, "the megapack no longer TRY_INJECTs building_airport -- re-check"
    mp_air_items = list_items(mp_inject, "production_method_groups")
    assert set(mp_air_items) == {"pmg_market_liquidity", "pmg_private_ownership_manufacture_stock"}, (
        f"the megapack's building_airport TRY_INJECT no longer contains exactly the "
        f"expected two groups, got {mp_air_items!r} -- re-check the merge")

    new_air = append_to_list(air_body, "production_method_groups", mp_air_items, "E&F x Morgenroete")
    out_records.append("REPLACE_OR_CREATE:" + "\n".join(new_air))

    write("common/buildings/zz_llwa_morg_ef_buildings.txt",
          "\n\n".join(out_records),
          "restore E&F's production_method_groups contributions on building_railway "
          "and building_airport",
          "`_llwa/llwa+morg out` (the author's own LLWA x Morgenroete compatch) "
          "bare-redefines both buildings' full bodies without E&F as a declared "
          "dependency, silently dropping E&F's plain INJECT: on both (railway: "
          "E&F's own file; airport: the closed E&F x Morgenroete pair folded into "
          "the megapack). Restored on top of llwa+morg out's current body -- "
          "Morgenroete's and LLWA's own contributions to both records, already "
          "reconciled by that compach, are carried through unchanged.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category = os.path.dirname(rel)
        depth = 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_llwa_morg_ef.py -> {OUT}")
    for name, fn in (
        ("buildings", build_buildings),
    ):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current llwa+morg out / E&F / megapack sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
