# -*- coding: utf-8 -*-
"""
regen_greys_tgr.py -- builds the Grey's x TGR compatch in `_greys/greys+tgr`.

Pair GR.7 -- 97 shared keys, full analysis in `_greys/analysis_gr7_tgr_report.md`.
This generator covers the pieces resolved and NOT blocked on cross-task
coordination or an in-game check, per the report's section 10 draft list:

  * GR.7a -- eight country ranks. Base body is _grey_soft_pop's TRY_REPLACE
    (it matches current 1.13 vanilla, see report 2.4 / plan TGR.1 -- TGR's own
    copy in TheGreatRevision/ is stale). Restored on top: TGR's
    state_export_advantage_mult / state_import_advantage_mult on six ranks
    (soft_pop's full body drops them), TGR's country_construction_add on
    great_power/major_power (a field vanilla/soft_pop never had at all).
    Decision 26-27.08.2026 (report section 12): country_loan_interest_rate_mult
    is commented OUT wherever soft_pop has it, matching TGR's own design --
    TGR's loan system drops rank-dependent interest entirely on purpose, this
    is a genuine design dispute, not a loss, and Grey's/TGR's choice was to
    follow TGR's here.

  * GR.7b -- four citizenship laws. Vanilla gives
    country_political_strength_full_acceptance_mult = 0.25/0.20/0.1/0.1 on
    law_ethnostate/law_national_supremacy/law_racial_segregation/
    law_cultural_exclusion. TGR INJECTs the exact same numbers negated, a
    counterweight that nets the vanilla bonus to zero. _grey_soft_pop's later
    TRY_REPLACE restates the vanilla (positive) values and TGR's INJECT lands
    under a body that no longer exists to receive it -- classic "counterweight
    with the opposite sign gets silently resurrected" (rules file, section 1).
    Since Grey's numbers match vanilla exactly, re-issuing TGR's own INJECT
    after the whole Grey's pack is an exact restoration.

  * GR.7c -- four defines. _grey_soft_econ / _grey_soft_pop both just restate
    the vanilla default for these four; TGR is the only side that made a
    deliberate change and it is lost because the later mod's define replaces
    the whole key. Restore TGR's values.

NOT covered here (see the plan / report for why):
  * GR.7d (building_trade_center has_max_level) -- blocked on an in-game
    screenshot check (report section 11), not written yet.
  * GR.7e (21 ownership production methods) -- 14 of 21 already closed via
    _greys/greys+ef done (GR.5); the remaining 7 need their own pass.
  * GR.7f (bg_consumer_goods / bg_trade) -- next pass.
  * Class A/B production-method restores (report section 6) -- next pass.
  * foreign_investment_rights, trade_states, monopoly_charter file dup,
    building_construction_sector, 14 pm_company_headquarter_* -- all cross-task
    (GR.8, GR.14, GR.10, GR.2, GR.5 respectively), handled there.

Usage:
    python3 regen_greys_tgr.py            # write the compatch
    python3 regen_greys_tgr.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

GREYS = res("../../vic3_mods_out/grey_add_alot_of_things")
SOFT_POP = os.path.join(GREYS, "_grey_soft_pop")
SOFT_ECON = os.path.join(GREYS, "_grey_soft_econ")
TGR = res("../../vic3_mods_out/TheGreatRevision")
OUT = res("../_greys/greys+tgr")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's x TGR compatch (GR.7) -- {what}
# Generated by tools/regen_greys_tgr.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: TGR -> ... -> Grey's pack -> THIS.
# Why this file exists: {why}
"""


def write(rel: str, text: str, what: str = "", why: str = "", bom: bool | None = None):
    path = os.path.join(OUT, rel)
    body = (HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n")
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


# ---------------------------------------------------------------------------
# GR.7a -- country ranks
# ---------------------------------------------------------------------------

# Ranks that lose TGR's state_export_advantage_mult / state_import_advantage_mult.
EXPORT_IMPORT_RANKS = [
    "major_power", "unrecognized_major_power", "minor_power",
    "unrecognized_regional_power", "insignificant_power", "unrecognized_power",
]
# Ranks where soft_pop still carries a vanilla-style country_loan_interest_rate_mult
# that the loan-rank decision (report section 12) says to comment out.
LOAN_RANKS = [
    "great_power", "major_power", "insignificant_power",
    "unrecognized_major_power", "unrecognized_regional_power", "unrecognized_power",
]
# Ranks that get TGR's new country_construction_add field.
CONSTRUCTION_RANKS = ["great_power", "major_power"]

ALL_RANKS = [
    "great_power", "major_power", "minor_power", "insignificant_power",
    "unrecognized_major_power", "unrecognized_regional_power", "unrecognized_power",
]


def build_country_ranks():
    sp_text = V.read(os.path.join(SOFT_POP, "common/country_ranks/MoG_SPA_country_ranks.txt"))
    tgr_trade_text = V.read(os.path.join(TGR, "common/country_ranks/TGR_TRADE_country_ranks.txt"))
    tgr_pol_text = V.read(os.path.join(TGR, "common/country_ranks/TGR_POLITICS_country_ranks.txt"))

    records = []
    for rank in ALL_RANKS:
        _, sp_body = V.entry(sp_text, rank, "TRY_REPLACE:")
        mod = V.sub(sp_body, "modifier")
        assert mod is not None, f"{rank}: soft_pop record has no modifier block -- re-check GR.7a"
        new_mod = mod

        if rank in LOAN_RANKS:
            m = re.search(r'\n([ \t]*)country_loan_interest_rate_mult\s*=\s*(-?[\d.]+)[^\n]*', new_mod)
            assert m, f"{rank}: expected country_loan_interest_rate_mult in soft_pop's modifier -- re-check GR.7a"
            indent = m.group(1)
            note = (f"\n{indent}# country_loan_interest_rate_mult = {m.group(2)}  restored to a comment on purpose --"
                    f"\n{indent}# decision 27.08.2026 (GR.7a): TGR's loan system drops rank-dependent interest"
                    f"\n{indent}# entirely, and that is followed here rather than Grey's vanilla-style value.")
            new_mod = new_mod[:m.start()] + note + new_mod[m.end():]

        extra_fields = []
        if rank in EXPORT_IMPORT_RANKS:
            _, tgr_body = V.entry(tgr_trade_text, rank, "INJECT:")
            tgr_mod = V.sub(tgr_body, "modifier")
            assert tgr_mod is not None, f"{rank}: TGR_TRADE_country_ranks.txt no longer INJECTs a modifier -- re-check GR.7a"
            fields = re.findall(r'(state_(?:export|import)_advantage_mult\s*=\s*-?[\d.]+)', tgr_mod)
            assert len(fields) == 2, f"{rank}: expected 2 TGR advantage fields, got {fields} -- re-check GR.7a"
            extra_fields += [f + "  # TGR, restored" for f in fields]

        if rank in CONSTRUCTION_RANKS:
            _, tgr_pol_body = V.entry(tgr_pol_text, rank, "REPLACE_OR_CREATE:")
            tgr_pol_mod = V.sub(tgr_pol_body, "modifier")
            assert tgr_pol_mod is not None
            m = re.search(r'country_construction_add\s*=\s*\d+', tgr_pol_mod)
            assert m, f"{rank}: TGR no longer adds country_construction_add -- re-check GR.7a"
            extra_fields.append(m.group(0) + "  # TGR, field didn't exist before")

        if extra_fields:
            close_idx = new_mod.rstrip().rfind('}')
            assert close_idx != -1
            new_mod = new_mod[:close_idx].rstrip() + "\n\t\t" + "\n\t\t".join(extra_fields) + "\n\t}"

        new_body = V.replace_sub(sp_body, "modifier", new_mod)
        records.append(f"REPLACE_OR_CREATE:{rank} = {{{new_body}}}")

    write(
        "common/country_ranks/zz_greys_tgr_country_ranks.txt",
        "\n\n".join(records),
        "restore TGR's trade-advantage and construction fields on seven ranks; drop rank-dependent loan interest per the loan decision",
        "_grey_soft_pop's TRY_REPLACE (matches current 1.13 vanilla, see TGR.1) restates every rank's "
        "modifier block whole, dropping TGR's state_export_advantage_mult/state_import_advantage_mult "
        "INJECT on six ranks and TGR's new country_construction_add on great_power/major_power -- both "
        "restored here, read live from TGR's own files. country_loan_interest_rate_mult is commented "
        "out wherever soft_pop carries it: decision 27.08.2026 (GR.7a) was to follow TGR's own design, "
        "which drops rank-dependent loan interest on purpose as part of its separate loan system, rather "
        "than keep Grey's vanilla-style value. decentralized_power is untouched by either side, not "
        "included. !! MAINTENANCE !! if soft_pop ever stops carrying country_loan_interest_rate_mult on "
        "one of these ranks, or TGR's advantage/construction values change, this generator's asserts will "
        "fail loudly -- re-run and re-check rather than editing the output by hand."
    )


# ---------------------------------------------------------------------------
# GR.7b -- four citizenship laws
# ---------------------------------------------------------------------------

CITIZENSHIP_LAWS = [
    "law_ethnostate", "law_national_supremacy", "law_racial_segregation", "law_cultural_exclusion",
]


def build_citizenship_laws():
    tgr_text = V.read(os.path.join(TGR, "common/laws/TGR_POLITICS_citizenship.txt"))
    sp_text = V.read(os.path.join(SOFT_POP, "common/laws/zMoG_SPA_citizenship.txt"))

    records = []
    for law in CITIZENSHIP_LAWS:
        _, tgr_body = V.entry(tgr_text, law, "INJECT:")
        tgr_mod = V.sub(tgr_body, "acceptance_modifier")
        assert tgr_mod is not None, f"{law}: TGR no longer INJECTs acceptance_modifier -- re-check GR.7b"
        m = re.search(r'country_political_strength_full_acceptance_mult\s*=\s*(-?[\d.]+)', tgr_mod)
        assert m, f"{law}: TGR's acceptance_modifier lost country_political_strength_full_acceptance_mult -- re-check GR.7b"
        tgr_value = float(m.group(1))
        assert tgr_value < 0, f"{law}: expected TGR's value to be negative (a counterweight), got {tgr_value}"

        _, sp_body = V.entry(sp_text, law, "TRY_REPLACE:")
        sp_mod = V.sub(sp_body, "acceptance_modifier")
        assert sp_mod is not None, f"{law}: soft_pop has no acceptance_modifier -- re-check GR.7b"
        sm = re.search(r'country_political_strength_full_acceptance_mult\s*=\s*(-?[\d.]+)', sp_mod)
        assert sm, f"{law}: soft_pop's acceptance_modifier lost country_political_strength_full_acceptance_mult -- re-check GR.7b"
        sp_value = float(sm.group(1))
        assert abs(sp_value + tgr_value) < 1e-9, (
            f"{law}: soft_pop's {sp_value} and TGR's {tgr_value} no longer net to zero -- "
            f"this is no longer a straight counterweight restore, re-check GR.7b before writing")

        records.append(
            f"INJECT:{law} = {{\n\tacceptance_modifier = {{\n\t\tcountry_political_strength_full_acceptance_mult = {m.group(1)}\n\t}}\n}}"
        )

    write(
        "common/laws/zz_greys_tgr_citizenship.txt",
        "\n\n".join(records),
        "re-issue TGR's acceptance-mult counterweight on four citizenship laws after Grey's later TRY_REPLACE",
        "vanilla gives country_political_strength_full_acceptance_mult = 0.25/0.20/0.1/0.1 on these four "
        "laws; TGR INJECTs the same numbers negated to net the bonus to zero. _grey_soft_pop's later "
        "TRY_REPLACE restates the vanilla (positive) values, and a modifier block's repeated keys sum -- "
        "so TGR's INJECT would need to land on top of a body that still carries the vanilla value to work, "
        "and Grey's body does, so simply re-issuing TGR's own INJECT after the whole Grey's pack nets back "
        "to zero exactly (rules file, section 1: 'counterweight with the opposite sign gets silently "
        "resurrected'). !! MAINTENANCE !! this only works because Grey's value still equals vanilla -- if "
        "_grey_soft_pop ever changes these four numbers on purpose, this stops being a restore and becomes "
        "a balance decision; the generator's assert catches exactly that."
    )


# ---------------------------------------------------------------------------
# GR.7c -- four defines
# ---------------------------------------------------------------------------

def _define(text: str, group: str, key: str) -> str:
    _, body = V.entry(text, group)
    m = re.search(r'(?m)^\s*' + re.escape(key) + r'\s*=\s*(-?[\d.]+)', body)
    assert m, f"{group}.{key} not found -- re-check GR.7c"
    return m.group(1)


def build_defines():
    tgr_trade = V.read(os.path.join(TGR, "common/defines/TGR_TRADE_defines.txt"))
    tgr_pops = V.read(os.path.join(TGR, "common/defines/TGR_POPS_defines.txt"))
    sea = V.read(os.path.join(SOFT_ECON, "common/defines/zzz_MoG_SEA_def.txt"))
    spa = V.read(os.path.join(SOFT_POP, "common/defines/zzz_MoG_SPA_def.txt"))

    # Sanity: Grey's currently just restates vanilla on all four -- if that ever
    # stops being true, this is a balance decision, not a restore.
    grey_hq = _define(sea, "NEconomy", "COMPANY_MINIMUM_LEVELS_PER_HQ")
    grey_downsize = _define(sea, "NEconomy", "AUTO_DOWNSIZE_BUILDING_MIN_UNUSED_TRADE_CAPACITY")
    grey_base = _define(spa, "NPops", "MAX_DEMAND_ADJUSTMENT_BASE_AMOUNT")
    grey_scaled = _define(spa, "NPops", "MAX_DEMAND_ADJUSTMENT_SCALED_AMOUNT")
    assert grey_hq == "5", f"soft_econ's COMPANY_MINIMUM_LEVELS_PER_HQ changed to {grey_hq} -- re-check GR.7c"
    assert grey_downsize == "20", f"soft_econ's AUTO_DOWNSIZE_BUILDING_MIN_UNUSED_TRADE_CAPACITY changed to {grey_downsize} -- re-check GR.7c"
    assert grey_base == "0.01", f"soft_pop's MAX_DEMAND_ADJUSTMENT_BASE_AMOUNT changed to {grey_base} -- re-check GR.7c"
    assert grey_scaled == "0.09", f"soft_pop's MAX_DEMAND_ADJUSTMENT_SCALED_AMOUNT changed to {grey_scaled} -- re-check GR.7c"

    tgr_hq = _define(tgr_trade, "NEconomy", "COMPANY_MINIMUM_LEVELS_PER_HQ")
    tgr_downsize = _define(tgr_trade, "NEconomy", "AUTO_DOWNSIZE_BUILDING_MIN_UNUSED_TRADE_CAPACITY")
    tgr_base = _define(tgr_pops, "NPops", "MAX_DEMAND_ADJUSTMENT_BASE_AMOUNT")
    tgr_scaled = _define(tgr_pops, "NPops", "MAX_DEMAND_ADJUSTMENT_SCALED_AMOUNT")

    text = (
        "NEconomy = {\n"
        f"\tCOMPANY_MINIMUM_LEVELS_PER_HQ = {tgr_hq}\n"
        f"\tAUTO_DOWNSIZE_BUILDING_MIN_UNUSED_TRADE_CAPACITY = {tgr_downsize}\n"
        "}\n\n"
        "NPops = {\n"
        f"\tMAX_DEMAND_ADJUSTMENT_BASE_AMOUNT = {tgr_base}\n"
        f"\tMAX_DEMAND_ADJUSTMENT_SCALED_AMOUNT = {tgr_scaled}\n"
        "}"
    )
    write(
        "common/defines/zz_greys_tgr_defines.txt",
        text,
        "restore four defines TGR deliberately changed and Grey's silently reverts to vanilla",
        "defines merge per key, last mod loaded wins (rules file, section 1). On these four keys "
        "_grey_soft_econ / _grey_soft_pop just restate the vanilla default -- not a decision, a "
        "no-op -- while TGR made a deliberate change on each. Loading later, Grey's plain vanilla "
        "restatement wins and TGR's choice is gone with nothing in error.log. PRICE_RANGE and "
        "BUY_SELL_DIFF_AT_MAX_FACTOR are NOT here -- decision point #3, soft_econ's own values (0.9 / 3) "
        "were kept on purpose, see the plan and report section 5."
    )


# ---------------------------------------------------------------------------

def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: {seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_tgr.py -> {OUT}")
    steps = (
        ("country ranks (GR.7a)", build_country_ranks),
        ("citizenship laws (GR.7b)", build_citizenship_laws),
        ("defines (GR.7c)", build_defines),
    )
    for name, fn in steps:
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current Grey's / TGR sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
