#!/usr/bin/env python3
"""
Д2.11 (night 6.10.2026) -- the switch of a company headquarters' ownership method, by company:
scripted_effects/zz_ef_listing_switch.txt of the E&F hotfix.

In 1.13 every company has its own headquarters building type, building_company_<company key> (the save: company
24 Rothschild_Bank_gbr -> building 13 = building_company_Rothschild_Bank_gbr, levels 33, dividends 9024 a week),
made by the engine from the template building_company_headquarter (group bg_company_headquarter). The only effect
that sets a method, activate_production_method, takes the building type as a literal key (state / country scope),
so the switch is a dispatcher over the company types: building scope ->
    zz_ef_listing_go_public  -- pm_company_headquarter_publicly_traded (EF.22)
    zz_ef_listing_go_private -- pm_company_headquarter_privately_owned (vanilla)
in the building's state. Only the companies the method is for (category capitalist_owned, the default when a company
type has none) of vanilla and E&F -- the hotfix's dependencies: a key of a mod that is not loaded would be an
unknown building type. Companies of other mods are not switched (the megapack can extend the list).

Reads vic3_mods_out (run on the PC: py_tool("regen_ef_listing", [])).

Usage:
    py tools/regen_ef_listing.py            # write
    py tools/regen_ef_listing.py --check    # exit 1 if the file differs
"""

from __future__ import annotations

import argparse
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HOTFIX = os.path.normpath(os.path.join(HERE, "..", "_ef", "ef hotfix 1.13"))
OUT = os.path.join(HOTFIX, "common", "scripted_effects", "zz_ef_listing_switch.txt")
OUT_DIR = os.path.normpath(os.path.join(HERE, "..", "..", "vic3_mods_out"))
SOURCES = [os.path.join(OUT_DIR, ".vanillaVIC3", "common", "company_types"),
           os.path.join(OUT_DIR, "E&F", "common", "company_types")]

PM_PUBLIC = "pm_company_headquarter_publicly_traded"
PM_PRIVATE = "pm_company_headquarter_privately_owned"

HEADER = """\
# GENERATED by tools/regen_ef_listing.py -- do not edit by hand.
#############################################
# Д2.11 (6.10.2026) -- the headquarters' ownership method by script (scripted_effects/zz_ef_listing.txt): one
# headquarters type per company (building_company_<key>), activate_production_method takes it as a literal, so a
# dispatcher over the capitalist-owned companies of vanilla and E&F. BUILDING scope (a headquarters).
#############################################

"""


def strip_comments(s: str) -> str:
    return re.sub(r"#[^\n]*", "", s)


def top_blocks(s: str):
    """(key, body) of the top-level `key = { ... }` blocks."""
    i, n = 0, len(s)
    while i < n:
        m = re.compile(r"([\w:.\-]+)\s*=\s*\{").search(s, i)
        if not m:
            return
        depth, j = 1, m.end()
        while j < n and depth:
            if s[j] == "{":
                depth += 1
            elif s[j] == "}":
                depth -= 1
            j += 1
        yield m.group(1), s[m.end():j - 1]
        i = j


def companies() -> list[str]:
    keys: dict[str, str] = {}
    for src in SOURCES:
        files = sorted(glob.glob(os.path.join(src, "*.txt")))
        if not files:
            sys.exit(f"no company types in {src}")
        for f in files:
            s = strip_comments(open(f, encoding="utf-8-sig", errors="replace").read())
            for key, body in top_blocks(s):
                if ":" in key:      # INJECT: / REPLACE: -- not a new type
                    continue
                m = re.search(r"\bcategory\s*=\s*(\w+)", body)
                keys[key] = m.group(1) if m else "capitalist_owned"
    return sorted(k for k, cat in keys.items() if cat == "capitalist_owned")


def dispatcher(name: str, pm: str, keys: list[str]) -> str:
    out = [f"{name} = {{\n"]
    for i, k in enumerate(keys):
        kw = "if" if i == 0 else "else_if"
        out.append(f"\t{kw} = {{\n\t\tlimit = {{ is_building_type = building_{k} }}\n"
                   f"\t\tstate = {{ activate_production_method = {{ building_type = building_{k} production_method = {pm} }} }}\n"
                   f"\t}}\n")
    out.append("}\n")
    return "".join(out)


def build() -> str:
    keys = companies()
    return HEADER + f"# {len(keys)} companies\n\n" + dispatcher("zz_ef_listing_go_public", PM_PUBLIC, keys) + "\n" + \
        dispatcher("zz_ef_listing_go_private", PM_PRIVATE, keys)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = build()
    if a.check:
        old = open(OUT, encoding="utf-8-sig").read() if os.path.exists(OUT) else ""
        if old != text:
            print("differs"); sys.exit(1)
        print("ok"); return
    with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT} ({text.count('else_if') // 2 + 1} companies)")


if __name__ == "__main__":
    main()
