#!/usr/bin/env python3
"""
В3.2 (decided 4.10, М.8 а; 5.10): a subject is in its overlord's currency zone -- the overlord's standard law, its
currency law (E&F has one law per currency, 95) and its parity, no parity of its own.

M.8 (4.10) already hands a subject's metal to the overlord's CB (zz_ef_subject_metal.txt, once at week 12); this
moves the laws. Monthly (zz_ef_money_model_monthly_step), from week 13, for a subject whose overlord has a central bank
on a metal standard (gold, silver, bimetallism) with a currency law:
  * the overlord's standard law if the subject's differs (E&F's on_activate_monetary_system_law runs: our M.10 switch
    converts the subject's metal -- none after M.8 -- and sets an E&F parity that is overwritten below);
  * the overlord's currency law if the subject's differs (activate_law bypasses the laws' possible);
  * var:money_value_target_1 = the overlord's (the parity), var:zz_ef_cur_zone = the overlord (the AI's parity rule
    and the player's devaluation law skip the zone: zz_ef_mp_can_work);
  * after E&F's introduction_new_currency (a subject without a bank building gets one and E&F's own currency for its
    tag), the zone is put back at once (zz_ef_cur_intro_after).
Not here (the user 4.10, "later"): overlords on fiat, the gold exchange standard, no monetary system, subjects without
a standard of their own (Е.8) -- the subject leaves the zone (the variable goes) and keeps its laws.

Writes _ef/ef hotfix 1.13/common/scripted_effects/zz_ef_currency_zone.txt and
common/scripted_triggers/zz_ef_currency_zone_triggers.txt. The 95 laws are read from E&F's
common/laws/01_ef_currency_type.txt (asserted).

Usage:
    py tools/regen_ef_currency_zone.py [--check]
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))
SRC = res(r"..\..\vic3_mods_out\E&F\common\laws\01_ef_currency_type.txt")
OUT = res(r"..\_ef\ef hotfix 1.13\common\scripted_effects\zz_ef_currency_zone.txt")
OUT_TRG = res(r"..\_ef\ef hotfix 1.13\common\scripted_triggers\zz_ef_currency_zone_triggers.txt")
STANDARDS = ["law_gold_standard", "law_silver_standard", "law_bimetallism_standard"]


def laws():
    t = open(SRC, encoding="utf-8-sig").read()
    out = re.findall(r"^(law_\w+_currency) = \{", t, re.M)
    assert len(out) == 95, f"{len(out)} currency laws, expected 95 (E&F changed)"
    return out


def build():
    L = laws()
    std = "".join(
        f"\t\telse_if = {{\n\t\t\tlimit = {{\n\t\t\t\toverlord = {{ has_law = law_type:{s} }}\n"
        f"\t\t\t\tNOT = {{ has_law = law_type:{s} }}\n\t\t\t}}\n\t\t\tactivate_law = law_type:{s}\n\t\t}}\n"
        for s in STANDARDS).replace("\t\telse_if", "\t\tif", 1)
    cur = "".join(
        f"\telse_if = {{\n\t\tlimit = {{\n\t\t\toverlord = {{ has_law = law_type:{x} }}\n"
        f"\t\t\tNOT = {{ has_law = law_type:{x} }}\n\t\t}}\n\t\tactivate_law = law_type:{x}\n\t}}\n"
        for x in L).replace("\telse_if", "\tif", 1)
    has_cur = "".join(f"\t\thas_law = law_type:{x}\n" for x in L)
    std_or = "".join(f"\t\t\t\t\thas_law = law_type:{s}\n" for s in STANDARDS)
    trg = f"""# GENERATED by tools/regen_ef_currency_zone.py -- do not edit by hand.
# В3.2 (5.10): a subject in its overlord's currency zone -- see the generator's docstring.

# Country scope: the country has one of E&F's 95 currency laws.
zz_ef_cur_zone_has_currency = {{
	OR = {{
{has_cur}	}}
}}
"""
    return trg, f"""# GENERATED by tools/regen_ef_currency_zone.py -- do not edit by hand.
# В3.2 (5.10): a subject in its overlord's currency zone -- see the generator's docstring.

# Country scope, monthly (zz_ef_money_model_monthly_step) and after introduction_new_currency.
zz_ef_cur_zone_step = {{
	if = {{
		limit = {{
			is_subject = yes
			has_variable = zz_ef_weeks_run
			var:zz_ef_weeks_run >= 13
			overlord = {{
				has_modifier = has_central_bank
				has_variable = money_value_target_1
				var:money_value_target_1 > 0
				OR = {{
{std_or}				}}
				zz_ef_cur_zone_has_currency = yes
			}}
		}}
		set_variable = {{ name = zz_ef_cur_zone value = overlord }}
{std}		zz_ef_cur_zone_currency = yes
		set_variable = {{ name = money_value_target_1 value = overlord.var:money_value_target_1 }}
	}}
	else_if = {{
		limit = {{ has_variable = zz_ef_cur_zone }}
		remove_variable = zz_ef_cur_zone
	}}
}}

# The overlord's currency law, if ours differs.
zz_ef_cur_zone_currency = {{
{cur}}}
"""


def main():
    bad = 0
    for path, out in zip((OUT_TRG, OUT), build()):
        assert out.count("{") == out.count("}")
        if "--check" in sys.argv:
            cur = open(path, encoding="utf-8-sig").read() if os.path.exists(path) else ""
            print("ok" if cur == out else "DIFFERS", path)
            bad += cur != out
            continue
        with open(path, "w", encoding="utf-8-sig", newline="\n") as f:
            f.write(out)
        print("ok", path)
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
