#!/usr/bin/env python3
"""
В5.5 (decided by the user 5.10; with EF.37, Ф.10): a bond is a part of the engine's government debt.

The engine's debt (principal) is the treasury's loan from its own economy: the interest goes to the pops whose
privately owned cash reserves back the loans (vanilla concept_budget_interest_desc; the nationally owned part lowers
the government dividends). The engine takes and repays it alone. E&F's treasury bonds (ai_buy_bond_1..10: the buyer's
treasury pays the price, the seller gets nothing; the buyer's interest is E&F's income modifier from nobody, since
Е.5 / Д.2 the seller paid it as an expense line; at maturity the buyer gets the price back from nobody) become a
record of WHO HOLDS A PART of the seller's principal:

  1. purchase  -- the price goes into the seller's bank pool (not its treasury), at most the seller's principal minus
                  the parts already held; the rest goes back to the buyer's treasury;
  2. interest  -- the seller pays the engine as usual; the holder gets (its part / principal) x the week's interest
                  (the bridge's GetInterestPayment, var:zz_ef_g_ipay), out of the seller's pool (the pool took the
                  price: it sold part of its claim). E&F's income modifier and our Д.2 expense line go;
  3. repayment -- the engine repays alone; the principal under the parts held -> each holder gets the difference back
                  from the seller's pool; E&F's maturity -> the part is bought back from the seller's pool (E&F's
                  payout from nobody removed);
  4. default   -- the principal falls by more than half in a week while the country is in default (in_default): the
                  parts over it are written off, nobody pays; a fast repayment out of default is bought back (5.10 evening).
Weekly, in the money model's step: the holder walks its 10 slots; the seller's side is summed in var:zz_ef_bl_acc_*
and rolled into var:zz_ef_f_bl_* at its own step (at most a week late). The bond tables (Е.6) -- later.

Private banks' bonds (В1.6, the user 5.10 evening: "as В5.5"): E&F's ai_privat_bank_bond_N / _renforcement (25 slots on
the buyer country, var:ai_privat_bank_bond_value_N, the seller in its list ai_privat_bank_seller_country_general_N) took
the price out of the buyer's pool and gave the seller nothing -- run s1e: one-off flows without a counterpart of
6-16M a month (Britain 1837.1, 1838.1; Qing 1837.8). The ledger watches each slot weekly: a rise of E&F's value is a
purchase -- the part (at most the seller's room) into the seller's pool, the rest back to the buyer's pool and off
E&F's value (its interest scaled with it); the principal under the parts -> the part bought back from the seller's
pool into the buyer's; E&F dropping the value (its seller gone) -- written off. The banks' yearly interest stays as
Ф.2 pays it (the issuer's treasury, bf28108). The parts count in the seller's var:zz_ef_bl_held with the treasury's.

A rise with no seller found in E&F's list goes back whole (run s1g: Britain 1838.1, 1.95M unpaired; log line EFP).

Only existing debt (the user 5.10 evening): E&F picks the seller by its own remaining_debt; the treasury's
ai_buy_bond_1..10, the banks' seller list central_bank_debt_variable_list and ai_privat_bank_bond_N_renforcement also
require room in the seller's engine debt (zz_ef_bl_room > 0) -- was: almost every purchase went back to the buyer
(run s1b: principal 0 everywhere).

Writes (via ld_gen, by entry keys, into the fork «E&F: Ledgerdemain»):
  common/scripted_effects/ld_bond_ledger.txt          -- the ledger (generated slots);
  common/script_values/ld_bond_ledger_values.txt      -- its script values.
The changes of E&F's own effects (ai_buy_bond_N / central_bank_debt_variable_list / ai_privat_bank_bond_N_renforcement
with the room test zz_ef_bl_room > 0; ai_bond_maturity_N without the payout; interest_per_month_from_foreign_debt_investment)
are in E&F's bodies; the generator does not read E&F.

Usage:
    py tools/regen_ef_bond_ledger.py [--check]    # --check: exit 1 if the fork files differ
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

OUT_LEDGER = "common/scripted_effects/zz_ef_bond_ledger.txt"        # пути хотфикса; ld_gen пишет в форк (ld_*)
OUT_VALUES = "common/script_values/zz_ef_bond_ledger_values.txt"
SLOTS = range(1, 11)
PB_SLOTS = range(1, 26)
HEAD = "# GENERATED by tools/regen_ef_bond_ledger.py -- do not edit by hand.\n"


def slot(n):
    return f"""
# slot {n}: E&F's ai_buy_bond_{n}_on / ai_seller_country_general_{n} / ai_total_bond_value_{n}
zz_ef_bl_slot_{n} = {{
	if = {{
		limit = {{
			has_variable = ai_buy_bond_{n}_on
			var:ai_buy_bond_{n}_on = 1
			NOT = {{ has_variable = zz_ef_bh_{n} }}
			has_variable = ai_seller_country_general_{n}
			has_variable = ai_total_bond_value_{n}
			exists = var:ai_seller_country_general_{n}
			var:ai_seller_country_general_{n} = {{ is_country_type = recognized }}
		}}
		set_variable = {{ name = zz_ef_bs_{n} value = var:ai_seller_country_general_{n} }}
		set_variable = {{ name = zz_ef_bh_{n} value = var:ai_total_bond_value_{n} }}
		zz_ef_bl_register = {{ N = {n} }}
	}}
	else_if = {{
		limit = {{
			has_variable = zz_ef_bh_{n}
			has_variable = ai_buy_bond_{n}_on
			var:ai_buy_bond_{n}_on = 1
			has_variable = zz_ef_bs_{n}
			exists = var:zz_ef_bs_{n}
		}}
		zz_ef_bl_hold = {{ N = {n} }}
	}}
	else_if = {{
		limit = {{ has_variable = zz_ef_bh_{n} }}
		zz_ef_bl_end = {{ N = {n} }}
	}}
}}
"""



def pb_slot(n):
    return f"""
# private banks' slot {n}: E&F's ai_privat_bank_bond_value_{n} / ai_privat_bank_seller_country_general_{n}
zz_ef_pb_slot_{n} = {{
	# no slot (E&F's value absent, nothing registered): the body would only set zeros nothing reads -- skip it
	if = {{
		limit = {{
			OR = {{
				has_variable = ai_privat_bank_bond_value_{n}
				has_variable = zz_ef_pbh_{n}
			}}
		}}
		if = {{ limit = {{ NOT = {{ has_variable = zz_ef_pbh_{n} }} }} set_variable = {{ name = zz_ef_pbh_{n} value = 0 }} }}
		set_variable = {{ name = zz_ef_pb_v value = 0 }}
		if = {{ limit = {{ has_variable = ai_privat_bank_bond_value_{n} }} set_variable = {{ name = zz_ef_pb_v value = var:ai_privat_bank_bond_value_{n} }} }}
		if = {{
			limit = {{ var:zz_ef_pb_v > var:zz_ef_pbh_{n} }}
			if = {{
				limit = {{ has_variable_list = ai_privat_bank_seller_country_general_{n} }}
				random_in_list = {{
					variable = ai_privat_bank_seller_country_general_{n}
					limit = {{ is_country_type = recognized }}
					save_scope_as = zz_ef_pbsel_{n}
				}}
			}}
			if = {{
				limit = {{ exists = scope:zz_ef_pbsel_{n} }}
				scope:zz_ef_pbsel_{n} = {{ save_scope_as = zz_ef_bl_seller }}
				set_variable = {{ name = zz_ef_pbs_{n} value = scope:zz_ef_pbsel_{n} }}
				zz_ef_pb_buy = {{ N = {n} }}
			}}
			else = {{
				zz_ef_pb_no_seller = {{ N = {n} }}
			}}
			set_variable = {{ name = zz_ef_pbh_{n} value = var:ai_privat_bank_bond_value_{n} }}
		}}
		else_if = {{
			limit = {{ var:zz_ef_pb_v < var:zz_ef_pbh_{n} }}
			zz_ef_pb_drop = {{ N = {n} }}
		}}
		if = {{
			limit = {{
				var:zz_ef_pbh_{n} > 0
				has_variable = zz_ef_pbs_{n}
				exists = var:zz_ef_pbs_{n}
				var:zz_ef_pbs_{n} = {{
					is_country_type = recognized
					has_variable = zz_ef_bl_ratio
					var:zz_ef_bl_ratio < 1
				}}
			}}
			zz_ef_pb_cutback = {{ N = {n} }}
		}}
		if = {{
			limit = {{ var:zz_ef_pbh_{n} <= 0 has_variable = zz_ef_pbs_{n} }}
			remove_variable = zz_ef_pbs_{n}
		}}
	}}
}}
"""


PB_COMMON = """
# Buyer scope, private banks' slot $N$ rose (E&F's purchase or reinforcement): var:zz_ef_pb_v - var:zz_ef_pbh_$N$ bought
# from scope:zz_ef_bl_seller; the part at most its room, the rest back to our pool and off E&F's value.
zz_ef_pb_buy = {
	set_variable = { name = zz_ef_bl_x value = var:zz_ef_pb_v }
	change_variable = { name = zz_ef_bl_x subtract = var:zz_ef_pbh_$N$ }
	set_variable = { name = zz_ef_bl_y value = var:zz_ef_bl_x }
	change_variable = { name = zz_ef_bl_y subtract = scope:zz_ef_bl_seller.zz_ef_bl_room }
	if = {
		limit = { var:zz_ef_bl_y > 0 }
		add_investment_pool = var:zz_ef_bl_y
		change_variable = { name = zz_ef_f_pb_refund add = var:zz_ef_bl_y }
		change_variable = { name = zz_ef_bl_x subtract = var:zz_ef_bl_y }
		zz_ef_pb_cut = { N = $N$ }
	}
	change_variable = { name = zz_ef_f_pb_buy add = var:zz_ef_bl_x }
	scope:zz_ef_bl_seller = {
		if = { limit = { NOT = { has_variable = zz_ef_bl_held } } set_variable = { name = zz_ef_bl_held value = 0 } }
		change_variable = { name = zz_ef_bl_held add = root.var:zz_ef_bl_x }
		zz_ef_bl_acc_add = { F = sold V = root.var:zz_ef_bl_x }
		add_investment_pool = root.var:zz_ef_bl_x
		# the seller's banks sold a part of their claim on the engine's debt -- their capital
		zz_ef_bl_seller_capital = { V = root.var:zz_ef_bl_x }
	}
	remove_variable = zz_ef_bl_x
	remove_variable = zz_ef_bl_y
}

# Buyer scope, slot $N$ rose with no seller found in E&F's list (run s1g: Britain 1838.1, 1.95M): no debt to hold a
# part of -- the whole purchase back to our pool and off E&F's value (only existing debt is bought).
zz_ef_pb_no_seller = {
	set_variable = { name = zz_ef_bl_y value = var:zz_ef_pb_v }
	change_variable = { name = zz_ef_bl_y subtract = var:zz_ef_pbh_$N$ }
	add_investment_pool = var:zz_ef_bl_y
	change_variable = { name = zz_ef_f_pb_refund add = var:zz_ef_bl_y }
	if = { limit = { zz_ef_logs_on = yes } debug_log = "EFP|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|slot $N$|no_seller [THIS.GetCountry.MakeScope.Var('zz_ef_bl_y').GetValue|0]" }
	zz_ef_pb_cut = { N = $N$ }
	remove_variable = zz_ef_bl_y
}

# Buyer scope: E&F's value of slot $N$ down by var:zz_ef_bl_y (at most to 0), its interest scaled with it.
zz_ef_pb_cut = {
	if = {
		limit = { var:ai_privat_bank_bond_value_$N$ > 0 }
		set_variable = {
			name = zz_ef_pb_r
			value = {
				value = var:ai_privat_bank_bond_value_$N$
				subtract = var:zz_ef_bl_y
				divide = var:ai_privat_bank_bond_value_$N$
				min = 0
				max = 1
			}
		}
		change_variable = { name = ai_privat_bank_bond_value_$N$ multiply = var:zz_ef_pb_r }
		if = {
			limit = { has_variable = ai_privat_bank_interest_calculated_$N$ }
			change_variable = { name = ai_privat_bank_interest_calculated_$N$ multiply = var:zz_ef_pb_r }
		}
		remove_variable = zz_ef_pb_r
	}
}

# Buyer scope, slot $N$ fell below what we registered (E&F reset it -- its seller gone): written off, nobody pays.
zz_ef_pb_drop = {
	set_variable = { name = zz_ef_bl_x value = var:zz_ef_pbh_$N$ }
	change_variable = { name = zz_ef_bl_x subtract = var:zz_ef_pb_v }
	change_variable = { name = zz_ef_f_bl_lost add = var:zz_ef_bl_x }
	# the part is in the banks' book (zz_ef_bank_bonds) -- gone with no money, out of their capital
	change_variable = { name = zz_ef_bank_capital subtract = var:zz_ef_bl_x }
	if = {
		limit = {
			has_variable = zz_ef_pbs_$N$
			exists = var:zz_ef_pbs_$N$
			var:zz_ef_pbs_$N$ = { is_country_type = recognized }
		}
		var:zz_ef_pbs_$N$ = {
			if = { limit = { has_variable = zz_ef_bl_held } change_variable = { name = zz_ef_bl_held subtract = root.var:zz_ef_bl_x } }
			zz_ef_bl_acc_add = { F = woff V = root.var:zz_ef_bl_x }
		}
	}
	set_variable = { name = zz_ef_pbh_$N$ value = var:zz_ef_pb_v }
	remove_variable = zz_ef_bl_x
}

# Buyer scope, slot $N$ live, the seller's principal under the parts held: our part cut by (1 - ratio) -- bought back
# from its pool into ours, or written off in a default.
zz_ef_pb_cutback = {
	var:zz_ef_pbs_$N$ = { save_scope_as = zz_ef_bl_seller }
	set_variable = { name = zz_ef_bl_x value = var:zz_ef_pbh_$N$ }
	change_variable = { name = zz_ef_bl_x multiply = { value = 1 subtract = scope:zz_ef_bl_seller.var:zz_ef_bl_ratio } }
	set_variable = { name = zz_ef_bl_y value = var:zz_ef_bl_x }
	zz_ef_pb_cut = { N = $N$ }
	change_variable = { name = zz_ef_pbh_$N$ subtract = var:zz_ef_bl_x }
	scope:zz_ef_bl_seller = { change_variable = { name = zz_ef_bl_held subtract = root.var:zz_ef_bl_x } }
	if = {
		limit = { scope:zz_ef_bl_seller = { has_variable = zz_ef_bl_woff_now } }
		change_variable = { name = zz_ef_f_bl_lost add = var:zz_ef_bl_x }
		# written off -- out of the banks' capital (the part was in their book)
		change_variable = { name = zz_ef_bank_capital subtract = var:zz_ef_bl_x }
		scope:zz_ef_bl_seller = { zz_ef_bl_acc_add = { F = woff V = root.var:zz_ef_bl_x } }
	}
	else = {
		zz_ef_bl_pay = { F = redeem TO = zz_ef_f_pb_back SHORT = zz_ef_f_bl_lost INTO = pool }
	}
	remove_variable = zz_ef_bl_x
	remove_variable = zz_ef_bl_y
}
"""

def ledger():
    slots = "".join(slot(n) for n in SLOTS)
    calls = "".join(f"\tzz_ef_bl_slot_{n} = yes\n" for n in SLOTS)
    calls += "\t# private banks (В1.6)\n" + "".join(f"\tzz_ef_pb_slot_{n} = yes\n" for n in PB_SLOTS)
    pslots = "".join(pb_slot(n) for n in PB_SLOTS)
    return HEAD + f"""# В5.5 (5.10): E&F's treasury bonds as parts of the seller's engine debt -- see the generator's docstring.
# Values: script_values/zz_ef_bond_ledger_values.txt (generated with this file).

# Country scope, weekly (zz_ef_money_model_step): the seller's side first (roll last week's sums, the ratio of the
# principal to the parts held), then this country's slots as a holder.
zz_ef_bond_ledger_step = {{
	# E&F's income modifier is gone (the holder is paid by the ledger)
	if = {{ limit = {{ has_modifier = interest_from_foreign_debt_investment }} remove_modifier = interest_from_foreign_debt_investment }}
	# --- as a seller ---
	zz_ef_bl_roll = {{ F = sold }}
	zz_ef_bl_roll = {{ F = int_out }}
	zz_ef_bl_roll = {{ F = redeem }}
	zz_ef_bl_roll = {{ F = woff }}
	set_variable = {{ name = zz_ef_bl_ratio value = 1 }}
	if = {{ limit = {{ has_variable = zz_ef_bl_woff_now }} remove_variable = zz_ef_bl_woff_now }}
	if = {{
		limit = {{
			has_variable = zz_ef_bl_held
			var:zz_ef_bl_held > 0
			zz_ef_bl_principal < var:zz_ef_bl_held
		}}
		set_variable = {{ name = zz_ef_bl_ratio value = zz_ef_bl_principal }}
		change_variable = {{ name = zz_ef_bl_ratio divide = var:zz_ef_bl_held }}
		# default: the principal more than halved in a week IN DEFAULT -> the parts over it are written off. Run
		# r1005_163333 (5.10 evening): Russia repaid its last 450K in one week and the holders' parts were written off --
		# a repayment is bought back from the pool, only the engine's default (in_default) writes off.
		if = {{
			limit = {{
				has_variable = zz_ef_bl_prev_principal
				zz_ef_bl_principal < zz_ef_bl_half_prev
				in_default = yes
			}}
			set_variable = {{ name = zz_ef_bl_woff_now value = yes }}
		}}
	}}
	set_variable = {{ name = zz_ef_bl_prev_principal value = zz_ef_bl_principal }}
	# --- as a holder ---
	set_variable = {{ name = zz_ef_f_bl_buy value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_refund value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_int_in value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_back value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_lost value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_int_short value = 0 }}
	set_variable = {{ name = zz_ef_f_pb_buy value = 0 }}
	set_variable = {{ name = zz_ef_f_pb_refund value = 0 }}
	set_variable = {{ name = zz_ef_f_pb_back value = 0 }}
{calls}	remove_variable = zz_ef_pb_v
	if = {{
		limit = {{
			OR = {{
				zz_ef_log_country = yes
				zz_ef_bl_held_v > 0
				zz_ef_bl_parts > 0
				zz_ef_bank_bonds > 0
			}}
		}}
		if = {{ limit = {{ zz_ef_logs_on = yes }} debug_log = "EFB|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|principal [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_bl_principal')|0]|held [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_bl_held_v')|0]|ratio [THIS.GetCountry.MakeScope.Var('zz_ef_bl_ratio').GetValue|3]|ipay [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_g_ipay')|0]|sold [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_sold')|0]|int_out [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_int_out')|0]|redeem [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_redeem')|0]|woff [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_woff')|0]|parts [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_treasury_bonds')|0]|buy [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_buy').GetValue|0]|refund [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_refund').GetValue|0]|int_in [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_int_in').GetValue|0]|back [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_back').GetValue|0]|lost [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_lost').GetValue|0]|pb_buy [THIS.GetCountry.MakeScope.Var('zz_ef_f_pb_buy').GetValue|0]|pb_refund [THIS.GetCountry.MakeScope.Var('zz_ef_f_pb_refund').GetValue|0]|pb_back [THIS.GetCountry.MakeScope.Var('zz_ef_f_pb_back').GetValue|0]|pbonds [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_bank_bonds')|0]" }}
	}}
}}

# var:zz_ef_f_bl_$F$ = var:zz_ef_bl_acc_$F$ (summed by the holders since our last step); the sum restarts.
zz_ef_bl_roll = {{
	set_variable = {{ name = zz_ef_f_bl_$F$ value = 0 }}
	if = {{
		limit = {{ has_variable = zz_ef_bl_acc_$F$ }}
		set_variable = {{ name = zz_ef_f_bl_$F$ value = var:zz_ef_bl_acc_$F$ }}
	}}
	set_variable = {{ name = zz_ef_bl_acc_$F$ value = 0 }}
}}

# Holder scope, slot $N$ just bought: var:zz_ef_bh_$N$ = E&F's price, var:zz_ef_bs_$N$ = the seller. The part is at
# most the seller's room (principal - the parts held); the rest back to our treasury; the part's price into the
# seller's pool.
zz_ef_bl_register = {{
	var:zz_ef_bs_$N$ = {{ save_scope_as = zz_ef_bl_seller }}
	set_variable = {{ name = zz_ef_bl_x value = scope:zz_ef_bl_seller.zz_ef_bl_room }}
	if = {{
		limit = {{ var:zz_ef_bh_$N$ > var:zz_ef_bl_x }}
		set_variable = {{ name = zz_ef_bl_y value = var:zz_ef_bh_$N$ }}
		change_variable = {{ name = zz_ef_bl_y subtract = var:zz_ef_bl_x }}
		add_treasury = var:zz_ef_bl_y
		zz_ef_tr_mark = {{ V = var:zz_ef_bl_y }}
		change_variable = {{ name = zz_ef_f_bl_refund add = var:zz_ef_bl_y }}
		set_variable = {{ name = zz_ef_bh_$N$ value = var:zz_ef_bl_x }}
	}}
	change_variable = {{ name = zz_ef_f_bl_buy add = var:zz_ef_bh_$N$ }}
	scope:zz_ef_bl_seller = {{
		if = {{ limit = {{ NOT = {{ has_variable = zz_ef_bl_held }} }} set_variable = {{ name = zz_ef_bl_held value = 0 }} }}
		change_variable = {{ name = zz_ef_bl_held add = root.var:zz_ef_bh_$N$ }}
		zz_ef_bl_acc_add = {{ F = sold V = root.var:zz_ef_bh_$N$ }}
		add_investment_pool = root.var:zz_ef_bh_$N$
		zz_ef_bl_seller_capital = {{ V = root.var:zz_ef_bh_$N$ }}
	}}
	remove_variable = zz_ef_bl_x
	if = {{ limit = {{ has_variable = zz_ef_bl_y }} remove_variable = zz_ef_bl_y }}
}}

# Holder scope, slot $N$ live: the seller's principal under the parts -> our part cut (paid back from its pool, or
# written off in a default); then the week's interest on what is left, from its pool.
zz_ef_bl_hold = {{
	var:zz_ef_bs_$N$ = {{ save_scope_as = zz_ef_bl_seller }}
	if = {{
		limit = {{
			scope:zz_ef_bl_seller = {{
				has_variable = zz_ef_bl_ratio
				var:zz_ef_bl_ratio < 1
			}}
		}}
		set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_bh_$N$ }}
		change_variable = {{ name = zz_ef_bl_x multiply = {{ value = 1 subtract = scope:zz_ef_bl_seller.var:zz_ef_bl_ratio }} }}
		change_variable = {{ name = zz_ef_bh_$N$ subtract = var:zz_ef_bl_x }}
		scope:zz_ef_bl_seller = {{ change_variable = {{ name = zz_ef_bl_held subtract = root.var:zz_ef_bl_x }} }}
		if = {{
			limit = {{ scope:zz_ef_bl_seller = {{ has_variable = zz_ef_bl_woff_now }} }}
			change_variable = {{ name = zz_ef_f_bl_lost add = var:zz_ef_bl_x }}
			scope:zz_ef_bl_seller = {{ zz_ef_bl_acc_add = {{ F = woff V = root.var:zz_ef_bl_x }} }}
		}}
		else = {{
			zz_ef_bl_pay = {{ F = redeem TO = zz_ef_f_bl_back SHORT = zz_ef_f_bl_lost INTO = treasury }}
		}}
	}}
	set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_bh_$N$ }}
	change_variable = {{ name = zz_ef_bl_x multiply = scope:zz_ef_bl_seller.zz_ef_bl_int_per_part }}
	# R1а.4: a holder's step after a gap -- the interest of the weeks its step covers
	change_variable = {{ name = zz_ef_bl_x multiply = zz_ef_step_weeks_v }}
	zz_ef_bl_pay = {{ F = int_out TO = zz_ef_f_bl_int_in SHORT = zz_ef_f_bl_int_short INTO = treasury }}
	remove_variable = zz_ef_bl_x
}}

# Holder scope, slot $N$ ended (E&F's maturity, its payout removed): the seller's pool buys the part back.
zz_ef_bl_end = {{
	if = {{
		limit = {{
			has_variable = zz_ef_bs_$N$
			exists = var:zz_ef_bs_$N$
			var:zz_ef_bs_$N$ = {{ is_country_type = recognized }}
		}}
		var:zz_ef_bs_$N$ = {{ save_scope_as = zz_ef_bl_seller }}
		set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_bh_$N$ }}
		scope:zz_ef_bl_seller = {{ change_variable = {{ name = zz_ef_bl_held subtract = root.var:zz_ef_bl_x }} }}
		zz_ef_bl_pay = {{ F = redeem TO = zz_ef_f_bl_back SHORT = zz_ef_f_bl_lost INTO = treasury }}
		remove_variable = zz_ef_bl_x
	}}
	else = {{
		change_variable = {{ name = zz_ef_f_bl_lost add = var:zz_ef_bh_$N$ }}
	}}
	remove_variable = zz_ef_bh_$N$
	if = {{ limit = {{ has_variable = zz_ef_bs_$N$ }} remove_variable = zz_ef_bs_$N$ }}
}}

# Holder scope: var:zz_ef_bl_x into our treasury (marked for the treasury's reconciliation, R1б В5) or our pool.
zz_ef_bl_into_treasury = {{
	add_treasury = var:zz_ef_bl_x
	zz_ef_tr_mark = {{ V = var:zz_ef_bl_x }}
}}
zz_ef_bl_into_pool = {{ add_investment_pool = var:zz_ef_bl_x }}

# Holder scope: var:zz_ef_bl_x from scope:zz_ef_bl_seller's pool (at most what it holds) to our treasury ($INTO$ =
# treasury) or our pool (pool, private banks);
# the seller sums it under $F$, we under var:$TO$; what its pool could not pay -- under var:$SHORT$.
zz_ef_bl_pay = {{
	set_variable = {{ name = zz_ef_bl_x0 value = var:zz_ef_bl_x }}
	change_variable = {{ name = $SHORT$ add = var:zz_ef_bl_x }}
	set_variable = {{
		name = zz_ef_bl_x
		value = {{
			value = var:zz_ef_bl_x
			max = {{
				value = scope:zz_ef_bl_seller.investment_pool
				min = 0
			}}
			min = 0
		}}
	}}
	scope:zz_ef_bl_seller = {{
		add_investment_pool = {{
			value = root.var:zz_ef_bl_x
			multiply = -1
		}}
		# R2, step 7: paid by the seller's banks (their capital)
		zz_ef_bl_seller_capital_out = {{ V = root.var:zz_ef_bl_x }}
		zz_ef_bl_acc_add = {{ F = $F$ V = root.var:zz_ef_bl_x }}
	}}
	zz_ef_bl_into_$INTO$ = yes
	change_variable = {{ name = $TO$ add = var:zz_ef_bl_x }}
	change_variable = {{ name = $SHORT$ subtract = var:zz_ef_bl_x }}
	# R2, step 7: the unpaid part
	set_variable = {{ name = zz_ef_bl_s value = var:zz_ef_bl_x0 }}
	change_variable = {{ name = zz_ef_bl_s subtract = var:zz_ef_bl_x }}
	if = {{ limit = {{ var:zz_ef_bl_s > 0 }} zz_ef_bl_short_$INTO$ = yes }}
	remove_variable = zz_ef_bl_s
	remove_variable = zz_ef_bl_x0
}}

# R2, step 7 (8.10): the seller's pool moves for its bonds (a sale, interest and repayments to the holders) are its
# banks' capital (the pool backs the engine's debt; the treasury pays the engine's interest as before) -- not «прочее».
zz_ef_bl_seller_capital = {{
	zz_ef_registry_init = yes
	change_variable = {{ name = zz_ef_bank_capital add = $V$ }}
}}
zz_ef_bl_seller_capital_out = {{
	zz_ef_registry_init = yes
	change_variable = {{ name = zz_ef_bank_capital subtract = $V$ }}
}}
# Holder scope, what the seller could not pay (var:zz_ef_bl_s): the private banks' part is in their book -- a loss of
# their capital; the treasury's parts are not in the banks' book.
zz_ef_bl_short_pool = {{ change_variable = {{ name = zz_ef_bank_capital subtract = var:zz_ef_bl_s }} }}
zz_ef_bl_short_treasury = {{ }}

# Seller scope: var:zz_ef_bl_acc_$F$ += $V$.
zz_ef_bl_acc_add = {{
	if = {{ limit = {{ NOT = {{ has_variable = zz_ef_bl_acc_$F$ }} }} set_variable = {{ name = zz_ef_bl_acc_$F$ value = 0 }} }}
	change_variable = {{ name = zz_ef_bl_acc_$F$ add = $V$ }}
}}
{slots}""" + PB_COMMON + pslots


def values():
    held = "".join(f"\tif = {{ limit = {{ has_variable = zz_ef_bh_{n} }} add = var:zz_ef_bh_{n} }}\n" for n in SLOTS)
    vf = "".join(f"zz_ef_v_f_bl_{k} = {{\n\tvalue = 0\n\tif = {{ limit = {{ has_variable = zz_ef_f_bl_{k} }} value = var:zz_ef_f_bl_{k} }}\n}}\n"
                 for k in ("sold", "int_out", "redeem", "woff", "buy", "refund", "int_in", "back", "lost", "int_short"))
    vf += "".join(f"zz_ef_v_f_pb_{k} = {{\n\tvalue = 0\n\tif = {{ limit = {{ has_variable = zz_ef_f_pb_{k} }} value = var:zz_ef_f_pb_{k} }}\n}}\n"
                  for k in ("buy", "refund", "back"))
    return HEAD + f"""# В5.5 (5.10): values of the bond ledger (scripted_effects/zz_ef_bond_ledger.txt) -- see the generator's docstring.

# the engine's debt
zz_ef_bl_principal = {{
	value = principal
	min = 0
}}
zz_ef_bl_half_prev = {{
	value = 0
	if = {{ limit = {{ has_variable = zz_ef_bl_prev_principal }} value = var:zz_ef_bl_prev_principal }}
	multiply = 0.5
}}
# the parts of our principal held abroad
zz_ef_bl_held_v = {{
	value = 0
	if = {{ limit = {{ has_variable = zz_ef_bl_held }} value = var:zz_ef_bl_held }}
	min = 0
}}
# room for new parts
zz_ef_bl_room = {{
	value = zz_ef_bl_principal
	subtract = zz_ef_bl_held_v
	min = 0
}}
# the week's interest per unit of principal (the bridge's GetInterestPayment / principal)
zz_ef_bl_int_per_part = {{
	value = 0
	if = {{
		limit = {{ zz_ef_bl_principal > 0 }}
		value = zz_ef_v_g_ipay
		divide = zz_ef_bl_principal
		min = 0
		max = 0.01
	}}
}}
# our parts of other countries' debt (the treasury's foreign bonds, replaces E&F's prices in zz_ef_treasury_bonds)
zz_ef_bl_parts = {{
	value = 0
{held}}}
# the week's results (0 if unset)
{vf}"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    for path, text in ((OUT_LEDGER, ledger()), (OUT_VALUES, values())):
        assert text.count("{") == text.count("}"), path
        ld_gen.emit(path, text)
    ld_gen.report("regen_ef_bond_ledger")


if __name__ == "__main__":
    main()
