"""
regen_vc_ef.py -- builds the E&F x VC compatch in `_vc/ef+vc done`.

The pair: E&F (+ hotfix) loads early, Victorian Century loads last. Machine
matrix: 145 shared keys, 0 shared paths (VC.2 in `План проекта.md`). Analysis:
`_vc/ef+vc done/conflicts_ef_vs_vc_report.md`.

Unlike the TGR x VC pair, nothing here needs a three-way body merge. VC's
REPLACE/REPLACE_OR_CREATE records already exist by the time this file loads
(VC loads before it); every fix below is a plain INJECT that appends E&F's own
lines -- lifted live from E&F's current files, never hand-copied -- into a
list or block VC already created. Source of truth is E&F's own file at
generation time, not a table in this script (rule from `Правила работы...`,
section 9: "источник истины брать из самого чужого мода").

What's real and what isn't, out of the 145 shared keys:
  * common/buy_packages -- 99 keys, all real. VC's REPLACE_OR_CREATE:wealth_N
    never mentions popneed_currency / popneed_financial_products, so E&F's
    INJECT (which adds exactly those) is a clean re-apply, unchanged since the
    January 2026 compatch (verified byte-identical against the current E&F
    file before writing this generator).
  * common/buildings -- 42 keys, 1 real. VC's buildings TRY_INJECT only
    can_build_private; E&F's INJECT only production_method_groups (adds
    pmg_market_liquidity + pmg_private_ownership_*) -- different sub-blocks,
    41 of them merge for free. The exception: building_opium_plantation. VC
    does a full REPLACE (not TRY_INJECT) there and its production_method_groups
    list does not carry E&F's two pmg's -- they vanish silently.
  * common/company_types -- 1 key, real. company_standard_oil: VC
    REPLACE_OR_CREATEs the whole company (its own American Standard Oil
    rework), E&F's INJECT adds two prestige goods to possible_prestige_goods
    that VC's body doesn't have.
  * common/defines (NEconomy) -- NOT a conflict. Both declare the group, but
    the specific member keys don't overlap: VC sets resource-discovery/slavery/
    minting/pop-profession keys, E&F sets PRICE_RANGE / GOODS_SHORTAGE_PENALTY_MAX
    / GOLD_RESERVE_RETURNS_FACTOR. E&F's own NATIONALIZATION_PER_LEVEL_COST and
    PRIVATIZATION_PER_LEVEL_COST lines that would collide are commented out.
    Same pattern as the TGR x VC pair's defines finding -- see the plan, VC.1.
  * common/technology/technologies (mutual_funds) -- NOT a conflict. E&F
    REPLACEs the tech and sets its own three modifier fields; VC's INJECT adds
    a fourth, disjoint field (country_free_charters_add) into the same
    `modifier` block. Different fields, same shape as buildings above.
  * common/history/global (GLOBAL) and common/on_actions
    (on_monthly_pulse_country) -- additive containers, not conflicts (pair_matrix
    already filters these; scan_conflicts.py's raw count of 147+2 includes them,
    hence 149 - 4 = 145 once you drop both occurrences of each).
  * ef hotfix's own 2 shared keys (GLOBAL, on_monthly_pulse_country) are the
    same two additive categories -- nothing to patch there either.

Usage:
    python3 regen_vc_ef.py            # write the compatch
    python3 regen_vc_ef.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

EF = res("../../vic3_mods_out/E&F")
VC = res("../../vic3_mods_out/VC")
OUT = res("../_vc/ef+vc done")

HEADER = """# E&F x VC compatch -- {what}
# Generated by tools/regen_vc_ef.py on {date}. Do not hand-edit: the next run
# overwrites this file. Change the generator instead.
#
# Load order: E&F -> E&F Hotfix -> ... -> Victorian Century -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}


def record(path: str, key: str) -> list[str] | None:
    """Lines of one top-level record, key line included, prefix stripped off."""
    lines = read_lines(path)
    pat = re.compile(r"^(?:[A-Z_]+:)?" + re.escape(key) + r"\s*=\s*\{")
    for i, raw in enumerate(lines):
        if pat.match(raw.split("#", 1)[0].lstrip("﻿")):
            depth = 0
            started = False
            for j in range(i, len(lines)):
                code = lines[j].split("#", 1)[0]
                depth += code.count("{") - code.count("}")
                if "{" in code:
                    started = True
                if started and depth <= 0:
                    body = lines[i:j + 1]
                    body[0] = re.sub(r"^﻿?(?:[A-Z_]+:)?", "", body[0])
                    return body
            return lines[i:]
    return None


def find_file(root: str, category: str, key: str) -> str | None:
    directory = os.path.join(root, category)
    if not os.path.isdir(directory):
        return None
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".txt"):
            continue
        full = os.path.join(directory, name)
        if record(full, key) is not None:
            return full
    return None


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


# ------------------------------------------------------------------- the pieces

def build_buy_packages():
    ef_f = find_file(EF, "common/buy_packages", "wealth_1")
    assert ef_f, "E&F wealth_1 not found -- did the buy_packages file move?"
    lines = read_lines(ef_f)
    injects = [ln for ln in lines if re.match(r"^INJECT:wealth_\d+\s*=", ln)]
    assert len(injects) == 99, f"expected 99 wealth_* INJECTs in E&F, found {len(injects)}"

    # Sanity: VC must not already define these two needs anywhere in its own
    # buy_packages file -- if it now does, this whole file needs a real per-key
    # merge instead of a blind re-apply, and this assert is the trip-wire.
    vc_f = find_file(VC, "common/buy_packages", "wealth_1")
    assert vc_f, "VC wealth_1 not found"
    vc_text = "\n".join(read_lines(vc_f))
    for need in ("popneed_currency", "popneed_financial_products"):
        assert need not in vc_text, (
            f"VC's buy_packages now mentions {need} -- re-check the merge, "
            "a blind re-inject would double it up")

    injects.sort(key=lambda ln: int(re.search(r"wealth_(\d+)", ln).group(1)))
    write("common/buy_packages/zz_vc_ef_buy_packages.txt",
          "\n".join(injects),
          "re-apply E&F's currency/financial-products needs",
          "VC's REPLACE_OR_CREATE:wealth_* wipes E&F's INJECTs (popneed_currency, "
          "popneed_financial_products) on all 99 tiers. VC never sets those two "
          "needs itself, so this is a clean re-apply of E&F's own lines, read "
          "live from its buy_packages file -- not a re-balance.")


def build_buildings():
    ef_f = find_file(EF, "common/buildings", "building_opium_plantation")
    assert ef_f, "E&F building_opium_plantation not found"
    ef_body = record(ef_f, "building_opium_plantation")
    ef_pmgs = [ln.strip() for ln in ef_body
               if re.match(r"^\s*pmg_", ln)]
    assert ef_pmgs, "E&F's building_opium_plantation INJECT has no pmg_* lines"

    vc_f = find_file(VC, "common/buildings", "building_opium_plantation")
    assert vc_f, "VC building_opium_plantation not found"
    vc_body = "\n".join(record(vc_f, "building_opium_plantation"))
    for pmg in ef_pmgs:
        assert pmg not in vc_body, (
            f"VC's building_opium_plantation now has {pmg} -- E&F's pmg may "
            "already be present, re-check before re-injecting")

    text = "INJECT:building_opium_plantation = {\n\tproduction_method_groups = {\n"
    for pmg in ef_pmgs:
        text += f"\t\t{pmg}\n"
    text += "\t}\n}\n"
    write("common/buildings/zz_vc_ef_buildings.txt",
          text,
          "re-apply E&F's production_method_groups on building_opium_plantation",
          "the only real building conflict out of 42 shared keys. VC does a "
          "bare REPLACE: (not TRY_INJECT) here, unlike its other 41 buildings, "
          "and its production_method_groups list doesn't carry E&F's "
          "pmg_market_liquidity / pmg_private_ownership_agricultural_stock -- "
          "this building alone loses market-liquidity and private-ownership "
          "mechanics that every other E&F-touched plantation keeps.")


def build_company_types():
    ef_f = find_file(EF, "common/company_types", "company_standard_oil")
    assert ef_f, "E&F company_standard_oil not found"
    ef_body = record(ef_f, "company_standard_oil")
    ef_goods = [ln.strip() for ln in ef_body
                if re.match(r"^\s*[a-z]", ln) and "possible_prestige_goods" not in ln
                and "{" not in ln and "}" not in ln]
    assert ef_goods, "E&F's company_standard_oil INJECT has no good lines"

    vc_f = find_file(VC, "common/company_types", "company_standard_oil")
    assert vc_f, "VC company_standard_oil not found"
    vc_body = "\n".join(record(vc_f, "company_standard_oil"))
    for good in ef_goods:
        assert good not in vc_body, (
            f"VC's company_standard_oil now has {good} -- re-check before "
            "re-injecting")

    text = "INJECT:company_standard_oil = {\n\tpossible_prestige_goods = {\n"
    for good in ef_goods:
        text += f"\t\t{good}\n"
    text += "\t}\n}\n"
    write("common/company_types/zz_vc_ef_company_types.txt",
          text,
          "re-apply E&F's prestige goods on company_standard_oil",
          "VC's REPLACE_OR_CREATE:company_standard_oil is its own American "
          "Standard Oil rework and only lists VC's own prestige good "
          "(prestige_good_us_stranderd_oil); E&F's INJECT adding "
          "mining_stock_usa and prestige_good_usa_oil to the same "
          "possible_prestige_goods list is lost. Whether these end up with a "
          "live slot at all is the separate potolok-3 question tracked as "
          "VC.7 in the plan -- this file only restores the definition.")


def build_static_modifiers():
    ef_f = find_file(EF, "common/static_modifiers", "base_values")
    assert ef_f, "E&F base_values not found"
    ef_body = record(ef_f, "base_values")
    inner = [ln for ln in ef_body[1:-1]]  # strip the "INJECT:base_values = {" / "}" lines
    assert inner, "E&F's base_values INJECT is empty"

    vc_f = find_file(VC, "common/static_modifiers", "base_values")
    assert vc_f, "VC base_values not found"
    vc_body = "\n".join(record(vc_f, "base_values"))
    assert "icon" not in vc_body, "VC's base_values now has its own icon line"

    text = "INJECT:base_values = {\n" + "\n".join(inner) + "\n}\n"
    write("common/static_modifiers/zz_vc_ef_static_modifiers.txt",
          text,
          "re-apply E&F's base_values additions",
          "VC's REPLACE_OR_CREATE:base_values wipes E&F's INJECT (an icon and "
          "country_minting_add = -500) silently. VC's own body already sets "
          "country_minting_add = 1000 for a different reason (a flat minting "
          "baseline); country_minting_add is an _add field and Vic3 stacks "
          "repeated _add fields within one modifier rather than letting the "
          "later one win (confirmed in `Правила работы...` section 6, the "
          "multiply-twice warning) -- so re-applying E&F's line here restores "
          "what both authors would get running together without VC's REPLACE_"
          "OR_CREATE wiping the block: 1000 + (-500) = net +500, same as no "
          "compatch would have produced if VC's directive were merge-friendly. "
          "Recorded as a decision, not silently dropped -- if this reads wrong "
          "in game, the fix is to drop E&F's line instead, not to guess again.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category = os.path.dirname(rel)
        depth = 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_vc_ef.py -> {OUT}")
    for name, fn in (
        ("buy_packages", build_buy_packages),
        ("buildings", build_buildings),
        ("company_types", build_company_types),
        ("static_modifiers", build_static_modifiers),
    ):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current E&F / VC sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
