#!/usr/bin/env python3
"""
EF.48, В4.1 (decided 2.10): devaluation / revaluation as a central bank tool with a target scale.

E&F's law_devaluation / law_revaluation (lawgroup_monetary_policy, laws/01_ef_monetary_policy.txt)
only hang a modifier (devaluation_currency_25..75: E&F's currency-good demand x1.25..1.75, its
monetary_policy_inflation +-0.25 a month) -- the printing goes into the currency good's stock, which
is not money any more. The AI never revalues; it devalues on a petition when
money_supply_state_ratio < 0.1 (meaningless in our money).

Now the measure is the metal cover (zz_ef_cb_cover: reserves at parity / money supply):
  * the law, when it comes into force, remembers the cover (start) and sets the target to it; the
    player moves the target in the CB panel (-5 -1 +1 +5 pp), the pace (1..5 pp a month, 2 by
    default); nothing happens while the target is untouched (var:zz_ef_mp_armed);
  * devaluation: the CB prints money INTO THE TREASURY (add_treasury; the 2.10 principle: new money
    goes through the state), M2 x pace / cover a month -- the cover falls by ~pace once it is spent.
    The treasury is outside M2: what the treasury has not spent yet (min(issued, treasury)) counts
    against what is still needed (M2 x (cover / target - 1)), so an idle treasury does not make the
    CB print without end;
  * revaluation: the CB takes money OUT OF THE TREASURY, M2 x pace / (cover + pace) a month, at most
    the treasury (no treasury -- the pace falls) and at most what is needed (M2 x (1 - cover /
    target)) minus what it has taken;
  * the target reached (or, revaluation, everything needed taken) -> the parity is rewritten to
    today's value (money_value_target_1 = money_value_0 -- a historical devaluation: new metal
    content; the user 2.10), the law goes back to law_no_monetary_policy, E&F's modifiers go;
    a cover already past the target when armed means the parity is rewritten at once (the AI's
    case below);
  * AI (M.4, the user 4.10; monthly, no law, metal standard with a CB, not in isolationism; no
    central_banking requirement since В4.4, 5.10 -- at the start only tech tier 1 has it, Qing lost its
    reserves 0.52 -> 0.12 in 2.3 years with no reaction): the parity is fixed; the cover under 25% (over 80%) for 24 months running ->
    the parity x cover / 40%, within 1 -+ 25% (devaluation / revaluation as a new metal content,
    no printing), then a 5 years' pause. E&F's petition and ai weights go (laws re-issued with
    ai_will_do = no).
  * the law (the player) completed: the parity x cover now / cover at the start (M.2 holds the value
    at the parity while the cover is 25%+, so the value itself no longer shows the devaluation).
  * E&F's 25/50/75% buttons (scripted guis devaluation_currency_* / revaluation_currency_*) are
    hidden; the scale is in the CB panel (tools/regen_ef_cb_rate_gui.py, mp_row).

Writes (_ef/ef hotfix 1.13/): common/scripted_effects/zz_ef_monetary_policy.txt,
common/script_values/zz_ef_monetary_policy_values.txt, common/scripted_triggers/zz_ef_monetary_policy_triggers.txt,
common/scripted_guis/zz_ef_monetary_policy_buttons.txt, common/laws/zz_ef_monetary_policy_laws.txt,
localization/<lang>/zz_ef_monetary_policy_l_<lang>.yml

Usage:
    py tools/regen_ef_monetary_policy.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))
EF_LAWS = res(r"..\..\vic3_mods_out\E&F\common\laws\01_ef_monetary_policy.txt")
EF_EFFECTS = res(r"..\..\vic3_mods_out\E&F\common\scripted_effects\01_economic_scripted_effects.txt")
HOTFIX = res(r"..\_ef\ef hotfix 1.13")
LANGS = ["english", "russian", "braz_por", "french", "german", "japanese",
         "korean", "polish", "simp_chinese", "spanish", "turkish"]

HEAD = ("# GENERATED by tools/regen_ef_monetary_policy.py -- do not edit by hand.\n"
        "# EF.48, В4.1 (2.10): devaluation / revaluation as a CB tool with a target scale -- see the\n"
        "# generator's docstring.\n")

EF_MODS = ["devaluation_currency_25", "devaluation_currency_50", "devaluation_currency_75",
           "devaluation_currency_100", "revaluation_currency_25", "revaluation_currency_50",
           "revaluation_currency_75"]


def block(text, name):
    m = re.search(rf"^{re.escape(name)} = \{{", text, re.M)
    assert m, name
    i = text.index("{", m.start())
    d = 0
    for j in range(i, len(text)):
        d += {"{": 1, "}": -1}.get(text[j], 0)
        if d == 0:
            return text[i:j + 1]
    raise AssertionError(name)


def drop_block(body, key):
    m = re.search(rf"\n\s*{key} = \{{", body)
    if not m:
        return body
    i = body.index("{", m.start())
    d = 0
    for j in range(i, len(body)):
        d += {"{": 1, "}": -1}.get(body[j], 0)
        if d == 0:
            return body[:m.start()] + body[j + 1:]
    raise AssertionError(key)


def laws():
    text = open(EF_LAWS, encoding="utf-8-sig").read()
    out = [HEAD, "# !! MAINTENANCE !! Full-body REPLACE of E&F's two laws: regenerate after an E&F update.\n"
                 "# Changed: ai_enact_weight_modifier (E&F's petition) dropped, ai_will_do = no -- the AI takes\n"
                 "# these laws only through zz_ef_mp_step (scripted_effects/zz_ef_monetary_policy.txt).\n\n"]
    for name in ("law_revaluation", "law_devaluation"):
        body = drop_block(drop_block(block(text, name), "ai_enact_weight_modifier"), "ai_will_do")
        body = body[:body.rstrip().rfind("}")].rstrip() + "\n\n\tai_will_do = {\n\t\talways = no\n\t}\n}"
        out.append(f"REPLACE:{name} = {body}\n\n")
    return "".join(out)


def effects():
    ef = open(EF_EFFECTS, encoding="utf-8-sig").read()
    # E&F's bodies, checked: the re-issue below keeps them and adds our init / clear
    for name, must in (("on_activate_law_no_monetary_policy", "remove_modifier = devaluation_currency_25"),
                       ("on_activate_law_revaluation", "name = revaluation_currency_25"),
                       ("on_activate_law_devaluation", "name = devaluation_currency_25")):
        assert must in block(ef, name), name
    clear_mods = "".join(f"\tremove_modifier = {m}\n" for m in EF_MODS)
    return HEAD + "# !! MAINTENANCE !! Key-level REPLACE_OR_CREATE of E&F's three on_activate effects.\n\n" + f"""\
REPLACE_OR_CREATE:on_activate_law_no_monetary_policy = {{
	zz_ef_mp_clear = yes
}}
REPLACE_OR_CREATE:on_activate_law_revaluation = {{
	remove_modifier = devaluation_currency_25
	remove_modifier = revaluation_currency_25
	add_modifier = {{
		name = revaluation_currency_25
	}}
	zz_ef_mp_init = yes
}}
REPLACE_OR_CREATE:on_activate_law_devaluation = {{
	remove_modifier = revaluation_currency_25
	remove_modifier = devaluation_currency_25
	add_modifier = {{
		name = devaluation_currency_25
	}}
	zz_ef_mp_init = yes
}}

# The law came into force: start = target = today's cover. The AI arms it at once with its
# target (zz_ef_mp_ai_target); the player arms it by moving the target (scripted guis).
zz_ef_mp_init = {{
	set_variable = {{ name = zz_ef_mp_cum value = 0 }}
	set_variable = {{ name = zz_ef_mp_dyn value = 0 }}
	set_variable = {{ name = zz_ef_mp_flow value = 0 }}
	if = {{
		limit = {{ NOT = {{ has_variable = zz_ef_mp_pace }} }}
		set_variable = {{ name = zz_ef_mp_pace value = zz_ef_mp_pace_default }}
	}}
	set_variable = {{ name = zz_ef_mp_start value = zz_ef_cb_cover }}
	set_variable = {{ name = zz_ef_mp_target value = zz_ef_cb_cover }}
	set_variable = {{ name = zz_ef_mp_prev value = zz_ef_cb_cover }}
	if = {{
		limit = {{ has_variable = zz_ef_mp_armed }}
		remove_variable = zz_ef_mp_armed
	}}
	if = {{
		limit = {{ is_ai = yes }}
		set_variable = {{ name = zz_ef_mp_target value = zz_ef_mp_ai_target }}
		set_variable = {{ name = zz_ef_mp_armed value = yes }}
	}}
}}

# Back to no policy: our state and every E&F modifier of the 25/50/75 buttons go (the pace stays,
# it is the player's setting).
zz_ef_mp_clear = {{
{clear_mods}\tif = {{ limit = {{ has_variable = zz_ef_mp_start }} remove_variable = zz_ef_mp_start }}
	if = {{ limit = {{ has_variable = zz_ef_mp_target }} remove_variable = zz_ef_mp_target }}
	if = {{ limit = {{ has_variable = zz_ef_mp_prev }} remove_variable = zz_ef_mp_prev }}
	if = {{ limit = {{ has_variable = zz_ef_mp_dyn }} remove_variable = zz_ef_mp_dyn }}
	if = {{ limit = {{ has_variable = zz_ef_mp_flow }} remove_variable = zz_ef_mp_flow }}
	if = {{ limit = {{ has_variable = zz_ef_mp_cum }} remove_variable = zz_ef_mp_cum }}
	if = {{ limit = {{ has_variable = zz_ef_mp_armed }} remove_variable = zz_ef_mp_armed }}
}}

# The target reached: the parity moves with the cover (new metal content), the law ends. Since
# M.2 (4.10) the value stays at the parity while the cover is 25%+, so "the parity becomes today's
# value" would change nothing: the parity x cover now / cover at the start -- the metal per unit
# falls (rises) as much as the money printed (taken) moved the cover, the cover at the new parity
# is the start's again.
zz_ef_mp_complete = {{
	set_variable = {{ name = zz_ef_mp_parity_before value = var:money_value_target_1 }}
	if = {{
		limit = {{
			has_variable = zz_ef_mp_start
			var:zz_ef_mp_start > 0
			zz_ef_cb_cover > 0
		}}
		change_variable = {{ name = money_value_target_1 multiply = zz_ef_cb_cover }}
		change_variable = {{ name = money_value_target_1 divide = var:zz_ef_mp_start }}
	}}
	debug_log = "EFM|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|done|cover [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_cb_cover')|3]|target [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_mp_target_v')|3]|cum [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_mp_cum_v')|0]|parity_before [THIS.GetCountry.MakeScope.Var('zz_ef_mp_parity_before').GetValue|4]|parity [THIS.GetCountry.MakeScope.Var('money_value_target_1').GetValue|4]"
	set_variable = {{ name = zz_ef_mp_cooldown value = yes days = 730 }}
	# EF.43 + В4.3 (5.10): a parity change raises the risk premium (scripted_effects/zz_ef_risk_premium.txt)
	zz_ef_risk_parity_changed = yes
	activate_law = law_type:law_no_monetary_policy
	zz_ef_mp_clear = yes
}}

# Monthly, from zz_ef_money_model_monthly_step.
zz_ef_mp_step = {{
	if = {{
		limit = {{
			OR = {{
				has_law = law_type:law_devaluation
				has_law = law_type:law_revaluation
			}}
		}}
		if = {{
			limit = {{ NOT = {{ has_variable = zz_ef_mp_target }} }}
			zz_ef_mp_init = yes
		}}
		set_variable = {{ name = zz_ef_mp_flow value = 0 }}
		if = {{
			limit = {{ zz_ef_mp_can_work = yes }}
			set_variable = {{ name = zz_ef_mp_dyn value = zz_ef_cb_cover }}
			change_variable = {{ name = zz_ef_mp_dyn subtract = var:zz_ef_mp_prev }}
			set_variable = {{ name = zz_ef_mp_prev value = zz_ef_cb_cover }}
			if = {{
				limit = {{ has_variable = zz_ef_mp_armed }}
				if = {{
					limit = {{ has_law = law_type:law_devaluation }}
					if = {{
						limit = {{ zz_ef_cb_cover <= var:zz_ef_mp_target }}
						zz_ef_mp_complete = yes
					}}
					else = {{
						set_variable = {{ name = zz_ef_mp_flow value = zz_ef_mp_issue }}
						add_treasury = var:zz_ef_mp_flow
						change_variable = {{ name = zz_ef_mp_cum add = var:zz_ef_mp_flow }}
					}}
				}}
				else = {{
					if = {{
						limit = {{
							OR = {{
								zz_ef_cb_cover >= var:zz_ef_mp_target
								zz_ef_mp_withdraw_left <= 0
							}}
						}}
						zz_ef_mp_complete = yes
					}}
					else = {{
						set_variable = {{ name = zz_ef_mp_flow value = zz_ef_mp_withdraw }}
						change_variable = {{ name = zz_ef_mp_cum add = var:zz_ef_mp_flow }}
						add_treasury = {{
							value = var:zz_ef_mp_flow
							multiply = -1
						}}
						change_variable = {{ name = zz_ef_mp_flow multiply = -1 }}
					}}
				}}
			}}
		}}
		if = {{
			limit = {{ has_variable = zz_ef_mp_target }}
			debug_log = "EFM|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|step|dev [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_mp_dir')|0]|armed [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_mp_armed_v')|0]|cover [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_cb_cover')|3]|start [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_mp_start_v')|3]|target [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_mp_target_v')|3]|flow [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_mp_flow_v')|0]|cum [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_mp_cum_v')|0]|m2 [THIS.GetCountry.MakeScope.ScriptValue('money_supply')|0]|trea [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_treasury')|0]|ratio [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_mp_value_ratio')|3]"
		}}
	}}
	# the AI's rule (M.4, the user 4.10): the parity is fixed; it moves only when the cover has been
	# under 25% (devaluation) or over 80% (revaluation) for two years running -- one step, at most
	# 25%, to the parity that puts the cover back at 40%, then 5 years' pause. No printing: the
	# metal content changes (zz_ef_mp_ai_parity_step). The months are counted every month, also
	# during the pause.
	else_if = {{
		limit = {{
			is_ai = yes
			has_law = law_type:law_no_monetary_policy
			zz_ef_mp_can_work = yes
			# not before the CB's metal is in our scale (run 25: on day 1 E&F's metal gave a cover of
			# 104 and nearly every AI took a revaluation before the rescale of week 12)
			has_variable = zz_ef_weeks_run
			var:zz_ef_weeks_run >= 13
			NOT = {{ has_variable = zz_ef_metal_rescale_due }}
		}}
		if = {{
			limit = {{ NOT = {{ has_variable = zz_ef_mp_low_months }} }}
			set_variable = {{ name = zz_ef_mp_low_months value = 0 }}
			set_variable = {{ name = zz_ef_mp_high_months value = 0 }}
		}}
		if = {{
			limit = {{ zz_ef_cb_cover < zz_ef_mp_ai_dev_cover }}
			change_variable = {{ name = zz_ef_mp_low_months add = 1 }}
		}}
		else = {{
			set_variable = {{ name = zz_ef_mp_low_months value = 0 }}
		}}
		if = {{
			limit = {{ zz_ef_cb_cover > zz_ef_mp_ai_rev_cover }}
			change_variable = {{ name = zz_ef_mp_high_months add = 1 }}
		}}
		else = {{
			set_variable = {{ name = zz_ef_mp_high_months value = 0 }}
		}}
		if = {{
			limit = {{
				NOT = {{ has_variable = zz_ef_mp_cooldown }}
				NOT = {{ has_law = law_type:law_isolationism }}
				OR = {{
					var:zz_ef_mp_low_months >= zz_ef_mp_ai_months
					var:zz_ef_mp_high_months >= zz_ef_mp_ai_months
				}}
			}}
			set_variable = {{ name = zz_ef_mp_parity_before value = var:money_value_target_1 }}
			change_variable = {{ name = money_value_target_1 multiply = zz_ef_mp_ai_parity_step }}
			debug_log = "EFM|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|ai_parity|cover [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_cb_cover')|3]|low [THIS.GetCountry.MakeScope.Var('zz_ef_mp_low_months').GetValue|0]|high [THIS.GetCountry.MakeScope.Var('zz_ef_mp_high_months').GetValue|0]|parity_before [THIS.GetCountry.MakeScope.Var('zz_ef_mp_parity_before').GetValue|4]|parity [THIS.GetCountry.MakeScope.Var('money_value_target_1').GetValue|4]"
			set_variable = {{ name = zz_ef_mp_low_months value = 0 }}
			set_variable = {{ name = zz_ef_mp_high_months value = 0 }}
			set_variable = {{ name = zz_ef_mp_cooldown value = yes days = 1825 }}
			zz_ef_risk_parity_changed = yes
		}}
	}}
}}
"""


VALUES = HEAD + """
# Pace of the policy, pp of cover a month (the player: 1..5).
zz_ef_mp_pace_default = 2
zz_ef_mp_pace_min = 1
zz_ef_mp_pace_max = 5
# The target the player can set, a share of the money supply.
zz_ef_mp_target_min = 0.05
zz_ef_mp_target_max = 3
# The AI's rule (M.4, 4.10): two years under 25% / over 80% cover -> one parity step towards 40%,
# at most 25%, then 5 years' pause (1825 days, in the effect). zz_ef_mp_ai_target stays for a law the AI might still get.
zz_ef_mp_ai_target = 0.4
zz_ef_mp_ai_dev_cover = 0.25
zz_ef_mp_ai_rev_cover = 0.8
zz_ef_mp_ai_months = 24
zz_ef_mp_ai_step_max = 0.25
# The parity's multiplier: cover / 40% (the cover at the new parity is 40%), within 1 -+ 25%.
zz_ef_mp_ai_parity_step = {
	value = zz_ef_cb_cover
	divide = zz_ef_mp_ai_target
	max = {
		value = 1
		add = zz_ef_mp_ai_step_max
	}
	min = {
		value = 1
		subtract = zz_ef_mp_ai_step_max
	}
}

zz_ef_mp_pace_frac = {
	value = zz_ef_mp_pace_default
	if = { limit = { has_variable = zz_ef_mp_pace } value = var:zz_ef_mp_pace }
	divide = 100
}
# The value of the currency against its parity (1 = at parity).
zz_ef_mp_value_ratio = {
	value = 0
	if = {
		limit = {
			has_variable = money_value_target_1
			var:money_value_target_1 > 0
		}
		value = money_value_0
		divide = var:money_value_target_1
	}
}
# Devaluation: money still to print to bring the cover down to the target once it is spent.
zz_ef_mp_need_issue = {
	value = 0
	if = {
		limit = {
			has_variable = zz_ef_mp_target
			var:zz_ef_mp_target > 0
		}
		value = zz_ef_cb_cover
		divide = var:zz_ef_mp_target
		subtract = 1
		multiply = money_supply
	}
	min = 0
}
# Printed money the treasury has not spent yet.
zz_ef_mp_pending = {
	value = zz_ef_mp_cum_v
	max = zz_ef_treasury
	min = 0
}
zz_ef_mp_issue = {
	value = money_supply
	multiply = zz_ef_mp_pace_frac
	divide = {
		value = zz_ef_cb_cover
		min = 0.01
	}
	max = {
		value = zz_ef_mp_need_issue
		subtract = zz_ef_mp_pending
		min = 0
	}
	min = 0
}
# Revaluation: money to take out to bring the cover up to the target; what is left of it.
zz_ef_mp_need_withdraw = {
	value = 0
	if = {
		limit = {
			has_variable = zz_ef_mp_target
			var:zz_ef_mp_target > 0
		}
		value = 1
		subtract = {
			value = zz_ef_cb_cover
			divide = var:zz_ef_mp_target
		}
		multiply = money_supply
	}
	min = 0
}
zz_ef_mp_withdraw_left = {
	value = zz_ef_mp_need_withdraw
	subtract = zz_ef_mp_cum_v
}
zz_ef_mp_withdraw = {
	value = money_supply
	multiply = zz_ef_mp_pace_frac
	divide = {
		value = zz_ef_cb_cover
		add = zz_ef_mp_pace_frac
		min = 0.01
	}
	max = zz_ef_treasury
	max = {
		value = zz_ef_mp_withdraw_left
		min = 0
	}
	min = 0
}

# For the panel and the log (0 if unset).
zz_ef_mp_start_v = {
	value = 0
	if = { limit = { has_variable = zz_ef_mp_start } value = var:zz_ef_mp_start }
}
zz_ef_mp_target_v = {
	value = 0
	if = { limit = { has_variable = zz_ef_mp_target } value = var:zz_ef_mp_target }
}
zz_ef_mp_cum_v = {
	value = 0
	if = { limit = { has_variable = zz_ef_mp_cum } value = var:zz_ef_mp_cum }
}
zz_ef_mp_flow_v = {
	value = 0
	if = { limit = { has_variable = zz_ef_mp_flow } value = var:zz_ef_mp_flow }
}
zz_ef_mp_dyn_pp = {
	value = 0
	if = { limit = { has_variable = zz_ef_mp_dyn } value = var:zz_ef_mp_dyn }
	multiply = 100
}
zz_ef_mp_pace_v = {
	value = zz_ef_mp_pace_frac
	multiply = 100
}
zz_ef_mp_armed_v = {
	value = 0
	if = { limit = { has_variable = zz_ef_mp_armed } value = 1 }
}
zz_ef_mp_dir = {
	value = 0
	if = { limit = { has_law = law_type:law_devaluation } value = 1 }
	if = { limit = { has_law = law_type:law_revaluation } value = -1 }
}
# Share of the way from the start to the target (0..1).
zz_ef_mp_progress = {
	value = 0
	if = {
		limit = {
			has_variable = zz_ef_mp_start
			has_variable = zz_ef_mp_target
			NOT = { var:zz_ef_mp_target = var:zz_ef_mp_start }
		}
		value = zz_ef_cb_cover
		subtract = var:zz_ef_mp_start
		divide = {
			value = var:zz_ef_mp_target
			subtract = var:zz_ef_mp_start
		}
	}
	min = 0
	max = 1
}
# Months left at the pace.
zz_ef_mp_months_left = {
	value = zz_ef_cb_cover
	subtract = zz_ef_mp_target_v
	abs = yes
	divide = zz_ef_mp_pace_frac
}
"""

TRIGGERS = HEAD + """
# The tool works on a metal standard with a central bank (the cover is metal at parity / money).
zz_ef_mp_can_work = {
	has_modifier = has_central_bank
	has_variable = money_value_target_1
	var:money_value_target_1 > 0
	OR = {
		has_law = law_type:law_gold_standard
		has_law = law_type:law_silver_standard
		has_law = law_type:law_bimetallism_standard
	}
}
zz_ef_mp_law_on = {
	OR = {
		has_law = law_type:law_devaluation
		has_law = law_type:law_revaluation
	}
}
"""


TARGET_MIN, TARGET_MAX = 0.05, 3.0


def target_button(name, delta):
    sign = "add" if delta > 0 else "subtract"
    # literal bounds: TARGET_MAX / TARGET_MIN as in zz_ef_mp_target_max / _min (values file)
    lim = (f"var:zz_ef_mp_target <= {TARGET_MAX - abs(delta) / 100:.2f}" if delta > 0 else
           f"var:zz_ef_mp_target >= {TARGET_MIN + abs(delta) / 100:.2f}")
    key = "zz_ef_mp_tt_target_max" if delta > 0 else "zz_ef_mp_tt_target_min"
    return f"""{name} = {{
	is_shown = {{ zz_ef_mp_law_on = yes }}
	is_valid = {{
		custom_tooltip = {{
			text = zz_ef_mp_tt_can_work
			zz_ef_mp_can_work = yes
		}}
		custom_tooltip = {{
			text = {key}
			has_variable = zz_ef_mp_target
			{lim}
		}}
	}}
	effect = {{
		custom_tooltip = {name}_effect
		hidden_effect = {{
			change_variable = {{ name = zz_ef_mp_target {sign} = {abs(delta) / 100} }}
			set_variable = {{ name = zz_ef_mp_armed value = yes }}
		}}
	}}
}}
"""


def pace_button(name, delta):
    lim = ("zz_ef_mp_pace_v < zz_ef_mp_pace_max" if delta > 0 else "zz_ef_mp_pace_v > zz_ef_mp_pace_min")
    return f"""{name} = {{
	is_shown = {{ zz_ef_mp_law_on = yes }}
	is_valid = {{
		custom_tooltip = {{
			text = zz_ef_mp_tt_pace_range
			{lim}
		}}
	}}
	effect = {{
		custom_tooltip = {name}_effect
		hidden_effect = {{
			set_variable = {{ name = zz_ef_mp_pace value = zz_ef_mp_pace_v }}
			change_variable = {{ name = zz_ef_mp_pace add = {delta} }}
		}}
	}}
}}
"""


def guis():
    out = [HEAD, "\n# The panel row (gui/00_00_ef_cb_rate_panel.gui, mp_row).\n",
           "zz_ef_mp_visible = {\n\tis_shown = { zz_ef_mp_law_on = yes }\n}\n"]
    for n, d in (("zz_ef_mp_target_m5", -5), ("zz_ef_mp_target_m1", -1),
                 ("zz_ef_mp_target_p1", 1), ("zz_ef_mp_target_p5", 5)):
        out.append(target_button(n, d))
    out.append(pace_button("zz_ef_mp_pace_minus", -1))
    out.append(pace_button("zz_ef_mp_pace_plus", 1))
    out.append("\n# E&F's 25/50/75% buttons (gui/00_ef_deported_gui_1.gui, budget_panel_economy_panel_content)\n"
               "# hidden: the scale replaces them. !! MAINTENANCE !! key-level REPLACE_OR_CREATE of E&F's guis.\n")
    for m in EF_MODS:
        if m.endswith("_100"):
            continue
        out.append(f"REPLACE_OR_CREATE:{m} = {{\n\tis_shown = {{ always = no }}\n\tis_valid = {{ always = no }}\n"
                   "\teffect = { }\n}\n")
    return "".join(out)


SV = "GetPlayer.MakeScope.ScriptValue"
COV = f"[{SV}('zz_ef_cb_cover')|%0]"
TGT = f"[{SV}('zz_ef_mp_target_v')|%0]"
STA = f"[{SV}('zz_ef_mp_start_v')|%0]"
DYN = f"[{SV}('zz_ef_mp_dyn_pp')|+1]"
MON = f"[{SV}('zz_ef_mp_months_left')|0]"
PACE = f"[{SV}('zz_ef_mp_pace_v')|0]"
CUR = "[GetPlayer.GetCustom('currency_symbol')]"
FLOW = f"[{SV}('zz_ef_mp_flow_v')|D+=]{CUR}"
CUM = f"[{SV}('zz_ef_mp_cum_v')|D]{CUR}"
DEVAL = "[GetLawType('law_devaluation').GetName]"
REVAL = "[GetLawType('law_revaluation').GetName]"
CB = "[concept_central_bank]"

RU = {
    "zz_ef_mp_title": f"Покрытие {COV} → цель {TGT} (при принятии закона {STA})",
    "zz_ef_mp_line2": f"За месяц: {DYN} п.п. покрытия, поток через казну {FLOW} (всего {CUM}). Осталось ≈ {MON} мес.",
    "zz_ef_mp_target_label": "Цель покрытия:",
    "zz_ef_mp_pace_label": "Темп, п.п. в месяц:",
    "zz_ef_mp_pace_value": PACE,
    "zz_ef_mp_btn_m5": "−5", "zz_ef_mp_btn_m1": "−1", "zz_ef_mp_btn_p1": "+1", "zz_ef_mp_btn_p5": "+5",
    "zz_ef_mp_tt": (
        f"{DEVAL} и {REVAL} — инструмент {CB}. Мера — покрытие: металл и валюта в резервах по паритету к деньгам в "
        "обращении. При принятии закона цель = текущее покрытие; двигайте цель кнопками.\\n\\n"
        f"{DEVAL}: {CB} печатает деньги в казну — государство их тратит, денег становится больше, покрытие падает к "
        "цели. Пока казна не потратила напечатанное, новые деньги не печатаются сверх нужного.\\n"
        f"{REVAL}: {CB} изымает деньги из казны (нет казны — темп падает).\\n\\n"
        "Цель достигнута — паритет переписывается на текущий курс (новое металлическое содержание), закон снимается. "
        "Если покрытие уже по другую сторону цели — паритет переписывается сразу."
    ),
    "zz_ef_mp_tt_can_work": f"Металлический стандарт и {CB}",
    "zz_ef_mp_tt_target_max": "Цель не выше 300%",
    "zz_ef_mp_tt_target_min": "Цель не ниже 5%",
    "zz_ef_mp_tt_pace_range": "Темп от 1 до 5 п.п. в месяц",
    "zz_ef_mp_target_m5_effect": "Цель покрытия −5 п.п.",
    "zz_ef_mp_target_m1_effect": "Цель покрытия −1 п.п.",
    "zz_ef_mp_target_p1_effect": "Цель покрытия +1 п.п.",
    "zz_ef_mp_target_p5_effect": "Цель покрытия +5 п.п.",
    "zz_ef_mp_pace_minus_effect": "Темп −1 п.п. в месяц",
    "zz_ef_mp_pace_plus_effect": "Темп +1 п.п. в месяц",
}
EN = {
    "zz_ef_mp_title": f"Cover {COV} → target {TGT} (when the law passed {STA})",
    "zz_ef_mp_line2": f"This month: {DYN} pp of cover, flow through the treasury {FLOW} (total {CUM}). About {MON} months left.",
    "zz_ef_mp_target_label": "Cover target:",
    "zz_ef_mp_pace_label": "Pace, pp a month:",
    "zz_ef_mp_pace_value": PACE,
    "zz_ef_mp_btn_m5": "−5", "zz_ef_mp_btn_m1": "−1", "zz_ef_mp_btn_p1": "+1", "zz_ef_mp_btn_p5": "+5",
    "zz_ef_mp_tt": (
        f"{DEVAL} and {REVAL} are a tool of the {CB}. The measure is the cover: metal and foreign currency in the "
        "reserves at parity against the money in circulation. When the law passes the target is today's cover; move "
        "it with the buttons.\\n\\n"
        f"{DEVAL}: the {CB} prints money into the treasury — the state spends it, there is more money, the cover falls "
        "to the target. While the treasury has not spent what was printed, no more than needed is printed.\\n"
        f"{REVAL}: the {CB} takes money out of the treasury (no treasury — the pace falls).\\n\\n"
        "Target reached — the parity is rewritten to today's value (a new metal content) and the law is lifted. If "
        "the cover is already past the target, the parity is rewritten at once."
    ),
    "zz_ef_mp_tt_can_work": f"A metal standard and a {CB}",
    "zz_ef_mp_tt_target_max": "Target at most 300%",
    "zz_ef_mp_tt_target_min": "Target at least 5%",
    "zz_ef_mp_tt_pace_range": "Pace from 1 to 5 pp a month",
    "zz_ef_mp_target_m5_effect": "Cover target −5 pp",
    "zz_ef_mp_target_m1_effect": "Cover target −1 pp",
    "zz_ef_mp_target_p1_effect": "Cover target +1 pp",
    "zz_ef_mp_target_p5_effect": "Cover target +5 pp",
    "zz_ef_mp_pace_minus_effect": "Pace −1 pp a month",
    "zz_ef_mp_pace_plus_effect": "Pace +1 pp a month",
}
assert set(RU) == set(EN)


def write(path, text, bom=True):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8-sig" if bom else "utf-8", newline="\n") as f:
        f.write(text)
    print("ok", path)


def main():
    c = os.path.join(HOTFIX, "common")
    write(os.path.join(c, "laws", "zz_ef_monetary_policy_laws.txt"), laws())
    write(os.path.join(c, "scripted_effects", "zz_ef_monetary_policy.txt"), effects())
    write(os.path.join(c, "script_values", "zz_ef_monetary_policy_values.txt"), VALUES)
    write(os.path.join(c, "scripted_triggers", "zz_ef_monetary_policy_triggers.txt"), TRIGGERS)
    write(os.path.join(c, "scripted_guis", "zz_ef_monetary_policy_buttons.txt"), guis())
    for lang in LANGS:
        d = RU if lang == "russian" else EN
        lines = [f"l_{lang}:\n", " # GENERATED by tools/regen_ef_monetary_policy.py -- do not edit by hand.\n"]
        if lang not in ("russian", "english"):
            lines.append(" # Not translated yet: English text.\n")
        for k, v in d.items():
            lines.append(f' {k}:0 "{v}"\n')
        write(os.path.join(HOTFIX, "localization", lang, f"zz_ef_monetary_policy_l_{lang}.yml"), "".join(lines))


if __name__ == "__main__":
    main()
