#!/usr/bin/env python3
"""
regen_ef_pm_stock_hook.py -- R1а.2 (Д.1, Р30): E&F's method-change hook checks one building, not the whole country.

Why
---
E&F's `ef_on_production_method_changed` ran `private_ownership_production_stocks` on the building's owner on EVERY
method change of any building: every state x 48 building types x 2 checks (98 `private_ownership_fraction` tests a
state). The sweep itself switches methods (`activate_production_method`), and each switch fires the hook again, so a
country with many mismatched buildings nests one full sweep in another -- 16.7 s in the R0.7 profile and the likely
cause of the STACK_OVERFLOW in r1007_164303 (yearly sweep, 1839.12).

The hook's scope is the building that changed its method. That building alone is checked: its "stock" method
(4 groups: manufacture / agricultural / mining / railroad) must follow its private ownership share (> 0.5 --
majority stock, <= 0.5 -- no stock), exactly as E&F's sweep decides. A switch fires the hook again for the same
building, which is then consistent -- no nesting. The financial centre's methods depend on the country's stock goods,
so `financial_center_production_methods` is called only after a stock switch (accepted at night 7.10, check), not on
every method change. The yearly sweep in `financial_center_ef_on_yearly_pulse_country` stays (Д.1).

What it writes (through ld_gen.emit, by entry keys, into the fork)
--------------
common/scripted_effects/ld_pm_stock_hook.txt -- `zz_ef_pm_stock_building` (building scope).
Reads the rules (building type, share test, method from, method to) from E&F's `private_ownership_production_stocks`
in common/scripted_effects/01_financial_scripted_effects.txt of the fork.

Usage:  python3 tools/regen_ef_pm_stock_hook.py [--check]
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ld_gen  # noqa: E402

SRC = "common/scripted_effects/01_financial_scripted_effects.txt"
OUT = "common/scripted_effects/ld_pm_stock_hook.txt"
RULE = re.compile(
    r"has_building = (\w+)\s+b:\w+\s*=\s*\{\s*private_ownership_fraction ([<>]=?) 0\.5\s*\}\s*"
    r"is_production_method_active = \{\s*building_type = \w+\s+production_method = (\w+)\s*\}\s*\}\s*"
    r"activate_production_method = \{\s*building_type = \w+\s+production_method = (\w+)")


def body(text, key):
    i = text.index(key + " = {")
    d = 0
    for j in range(i, len(text)):
        if text[j] == "{":
            d += 1
        elif text[j] == "}":
            d -= 1
            if d == 0:
                return text[i:j + 1]
    raise SystemExit(f"{key}: no closing brace")


def rules():
    text = Path(ld_gen.FORK, SRC).read_text(encoding="utf-8-sig")
    rs = RULE.findall(body(text, "private_ownership_production_stocks"))
    if len(rs) != 98:
        raise SystemExit(f"expected 98 rules in private_ownership_production_stocks, got {len(rs)}")
    # (share test, from, to) -> [building types], in E&F's order
    groups: dict[tuple[str, str, str], list[str]] = {}
    for bt, op, pm_from, pm_to in rs:
        groups.setdefault((op, pm_from, pm_to), []).append(bt)
    return groups


def gen():
    out = [
        "# Generated by ../vic3_mods/tools/regen_ef_pm_stock_hook.py -- do not edit by hand (docs/generators.md).",
        "# R1а.2 (Д.1): E&F's method-change hook, one building. Rules -- E&F's private_ownership_production_stocks.",
        "",
        "# Scope: building (root of on_production_method_changed). Its stock method follows its private ownership",
        "# share; after a switch -- the owner's financial centre methods (they depend on the stock goods).",
        "zz_ef_pm_stock_building = {",
    ]
    first = True
    for (op, pm_from, pm_to), bts in rules().items():
        out.append(f"\t{'if' if first else 'else_if'} = {{")
        first = False
        out.append(f"\t\tlimit = {{")
        out.append(f"\t\t\thas_active_production_method = {pm_from}")
        out.append(f"\t\t\tprivate_ownership_fraction {op} 0.5")
        out.append(f"\t\t\tor = {{")
        out.extend(f"\t\t\t\tis_building_type = {bt}" for bt in bts)
        out.append(f"\t\t\t}}")
        out.append(f"\t\t}}")
        for i, bt in enumerate(bts):
            out.append(f"\t\t{'if' if i == 0 else 'else_if'} = {{")
            out.append(f"\t\t\tlimit = {{ is_building_type = {bt} }}")
            out.append(f"\t\t\tstate = {{ activate_production_method = {{ building_type = {bt} "
                       f"production_method = {pm_to} }} }}")
            out.append(f"\t\t}}")
        out.append(f"\t\towner = {{")
        out.append(f"\t\t\tif = {{")
        out.append(f"\t\t\t\tlimit = {{ has_modifier = has_financial_center }}")
        out.append(f"\t\t\t\tfinancial_center_production_methods = yes")
        out.append(f"\t\t\t}}")
        out.append(f"\t\t}}")
        out.append(f"\t}}")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    text = gen()
    dst = os.path.join(ld_gen.FORK, OUT)
    if not os.path.exists(dst) and not ld_gen.CHECK:
        # first run: the file does not exist yet -- write it whole (ld_gen.emit only replaces existing entries)
        Path(dst).write_text(text, encoding="utf-8-sig", newline="\n")
    ld_gen.emit(OUT, text)
    ld_gen.report("regen_ef_pm_stock_hook")


if __name__ == "__main__":
    main()
