#!/usr/bin/env python3
"""
Д2.4 (5.10.2026) -- the private banks' seed: scripted_effects/zz_ef_bank_seed.txt of the E&F hotfix.

Banks (building_zz_ef_bank) make the bank settlements (the former E&F currency good) that used to come from the
central bank from day one, so every country gets banks in its capital in its first monthly pulse, sized to its
GDP (script_values/zz_ef_bank_values.txt: zz_ef_bank_seed_levels = GDP / 520000).

Why a ladder of fixed sizes (run r1005_192418, 5.10):
  * add_ownership exists only inside create_building and its `levels` cannot read a variable;
  * calling create_building again on a building that is already there adds NO levels -- the first version looped
    one level per call and Britain's 90 seeded levels came out as a 0-level bank;
  * an owner building (financial district) needs a literal `region = "STATE_..."` -- the capital differs per
    country, so the owner is the state; the bank has ai_nationalization_desire = -5 (buildings/zz_ef_bank.txt),
    so the AI sells its levels to private owners over time (decided in the day session, check).
So one create_building per country, the largest ladder size not above the wanted levels (error < ~15%).

Usage:
    py tools/regen_ef_bank_seed.py            # write
    py tools/regen_ef_bank_seed.py --check    # exit 1 if the file differs
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "_ef", "ef hotfix 1.13", "common", "scripted_effects", "zz_ef_bank_seed.txt"))

SIZES = [1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 18, 20, 23, 26, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100, 115, 130,
         150, 175, 200, 250, 300, 350, 400]

HEADER = """\
# GENERATED by tools/regen_ef_bank_seed.py -- do not edit by hand.
#############################################
# Д2.4 (5.10.2026) -- the private banks are seeded once, in a country's first monthly pulse
# (on_actions/zz_ef_bank_on_actions.txt): bank settlements (the former currency good) used to come from the
# central bank from day one, and a market without them buys none for its businesses and population.
#
# COUNTRY scope. One create_building in the capital, the largest ladder size not above zz_ef_bank_seed_levels
# (GDP / 520000); owner -- the state, sold to private owners by the AI (ai_nationalization_desire -5). Why a
# ladder and not a loop, why not the financial district: the generator's docstring. reserves = 0: no cash from
# nowhere (В1.3). Logged once per country: EFK|date|country|levels|gdp (levels = wanted, before the ladder).
#############################################

"""


def build() -> str:
    out = [HEADER, "zz_ef_bank_seed_step = {\n",
           "\tif = {\n\t\tlimit = {\n\t\t\tNOT = { has_variable = zz_ef_bank_seeded }\n\t\t\texists = capital\n\t\t}\n",
           "\t\tset_variable = zz_ef_bank_seeded\n",
           "\t\tset_variable = { name = zz_ef_bank_n value = zz_ef_bank_seed_levels }\n",
           "\t\tsave_scope_as = zz_ef_bank_c\n",
           "\t\tdebug_log = \"EFK|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|levels "
           "[THIS.GetCountry.MakeScope.Var('zz_ef_bank_n').GetValue|0]|gdp [THIS.GetCountry.GetGDP|0]\"\n",
           "\t\tcapital = {\n"]
    first = True
    for size in sorted(SIZES, reverse=True):
        kw = "if" if first else "else_if"
        first = False
        out.append(
            f"\t\t\t{kw} = {{\n"
            f"\t\t\t\tlimit = {{ scope:zz_ef_bank_c.var:zz_ef_bank_n >= {size} }}\n"
            f"\t\t\t\tcreate_building = {{\n"
            f"\t\t\t\t\tbuilding = building_zz_ef_bank\n"
            f"\t\t\t\t\treserves = 0\n"
            f"\t\t\t\t\tadd_ownership = {{\n"
            f"\t\t\t\t\t\tcountry = {{\n"
            f"\t\t\t\t\t\t\tcountry = scope:zz_ef_bank_c\n"
            f"\t\t\t\t\t\t\tlevels = {size}\n"
            f"\t\t\t\t\t\t}}\n"
            f"\t\t\t\t\t}}\n"
            f"\t\t\t\t}}\n"
            f"\t\t\t}}\n")
    out.append("\t\t}\n\t\tremove_variable = zz_ef_bank_n\n\t}\n}\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = build()
    assert text.count("{") == text.count("}")
    old = open(OUT, encoding="utf-8-sig").read() if os.path.exists(OUT) else ""
    if args.check:
        if old != text:
            print(f"DIFF: {OUT} is not what the generator writes")
            return 1
        print("ok")
        return 0
    with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT} ({text.count(chr(10))} lines, {len(SIZES)} sizes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
