# -*- coding: utf-8 -*-
"""
regen_greys_food_fix.py -- builds an internal Grey's fix in
`_greys/greys_food_fix done` (GR.14).

Not a pair against an outside mod -- an intra-block overlap between two Grey's
mods that pair_matrix.py and content_holes.py cannot see at all (both compare
across blocks.json blocks, and the whole Grey's pack is one block). Found only
by reading the plan's GR.14 note ("похоже на штатную модульность, тела не
сравнивались") and actually diffing the bodies.

Pack load order (`План проекта.md`, "Целевой порядок запуска"): soft_econ ->
soft_pop -> USU -> cinosphere -> food -> ranch -> diplo -> subject. So grey_food
loads AFTER grey_usu and wins any shared key outright.

Nine production methods are declared TRY_REPLACE: by both grey_usu
(`xMoG_USU_trains_misc_resource.txt` / `xMoG_USU_trains_agriculture.txt`) and
grey_food (`mog_ztrains_food_inputs.txt`) -- the shared refrigeration/cooling
methods for fishing wharf, whaling station and (via grey_food only) livestock
ranch. Seven of the nine are byte-identical between the two mods -- grey_food's
author kept them in sync deliberately, same pattern as GR.10. Two are not:

  * `pm_refrigerated_storage_building_fishing_wharf` -- grey_usu's body adds
    `goods_input_transportation_add = 5` next to the electricity cost;
    grey_food's body only carries the electricity line. Real loss: grey_food
    wins the whole key, USU's transport-cost addition silently disappears.
  * `pm_unrefrigerated` -- grey_usu's body carries a whole `building_modifiers`
    block (`workforce_scaled.goods_input_transportation_add = 1`); grey_food's
    body has no `building_modifiers` at all. Same shape, bigger loss -- the
    entire block is gone, not just one field inside it.

Nothing else in grey_food re-adds these fields elsewhere (checked, single
declaration each). This fix TRY_INJECTs both fields back onto grey_food's
winning bodies, read live out of grey_usu's own file so a future USU or food
edit is caught as drift rather than silently going stale.

The other seven overlaps in GR.14's note are NOT here, checked separately and
found to be non-issues:
  * usu x ranch (2 keys, refrigerated rail cars / storage on livestock ranch):
    grey_usu's own TRY_INJECT: for these two carries only the state_modifiers
    throughput field, and that exact number (0.02 / 0.01) is already present,
    byte-for-byte, inside both grey_food's and grey_food_2_ranch's full
    REPLACE_OR_CREATE: bodies -- author sync, not a gap.
  * food x ranch (4 keys: pm_slaughterhouses, pm_mechanized_slaughtering,
    pm_butchering_tools, pm_open_air_stockyards): grey_food_2_ranch's
    REPLACE_OR_CREATE: bodies are RPR's own comprehensive rebalance (new
    "rpr_"/"m1_" textures, new ai_value, every number touched, employment
    signs flipped) -- a genuine design redo, decision #12, ranch wins, no fix.

Usage:
    python3 regen_greys_food_fix.py            # write the fix
    python3 regen_greys_food_fix.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

GREYS = res("../../vic3_mods_out/grey_add_alot_of_things")
USU_FILE = os.path.join(GREYS, "grey_usu/common/production_methods/xMoG_USU_trains_misc_resource.txt")
OUT = res("../_greys/greys_food_fix done")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's internal fix (GR.14) -- {what}
# Generated by tools/regen_greys_food_fix.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: grey_usu -> ... -> grey_food -> THIS.
# Why this file exists: {why}
"""


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_cooling():
    usu_text = V.read(USU_FILE)

    import re

    _decl, wharf_body = V.entry(usu_text, "pm_refrigerated_storage_building_fishing_wharf", "TRY_REPLACE:")
    bm = V.sub(wharf_body, "building_modifiers")
    assert bm, "pm_refrigerated_storage_building_fishing_wharf: grey_usu no longer carries building_modifiers"
    ws = V.sub(bm[1:-1], "workforce_scaled")
    assert ws and "goods_input_transportation_add" in ws, (
        "pm_refrigerated_storage_building_fishing_wharf: grey_usu no longer carries "
        "goods_input_transportation_add -- re-check GR.14, this fix may be stale")
    m = re.search(r"goods_input_transportation_add\s*=\s*(\S+)", ws)
    wharf_val = m.group(1)

    _decl, unref_body = V.entry(usu_text, "pm_unrefrigerated", "TRY_REPLACE:")
    bm2 = V.sub(unref_body, "building_modifiers")
    assert bm2, "pm_unrefrigerated: grey_usu no longer carries building_modifiers"
    ws2 = V.sub(bm2[1:-1], "workforce_scaled")
    m2 = re.search(r"goods_input_transportation_add\s*=\s*(\S+)", ws2) if ws2 else None
    assert m2, ("pm_unrefrigerated: grey_usu no longer carries "
                "goods_input_transportation_add -- re-check GR.14, this fix may be stale")
    unref_val = m2.group(1)

    text = (
        "# grey_food's own TRY_REPLACE: bodies for these two keys drop a field grey_usu's\n"
        "# TRY_REPLACE: added -- grey_food loads later and wins the whole key, so the field\n"
        "# silently disappears. Both values read live from grey_usu's own file.\n"
        f"TRY_INJECT:pm_refrigerated_storage_building_fishing_wharf = {{\n"
        f"\tbuilding_modifiers = {{\n"
        f"\t\tworkforce_scaled = {{\n"
        f"\t\t\tgoods_input_transportation_add = {wharf_val}\n"
        f"\t\t}}\n"
        f"\t}}\n"
        f"}}\n\n"
        f"TRY_INJECT:pm_unrefrigerated = {{\n"
        f"\tbuilding_modifiers = {{\n"
        f"\t\tworkforce_scaled = {{\n"
        f"\t\t\tgoods_input_transportation_add = {unref_val}\n"
        f"\t\t}}\n"
        f"\t}}\n"
        f"}}"
    )
    write("common/production_methods/zz_greys_food_fix_cooling.txt", text,
          "restore two transport-cost fields grey_food's TRY_REPLACE: drops from grey_usu's bodies",
          "grey_food redeclares nine cooling production methods that grey_usu also declares, in "
          "sync for seven of them. Two aren't: pm_refrigerated_storage_building_fishing_wharf "
          "loses goods_input_transportation_add, pm_unrefrigerated loses its whole "
          "building_modifiers block (same field). Neither is a design dispute -- grey_food's "
          "body is a strict subset missing the field, not a redone number. Restored via "
          "TRY_INJECT: so a future grey_food edit that re-adds the field on its own does not "
          "double it up silently (the generator would still run, just add a redundant but "
          "harmless line -- re-check by hand if grey_food's body ever changes here).")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        import re as _re
        doubled = _re.findall(r"^[A-Z_]+:[A-Z_]+:", text, _re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        empty_colon = _re.findall(r"^[A-Z_]+::", text, _re.M)
        if empty_colon:
            print(f"  FAIL {rel}: {len(empty_colon)} bad '::' prefix(es), e.g. {empty_colon[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = _re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_food_fix.py -> {OUT}")
    for name, fn in (("cooling", build_cooling),):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current grey_usu / grey_food sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
