#!/usr/bin/env python3
"""
EF.48, В5.1 (decided 2.10): the government's loan from the central bank -- step 0.5% of GDP, cap 50%.

E&F's three scripted guis (scripted_guis/00_financial_scripted_guis.txt: debt_issued_relative_GDP_increase / _reduce /
set_debt_issued: step 0.5%, share 0.5..50%, "take" valid while the debt to the CB after the loan <= 50% of GDP) and
the |%1 re-issue of its text debt_issued_relative_GDP_2 are in E&F's own bodies; the generator keeps what is in the
fork's ld_* files: the script values the guis use and the tooltip texts (en, ru).

Writes (via ld_gen, by entry keys, into the fork «E&F: Ledgerdemain»): common/script_values/ld_cb_loan_values.txt,
localization/<lang>/replace/ld_cb_loan_replace_l_<lang>.yml (english, russian)

Usage:
    py tools/regen_ef_cb_loan.py            # write
    py tools/regen_ef_cb_loan.py --check    # exit 1 if the fork files differ
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

LANGS = ["english", "russian", "braz_por", "french", "german", "japanese",
         "korean", "polish", "simp_chinese", "spanish", "turkish"]

STEP = 0.005
SHARE_MAX = 0.5
DEBT_CAP = 0.5

VALUES = f"""# GENERATED by tools/regen_ef_cb_loan.py -- do not edit by hand.
# EF.48, В5.1 (2.10): the debt to the CB after one more loan, a share of GDP (the cap of set_debt_issued).
zz_ef_cb_loan_after_to_gdp = {{
	value = 0
	if = {{ limit = {{ has_variable = credit_at_central_bank }} value = var:credit_at_central_bank }}
	add = debt_issued_relative_GDP
	divide = {{
		value = gdp_var
		min = 1
	}}
}}
zz_ef_cb_loan_now_to_gdp = {{
	value = 0
	if = {{ limit = {{ has_variable = credit_at_central_bank }} value = var:credit_at_central_bank }}
	divide = {{
		value = gdp_var
		min = 1
	}}
}}
"""

NOW = "[GetPlayer.MakeScope.ScriptValue('zz_ef_cb_loan_now_to_gdp')|%1]"
AFTER = "[GetPlayer.MakeScope.ScriptValue('zz_ef_cb_loan_after_to_gdp')|%1]"
TEXTS = {
    "russian": {
        "zz_ef_loan_tt_share_max": f"Доля займа не выше {SHARE_MAX:.0%} ВВП",
        "zz_ef_loan_tt_share_min": f"Доля займа не ниже {STEP:.1%} ВВП",
        "zz_ef_loan_tt_cap": f"Долг центробанку после займа — не больше {DEBT_CAP:.0%} ВВП (сейчас {NOW}, после займа {AFTER})",
    },
    "english": {
        "zz_ef_loan_tt_share_max": f"Loan at most {SHARE_MAX:.0%} of GDP",
        "zz_ef_loan_tt_share_min": f"Loan at least {STEP:.1%} of GDP",
        "zz_ef_loan_tt_cap": f"Debt to the central bank after the loan at most {DEBT_CAP:.0%} of GDP (now {NOW}, after {AFTER})",
    },
}

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    ld_gen.emit("common/script_values/zz_ef_cb_loan_values.txt", VALUES)
    for lang in LANGS:
        tx = TEXTS.get(lang, TEXTS["english"])
        lines = [f"l_{lang}:\n", " # GENERATED by tools/regen_ef_cb_loan.py -- do not edit by hand.\n",
                 " # E&F's loan share with one decimal (step 0.5% of GDP); the loan's limits.\n"]
        lines += [f' {k}:0 "{v}"\n' for k, v in tx.items()]
        ld_gen.emit(f"localization/{lang}/replace/zz_ef_cb_loan_replace_l_{lang}.yml", "".join(lines))
    ld_gen.report("regen_ef_cb_loan")


if __name__ == "__main__":
    main()
