#!/usr/bin/env python3
"""
EF.48, В2.1 (decided 2.10): trade reserve currency as a real flow.

The trade reserve currency as a real flow (E&F's trade_balance itself is edited in the fork's E&F file by hand).

Generated:
  * zz_ef_fx_liab: the country's currency held by other CBs (its debt abroad), for the log and M3.
  * zz_ef_rc_currency_value: the scope country's currency at its parity in gold (clearing).
The monthly trade-reserve step zz_ef_rc_step (its call was commented out) is in the fork's
_archive/ef_reserve_trade_step/ (ФК2, 6.10).

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys):
  common/script_values/ld_reserve_trade_values.txt
Reads the fork's common/scripted_effects/01_economic_scripted_effects.txt (the list of currencies).

Usage:
    python3 tools/regen_ef_reserve_trade.py [--check]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

SRC = os.path.join(ld_gen.FORK, "common", "scripted_effects", "01_economic_scripted_effects.txt")
# hotfix path; ld_gen writes into the fork (ld_reserve_trade_values.txt)
OUT_SV = "common/script_values/zz_ef_reserve_trade_values.txt"

HEAD = ("# GENERATED by tools/regen_ef_reserve_trade.py -- do not edit by hand.\n"
        "# EF.48, В2.1 (2.10): trade reserve currency as a flow -- see the generator's docstring.\n")



def currencies():
    text = open(SRC, encoding="utf-8-sig").read()
    cur = sorted(set(re.findall(r"^\t?sell_([a-z_]+)_currency_crisis = \{", text, re.M)))
    assert len(cur) >= 90, len(cur)
    return cur


def chain(cur, body):
    """if / else_if over the currency laws of the scope country; body(c) is the branch's effect."""
    out = []
    for i, c in enumerate(cur):
        kw = "if" if i == 0 else "else_if"
        out.append(f"\t{kw} = {{ limit = {{ has_law = law_type:law_{c}_currency }} {body(c)} }}\n")
    return "".join(out)


VALUES = ""  # the EFX fields zz_ef_v_rc_* -- nothing set their variables (fork _archive/ld_dead_readers/, 8.10)


def values(cur):
    out = [HEAD, VALUES]
    out.append("# The scope country's currency at its parity in gold (E&F's money_value_<currency>: the leading\n"
               "# country's money_value_target_real_in_gold).\n"
               "zz_ef_rc_currency_value = {\n\tvalue = 0\n")
    out.append(chain(cur, lambda c: f"value = money_value_{c}"))
    out.append("}\n")
    out.append("# The scope country's currency held by the other countries' CBs (capital CB states), in its own\n"
               "# money: its debt abroad (В2.1). Countries on the same currency law are not foreigners here.\n"
               "zz_ef_fx_liab = {\n\tvalue = 0\n")
    out.append(chain(cur, lambda c: f"every_country = {{ limit = {{ NOT = {{ this = root }} NOT = {{ has_law = law_type:law_{c}_currency }} "
                                    f"has_modifier = has_central_bank }} capital = {{ if = {{ limit = {{ has_variable = stockpiling_{c}_state_1 }} "
                                    f"add = {{ value = var:stockpiling_{c}_state_1 min = 0 }} }} }} }}"))
    out.append("\tmin = 0\n}\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    cur = currencies()
    ld_gen.emit(OUT_SV, values(cur))
    ld_gen.report("regen_ef_reserve_trade")


if __name__ == "__main__":
    main()
