"""
regen_llwa_companies.py -- builds `_llwa/llwa+companies done`: gives LLWA's
transport buildings to the natural-candidate historical companies across the
set, as extension_building_types.

Not a two-mod pair. LLWA closes its own four companies over its own seven
buildings (LLWA_companies.txt) -- turnpike (roadway/waterway/riverway),
ship_line (waterway/riverway/port), railroad (railway), airline (airway).
llwa_building_freight_depot, llwa_building_exchange, and
LLWA_building_logistics_hub are deliberately not on any company anywhere
(logistics_hub is `no_ownership`; the other two look like a deliberate
"one per state, not a company holding" choice by LLWA's own author -- not
touched here).

Everyone ELSE's historical companies -- Orient Express, GWR, Suez, Panama,
Prussian State Railways, Mantetsu, and ~50 more across vanilla, TGR, VC, HC,
MoH -- know nothing about LLWA, because LLWA didn't exist when they were
written. Checked live (index of all `common/company_types` in the set):
zero of them mention any LLWA building. This isn't a conflict (nothing is
overwritten, nothing is silently dropped) -- it's LLWA's new transport
network sitting invisible to every company whose whole point is building
exactly that kind of infrastructure.

E&F's ~100 banks also carry building_railway (diversified financial
companies, not transport companies -- railway is one of 7-10 holdings each)
and Grey's/USU's ~70 railway companies are deliberately excluded here: E&F
is a separate, undecided question (would these get llwa_building_exchange?
not settled), and USU is addon-Grey's own territory (GR.9).

Rule, applied uniformly, not by hand-picking companies:
  * company_types with building_railway in building_types
      -> extension_building_types += LLWA_building_roadway
  * company_types with building_port in building_types
      -> extension_building_types += LLWA_building_waterway, LLWA_building_riverway
Three companies (company_hbc, company_russian_american_company,
company_yasuda) have both and get all three additions.

extension_building_types is confirmed present (declared, possibly empty) on
every single company record checked across all five source mods -- this is
INJECT: adding list items to an existing field, not creating a new one.

A company defined by more than one source mod in this list (e.g.
company_orient_express: vanilla AND VC) is emitted ONCE -- this addon loads
last in the chain, so one INJECT: lands on whichever definition is final at
merge time regardless of how many earlier mods touched the same key.

Usage:
    python3 regen_llwa_companies.py            # write the compatch
    python3 regen_llwa_companies.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

OUT = res("../_llwa/llwa+companies done")

SOURCES = {
    "VANILLA": res("../../vic3_mods_out/.vanillaVIC3/common/company_types"),
    "TGR": res("../../vic3_mods_out/TheGreatRevision/common/company_types"),
    "VC": res("../../vic3_mods_out/VC/common/company_types"),
    "HC": res("../../vic3_mods_out/for addon/hailcolumbia/common/company_types"),
    "MoH": res("../../vic3_mods_out/for addon/mandateofheaven/common/company_types"),
}

HEADER = """# LLWA x historical companies -- {what}
# Generated by tools/regen_llwa_companies.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: vanilla/TGR/VC/HC/MoH company_types -> ... -> LLWA -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

# Rail candidates -- have building_railway in building_types somewhere in the
# chain -> get LLWA_building_roadway.
RAIL = [
    "company_altos_hornos_de_vizcaya", "company_cfr", "company_cordoba_railway", "company_csfa",
    "company_dmc", "company_egyptian_rail", "company_franco_belge",
    "company_great_indian_railway", "company_gwr", "company_hbc",
    "company_imperial_ethiopian_railways", "company_iranian_state_railway",
    "company_kaiping_mining", "company_lkab", "company_mantero_seta",
    "company_mantero_seta_two_sicilies", "company_mantetsu", "company_massey_harris",
    "company_ong_lung_sheng_tea_company_heaven_kingdom", "company_orient_express",
    "company_prussian_state_railways", "company_sao_paulo_railway", "company_sherkate_eslamiya",
    "company_siemens_and_halske", "company_standard_oil", "company_tashkent_railroad",
    "company_united_fruit", "company_usfp_union_pacific", "company_yasuda"
]

# Port candidates -- have building_port in building_types somewhere in the
# chain -> get LLWA_building_waterway + LLWA_building_riverway.
PORT = [
    "company_a_markwald_and_company", "company_admiralty_rijkswerf", "company_ap_moller",
    "company_caribbean_petroleum", "company_david_sassoon", "company_hbc", "company_john_holt",
    "company_lanfang_kongsi", "company_panama_company", "company_russian_american_company",
    "company_societe_francaise_charbonnages_du_tonkin", "company_stt", "company_sudamericana_de_vapores",
    "company_suez_company", "company_uragadockcompany", "company_white_star_line", "company_yasuda",
    "company_ynchausti_y_compania",
]


def find_company(key: str) -> tuple[str, list[str]] | None:
    """Search all five source mods for `key`; return (mod label, its
    building_types list) from the LAST (highest-priority) source that
    defines it, or None if nobody defines it any more."""
    found = None
    for label, base in SOURCES.items():
        if not os.path.isdir(base):
            continue
        for f in sorted(os.listdir(base)):
            if not f.endswith(".txt"):
                continue
            text = "\n".join(read_lines(os.path.join(base, f)))
            m = re.search(r"(?m)^(?:[A-Z_]+:)?" + re.escape(key) + r"\s*=\s*\{", text)
            if not m:
                continue
            i = text.index("{", m.start())
            d = 0
            for j in range(i, len(text)):
                if text[j] == "{":
                    d += 1
                elif text[j] == "}":
                    d -= 1
                    if d == 0:
                        break
            body = text[i + 1:j]
            bt = re.search(r"building_types\s*=\s*\{([^}]*)\}", body)
            found = (label, bt.group(1).split() if bt else [])
    return found


def verify_and_collect() -> dict[str, list[str]]:
    additions: dict[str, set[str]] = {}
    missing = []
    wrong = []
    for key in RAIL:
        hit = find_company(key)
        if not hit:
            missing.append(key)
            continue
        label, bt = hit
        if "building_railway" not in bt:
            wrong.append((key, label, "no longer has building_railway"))
            continue
        additions.setdefault(key, set()).add("LLWA_building_roadway")
    for key in PORT:
        hit = find_company(key)
        if not hit:
            missing.append(key)
            continue
        label, bt = hit
        if "building_port" not in bt:
            wrong.append((key, label, "no longer has building_port"))
            continue
        additions.setdefault(key, set()).update(
            {"LLWA_building_waterway", "LLWA_building_riverway"})
    assert not missing, f"{len(missing)} companies no longer found anywhere: {missing[:5]}..."
    assert not wrong, f"{len(wrong)} companies drifted: {wrong[:5]}"
    return {k: sorted(v) for k, v in additions.items()}


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build():
    additions = verify_and_collect()
    out_records = []
    for key in sorted(additions):
        items = "\n".join(f"\t\t{it}" for it in additions[key])
        out_records.append(
            f"INJECT:{key} = {{\n\textension_building_types = {{\n{items}\n\t}}\n}}"
        )
    write("common/company_types/zz_llwa_companies_extensions.txt",
          "\n\n".join(out_records),
          f"add LLWA transport buildings to {len(additions)} historical companies "
          f"as extension buildings",
          "Every historical railway/port company across vanilla, TGR, VC, HC, and "
          "MoH predates LLWA and knows nothing about its roads/canals/rivers. "
          "extension_building_types is additive and declared (even if empty) on "
          "every company record checked, so this is a pure INJECT: -- nothing "
          "overwritten, no company's own design touched. E&F's ~100 banks and "
          "Grey's/USU's ~70 railway companies are deliberately not here -- see "
          "the generator's module docstring.")
    print(f"  {len(additions)} companies: "
          f"{sum(1 for v in additions.values() if 'LLWA_building_roadway' in v)} get roadway, "
          f"{sum(1 for v in additions.values() if 'LLWA_building_waterway' in v)} get waterway/riverway, "
          f"{sum(1 for v in additions.values() if len(v) == 3)} get all three")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        # duplicate-INJECT-target check (different rule than the buildings
        # generators: here EVERY record is INJECT:, so "duplicate" means the
        # same company key appears twice in this file, which would be a
        # generator bug, not a cross-mod layering pattern)
        keys = re.findall(r"(?m)^INJECT:([A-Za-z0-9_]+)\s*=\s*\{", text)
        for k in keys:
            where = ("common/company_types", k)
            if where in seen:
                print(f"  FAIL duplicate INJECT target {k} in {rel}")
                bad += 1
            seen[where] = rel
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} INJECT targets, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_llwa_companies.py -> {OUT}")
    build()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
