# -*- coding: utf-8 -*-
"""
regen_greys_subject_fix.py -- builds an internal Grey's fix in
`_greys/greys_subject_fix done` (GR.14).

Not a pair against an outside mod -- an intra-block overlap between two Grey's
mods that pair_matrix.py and content_holes.py cannot see at all (both compare
across blocks.json blocks, and the whole Grey's pack is one block). Found only
by reading the plan's GR.14 note and actually diffing the bodies.

Pack load order (`План проекта.md`, "Целевой порядок запуска"): soft_econ ->
soft_pop -> USU -> cinosphere -> food -> ranch -> diplo -> subject. grey_subject
loads LAST in the block, so it wins any shared key outright over grey_diplo.

Both grey_diplo (`zzzz04_trade_statez.txt`) and grey_subject
(`04_trade_statez.txt`) redeclare the vanilla `trade_states` diplomatic action
in full (TRY_REPLACE: / REPLACE_OR_CREATE:). Byte-diffed: grey_subject's body
is not a redesign, it is an older/different copy that is missing every one of
grey_diplo's deliberate "# Modded" additions and carries one broken field:

  * `second_state_trigger` -- grey_diplo adds an extra OR-alternative,
    `scope:country = { any_subject_or_below = { is_adjacent_to_state = root } }`
    (tagged "# Modded"). Missing from grey_subject entirely, not shortened --
    the whole line is gone.
  * AI `accept_score` -- grey_diplo adds three tagged "# Modded" pieces:
    a subtract-100 penalty when the traded state's port is defunct and the
    target outranks the actor, a +100 bonus when the first state is the
    target's cultural homeland, and a whole `else_if` branch giving AI value
    when only the first state qualifies for a split-state exchange (plus the
    split-state bonus itself bumped from 25 to 30, self-documented with a
    trailing `# 25` comment). All absent from grey_subject.
  * `has_port` vs `has_port_country` -- both `first_state_trigger` and
    `second_state_trigger` call `has_port` at country scope in grey_diplo;
    grey_subject's copy calls `has_port_country` instead. This spelling
    appears nowhere else in the entire Grey's pack -- not in grey_subject's
    own other files (`z43_subjects_demand_states.txt` uses `has_port`), not
    in grey_diplo's other files (`z13_goods_transfer.txt`,
    `zzzz06_transfer_state.txt`, both also `has_port`). Treated as a typo in
    grey_subject's file, not a deliberate rename.

Checked the reverse direction too: grey_subject's body adds nothing of its own
that grey_diplo's version lacks (the only other differences are whitespace and
a shortened `# is_subject = no` comment with the "Modded" explanation trimmed
off, both cosmetic). grey_diplo's body is a strict superset -- the fix is a
straight TRY_REPLACE: with grey_diplo's own body, read live so a future change
on either side is caught by --check rather than silently going stale.

Usage:
    python3 regen_greys_subject_fix.py            # write the fix
    python3 regen_greys_subject_fix.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

GREYS = res("../../vic3_mods_out/grey_add_alot_of_things")
DIPLO_FILE = os.path.join(GREYS, "grey_diplo/common/diplomatic_actions/zzzz04_trade_statez.txt")
SUBJECT_FILE = os.path.join(GREYS, "grey_subject/common/diplomatic_actions/04_trade_statez.txt")
OUT = res("../_greys/greys_subject_fix done")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's internal fix (GR.14) -- {what}
# Generated by tools/regen_greys_subject_fix.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: grey_diplo -> ... -> grey_subject -> THIS.
# Why this file exists: {why}
"""


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_trade_states():
    key = "trade_states"
    diplo_text = V.read(DIPLO_FILE)
    _decl, diplo_body = V.entry(diplo_text, key, "TRY_REPLACE:")

    subject_text = V.read(SUBJECT_FILE)
    _decl2, subject_body = V.entry(subject_text, key, "REPLACE_OR_CREATE:")

    # Markers this fix depends on -- if any of these stop matching, grey_diplo
    # or grey_subject changed this record and the fix needs re-checking by hand.
    assert "any_subject_or_below" in diplo_body, (
        f"{key}: grey_diplo no longer carries the any_subject_or_below alternative "
        f"-- re-check GR.14, this fix may be stale")
    assert "any_subject_or_below" not in subject_body, (
        f"{key}: grey_subject now carries any_subject_or_below too -- the author may "
        f"have caught up with grey_diplo, re-check whether this fix is still needed")
    assert "has_port_country" in subject_body, (
        f"{key}: grey_subject no longer uses has_port_country -- the typo may be fixed "
        f"upstream, re-check whether this fix is still needed")
    assert "has_port_country" not in diplo_body, (
        f"{key}: grey_diplo now uses has_port_country too -- re-check which spelling is "
        f"actually correct before trusting this fix's assumption")
    assert "# Modded" in diplo_body, (
        f"{key}: grey_diplo's Modded markers are gone -- re-check GR.14, this fix may be stale")

    write("common/diplomatic_actions/zz_greys_subject_fix_trade_states.txt",
          f"TRY_REPLACE:{key} = {{{diplo_body}}}",
          "restore grey_diplo's trade_states body, which grey_subject's older copy silently wins over and wipes",
          "grey_diplo and grey_subject both redeclare the vanilla trade_states action in full. "
          "grey_subject's copy is not a redesign -- it is an older/different copy missing every "
          "one of grey_diplo's \"# Modded\" additions (an extra adjacency path through subjects "
          "on second_state_trigger; three AI acceptance-score tweaks: a defunct-port penalty, a "
          "homeland bonus, and an else_if branch for one-sided split-state exchanges; a bumped "
          "split-state AI value 25->30) and carries a has_port_country typo where grey_diplo (and "
          "every other file in the pack, including grey_subject's own) uses has_port. grey_subject "
          "loads last in the block and wins the whole record, wiping all of it silently -- nothing "
          "in error.log. grey_subject adds nothing of its own to this record (checked both "
          "directions), so the fix is grey_diplo's body verbatim, read live rather than hand-copied.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        import re as _re
        doubled = _re.findall(r"^[A-Z_]+:[A-Z_]+:", text, _re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        empty_colon = _re.findall(r"^[A-Z_]+::", text, _re.M)
        if empty_colon:
            print(f"  FAIL {rel}: {len(empty_colon)} bad '::' prefix(es), e.g. {empty_colon[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = _re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_subject_fix.py -> {OUT}")
    for name, fn in (("trade_states", build_trade_states),):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current grey_diplo / grey_subject sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
