#!/usr/bin/env python3
"""
П.8 (В.5): the table of the CB's reserves -- its foreign money by issuer: units, in money, in gold, the week's change
(zz_ef_cbfx_*; the list -- scripted GUI zz_ef_cbfx_update_sorted, the holders' pie -- zz_ef_holders_update; the table --
gui/ld_economy_panel.gui of the fork, by hand), and its localization.

The clearing itself (common/scripted_effects/ld_clearing.txt, common/script_values/ld_clearing_values.txt) is written by
hand since R8в (Д.R8в.4, Д.R8в.11): no part of it is generated.

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys):
  common/scripted_guis/ld_cbfx.txt, localization/{english,russian}/ld_cbfx_l_*.yml

Usage:
    python3 tools/regen_ef_clearing.py [--check]
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ld_gen  # noqa: E402
from ld_curdata import currencies  # noqa: E402

# hotfix paths; ld_gen writes into the fork (ld_cbfx.txt, ld_cbfx_l_*.yml)
OUT_SG = "common/scripted_guis/zz_ef_cbfx.txt"
LANGS = ["english", "russian", "braz_por", "french", "german", "japanese",
         "korean", "polish", "simp_chinese", "spanish", "turkish"]

HEAD = ("# GENERATED by tools/regen_ef_clearing.py -- do not edit by hand.\n"
        "# the table of the CB's foreign reserves -- see the generator's docstring.\n")

def sguis(cur):
    return HEAD + """
# The CB's foreign money by issuer (map zz_ef_rq_cb_m), the biggest in gold first: global list zz_ef_cbfx_list of the
# issuers; on each issuer the row -- units (var:zz_ef_cbfx_u), in gold (zz_ef_cbfx_g), in our money (zz_ef_cbfx_mn), the
# week's change (zz_ef_cbfx_dd, zz_ef_cbfx_week_step).
zz_ef_cbfx_update_sorted = {
	effect = {
		clear_global_variable_list = zz_ef_cbfx_list
		save_scope_as = zz_ef_cbfx_h
		set_variable = { name = zz_ef_cbfx_gpm value = zz_ef_clr_gold_per_money }
		if = {
			limit = { has_variable_map = zz_ef_rq_cb_m }
			zz_ef_rq_keys_take = { MAP = zz_ef_rq_cb_m }
			every_in_list = {
				variable = zz_ef_rq_keys
				save_temporary_scope_as = zz_ef_cbfx_k
				scope:zz_ef_cbfx_h = {
					zz_ef_rq_get = { MAP = zz_ef_rq_cb_m D = scope:zz_ef_cbfx_k }
					set_variable = { name = zz_ef_cbfx_t value = var:zz_ef_rq_h }
					zz_ef_rq_get = { MAP = zz_ef_cbfx_d D = scope:zz_ef_cbfx_k }
				}
				set_variable = { name = zz_ef_cbfx_u value = scope:zz_ef_cbfx_h.var:zz_ef_cbfx_t }
				set_variable = { name = zz_ef_cbfx_dd value = scope:zz_ef_cbfx_h.var:zz_ef_rq_h }
				set_variable = { name = zz_ef_cbfx_g value = { value = var:zz_ef_cbfx_u multiply = zz_ef_rq_gpm_v } }
				set_variable = { name = zz_ef_cbfx_mn value = 0 }
				if = {
					limit = { scope:zz_ef_cbfx_h.var:zz_ef_cbfx_gpm > 0 }
					set_variable = { name = zz_ef_cbfx_mn value = { value = var:zz_ef_cbfx_g divide = scope:zz_ef_cbfx_h.var:zz_ef_cbfx_gpm } }
				}
			}
			ordered_in_list = {
				variable = zz_ef_rq_keys
				order_by = zz_ef_cbfx_g_v
				max = 200
				check_range_bounds = no
				add_to_global_variable_list = { name = zz_ef_cbfx_list target = this }
			}
			clear_variable_list = zz_ef_rq_keys
		}
		remove_variable = zz_ef_cbfx_t
	}
}

# the other CBs holding the player's money (global list zz_ef_holders_list; the amount in the player's money on each
# holder, var:zz_ef_holds_pc), for the pie chart; the biggest holder first.
zz_ef_holders_update = {
	effect = {
		clear_global_variable_list = zz_ef_holders_list
		save_scope_as = holders_root
		every_country = {
			limit = { has_variable = zz_ef_holds_pc }
			remove_variable = zz_ef_holds_pc
		}
		every_country = {
			limit = {
				NOT = { this = scope:holders_root }
				has_variable_map = zz_ef_rq_cb_m
				is_key_in_variable_map = { name = zz_ef_rq_cb_m target = scope:holders_root }
			}
			zz_ef_rq_get = { MAP = zz_ef_rq_cb_m D = scope:holders_root }
			set_variable = { name = zz_ef_holds_pc value = var:zz_ef_rq_h }
		}
		ordered_country = {
			limit = { has_variable = zz_ef_holds_pc }
			order_by = zz_ef_holds_pc_v
			max = 1000
			check_range_bounds = no
			add_to_global_variable_list = { name = zz_ef_holders_list target = this }
		}
	}
}
"""


def write_loc(cur):
    for lang in LANGS:
        ru = lang == "russian"
        w = "за неделю" if ru else "a week"
        sv = lambda n: f"[GetPlayer.MakeScope.ScriptValue('{n}')"
        lines = [f"l_{lang}:\n",
                 ' zz_ef_ep_cbfx_title:0 "%s"\n' % ("Резервы ЦБ по валютам" if ru else "CB reserves by currency"),
                 ' zz_ef_ep_cbfx_tt:0 "%s"\n' % (
                     "Чужие деньги в резервах ЦБ — вклады в банках стран-эмитентов (мировой клиринг): количество, в наших "
                     "деньгах, в золоте и изменение за неделю. В подсказке денежной массы они в счёте «Заграница», в "
                     "покрытии — деньги эмитентов, разменивающих их на металл." if ru else
                     "Foreign money in the CB's reserves -- deposits in the issuers' banks (the world clearing): units, in "
                     "our money, in gold and the week's change. In the money supply tooltip it is in the 'Abroad' account; "
                     "the money of issuers that redeem it in metal counts in the cover.")]
        lines.append(' zz_ef_cbfx_week:0 "%s"\n' % w)
        ld_gen.emit(f"localization/{lang}/zz_ef_cbfx_l_{lang}.yml", "".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    cur = currencies()
    write_loc(cur)
    for path, text in ((OUT_SG, sguis(cur)),):
        assert text.count("{") == text.count("}"), path
        ld_gen.emit(path, text)
    ld_gen.report("regen_ef_clearing")


if __name__ == "__main__":
    main()
