# -*- coding: utf-8 -*-
"""
regen_greys_addonvc.py -- builds the Grey's x addon-VC compatch in
`_greys/greys+addon-vc done`.

Pair GR.18. Not the same pair as GR.1 (`_greys/greys+vc done`, raw Victorian
Century vs the Grey's pack, 129 keys): addon-VC is a *build* -- VC merged with
its own compat layers (`zz_vc_tgr_*`, `zz_vc_morg_*`, `zz_vc_ef_*`, ...) --
and it carries content raw VC alone does not, the same class of gap GR.17
closed for the megapack. `content_holes.py --only builds` reports 8 keys under
"АДДОН-VC × USU" (3) and "АДДОН-VC × ranch" (2, one already closed) plus
interest_groups / ai_strategies keys against HC and LLWA that are not Grey's
business at all.

Of the four `pop_needs` keys (`popneed_free_movement`, `popneed_heating`,
`popneed_leisure`, `popneed_luxury_food`; `popneed_basic_food` was the fifth
and is already closed in GR.1), checked one at a time against grey_usu's and
grey_food_2_ranch's actual bodies:

  * `popneed_free_movement` -- NOT a loss. addon-VC's own Morgenroete-compat
    file (`zz_vc_morg_pop_needs.txt`) re-applies an `air_travel` entry
    (weight 4, max_supply_share 0.01) that grey_usu's REPLACE: wipes -- but
    grey_usu's own file (`yMoG_USU_pop_needs.txt`) already TRY_INJECTs the
    exact same entry, byte-for-byte, right after its own REPLACE:. Checked,
    no file.
  * `popneed_heating` -- a genuine two-design dispute, not a silent loss.
    addon-VC's body here is TGR's real rebalance (commented `# TGR (N
    vanilla)` throughout, not a vanilla copy the way GR.1 found for
    `popneed_basic_food`). grey_usu's REPLACE: touches every one of TGR's
    five goods with its own commented before/after numbers and adds a sixth
    (services) -- a superset, not an omission. Same rule as GR.1's decision
    #12 (Grey's wins fields it actually moved): USU wins, no file.
  * `popneed_luxury_food` -- same shape as heating. addon-VC's body is TGR's
    real rebalance; grey_food_2_ranch's TRY_REPLACE: is RPR's own considered
    redesign (explicit "RPR - Added" / "RPR: ..." comments on every entry,
    including a deliberate `default` change). Two designs, ranch wins, no
    file.
  * `popneed_leisure` -- the one real loss. grey_usu's REPLACE:
    (`mMoG_USU_pop_needs.txt`) is its own deliberate leisure redesign, but it
    carries an `air_travel` entry commented OUT with the note "Gets added
    with Morgenrote" -- i.e. the author expected Morgenroete's own
    TRY_INJECT: to still apply. It doesn't: the REPLACE: wipes it, and
    grey_usu's own follow-up TRY_INJECT: (`zzzMoG_USU_MR_pop_needs.txt`)
    restores only `elgar_music`, never `air_travel`. addon-VC's own
    Morgenroete-compat file carries the exact entry that would fill the gap
    the author left. Restored here.

Four companies (`company_imperial_arsenal`, `company_russian_american_company`,
`company_standard_oil`, `company_william_cramp`) round out content_holes.py's
original count of interest, but none show up as a builds conflict at all --
`content_holes.py --only builds` reports zero `company_types` keys for
"АДДОН-VC". Consistent with GR.1/GR.5/GR.7: USU only `TRY_INJECT:`s these,
additive, nothing of addon-VC's is displaced. No file.

`interest_groups` (vs HC/addon-HC) and `ai_strategies` (vs LLWA/addon-LLWA)
that content_holes.py also reports under "АДДОН-VC" are not this pair -- Grey's
touches neither.

Usage:
    python3 regen_greys_addonvc.py            # write the compatch
    python3 regen_greys_addonvc.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

ADDON_VC = res("../__addon/addon vc")
USU = res("../../vic3_mods_out/grey_add_alot_of_things/grey_usu")
OUT = res("../_greys/greys+addon-vc done")

ADDONVC_SRC = os.path.join(ADDON_VC, "common/pop_needs/zz_vc_morg_pop_needs.txt")
USU_LEISURE_FILE = os.path.join(USU, "common/pop_needs/mMoG_USU_pop_needs.txt")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's x addon-VC compatch (GR.18) -- {what}
# Generated by tools/regen_greys_addonvc.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: ... -> addon-VC -> ... -> Grey's pack -> THIS.
# Why this file exists: {why}
"""


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_leisure():
    key = "popneed_leisure"
    addonvc_text = V.read(ADDONVC_SRC)
    _decl, addonvc_body = V.entry(addonvc_text, key, "TRY_INJECT:")
    entry_block = V.sub(addonvc_body, "entry")
    assert entry_block, f"{key}: addon-VC's own TRY_INJECT: no longer carries an entry block"
    assert "air_travel" in entry_block, f"{key}: addon-VC's entry is no longer air_travel -- re-check GR.18"

    usu_text = V.read(USU_LEISURE_FILE)
    _decl, usu_body = V.entry(usu_text, key, "REPLACE:")
    usu_body_live = "\n".join(line for line in usu_body.split("\n") if not line.strip().startswith("#"))
    assert "goods = air_travel" not in usu_body_live, (
        f"{key}: grey_usu's REPLACE: now carries an active (non-commented) air_travel entry -- "
        f"re-read the body by hand, this generator's assumption may be stale")
    assert "goods = air_travel" in usu_body, (
        f"{key}: grey_usu's REPLACE: no longer even mentions air_travel commented-out -- "
        f"the author may have removed the reference, re-check the module docstring's story")

    text = (
        "# grey_usu's own REPLACE: (mMoG_USU_pop_needs.txt) leaves this entry commented OUT\n"
        "# with the note \"Gets added with Morgenrote\" -- the author expected Morgenroete's own\n"
        "# TRY_INJECT: to still apply after the REPLACE:. It doesn't (REPLACE: wipes it), and\n"
        "# grey_usu's own follow-up TRY_INJECT: (zzzMoG_USU_MR_pop_needs.txt) restores only\n"
        "# elgar_music, never this. Read live from addon-VC's own Morgenroete-compat file.\n"
        f"TRY_INJECT:{key} = {{\n\tentry = {entry_block}\n}}"
    )
    write("common/pop_needs/zz_greys_addonvc_pop_needs.txt", text,
          "restore the air_travel entry on popneed_leisure that grey_usu's author left unfinished",
          "grey_usu's REPLACE:popneed_leisure is a deliberate redesign (fine_art / wine / "
          "transportation / usu_logistics / merchant_marine / small_arms / aeroplanes / "
          "clippers / steamers), but its own source carries an air_travel entry commented OUT "
          "with \"Gets added with Morgenrote\" -- the author relied on Morgenroete's original "
          "TRY_INJECT: still applying, which a REPLACE: wipes. grey_usu's own follow-up "
          "TRY_INJECT: (for elgar_music) shows the author knows this record needs a Morgenrote "
          "top-up; it only restores elgar_music, not air_travel. addon-VC's own "
          "Morgenroete-compat file carries the exact entry -- read live from there rather than "
          "hand-copied, so a future addon-VC rebalance is caught by drift. popneed_free_movement, "
          "popneed_heating and popneed_luxury_food are NOT here -- see the module docstring, "
          "checked and not silent losses.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        import re as _re
        doubled = _re.findall(r"^[A-Z_]+:[A-Z_]+:", text, _re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        empty_colon = _re.findall(r"^[A-Z_]+::", text, _re.M)
        if empty_colon:
            print(f"  FAIL {rel}: {len(empty_colon)} bad '::' prefix(es), e.g. {empty_colon[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = _re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_addonvc.py -> {OUT}")
    for name, fn in (("leisure", build_leisure),):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current addon-VC / Grey's sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
