"""
regen_hc_ef.py -- builds the HC+GoB x E&F compatch in `_HC+GoB+MoH/hc+ef done`.

Task HC.12. The pair was marked `noneed` on 2026-08-25 ("nothing shared but 7
localisation keys") and that was wrong for exactly the reason LLWA x E&F was
wrong: `pair_matrix.py` only sees keys BOTH mods define, so a brand new
building one mod adds and the other never mentions cannot show up as a shared
key -- and therefore cannot show up as a conflict. Found on 2026-08-26 by
`tools/content_holes.py --only registry`.

Hail, Columbia! and Gates of the Bosphorus add three privately-ownable
buildings between them:

    building_usfp_fur_trapper        HC   bg_usfp_fur_trapping
    usfp_hippo_ranch                 HC   bg_ranching
    gbbf_building_esparto_plantation GoB  bg_plantations

All three are `ownership_type = self`. E&F's stock/liquidity machinery is a
hand-written per-building whitelist -- `production_method_groups` INJECTs in
`common/buildings/ef_*.txt`, plus 49 buildings hand-listed in
`private_ownership_production_stocks`
(common/scripted_effects/01_financial_scripted_effects.txt). Checked live: not
one of the three names appears anywhere in E&F, the hotfix, the megapack or
the assembled HC addon. Without this compatch those three buildings produce no
liquidity, issue no stock and never switch on private ownership. Silent --
nothing in error.log.

STOCK TYPE: all three get `agricultural_stock`, and that is not a guess.
E&F's own agricultural list already carries the primary-extraction buildings
next to the farms: building_logging_camp, building_fishing_wharf,
building_whaling_station sit there beside the plantations and the livestock
ranch. A fur trapper belongs with whaling and logging, a hippo ranch with the
livestock ranch, an esparto plantation with the plantations. One stock type
for all three, so no new PM group and no new localisation -- the group's
display name is already in the chain via ef+morg done's loc file.

Deliberately NOT included: building_usfp_national_park and GoB's government
and monument buildings -- they are not `ownership_type = self`, so private
ownership cannot apply to them at all. Same reasoning that excluded
LLWA_building_logistics_hub from `_llwa/llwa+ef done`.

Shape copied from `_llwa/llwa+ef done` (which in turn copies `_ef/ef+morg done`,
E&F's own solution for Morgenroete's 62 buildings): four files, same roles.

Usage:
    python3 regen_hc_ef.py            # write the compatch
    python3 regen_hc_ef.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

HC = res("../../vic3_mods_out/for addon/hailcolumbia")
GOB = res("../../vic3_mods_out/for addon/gatesofbosphorus")
EF = res("../../vic3_mods_out/E&F")
OUT = res("../_HC+GoB+MoH/hc+ef done")

HEADER = """# HC+GoB x E&F compatch -- {what}
# Generated by tools/regen_hc_ef.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: E&F -> ... -> Hail Columbia -> Gates of the Bosphorus -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

# The three HC/GoB buildings that can be privately owned (ownership_type = self),
# each with the file it is defined in so --check catches a rename upstream.
# Everything else HC and GoB add is government-owned or a monument -- excluded.
BUILDINGS = [
    ("building_usfp_fur_trapper", "HC", "common/buildings/usfp_buildings.txt"),
    ("usfp_hippo_ranch", "HC", "common/buildings/usfp_buildings.txt"),
    ("gbbf_building_esparto_plantation", "GOB",
     "common/buildings/gbbf_04_buildings_plantations.txt"),
]
STOCK = "agricultural"


def record_exists(path: str, key: str, prefix: str | None = None) -> bool:
    lines = read_lines(path)
    pat_prefix = re.escape(prefix) if prefix else r"(?:[A-Z_]+:)?"
    pat = re.compile(r"^" + pat_prefix + re.escape(key) + r"\s*=\s*\{")
    return any(pat.match(raw.split("#", 1)[0].lstrip("﻿")) for raw in lines)


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def verify_sources():
    roots = {"HC": HC, "GOB": GOB}
    for b, who, rel in BUILDINGS:
        path = os.path.join(roots[who], rel)
        assert os.path.isfile(path), f"{who}: {rel} not found -- did the mod rename it?"
        assert record_exists(path, b), (
            f"{who} no longer defines {b} in {rel} -- re-check the building list")
        # ownership_type = self is the whole reason this building is in the list
        body = "\n".join(read_lines(path))
        start = body.index(b)
        chunk = body[start:start + 4000]
        assert "ownership_type = self" in chunk.split("\nbuilding")[0], (
            f"{b} no longer looks privately ownable -- re-check before running")

    ef_pm = os.path.join(EF, "common/production_methods/02_ef_agro.txt")
    assert os.path.isfile(ef_pm), "E&F's 02_ef_agro.txt not found -- re-check"
    for pm in (f"pm_no_private_ownership_{STOCK}_stock",
               f"pm_private_ownership_majority_{STOCK}_stock"):
        assert record_exists(ef_pm, pm), f"E&F no longer defines {pm} -- re-check the merge"

    ef_pmg = os.path.join(EF, "common/production_method_groups/02_ef_agro.txt")
    assert record_exists(ef_pmg, f"pmg_private_ownership_{STOCK}_stock"), (
        f"E&F no longer defines pmg_private_ownership_{STOCK}_stock -- re-check")

    ef_switch = os.path.join(EF, "common/scripted_effects/01_financial_scripted_effects.txt")
    assert record_exists(ef_switch, "private_ownership_production_stocks"), (
        "E&F no longer defines private_ownership_production_stocks -- re-check the switch effect")
    text = read_lines(ef_switch)
    joined = "\n".join(text)
    for b, _who, _rel in BUILDINGS:
        assert f"building_type = {b}" not in joined, (
            f"E&F's private_ownership_production_stocks already switches {b} -- "
            f"this generator's own switch would double it, re-check before running")


def build_buildings_inject():
    out_records = []
    for b, who, _rel in BUILDINGS:
        out_records.append(
            f"# {b} ({who})\n"
            f"TRY_INJECT:{b} = {{\n"
            f"\tproduction_method_groups = {{\n"
            f"\t\tpmg_market_liquidity\n"
            f"\t\tpmg_private_ownership_{STOCK}_stock\n"
            f"\t}}\n"
            f"}}"
        )
    write("common/buildings/zz_hc_ef_buildings_inject.txt",
          "\n\n".join(out_records),
          "add E&F's financial PM groups to the three privately-owned HC/GoB buildings",
          "E&F's stock/liquidity machinery is a hand-written per-building whitelist "
          "that predates both mods and mentions none of these three. TRY_INJECT so a "
          "building renamed in a future HC/GoB version does not spam the error log. "
          "building_usfp_national_park and GoB's government/monument buildings are not "
          "here on purpose -- they are not ownership_type = self.")


def build_switch_effect():
    blocks = []
    for b, who, _rel in BUILDINGS:
        blocks.append(f"""\t\t# {b} ({who}, {STOCK} stock)
\t\tif = {{
\t\t\tlimit = {{
\t\t\t\thas_building = {b}
\t\t\t\tb:{b} = {{
\t\t\t\t\tprivate_ownership_fraction > 0.5
\t\t\t\t}}
\t\t\t\tis_production_method_active = {{
\t\t\t\t\tbuilding_type = {b}
\t\t\t\t\tproduction_method = pm_no_private_ownership_{STOCK}_stock
\t\t\t\t}}
\t\t\t}}
\t\t\tactivate_production_method = {{
\t\t\t\tbuilding_type = {b}
\t\t\t\tproduction_method = pm_private_ownership_majority_{STOCK}_stock
\t\t\t}}
\t\t}}
\t\tif = {{
\t\t\tlimit = {{
\t\t\t\thas_building = {b}
\t\t\t\tb:{b} = {{
\t\t\t\t\tprivate_ownership_fraction <= 0.5
\t\t\t\t}}
\t\t\t\tis_production_method_active = {{
\t\t\t\t\tbuilding_type = {b}
\t\t\t\t\tproduction_method = pm_private_ownership_majority_{STOCK}_stock
\t\t\t\t}}
\t\t\t}}
\t\t\tactivate_production_method = {{
\t\t\t\tbuilding_type = {b}
\t\t\t\tproduction_method = pm_no_private_ownership_{STOCK}_stock
\t\t\t}}
\t\t}}""")
    text = "hc_private_ownership_production_stocks = {\n\tevery_scope_state = {\n\n" + \
           "\n\n".join(blocks) + "\n\t}\n}"
    write("common/scripted_effects/zz_hc_ef_private_ownership_effects.txt",
          text,
          "extend E&F's \"private ownership -> stocks\" switching to the HC/GoB buildings",
          "same shape as _ef/ef+morg done's mr_private_ownership_production_stocks -- "
          "E&F's own switch effect only lists vanilla/E&F buildings, so these three "
          "need their own yearly check. Wired in additively (see the on_action and "
          "history/global files in this same compatch), overrides nothing of E&F's.")


def build_on_action():
    text = ("on_yearly_pulse_country = {\n"
            "\ton_actions = {\n"
            "\t\tzz_hc_ef_on_yearly_pulse_country\n"
            "\t}\n"
            "}\n\n"
            "zz_hc_ef_on_yearly_pulse_country = {\n"
            "\teffect = {\n"
            "\t\thc_private_ownership_production_stocks = yes\n"
            "\t}\n"
            "}")
    write("common/on_actions/zz_hc_ef_on_actions.txt",
          text,
          "hook the LLWA private-ownership stock switch into the yearly pulse",
          "on_actions are additive across mods -- this overrides nothing from E&F, "
          "ef+morg done, llwa+ef done, or anyone else also appending to "
          "on_yearly_pulse_country.")


def build_history_init():
    text = ("GLOBAL = {\n"
            "\tevery_country = {\n"
            "\t\thc_private_ownership_production_stocks = yes\n"
            "\t}\n"
            "}")
    write("common/history/global/zz_hc_ef_stocks_init.txt",
          text,
          "initialise the stock production methods at game start",
          "on_yearly_pulse_country only fires a year after the start, so LLWA's "
          "buildings would sit on \"No ... Stock\" for the whole first year even "
          "when private ownership is already past half. Same fix E&F uses for its "
          "own buildings and ef+morg done uses for Morgenroete's. GLOBAL blocks "
          "stack across mods -- additive, overrides nothing.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category = os.path.dirname(rel)
        depth = 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_hc_ef.py -> {OUT}")
    verify_sources()
    for name, fn in (
        ("buildings inject", build_buildings_inject),
        ("switch effect", build_switch_effect),
        ("on_action", build_on_action),
        ("history init", build_history_init),
    ):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current HC / GoB / E&F sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
