#!/usr/bin/env python3
"""
regen_ef_metal_hoard.py -- stage 2, night 6.10, step 4: pops buy gold and silver (Д2.21, Д2.24).

Why
---
Metal is a good (М, the user 6.10): every unit on any account was bought on the market. The pops are one of its
buyers: their metal is part of their savings, held out of distrust (Д3.4) -- in the XIX century the hoard was the
peasants' and workers' savings, the rich held paper.
  * wealth 15+: gold and silver are two more choices in E&F's popneed_financial_products (bonds, stocks, mutual
    funds) -- pops take what is cheaper, the weight follows the market's sell orders (Д2.21);
  * wealth 5-14: a new need, popneed_metal_hoard -- metals only (Д2.24 б: metals from wealth 5, paper from 15).
The money pops spend on them leaves their income through the market (the leak to their savings falls by as much),
the metal goes to their account var:zz_ef_popm_gold / _silver (scripted_effects/zz_ef_metal_accounts.txt: the
states' consumption minus the banks' buildings' input, x 100 / x 775 units a good).

What it writes (the E&F hotfix)
--------------
1. common/pop_needs/zz_ef_metal_hoard.txt -- popneed_metal_hoard (silver default, gold) and INJECT of the two
   entries into popneed_financial_products.
2. common/buy_packages/zz_ef_metal_hoard_packages.txt -- INJECT into wealth_5..wealth_14: SHARE_LOW of the level's
   basket (TGR's packages, money at base prices) at wealth 5, rising to SHARE_HIGH at wealth 14.
   The VC branch: addon-VC's merged REPLACE_OR_CREATE file wipes this INJECT, tools/regen_addon_vc.py re-adds it.
3. localization (english, russian).

!! TUNING !! (accepted at night 6.10, check): SHARE_LOW / SHARE_HIGH, the entries' weight and max_supply_share
(pops must not buy the market out from under the CBs: max_supply_share 0.5).

Usage:  python3 tools/regen_ef_metal_hoard.py [--check]     (needs vic3_mods_out: run on the PC, py_tool)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import regen_ef_household_construction as HC  # noqa: E402  (TGR's basket sums, emit)

HOTFIX = HC.HOTFIX
NEED = "popneed_metal_hoard"
LEVELS = range(5, 15)
SHARE_LOW, SHARE_HIGH = 0.01, 0.02
WEIGHT, MAX_SHARE = 0.5, 0.5

OUT_NEED = HOTFIX / "common/pop_needs/zz_ef_metal_hoard.txt"
OUT_PKG = HOTFIX / "common/buy_packages/zz_ef_metal_hoard_packages.txt"

LOC = {
    "english": {
        NEED: "Hoarded Metal",
        NEED + "_desc": "Gold and silver coin kept at home: the savings of those who trust neither banks nor paper.",
    },
    "russian": {
        NEED: "Металл в кубышке",
        NEED + "_desc": "Золотая и серебряная монета дома: сбережения тех, кто не доверяет ни банкам, ни бумагам.",
    },
}

HEAD = """### GENERATED by tools/regen_ef_metal_hoard.py -- do not edit by hand.
### Stage 2, night 6.10 (Д2.21, Д2.24): pops buy gold and silver -- metals from wealth 5, paper from wealth 15.
"""


def share(w: int) -> float:
    return SHARE_LOW + (SHARE_HIGH - SHARE_LOW) * (w - LEVELS[0]) / (LEVELS[-1] - LEVELS[0])


def package_values() -> dict[int, int]:
    sums = HC.tgr_package_sums()
    return {w: max(1, round(sums[w] * share(w))) for w in LEVELS}


def entry(good: str) -> str:
    return f"""
	entry = {{
		goods = {good}

		weight = {WEIGHT:g}
		max_supply_share = {MAX_SHARE:g}
		min_supply_share = 0.0
	}}
"""


def build_need() -> str:
    return HEAD + f"""### The hoard: metals only, silver by default (the small saver's coin). Weight by the market's sell orders.

{NEED} = {{
	default = silver
{entry("silver")}{entry("gold")}}}

### Wealth 15+: gold and silver next to E&F's bonds, stocks and funds -- pops take what is cheaper (Д2.21).
INJECT:popneed_financial_products = {{
{entry("gold")}{entry("silver")}}}
"""


def build_packages(vals: dict[int, int]) -> str:
    out = [HEAD + f"""### {NEED} in wealth_{LEVELS[0]}..wealth_{LEVELS[-1]}: {SHARE_LOW:.1%} of the level's basket (TGR's packages, money
### at base prices) at wealth {LEVELS[0]}, rising to {SHARE_HIGH:.1%} at wealth {LEVELS[-1]}; from wealth 15 E&F's financial products.
### The VC branch: addon-VC's REPLACE_OR_CREATE wipes these, tools/regen_addon_vc.py re-adds them.
"""]
    for w in LEVELS:
        out.append(f"INJECT:wealth_{w} = {{\n\tgoods = {{\n\t\t{NEED} = {vals[w]}\n\t}}\n}}\n")
    return "\n".join(out)


def build_loc(lang: str) -> str:
    lines = [f"l_{lang}:"] + [f' {k}:0 "{v}"' for k, v in LOC[lang].items()]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    vals = package_values()
    files = [(OUT_NEED, build_need(), True), (OUT_PKG, build_packages(vals), True)]
    for lang in LOC:
        files.append((HOTFIX / f"localization/{lang}/zz_ef_metal_hoard_l_{lang}.yml", build_loc(lang), True))
    ok = True
    for path, text, bom in files:
        assert text.count("{") == text.count("}"), path
        ok &= HC.emit(path, text, a.check, bom)
    print("  packages: " + ", ".join(f"wealth {w} {vals[w]}" for w in LEVELS))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
