# -*- coding: utf-8 -*-
"""
regen_greys_hc.py -- builds the Grey's x HC+GoB+MoH compatch in `_greys/greys+hc done`.

Pair GR.4. 11 shared keys plus one shared file path, in four groups:

1. GR.4a CRITICAL: _grey_soft_pop's REPLACE_OR_CREATE:is_usfp_active={always=no}
   loads after Hail Columbia's own REPLACE_OR_CREATE:...=yes and silently
   disables the whole mod (every is_usfp_active = yes gate inside it goes
   false). Re-issued here as always=yes, loaded after the whole Grey's pack.

2. GR.4b: five cultures (han, hakka, manchu, min, yue). grey_deeper_cinosphere
   TRY_REPLACEs/REPLACEs all five with full bodies -- a stale pre-1.13 copy in
   places (GR.12: no seal_and_signature_texture) -- and Mandate of Heaven also
   touches all five (INJECT for four, REPLACE for manchu, both adding names to
   the same name-pool sub-blocks cinosphere restates). A full body silently
   drops whatever the earlier mod added to a sub-block it renames. Merge per
   culture: cinosphere's body as base (richer for four of five; the actual
   redesign author for all five), MoH's name-pool tokens unioned in wherever
   cinosphere doesn't already carry them (verbatim-string dedup; both sides
   have working localization for their custom tokens, checked), MoH-only
   sub-blocks (noble_last_names, absent from cinosphere's body for all five)
   carried forward, seal_and_signature_texture restored from vanilla.

3. GR.4c: decree_greener_grass_campaign -- both REPLACE full bodies. HC adds
   an anti-stacking gate to state_trigger (against its own Homestead Act /
   Gold Rush decrees) that soft_pop's later body doesn't carry -- soft_pop
   never touches state_trigger, so it's a straight vanilla-value restatement
   there, and HC's gate is the only real change to merge in. soft_pop's own
   migration-pull numbers and ai_weight redesign stay as-is.

4. GR.4d: one shared file path (`common/history/countries/mon - montenegro.txt`,
   grey_usu vs Gates of Bosphorus -- not REPLACE:-prefixed, so this is a raw
   virtual-filesystem path collision, not a by-key merge) plus four more keys:
   pm_religious_bureaucrats (grey_usu's REPLACE_OR_CREATE restates
   disallowing_laws verbatim from vanilla and drops HC's INJECT of a third
   law), state_trait_columbia_river (grey_usu's TRY_REPLACE, already carrying
   VC's layer in _greys/greys+vc done for GR.1, needs HC's INJECT:modifier
   layer too -- written here as the HC-only version, see the note in that
   build function for the VC+HC-together gap), NAI (checked, NOT a conflict:
   soft_econ/USU/HC each define disjoint sets of defines, and defines merge
   per-key -- no file), law_ethnostate (_grey_soft_pop's TRY_REPLACE never
   names on_activate, so HC's culture-switch effect on enactment survives by
   default -- but merged in explicitly anyway, full-body-safe practice, see
   Правила работы с модами Victoria 3, section 1).

Usage:
    python3 regen_greys_hc.py            # write the compatch
    python3 regen_greys_hc.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

VANILLA = res("../../vic3_mods_out/.vanillaVIC3")
GREYS = res("../../vic3_mods_out/grey_add_alot_of_things")
SOFT_POP = os.path.join(GREYS, "_grey_soft_pop")
SOFT_ECON = os.path.join(GREYS, "_grey_soft_econ")
USU = os.path.join(GREYS, "grey_usu")
CINO = os.path.join(GREYS, "grey_deeper_cinosphere")
HC = res("../../vic3_mods_out/for addon/hailcolumbia")
GOB = res("../../vic3_mods_out/for addon/gatesofbosphorus")
MOH = res("../../vic3_mods_out/for addon/mandateofheaven")
OUT = res("../_greys/greys+hc done")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's x HC+GoB+MoH compatch (GR.4) -- {what}
# Generated by tools/regen_greys_hc.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: ... -> Hail Columbia -> Gates of Bosphorus -> Mandate of Heaven
# -> addon-HC -> ... -> Grey's pack -> THIS.
# Why this file exists: {why}
"""


def write(rel: str, text: str, what: str = "", why: str = "", bom: bool | None = None, raw: bool = False):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = text if raw else (HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n")
    if not raw:
        body = body.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


# ---------------------------------------------------------------------------
# GR.4a -- is_usfp_active
# ---------------------------------------------------------------------------

def build_is_usfp_active():
    hc_text = V.read(os.path.join(HC, "common/scripted_triggers/zz_usfp_compatibility_trigger_overwrites.txt"))
    _, hc_body = V.entry(hc_text, "is_usfp_active", "REPLACE_OR_CREATE:")
    assert "always" in hc_body and "yes" in hc_body, \
        "HC no longer sets is_usfp_active to yes -- re-check GR.4a"
    sp_text = V.read(os.path.join(SOFT_POP, "common/scripted_triggers/00_SPA_mod_compat_active_triggers.txt"))
    _, sp_body = V.entry(sp_text, "is_usfp_active", "REPLACE_OR_CREATE:")
    assert "no" in sp_body, \
        "_grey_soft_pop no longer disables is_usfp_active -- re-check GR.4a, this pair may now be noneed"

    text = "REPLACE_OR_CREATE:is_usfp_active = {\n\talways = yes\n}"
    write("common/scripted_triggers/zz_greys_hc_is_usfp_active.txt", text,
          "re-enable Hail Columbia after _grey_soft_pop clobbers the shared flag",
          "CMF's *_is_active registry pattern is meant for exactly two declarations: CMF itself "
          "(always = no) and the detected mod (always = yes). _grey_soft_pop declares "
          "is_usfp_active = no as a defensive fallback for when Hail Columbia isn't installed, with "
          "no idea where it sits relative to Hail Columbia in the load order -- and the whole Grey's "
          "pack loads after the whole HC+GoB+MoH block, so its REPLACE_OR_CREATE wins outright and "
          "Hail Columbia is switched off entirely: every is_usfp_active = yes gate inside it goes "
          "false, silently, with nothing in error.log. Re-issued here, loaded after the whole pack.")


# ---------------------------------------------------------------------------
# GR.4b -- five cultures
# ---------------------------------------------------------------------------

VANILLA_CULTURES = os.path.join(VANILLA, "common/cultures/00_cultures.txt")
CINO_EDIT = os.path.join(CINO, "common/cultures/zMoG_DS_K_cultures_edit.txt")   # hakka, min, yue
CINO_JNI = os.path.join(CINO, "common/cultures/zz_JNI_EINI_extra_imports.txt")  # han, manchu
MOH_CULTURES = os.path.join(MOH, "common/cultures/moh_cultures.txt")

# name -> (cinosphere file, cinosphere prefix, MoH prefix)
CULTURES = [
    ("han", CINO_JNI, "TRY_REPLACE:", "INJECT:"),
    ("hakka", CINO_EDIT, "TRY_REPLACE:", "INJECT:"),
    ("manchu", CINO_JNI, "TRY_REPLACE:", "REPLACE:"),
    ("min", CINO_EDIT, "TRY_REPLACE:", "INJECT:"),
    ("yue", CINO_EDIT, "TRY_REPLACE:", "INJECT:"),
]

# fields cinosphere alone carries for a given culture, past what MoH ever touches
EXTRA_ONLY = {
    "manchu": ["male_regal_first_names", "regal_last_names"],
}

SCALAR_BLOCK_FIELDS = ["traditions"]          # brace-block scalar fields (V.sub finds these)
SCALAR_LINE_FIELDS = ["color", "religion", "heritage", "language", "name_format"]  # bare "k = v" lines
LIST_FIELDS = ["male_common_first_names", "female_common_first_names", "common_last_names", "noble_last_names"]


def scalar_line(body: str, name: str) -> str | None:
    """Value text of a bare single-line 'name = value' field at depth 0 (no braces of its own)."""
    m = re.search(r'(?m)^[ \t]*' + re.escape(name) + r'[ \t]*=[ \t]*(.+?)[ \t]*$', body)
    return m.group(1) if m else None


def list_tokens(block: str | None) -> list[str]:
    if block is None:
        return []
    inner = block.strip()
    assert inner.startswith("{") and inner.endswith("}"), f"not a brace block: {inner[:40]!r}"
    inner = inner[1:-1]
    toks = []
    for line in inner.split("\n"):
        toks.extend(line.split("#", 1)[0].split())
    return toks


def render_list(name: str, tokens: list[str]) -> str:
    return f"\t{name} = {{\n" + "".join(f"\t\t{t}\n" for t in tokens) + "\t}"


def build_one_culture(name: str, cino_path: str, cino_prefix: str, moh_prefix: str) -> str:
    vtext = V.read(VANILLA_CULTURES)
    _, vbody = V.entry(vtext, name)
    ctext = V.read(cino_path)
    cdecl, cbody = V.entry(ctext, name, cino_prefix)
    mtext = V.read(MOH_CULTURES)
    mdecl, mbody = V.entry(mtext, name, moh_prefix)

    notes = [f"# {name}: base cinosphere {cdecl.split('=')[0].strip()} "
             f"({len(cbody.splitlines())} lines); MoH {mdecl.split('=')[0].strip()} "
             f"({len(mbody.splitlines())} lines)"]
    out = []

    for f in SCALAR_LINE_FIELDS:
        val = scalar_line(cbody, f)
        src = "cinosphere"
        if val is None:
            val = scalar_line(vbody, f)
            src = "vanilla (cinosphere's TRY_REPLACE doesn't name it)"
            notes.append(f"#   {f}: restored from vanilla")
        assert val is not None, f"{name}.{f}: missing from both cinosphere and vanilla"
        out.append(f"\t{f} = {val}")

    for f in SCALAR_BLOCK_FIELDS:
        blk = V.sub(cbody, f) or V.sub(vbody, f)
        assert blk is not None, f"{name}.{f}: missing from both cinosphere and vanilla"
        out.append(f"\t{f} = {blk}")

    # obsessions -- union of cinosphere's and MoH's tokens, when either declares it
    cobs, mobs = V.sub(cbody, "obsessions"), V.sub(mbody, "obsessions")
    if cobs is not None or mobs is not None:
        base = list_tokens(cobs)
        extra = [t for t in list_tokens(mobs) if t not in base]
        if extra:
            notes.append(f"#   obsessions: MoH adds {extra}, unioned in")
        toks = base + extra
        if toks:
            out.append(render_list("obsessions", toks))

    for f in LIST_FIELDS:
        cblk, mblk = V.sub(cbody, f), V.sub(mbody, f)
        if cblk is None and mblk is None:
            continue
        base = list_tokens(cblk)
        moh_toks = list_tokens(mblk)
        missing = [t for t in moh_toks if t not in base]
        if cblk is None:
            notes.append(f"#   {f}: cinosphere doesn't name it, MoH's {len(moh_toks)} names carried as-is")
        elif missing:
            notes.append(f"#   {f}: {len(missing)} of MoH's names aren't in cinosphere's list, unioned in")
        out.append(render_list(f, base + missing))

    for f in EXTRA_ONLY.get(name, []):
        blk = V.sub(cbody, f)
        assert blk is not None, f"{name}.{f}: cinosphere-only field is gone -- re-check GR.4b"
        out.append(f"\t{f} = {blk}")

    eth = V.sub(cbody, "ethnicities") or V.sub(vbody, "ethnicities")
    assert eth is not None, f"{name}.ethnicities: missing everywhere"
    out.append(f"\tethnicities = {eth}")

    graphics = scalar_line(cbody, "graphics") or scalar_line(vbody, "graphics")
    assert graphics is not None, f"{name}.graphics: missing everywhere"
    out.append(f"\tgraphics = {graphics}")

    seal = scalar_line(vbody, "seal_and_signature_texture")
    assert seal is not None, f"{name}: vanilla itself has no seal_and_signature_texture to restore from"
    if scalar_line(cbody, "seal_and_signature_texture") is None:
        notes.append("#   seal_and_signature_texture: restored from vanilla "
                      "(GR.12 -- cinosphere is a stale pre-1.13 body here)")
    out.append(f"\tseal_and_signature_texture = {seal}")

    return "\n".join(notes) + "\nREPLACE_OR_CREATE:" + name + " = {\n" + "\n".join(out) + "\n}"


def build_cultures():
    bodies = [build_one_culture(*c) for c in CULTURES]
    text = "\n\n".join(bodies)
    write("common/cultures/zz_greys_hc_cultures.txt", text,
          "merge grey_deeper_cinosphere x Mandate of Heaven on five culture records",
          "cinosphere TRY_REPLACEs/REPLACEs han, hakka, manchu, min and yue with full bodies; MoH "
          "INJECTs (REPLACEs for manchu) names into the same sub-blocks, and loads earlier, so its "
          "additions are silently dropped when cinosphere's full body restates the same sub-block "
          "name. Per culture: cinosphere's body as the base, MoH's name-pool tokens unioned in "
          "wherever cinosphere's list doesn't already carry them (both sides' custom tokens have "
          "working localization, checked), MoH-only sub-blocks carried forward as-is, "
          "seal_and_signature_texture restored from vanilla where cinosphere's body omits it (GR.12).")


# ---------------------------------------------------------------------------
# GR.4c -- decree_greener_grass_campaign
# ---------------------------------------------------------------------------

def build_decree():
    vtext = V.read(os.path.join(VANILLA, "common/decrees/00_decree.txt"))
    _, vbody = V.entry(vtext, "decree_greener_grass_campaign")
    hctext = V.read(os.path.join(HC, "common/decrees/usfp_decrees_overwrite.txt"))
    _, hcbody = V.entry(hctext, "decree_greener_grass_campaign", "REPLACE:")
    sptext = V.read(os.path.join(SOFT_POP, "common/decrees/zzz_MoG_SPA_greener_grass_decree.txt"))
    _, spbody = V.entry(sptext, "decree_greener_grass_campaign", "REPLACE:")

    hc_trigger = V.sub(hcbody, "state_trigger")
    sp_trigger = V.sub(spbody, "state_trigger")
    van_trigger = V.sub(vbody, "state_trigger")
    assert hc_trigger is not None and "usfp_homestead_act_modifier" in hc_trigger, \
        "HC's anti-stacking gate is gone from state_trigger -- re-check GR.4c"
    assert sp_trigger is not None and re.sub(r"\s+", " ", sp_trigger).strip() == \
        re.sub(r"\s+", " ", van_trigger).strip(), \
        "_grey_soft_pop now customizes state_trigger too -- re-check GR.4c, this merge assumes it's still vanilla's"

    merged = V.replace_sub(spbody, "state_trigger", hc_trigger)
    text = ("# base: _grey_soft_pop's REPLACE (its own migration-pull numbers and ai_weight redesign).\n"
            "# HC's state_trigger layer merged in: a gate against stacking Greener Grass with HC's own\n"
            "# Homestead Act / Gold Rush decrees. soft_pop's body never touches state_trigger (its copy\n"
            "# is verbatim vanilla), so HC's gate would otherwise be dropped silently.\n"
            "REPLACE_OR_CREATE:decree_greener_grass_campaign = {" + merged + "}")
    write("common/decrees/zz_greys_hc_greener_grass.txt", text,
          "carry HC's decree-stacking gate on top of soft_pop's decree redesign",
          "Both HC and _grey_soft_pop REPLACE this vanilla decree with full bodies. HC's only change "
          "from vanilla is one NOR gate added to state_trigger; soft_pop's is an unrelated rebalance "
          "of the migration-pull modifier and the AI-weight branches, restating state_trigger with "
          "vanilla's own content. Grey's loads later, so its full body wins and HC's gate is gone, "
          "with nothing in error.log.")


# ---------------------------------------------------------------------------
# GR.4d -- shared file path: common/history/countries/mon - montenegro.txt
# ---------------------------------------------------------------------------

def build_montenegro():
    gob_path = os.path.join(GOB, "common/history/countries/mon - montenegro.txt")
    usu_path = os.path.join(USU, "common/history/countries/mon - montenegro.txt")
    gob_text = V.read(gob_path)
    usu_text = V.read(usu_path)

    assert "set_military_wage_level = low" in usu_text, \
        "USU's military-wage line is gone -- re-check GR.4d"
    assert "g:usu_logistics" in usu_text, \
        "USU no longer redirects the tariff good to g:usu_logistics -- re-check GR.4d"
    assert "goods = g:merchant_marine" in gob_text, \
        "GoB no longer names g:merchant_marine on this tariff line -- re-check GR.4d"

    merged = gob_text
    before = merged
    merged = merged.replace(
        "set_import_tariff_level = {\n\t\t\t\tgoods = g:merchant_marine",
        "set_import_tariff_level = { # USU -- Montenegro is landlocked, its Trade Center needs "
        "logistics, not Merchant Marine\n\t\t\t\tgoods = g:usu_logistics",
        1,
    )
    assert merged != before and "g:usu_logistics" in merged, \
        "GoB's import-tariff block indentation changed -- the merchant_marine substitution didn't match, re-check GR.4d"

    before = merged
    merged = merged.replace(
        "set_tax_level = very_low\n",
        "set_tax_level = very_low\n\t\t\tset_military_wage_level = low # USU\n",
        1,
    )
    assert merged != before, \
        "GoB's set_tax_level line changed -- the anchor for USU's wage line didn't match, re-check GR.4d"

    header = (
        "# Grey's x HC+GoB+MoH compatch (GR.4) -- reconcile the shared file path\n"
        "# common/history/countries/mon - montenegro.txt\n"
        "# Generated by tools/regen_greys_hc.py on " + DATE + ". Do not hand-edit: the next run\n"
        "# overwrites this file. Change the generator instead.\n"
        "#\n"
        "# grey_usu and Gates of Bosphorus both ship a file at this exact relative path. It is not\n"
        "# REPLACE:-prefixed -- this is a raw virtual-filesystem path collision, not a by-key merge:\n"
        "# whichever mod loads last provides the ONLY copy the game reads, the earlier one is\n"
        "# invisible, not merged. grey_usu (Grey's block) loads after the whole HC+GoB+MoH block, so\n"
        "# its 94-line body wins outright and GoB's 102-line body -- three new starting techs, a new\n"
        "# journal entry (je_balkfm_mon_prince_bishopric), GoB's own IP3 state-formation integration,\n"
        "# and an else-branch event (balkfm_montenegro.001/.019) -- never runs at all.\n"
        "#\n"
        "# Base here: GoB's body (vanilla is 93 lines, GoB's is the substantial, deliberate rework;\n"
        "# USU's 94-line delta from vanilla is one new line and one changed good). USU's own two\n"
        "# changes layered on top: landlocked Montenegro's first Trade Center tariff good redirected\n"
        "# from g:merchant_marine to USU's own g:usu_logistics, and set_military_wage_level = low\n"
        "# added after set_tax_level.\n\n"
    )
    text = header + merged.lstrip("﻿")
    write("common/history/countries/mon - montenegro.txt", text, raw=True)


# ---------------------------------------------------------------------------
# GR.4d -- pm_religious_bureaucrats
# ---------------------------------------------------------------------------

def build_pm_religious_bureaucrats():
    usu_text = V.read(os.path.join(USU, "common/production_methods/yMoG_USU_govadmin_other_pms.txt"))
    _, usu_body = V.entry(usu_text, "pm_religious_bureaucrats", "REPLACE_OR_CREATE:")
    hc_text = V.read(os.path.join(HC, "common/production_methods/usfp_pm_overrides.txt"))
    _, hc_body = V.entry(hc_text, "pm_religious_bureaucrats", "INJECT:")
    van_text = V.read(os.path.join(VANILLA, "common/production_methods/07_government.txt"))
    _, van_body = V.entry(van_text, "pm_religious_bureaucrats")

    usu_dl = V.sub(usu_body, "disallowing_laws")
    van_dl = V.sub(van_body, "disallowing_laws")
    assert usu_dl is not None and van_dl is not None and usu_dl.split() == van_dl.split(), \
        "USU's disallowing_laws on pm_religious_bureaucrats no longer matches vanilla verbatim -- re-check GR.4d"
    hc_law = "law_usfp_nominal_separation"
    hc_dl = V.sub(hc_body, "disallowing_laws")
    assert hc_dl is not None and hc_law in hc_dl, "HC's injected law changed -- re-check GR.4d"

    inner = usu_dl.strip()
    assert inner.startswith("{") and inner.endswith("}")
    merged_dl = inner[:-1].rstrip() + f"\n\t\t{hc_law}\n\t}}"
    merged = V.replace_sub(usu_body, "disallowing_laws", merged_dl)

    text = (
        "# base: grey_usu's REPLACE_OR_CREATE (halves clergy/bureaucrat employment, 250 -> 125).\n"
        "# disallowing_laws is a verbatim copy of vanilla's two laws -- HC's INJECT of a third\n"
        "# (law_usfp_nominal_separation) is added back here, since USU's full body would otherwise\n"
        "# silently drop it.\n"
        "REPLACE_OR_CREATE:pm_religious_bureaucrats = {" + merged + "}"
    )
    write("common/production_methods/zz_greys_hc_religious_bureaucrats.txt", text,
          "restore HC's disallowing_laws entry on top of USU's rebalanced pm_religious_bureaucrats",
          "grey_usu's REPLACE_OR_CREATE re-states disallowing_laws verbatim from vanilla (its own "
          "edit is only to building_modifiers) and loads later than HC's INJECT of a third law, so "
          "the third law is gone with nothing in error.log.")


# ---------------------------------------------------------------------------
# GR.4d -- state_trait_columbia_river
# ---------------------------------------------------------------------------

def build_state_trait_columbia_river():
    usu_text = V.read(os.path.join(USU, "common/state_traits/yMoG_USU_overwrite_river_state_traits.txt"))
    _, usu_body = V.entry(usu_text, "state_trait_columbia_river", "TRY_REPLACE:")
    hc_text = V.read(os.path.join(HC, "common/state_traits/usfp_state_traits.txt"))
    _, hc_body = V.entry(hc_text, "state_trait_columbia_river", "INJECT:")

    hc_mod = V.sub(hc_body, "modifier")
    hc_field = "building_group_bg_logging_throughput_add = 0.30"
    assert hc_mod is not None and hc_field in hc_mod, "HC's injected modifier field changed -- re-check GR.4d"

    usu_mod = V.sub(usu_body, "modifier")
    assert usu_mod is not None
    inner = usu_mod.strip()
    merged_mod = inner[:-1].rstrip() + f"\n\t\t{hc_field}\t# HC\n\t}}"
    merged = V.replace_sub(usu_body, "modifier", merged_mod)

    text = (
        "# base: grey_usu's TRY_REPLACE. HC's INJECT:modifier layer merged in\n"
        "# (building_group_bg_logging_throughput_add).\n"
        "#\n"
        "# NOTE -- this is the HC-only version of this record. The same record already carries VC's\n"
        "# layer for GR.1 in _greys/greys+vc done/common/state_traits/zz_gvc_state_traits.txt, and\n"
        "# that file does not carry HC's layer. Neither file alone is correct for decision #11's\n"
        "# 'both VC and HC together' branch (\"for madmen\") -- tracked as a follow-up in the plan,\n"
        "# not solved here: defining the merged record in both loaded compachs at once would just\n"
        "# recreate the same last-write-wins conflict this fix exists to close.\n"
        "REPLACE_OR_CREATE:state_trait_columbia_river = {" + merged + "}"
    )
    write("common/state_traits/zz_greys_hc_state_traits.txt", text,
          "carry HC's logging-throughput layer on top of USU's state_trait_columbia_river",
          "grey_usu's TRY_REPLACE restates the modifier block and loads later than HC's INJECT, so "
          "HC's building_group_bg_logging_throughput_add is gone with nothing in error.log.")


# ---------------------------------------------------------------------------
# GR.4d -- NAI (checked, not a conflict)
# ---------------------------------------------------------------------------

def check_nai_not_conflict():
    sea = V.read(os.path.join(SOFT_ECON, "common/defines/zzz_MoG_SEA_def.txt"))
    usu_d = V.read(os.path.join(USU, "common/defines/zzz_MoG_USU_def.txt"))
    hc_d = V.read(os.path.join(HC, "common/defines/usfp_defines.txt"))
    _, sea_nai = V.entry(sea, "NAI")
    _, usu_nai = V.entry(usu_d, "NAI")
    _, hc_nai = V.entry(hc_d, "NAI")

    def keys(body):
        return {m for m in re.findall(r'(?m)^\s*([A-Z][A-Z0-9_]*)\s*=', body)}

    sea_k, usu_k, hc_k = keys(sea_nai), keys(usu_nai), keys(hc_nai)
    overlap = (sea_k & hc_k) | (usu_k & hc_k) | (sea_k & usu_k)
    assert overlap == set(), \
        f"NAI keys now overlap between Grey's and HC: {sorted(overlap)} -- GR.4 needs a real file for this"
    print(f"  NAI: checked, no conflict. soft_econ {len(sea_k)} keys, grey_usu {len(usu_k)} keys, "
          f"HC {len(hc_k)} keys {sorted(hc_k)} -- all disjoint, defines merge per-key. No file written.")


# ---------------------------------------------------------------------------
# GR.4d -- law_ethnostate
# ---------------------------------------------------------------------------

def build_law_ethnostate():
    sp_text = V.read(os.path.join(SOFT_POP, "common/laws/zMoG_SPA_citizenship.txt"))
    _, sp_body = V.entry(sp_text, "law_ethnostate", "TRY_REPLACE:")
    hc_text = V.read(os.path.join(HC, "common/laws/usfp_law_overrides.txt"))
    _, hc_body = V.entry(hc_text, "law_ethnostate", "INJECT:")

    assert V.sub(sp_body, "on_activate") is None, \
        "_grey_soft_pop now names on_activate on law_ethnostate too -- re-check GR.4d, this merge assumes it doesn't"
    hc_activate = V.sub(hc_body, "on_activate")
    assert hc_activate is not None and "cu:dixie" in hc_activate, \
        "HC's on_activate content changed -- re-check GR.4d"

    anchor = "\ton_enact = {"
    assert sp_body.count(anchor) == 1, \
        f"expected exactly one 'on_enact = {{' in soft_pop's body, found {sp_body.count(anchor)} -- re-check GR.4d"
    merged = sp_body.replace(anchor, f"\ton_activate = {hc_activate}\n\n{anchor}", 1)

    text = (
        "# base: _grey_soft_pop's TRY_REPLACE (progressiveness -100, CMF is_visible gate, its own\n"
        "# acceptance_modifier rebalance). HC's on_activate layer merged in: switches the USA's\n"
        "# primary culture from cu:afro_american to cu:dixie on enactment. soft_pop's body never\n"
        "# names on_activate, so under a strict 'REPLACE only patches named sub-blocks' reading HC's\n"
        "# effect already survives -- merged in explicitly anyway, since that reading is still an open\n"
        "# question (Правила работы с модами Victoria 3, section 1) and a full body is correct either way.\n"
        "REPLACE_OR_CREATE:law_ethnostate = {" + merged + "}"
    )
    write("common/laws/zz_greys_hc_ethnostate.txt", text,
          "carry HC's on_activate culture-switch effect explicitly on soft_pop's law_ethnostate body",
          "Safe-practice full body per the open REPLACE-semantics question: soft_pop's TRY_REPLACE "
          "doesn't name on_activate, so this is very likely a no-op restatement rather than a rescue -- "
          "written anyway so correctness doesn't depend on which reading turns out right.")


# ---------------------------------------------------------------------------

def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_hc.py -> {OUT}")
    steps = (
        ("is_usfp_active (GR.4a)", build_is_usfp_active),
        ("five cultures (GR.4b)", build_cultures),
        ("decree_greener_grass_campaign (GR.4c)", build_decree),
        ("mon - montenegro.txt (GR.4d)", build_montenegro),
        ("pm_religious_bureaucrats (GR.4d)", build_pm_religious_bureaucrats),
        ("state_trait_columbia_river (GR.4d)", build_state_trait_columbia_river),
        ("NAI, checked (GR.4d)", check_nai_not_conflict),
        ("law_ethnostate (GR.4d)", build_law_ethnostate),
    )
    for name, fn in steps:
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current Grey's / HC+GoB+MoH sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
