"""
regen_llwa_vc.py -- builds the LLWA x VC compatch in `_llwa/llwa+vc done`.

The pair: VC loads early (megapack -> VC -> addon-VC -> HC+GoB+MoH ->
addon-HC), LLWA loads last in the target chain. Machine matrix: 6 shared
keys (LLWA.3/plan) -- 3 in common/ai_strategies, 3 in
common/production_methods.

## production_methods (this generator)

pm_no_passenger_trains, pm_steel_passenger_carriages,
pm_wooden_passenger_carriages. VC injects the SAME thing into all three:
`INJECT:building_modifiers = { unscaled = { building_job_attractiveness_mult
= 2 } }`. LLWA's REPLACE: on these three (`LLWA_rails.txt`, same file as the
TGR pair) is a bare full body that never declares `building_modifiers.
unscaled` at all -- on pm_no_passenger_trains it has no building_modifiers
block whatsoever. Restored here the same way as the TGR restore: LLWA's own
body stays the base, VC's addition is spliced in.

These three keys are ALSO shared with TGR (10-key machine matrix in
LLWA.1/`_llwa/llwa+tgr done`) -- per the plan ("один файл на обе пары не
делать") they are written exactly once, here, not duplicated in the TGR
compatch. TGR's own numeric rebalance on these three is a genuine second
author's design choice on the SAME fields LLWA also rebalances (not an
absent key like VC's `unscaled`), so per the "LLWA loads last, LLWA's
numbers win" rule from the TGR compatch it is not restored anywhere --
there is nothing of TGR's left to write for these three once VC's addition
is accounted for.

## ai_strategies (NOT this generator)

`ai_strategy_great_reforms`, `_meiji_restoration`, `_tanzimat_reforms` are
the same three keys LLWA shares with KAI (LLWA.2) -- LLWA's stale
`03_political_strategies.txt` wipes an already-closed KAI x VC three-way
merge (`_vc/kai+vc done`) on all three. That restoration is generated by
`tools/regen_llwa_kai.py` into `_llwa/llwa+kai done` (it needs KAI's own
file too, and the vanilla-restore file both pairs depend on lives there) --
see that folder's README for the ai_strategies half of this pair.

Usage:
    python3 regen_llwa_vc.py            # write the compatch
    python3 regen_llwa_vc.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

LLWA = res("../../vic3_mods_out/llwa")
VC = res("../../vic3_mods_out/VC")
OUT = res("../_llwa/llwa+vc done")

HEADER = """# LLWA x VC compatch -- {what}
# Generated by tools/regen_llwa_vc.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: VC -> ... -> LLWA -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

KEYS = [
    "pm_no_passenger_trains",
    "pm_steel_passenger_carriages",
    "pm_wooden_passenger_carriages",
]


def block(lines: list[str], i: int) -> tuple[list[str], int]:
    depth = 0
    started = False
    for j in range(i, len(lines)):
        code = lines[j].split("#", 1)[0]
        depth += code.count("{") - code.count("}")
        if "{" in code:
            started = True
        if started and depth <= 0:
            return lines[i:j + 1], j + 1
    return lines[i:], len(lines)


def record(path: str, key: str) -> list[str] | None:
    lines = read_lines(path)
    pat = re.compile(r"^(?:[A-Z_]+:)?" + re.escape(key) + r"\s*=\s*\{")
    for i, raw in enumerate(lines):
        if pat.match(raw.split("#", 1)[0].lstrip("﻿")):
            body, _ = block(lines, i)
            body[0] = re.sub(r"^﻿?(?:[A-Z_]+:)?", "", body[0])
            return body
    return None


def top_subblocks(body: list[str]) -> dict[str, tuple[int, int]]:
    out: dict[str, tuple[int, int]] = {}
    depth = 0
    i = 0
    n = len(body)
    while i < n:
        code = body[i].split("#", 1)[0]
        if i == 0:
            depth += code.count("{") - code.count("}")
            i += 1
            continue
        if depth == 1:
            m = re.match(r"^\s*([A-Za-z0-9_]+)\s*=\s*\{", code)
            if m:
                sub, j = block(body, i)
                out[m.group(1)] = (i, j - 1)
                depth += sum(c.count("{") - c.count("}") for c in
                             [x.split("#", 1)[0] for x in body[i:j]])
                i = j
                continue
        depth += code.count("{") - code.count("}")
        i += 1
    return out


def extract_nested(body: list[str], parent: str, nested: str) -> list[str] | None:
    subs = top_subblocks(body)
    if parent not in subs:
        return None
    lo, hi = subs[parent]
    parent_body = body[lo:hi + 1]
    inner = top_subblocks(parent_body)
    if nested not in inner:
        return None
    ilo, ihi = inner[nested]
    return parent_body[ilo + 1:ihi]


def dedent(lines: list[str]) -> list[str]:
    non_empty = [l for l in lines if l.strip()]
    if not non_empty:
        return lines
    base = min(len(l) - len(l.lstrip("\t")) for l in non_empty)
    return [l[base:] if l.startswith("\t" * base) else l for l in lines]


def insert_nested(body: list[str], parent: str, nested: str, nested_lines: list[str]) -> list[str]:
    nested_lines = dedent(nested_lines)
    subs = top_subblocks(body)
    out = list(body)
    if parent in subs:
        lo, hi = subs[parent]
        assert "\t\t" + nested + " = {" not in [l.rstrip() for l in out[lo:hi + 1]], (
            f"{parent}.{nested} already present -- would duplicate")
        insertion = ["\t\t" + nested + " = {"] + ["\t\t\t" + l for l in nested_lines] + ["\t\t}"]
        out = out[:hi] + insertion + out[hi:]
    else:
        insertion = ["\t" + parent + " = {", "\t\t" + nested + " = {"] + \
                    ["\t\t\t" + l for l in nested_lines] + ["\t\t}", "\t}"]
        out = out[:-1] + insertion + out[-1:]
    return out


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_rails():
    llwa_f = os.path.join(LLWA, "common/production_methods/LLWA_rails.txt")
    vc_f = os.path.join(VC, "common/production_methods/joi_methods.txt")
    assert os.path.isfile(llwa_f), "LLWA_rails.txt not found -- did LLWA rename it?"
    assert os.path.isfile(vc_f), "VC's joi_methods.txt not found -- did VC rename it?"

    out_records: list[str] = []
    for key in KEYS:
        llwa_body = record(llwa_f, key)
        assert llwa_body, f"LLWA has no {key} in LLWA_rails.txt -- re-check the key list"
        vc_body = record(vc_f, key)
        assert vc_body, f"VC has no {key} in joi_methods.txt -- re-check the key list"

        unscaled_lines = extract_nested(vc_body, "building_modifiers", "unscaled")
        assert unscaled_lines is not None, (
            f"VC's {key} no longer INJECTs building_modifiers.unscaled -- "
            f"the thing this compatch restores may already be gone, re-check")
        joined = " ".join(l.split("#", 1)[0].strip() for l in unscaled_lines if l.strip())
        assert re.sub(r"\s+", "", joined) == "building_job_attractiveness_mult=2", (
            f"VC's {key} unscaled block is no longer just "
            f"building_job_attractiveness_mult=2, got: {unscaled_lines!r} -- re-check the merge")

        llwa_subs = top_subblocks(llwa_body)
        if "building_modifiers" in llwa_subs:
            existing = extract_nested(llwa_body, "building_modifiers", "unscaled")
            assert existing is None, (
                f"LLWA's {key}.building_modifiers already has an unscaled "
                f"sub-block -- this generator assumes a pure addition, re-check")

        new_body = insert_nested(llwa_body, "building_modifiers", "unscaled", unscaled_lines)
        text = "REPLACE_OR_CREATE:" + "\n".join(new_body)
        out_records.append(text)

    write("common/production_methods/zz_llwa_vc_rails.txt",
          "\n\n".join(out_records),
          "restore VC's job-attractiveness modifier on three rail production methods",
          "LLWA's REPLACE: on these three records (loading last in the target "
          "chain) is a bare full body -- on pm_no_passenger_trains there is no "
          "building_modifiers block at all -- so VC's `INJECT:building_modifiers "
          "= { unscaled = { building_job_attractiveness_mult = 2 } }` is "
          "silently dropped. LLWA's own numbers (where it has any) are NOT "
          "touched. These three records are ALSO shared with TGR (see "
          "_llwa/llwa+tgr done) -- TGR's own numeric rebalance on them is not "
          "restored anywhere (LLWA loads last, LLWA's numbers win, same rule "
          "as the TGR compatch), so there is nothing of TGR's left to add here "
          "and this key isn't written twice across the two compaches.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category = os.path.dirname(rel)
        depth = 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_llwa_vc.py -> {OUT}")
    for name, fn in (
        ("rails", build_rails),
    ):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current LLWA / VC sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
