#!/usr/bin/env python3
"""
E&F's buy_currency_privat_bank (01_economic_scripted_effects.txt): a private bank buys a currency for
metal when the key rate rises (privat_bank_buy_currency, monthly under rise_base_rate). The buyer is
random_in_global_list over global_arbitrage_bank_variable_list_ordered -- the bank COMPANIES (Rothschild,
JP Morgan, ...), which do not exist in the first years. Empty list -> no scope:buyer, and the body runs on
anyway: "Undefined event target 'buyer'", money_value / is_weak_currency on a 'none' scope (run 26, 2.10:
~800 + ~1700 errors in 3 minutes; the key rate rises more often since the cover is valued at parity).

The same fix as zz_ef_currency_scope_guard_fix.txt (sell side): E&F's body, everything after the buyer is
picked wrapped in `if = { limit = { exists = scope:buyer } }`.

Writes _ef/ef hotfix 1.13/common/scripted_effects/zz_ef_privat_bank_buy_guard.txt
(key-level REPLACE_OR_CREATE: regenerate after an E&F update).

Usage:
    py tools/regen_ef_privat_bank_buy_guard.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))
SRC = res(r"..\..\vic3_mods_out\E&F\common\scripted_effects\01_economic_scripted_effects.txt")
OUT = res(r"..\_ef\ef hotfix 1.13\common\scripted_effects\zz_ef_privat_bank_buy_guard.txt")
NAME = "buy_currency_privat_bank"


def match(text, i):
    d = 0
    for j in range(i, len(text)):
        d += {"{": 1, "}": -1}.get(text[j], 0)
        if d == 0:
            return j
    raise AssertionError


def main():
    t = open(SRC, encoding="utf-8-sig").read()
    m = re.search(rf"^{NAME} = \{{", t, re.M)
    assert m
    i = t.index("{", m.start())
    body = t[i + 1:match(t, i)]
    # the buyer pick: random_in_global_list = { ... save_scope_as = buyer }
    r = re.search(r"\n\trandom_in_global_list = \{", body)
    assert r, "random_in_global_list moved"
    k = match(body, body.index("{", r.start()))
    pick = body[:k + 1]
    assert "global_arbitrage_bank_variable_list_ordered" in pick and "save_scope_as = buyer" in pick
    rest = body[k + 1:]
    rest = "\n".join(("\t" + ln) if ln.strip() else ln for ln in rest.split("\n"))
    out = ("# GENERATED by tools/regen_ef_privat_bank_buy_guard.py -- do not edit by hand.\n"
           "# E&F's buy_currency_privat_bank with an empty bank list guarded (exists = scope:buyer).\n"
           "# !! MAINTENANCE !! Key-level REPLACE_OR_CREATE of E&F's effect: regenerate after an E&F update.\n\n"
           f"REPLACE_OR_CREATE:{NAME} = {{{pick}\n\tif = {{\n\t\tlimit = {{ exists = scope:buyer }}{rest}\n\t}}\n}}\n")
    assert out.count("{") == out.count("}")
    with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write(out)
    print("ok", OUT)


if __name__ == "__main__":
    main()
