#!/usr/bin/env python3
"""
GR.21 -- GUI merge E&F x CMF (Multi-line Production Methods and CMF's panels).

Why this exists
---------------
E&F ships its own copies of five vanilla GUI types (building browser rows,
the goods-state input/output row, the construction row of the map list, the
mobilization widget). They are vanilla bodies with 0-4 lines of E&F edits.
CMF (Community Mod Framework, which carries MPM -- Multi-line Production
Methods) redefines the same five types with its own features: multi-line
production-method areas, hover states, CMF hooks. A type defined twice is not
an error: the later definition in load order wins -- and E&F loads after CMF,
so E&F's near-vanilla copies silently switch CMF's features off in all five.

What this does
--------------
Re-issues CMF's five types verbatim, from files that load after E&F (the
megapacks), and carries E&F's edits over where they still mean something:
  * E&F hides its own financial production-method groups (market liquidity,
    private-ownership stocks) from two lists -- the building browser's bulk
    PM change and the goods panel's building rows. In CMF's version the
    browser's PM list lives in the MPM template MPM_pms_area_building_type
    (used by the browser only), so that template is re-issued with E&F's
    filter; the goods row gets it on its PM item widget.
  * NOT carried over: E&F's `[GetCustom('currency_symbol')]` in place of
    `@money!` (E&F itself went back to `@money!` in its budget panel in 2.09,
    and the currency_symbol lookups are the log spam in the plan's E&F bug
    list); E&F's older piracy and expand-tooltip lines (older vanilla, CMF
    has the current ones).
E&F's own `gui/00_MPM_building_details_panel.gui` is not touched: it is CMF's
current file plus one E&F line (checked 2026-09-25).

GUI @constants are file-local, so every output file is one CMF source file's
types plus that file's @constants.

Output: `_ef/ef+cmf done/gui/zz_ef_cmf_*.gui`, copied into every megapack
that carries E&F (`megapack`, `megapack no t&r`, `megapack no tgr`).

Usage:
    py tools/regen_ef_cmf_gui.py            # write
    py tools/regen_ef_cmf_gui.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

WS = r"C:\Games\Steam\steamapps\workshop\content\529340"
CMF = os.path.join(WS, "3385002128")
EF = os.path.join(WS, "3143591632")
OUT = res("../_ef/ef+cmf done")
MEGAPACKS = [res("../__megapacks/megapack"), res("../__megapacks/megapack no t&r"),
             res("../__megapacks/megapack no tgr")]
DATE = "2026-09-25"

EF_BROWSER = os.path.join(EF, "gui/ef_dev_and_custom_windows/maj/Essential/building_browser_panel.gui")
EF_GOODS = os.path.join(EF, "gui/ef_dev_and_custom_windows/maj/Essential/goods_state_panel.gui")

# output file -> (CMF source file, namespace, [types])
JOBS = {
    "gui/zz_ef_cmf_building_browser.gui": ("gui/00_MPM_building_browser_panel.gui", "building_browser_panel_types",
                                           ["building_browser_building_item", "building_browser_building_type_item"]),
    "gui/zz_ef_cmf_mpm_types.gui": ("gui/MPM_custom_types.gui", "MPM_types", ["MPM_pms_area_building_type"]),
    "gui/zz_ef_cmf_goods_state.gui": ("gui/00_MPM_goods_state_panel.gui", "goods_state_panel",
                                      ["goods_state_panel_input_output_item"]),
    "gui/zz_ef_cmf_map_list.gui": ("gui/00_MPM_map_list_panel.gui", "map_list_panel_types",
                                   ["construction_interaction_item_full"]),
    "gui/zz_ef_cmf_military.gui": ("gui/00_com_gui_panel_military.gui", "mobilization_options",
                                   ["mobilization_widget"]),
}

HEADER = """# GR.21 -- E&F x CMF GUI merge: {what}
# Generated by tools/regen_ef_cmf_gui.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: CMF -> ... -> E&F -> THIS (megapack). A GUI type defined twice:
# the later definition wins. E&F's near-vanilla copies of these types would
# otherwise switch CMF's (MPM's) versions off. Source: CMF {src}, verbatim
# except where marked ### E&F.
"""

FILTER_RE = re.compile(r'visible = "\[Not\(Or\((?:Or\()*EqualTo_string\(ProductionMethodGroup\.GetKey,\'pmg_market_liquidity\'\).*?\)\]"')


def type_block(text: str, name: str) -> str:
    m = re.search(r"(?m)^[ \t]*type\s+" + re.escape(name) + r"\s*=", text)
    assert m, f"type {name} not found -- did CMF rename it?"
    i = text.index("{", m.end())
    d = 0
    for j in range(i, len(text)):
        if text[j] == "{":
            d += 1
        elif text[j] == "}":
            d -= 1
            if d == 0:
                break
    start = text.rfind("\n", 0, m.start()) + 1
    return text[start:j + 1]


def ef_filter() -> str:
    a = FILTER_RE.findall(V.read(EF_BROWSER))
    b = FILTER_RE.findall(V.read(EF_GOODS))
    assert len(a) == 1 and len(b) == 1, f"E&F's PM filter: expected one per file, got {len(a)}/{len(b)} -- re-check"
    assert a[0] == b[0], "E&F's PM filter differs between the browser and the goods panel -- re-check"
    return a[0]


def insert_after(block: str, anchor_re: str, line: str, what: str) -> str:
    m = list(re.finditer(anchor_re, block))
    assert len(m) == 1, f"{what}: anchor found {len(m)} times -- CMF changed shape, re-check"
    m = m[0]
    indent = re.match(r"[ \t]*", block[block.rfind("\n", 0, m.end()) + 1:]).group(0)
    return block[:m.end()] + "\n" + indent + "### E&F: hide E&F's financial PM groups in this list\n" + indent + line + block[m.end():]


VANILLA = r"C:\Games\Steam\steamapps\common\Victoria 3\game"
EF_TYPES = {  # type -> (E&F file, vanilla file)
    "building_browser_building_item": (EF_BROWSER, "gui/building_browser_panel.gui"),
    "building_browser_building_type_item": (EF_BROWSER, "gui/building_browser_panel.gui"),
    "goods_state_panel_input_output_item": (EF_GOODS, "gui/goods_state_panel.gui"),
    "construction_interaction_item_full": (os.path.join(EF, "gui/ef_dev_and_custom_windows/maj/NonEssential/map_list_panel.gui"), "gui/map_list_panel.gui"),
    "mobilization_widget": (os.path.join(EF, "gui/ef_dev_and_custom_windows/maj/NonEssential/panel_military.gui"), "gui/panel_military.gui"),
}
# E&F's lines that differ from vanilla in its copies, all classified above.
EF_KNOWN = [r"currency_symbol", r"pmg_market_liquidity", r'^tooltip = "EXPAND"$',
            r"^visible = \"\[GoodsPanelValue\.IsPiracy\]\"$",
            r"^visible = \"\[And\(Not\(GoodsPanelValue\.HasBuildingInfo\),Not\(GoodsPanelValue\.IsPiracy\)\)\]\"$"]


def check_ef_copies():
    """Stop if E&F's copies gained anything beyond the edits classified above."""
    norm = lambda b: {re.sub(r"\s+", " ", l.split("#")[0]).strip() for l in b.split("\n")} - {""}
    for t, (ef_path, van_rel) in EF_TYPES.items():
        new = norm(type_block(V.read(ef_path), t)) - norm(type_block(V.read(os.path.join(VANILLA, van_rel)), t))
        unknown = [l for l in new if not any(re.search(p, l) for p in EF_KNOWN)]
        assert not unknown, f"{t}: E&F has new lines of its own -- classify them: {unknown[:3]}"


def build() -> dict[str, str]:
    check_ef_copies()
    filt = ef_filter()
    out = {}
    for rel, (src, ns, types) in JOBS.items():
        text = V.read(os.path.join(CMF, src))
        assert re.search(r"(?m)^types\s+" + re.escape(ns) + r"\s*\{", text), f"{src}: namespace {ns} not found"
        consts = [l for l in text.split("\n") if re.match(r"^@\w+\s*=", l)]
        blocks = []
        for t in types:
            b = type_block(text, t)
            # E&F's copies of all five must still be the near-vanilla ones this merge
            # was written against: only the browser/goods filter is E&F's own content.
            if t == "MPM_pms_area_building_type":
                b = insert_after(b, r"tooltip = \"BUILDING_TYPE_BULK_CHANGE_TOOLTIP\"", filt, t)
            elif t == "goods_state_panel_input_output_item":
                b = insert_after(b, r"flowcontainer = \{[^\n]*\n[ \t]*datamodel = \"\[Building\.AccessProductionMethodGroups\]\"[\s\S]*?item = \{\s*widget = \{\s*size = \{ 50 50 \}", filt, t)
            blocks.append(b)
        body = (HEADER.format(what=", ".join(types), date=DATE, src=src) + "\n"
                + ("\n".join(consts) + "\n\n" if consts else "")
                + f"types {ns} {{\n" + "\n\n".join(blocks) + "\n}\n")
        assert V.brace_balance(body) == 0, f"{rel}: brace balance"
        out[rel] = body
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    files = build()
    drift = []
    for root in [OUT] + MEGAPACKS:
        for rel, body in files.items():
            p = os.path.join(root, rel)
            blob = ("\ufeff" + body).encode("utf-8")
            old = open(p, "rb").read() if os.path.isfile(p) else None
            if old != blob:
                drift.append(p)
                if not a.check:
                    os.makedirs(os.path.dirname(p), exist_ok=True)
                    open(p, "wb").write(blob)
    if a.check:
        for p in drift:
            print("  DRIFT", p)
        print("all files match the current CMF / E&F sources" if not drift else f"{len(drift)} file(s) drifted")
        return 1 if drift else 0
    print(f"  {len(files)} files x {1 + len(MEGAPACKS)} places, {len(drift)} written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
