"""
regen_llwa_ef.py -- builds the LLWA x E&F compatch in `_llwa/llwa+ef done`.

The pair the plan called `noneed` and shouldn't have. `pair_matrix.py` only
catches "both mods touch the same KEY" -- a brand new key one mod adds and
the other never mentions can never show up as a shared key, so it can never
show up as a conflict either. That is exactly this pair: LLWA adds six new
privately-ownable buildings (roadway, waterway, riverway, airway,
freight_depot, exchange -- LLWA_building_logistics_hub is `ownership_type =
no_ownership`, excluded on purpose) and E&F's stock/liquidity machinery is a
hand-written per-building whitelist (checked live: `production_method_groups`
INJECTs in `common/buildings/ef_*.txt`, and 49 buildings hand-listed in
`private_ownership_production_stocks`,
common/scripted_effects/01_financial_scripted_effects.txt) that predates LLWA
and mentions none of its six buildings. Without this, none of LLWA's
transport network participates in E&F's economy: no liquidity, no stock, no
private-ownership switching. Silent, nothing in error.log.

Exact same shape of problem E&F already solved once, for Morgenroete's 62
custom buildings: `_ef/ef+morg done` (in the megapack). This generator copies
that compatch's structure -- four files, same roles -- scaled down to LLWA's
six buildings, all using the SAME stock type: pmg_private_ownership_
railroad_stock (decision -- LLWA's whole network is road/water/air TRANSPORT,
not treated as manufacture/agriculture/mining; railroad_stock already exists
and already covers building_railway, so no new PM group, no new
localisation -- the group's display name is already patched into the chain
by ef+morg done's own loc file, which the whole set already loads).

No localisation file needed here for the same reason. No inflation-basket
patch needed either -- LLWA's two goods (llwa_market_conn, llwa_logi_conn)
are both `tradeable = no` + `fixed_price = yes`, so they never enter E&F's
consumer/raw-material baskets in the first place.

Usage:
    python3 regen_llwa_ef.py            # write the compatch
    python3 regen_llwa_ef.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

LLWA = res("../../vic3_mods_out/llwa")
EF = res("../../vic3_mods_out/E&F")
OUT = res("../_llwa/llwa+ef done")

HEADER = """# LLWA x E&F compatch -- {what}
# Generated by tools/regen_llwa_ef.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: E&F -> ... -> LLWA -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

# The six LLWA buildings that can be privately owned (ownership_type = self).
# LLWA_building_logistics_hub is `no_ownership` -- deliberately excluded.
BUILDINGS = [
    "LLWA_building_roadway",
    "LLWA_building_waterway",
    "LLWA_building_riverway",
    "LLWA_building_airway",
    "llwa_building_freight_depot",
    "llwa_building_exchange",
]


def record_exists(path: str, key: str, prefix: str | None = None) -> bool:
    lines = read_lines(path)
    pat_prefix = re.escape(prefix) if prefix else r"(?:[A-Z_]+:)?"
    pat = re.compile(r"^" + pat_prefix + re.escape(key) + r"\s*=\s*\{")
    return any(pat.match(raw.split("#", 1)[0].lstrip("﻿")) for raw in lines)


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def verify_sources():
    llwa_bld = os.path.join(LLWA, "common/buildings/LLWA_buildings.txt")
    assert os.path.isfile(llwa_bld), "LLWA_buildings.txt not found -- did LLWA rename it?"
    for b in BUILDINGS:
        assert record_exists(llwa_bld, b), (
            f"LLWA no longer defines {b} in LLWA_buildings.txt -- re-check the building list")

    ef_pm = os.path.join(EF, "common/production_methods/11_ef_private_infrastructure.txt")
    assert os.path.isfile(ef_pm), "E&F's 11_ef_private_infrastructure.txt not found -- re-check"
    for pm in ("pm_no_private_ownership_railroad_stock", "pm_private_ownership_majority_railroad_stock"):
        assert record_exists(ef_pm, pm), f"E&F no longer defines {pm} -- re-check the merge"

    ef_pmg = os.path.join(EF, "common/production_method_groups/11_ef_private_infrastructure.txt")
    assert record_exists(ef_pmg, "pmg_private_ownership_railroad_stock"), (
        "E&F no longer defines pmg_private_ownership_railroad_stock -- re-check")

    ef_switch = os.path.join(EF, "common/scripted_effects/01_financial_scripted_effects.txt")
    assert record_exists(ef_switch, "private_ownership_production_stocks"), (
        "E&F no longer defines private_ownership_production_stocks -- re-check the switch effect")
    text = read_lines(ef_switch)
    joined = "\n".join(text)
    for b in BUILDINGS:
        assert f"building_type = {b}" not in joined, (
            f"E&F's private_ownership_production_stocks already switches {b} -- "
            f"this generator's own switch would double it, re-check before running")


def build_buildings_inject():
    out_records = []
    for b in BUILDINGS:
        out_records.append(
            f"TRY_INJECT:{b} = {{\n"
            f"\tproduction_method_groups = {{\n"
            f"\t\tpmg_market_liquidity\n"
            f"\t\tpmg_private_ownership_railroad_stock\n"
            f"\t}}\n"
            f"}}"
        )
    write("common/buildings/zz_llwa_ef_buildings_inject.txt",
          "\n\n".join(out_records),
          "add E&F's financial PM groups to LLWA's six privately-owned buildings",
          "E&F's stock/liquidity machinery is a hand-written per-building whitelist "
          "that predates LLWA and mentions none of its buildings. TRY_INJECT so a "
          "building renamed in a future LLWA version does not spam the error log. "
          "LLWA_building_logistics_hub (ownership_type = no_ownership) is not here "
          "on purpose -- it cannot be privately owned at all.")


def build_switch_effect():
    blocks = []
    for b in BUILDINGS:
        blocks.append(f"""\t\t# {b} (railroad stock)
\t\tif = {{
\t\t\tlimit = {{
\t\t\t\thas_building = {b}
\t\t\t\tb:{b} = {{
\t\t\t\t\tprivate_ownership_fraction > 0.5
\t\t\t\t}}
\t\t\t\tis_production_method_active = {{
\t\t\t\t\tbuilding_type = {b}
\t\t\t\t\tproduction_method = pm_no_private_ownership_railroad_stock
\t\t\t\t}}
\t\t\t}}
\t\t\tactivate_production_method = {{
\t\t\t\tbuilding_type = {b}
\t\t\t\tproduction_method = pm_private_ownership_majority_railroad_stock
\t\t\t}}
\t\t}}
\t\tif = {{
\t\t\tlimit = {{
\t\t\t\thas_building = {b}
\t\t\t\tb:{b} = {{
\t\t\t\t\tprivate_ownership_fraction <= 0.5
\t\t\t\t}}
\t\t\t\tis_production_method_active = {{
\t\t\t\t\tbuilding_type = {b}
\t\t\t\t\tproduction_method = pm_private_ownership_majority_railroad_stock
\t\t\t\t}}
\t\t\t}}
\t\t\tactivate_production_method = {{
\t\t\t\tbuilding_type = {b}
\t\t\t\tproduction_method = pm_no_private_ownership_railroad_stock
\t\t\t}}
\t\t}}""")
    text = "llwa_private_ownership_production_stocks = {\n\tevery_scope_state = {\n\n" + \
           "\n\n".join(blocks) + "\n\t}\n}"
    write("common/scripted_effects/zz_llwa_ef_private_ownership_effects.txt",
          text,
          "extend E&F's \"private ownership -> stocks\" switching to LLWA's buildings",
          "same shape as _ef/ef+morg done's mr_private_ownership_production_stocks -- "
          "E&F's own switch effect only lists vanilla/E&F buildings, so LLWA's six "
          "need their own yearly check. Wired in additively (see the on_action and "
          "history/global files in this same compatch), overrides nothing of E&F's.")


def build_on_action():
    text = ("on_yearly_pulse_country = {\n"
            "\ton_actions = {\n"
            "\t\tzz_llwa_ef_on_yearly_pulse_country\n"
            "\t}\n"
            "}\n\n"
            "zz_llwa_ef_on_yearly_pulse_country = {\n"
            "\teffect = {\n"
            "\t\tllwa_private_ownership_production_stocks = yes\n"
            "\t}\n"
            "}")
    write("common/on_actions/zz_llwa_ef_on_actions.txt",
          text,
          "hook the LLWA private-ownership stock switch into the yearly pulse",
          "on_actions are additive across mods -- this overrides nothing from E&F, "
          "Morgenroete's own compatch, or anyone else also appending to "
          "on_yearly_pulse_country.")


def build_history_init():
    text = ("GLOBAL = {\n"
            "\tevery_country = {\n"
            "\t\tllwa_private_ownership_production_stocks = yes\n"
            "\t}\n"
            "}")
    write("common/history/global/zz_llwa_ef_stocks_init.txt",
          text,
          "initialise the stock production methods at game start",
          "on_yearly_pulse_country only fires a year after the start, so LLWA's "
          "buildings would sit on \"No ... Stock\" for the whole first year even "
          "when private ownership is already past half. Same fix E&F uses for its "
          "own buildings and ef+morg done uses for Morgenroete's. GLOBAL blocks "
          "stack across mods -- additive, overrides nothing.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category = os.path.dirname(rel)
        depth = 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_llwa_ef.py -> {OUT}")
    verify_sources()
    for name, fn in (
        ("buildings inject", build_buildings_inject),
        ("switch effect", build_switch_effect),
        ("on_action", build_on_action),
        ("history init", build_history_init),
    ):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current LLWA / E&F sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
