#!/usr/bin/env python3
"""
EF.48, В3.3 (decided 2.10): a customs union member keeps its own currency, with a trade account.

The customs union member's own currency: money_value and money_value_in_gold (E&F, 00_economic_scripted_value.txt)
are edited in the fork's E&F file by hand, with the trigger zz_ef_currency_own in place of market_owner_is_root_4.
The engine counts no exports inside a common market, so our Hume step (zz_ef_trade_net_week: the market's
exports - imports, market owners only) would see nothing of a member's trade.

Generated:
  * zz_ef_cu_member / zz_ef_currency_own (scripted triggers): the country owns its market, or it is a member
    with a CB that is not a subject (is_subject_custom_trigger = no; subjects -- the suzerain's currency, В3.2);
  * zz_ef_member_goods_net: a member's trade account -- what its states produce beyond what they consume,
    good by good (state_goods_production - state_goods_consumption), at the market's price; the 53
    vanilla goods (sg: takes a fixed key only; the goods of other mods -- Morgenroete, PSC -- are a small
    share of trade and are left out);
  * zz_ef_members_trade_sum: the market owner's side -- the members' accounts it pays (used in
    zz_ef_trade_net_week, values file of the money model).

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys): common/script_values/ld_customs_union_values.txt,
common/scripted_triggers/ld_customs_union_triggers.txt
Reads vanilla goods (vic3_mods_out/.vanillaVIC3/common/goods/00_goods.txt) -- run on the PC.

Usage:
    python3 tools/regen_ef_customs_union.py [--check]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

VANILLA_GOODS = os.path.normpath(os.path.join(HERE, "..", "..", "vic3_mods_out", ".vanillaVIC3", "common", "goods", "00_goods.txt"))
# hotfix paths; ld_gen writes into the fork (ld_customs_union_values.txt, ld_customs_union_triggers.txt)
OUT_SV = "common/script_values/zz_ef_customs_union_values.txt"
OUT_TR = "common/scripted_triggers/zz_ef_customs_union_triggers.txt"

HEAD = ("# GENERATED by tools/regen_ef_customs_union.py -- do not edit by hand.\n"
        "# a customs union member's own currency and trade account -- see the generator.\n")


def goods():
    t = open(VANILLA_GOODS, encoding="utf-8-sig").read()
    g = re.findall(r"^([a-z_]+) = \{", t, re.M)
    assert len(g) == 53, len(g)
    return g


def values():
    out = [HEAD]
    out.append("# A member's trade account for the week: its states' production beyond their consumption, at the\n"
               "# market's price (engine money; + it sells into the common market). 0 for others.\n"
               "zz_ef_member_goods_net = {\n\tvalue = 0\n\tif = {\n\t\tlimit = { zz_ef_cu_member = yes }\n")
    for g in goods():
        out.append(f"\t\tadd = {{\n\t\t\tvalue = 0\n"
                   f"\t\t\tevery_scope_state = {{ add = sg:{g}.state_goods_production subtract = sg:{g}.state_goods_consumption }}\n"
                   f"\t\t\tmultiply = {{ value = market.mg:{g}.market_goods_pricier add = 1 }}\n"
                   f"\t\t\tmultiply = g:{g}.base_price\n\t\t}}\n")
    out.append("\t}\n}\n")
    out.append("# The market owner's side: the members' accounts of the week (stored by each member's receiver).\n"
               "zz_ef_members_trade_sum = {\n\tvalue = 0\n"
               "\tevery_country = {\n\t\tlimit = {\n\t\t\tNOT = { this = root }\n\t\t\tzz_ef_cu_member = yes\n"
               "\t\t\tmarket.owner = root\n\t\t\thas_variable = zz_ef_member_trade\n\t\t}\n"
               "\t\tadd = var:zz_ef_member_trade\n\t}\n}\n")
    return "".join(out)


TRIGGERS = HEAD + """
# A customs union member with a currency of its own: in a market it does not own, with a central bank,
# not a subject (subjects: the suzerain's currency, В3.2).
zz_ef_cu_member = {
	exists = market
	NOT = { market.owner = this }
	has_modifier = has_central_bank
	is_subject_custom_trigger = no
}
# The country's money is its own (E&F's money_value / money_value_in_gold): it owns its market or is
# such a member.
zz_ef_currency_own = {
	exists = market
	OR = {
		market.owner = this
		zz_ef_cu_member = yes
	}
}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    ld_gen.emit(OUT_SV, values())
    ld_gen.emit(OUT_TR, TRIGGERS)
    ld_gen.report("regen_ef_customs_union")


if __name__ == "__main__":
    main()
