#!/usr/bin/env python3
"""
Д2.2 (5.10.2026) -- the population's need for bank settlements in the E&F hotfix:
common/buy_packages/zz_ef_currency_need_packages.txt.

E&F INJECTs popneed_currency into all 99 wealth tiers (common/buy_packages of E&F); this re-INJECTs the same key
scaled by tools/ef_settlements_need.py (POP_NEED_FACTOR) -- inside a block a named entry overrides the one of the
same name (rules, "INJECT: сливает под-блоки"), and the hotfix loads after E&F. Values read live from E&F.
The VC branch: tools/regen_vc_ef.py applies the same factor.

Usage:
    py tools/regen_ef_currency_need.py            # write
    py tools/regen_ef_currency_need.py --check    # exit 1 if the file differs
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ef_settlements_need import POP_NEED_FACTOR, scale_line  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))
EF_FILE = res("../../vic3_mods_out/E&F/common/buy_packages/00_ef_buy_packages.txt")
OUT = res("../_ef/ef hotfix 1.13/common/buy_packages/zz_ef_currency_need_packages.txt")


def build() -> str:
    lines = open(EF_FILE, encoding="utf-8-sig").read().splitlines()
    out = []
    for ln in lines:
        m = re.match(r"^INJECT:(wealth_\d+)\s*=\s*\{goods=\{.*popneed_currency=(\d+)", ln)
        if m:
            out.append(scale_line(f"INJECT:{m.group(1)} = {{ goods = {{ popneed_currency = {m.group(2)} }} }}"))
    assert len(out) == 99, f"expected 99 wealth tiers with popneed_currency in E&F, found {len(out)}"
    out.sort(key=lambda ln: int(re.search(r"wealth_(\d+)", ln).group(1)))
    head = (
        "# GENERATED by tools/regen_ef_currency_need.py -- do not edit by hand.\n"
        "# Д2.2 (5.10.2026, decided by the user): the population's need for bank settlements (popneed_currency,\n"
        f"# the former E&F currency) = E&F's x {POP_NEED_FACTOR} -- population ~2% of GDP, businesses ~3%\n"
        "# (production_methods/zz_ef_market_liquidity_input.txt). Re-INJECT of E&F's key: the later named entry wins.\n\n"
    )
    return head + "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = build()
    old = open(OUT, encoding="utf-8-sig").read() if os.path.exists(OUT) else ""
    if args.check:
        if old != text:
            print(f"DIFF: {OUT}")
            return 1
        print("ok")
        return 0
    with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT} (99 tiers, factor {POP_NEED_FACTOR})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
