# -*- coding: utf-8 -*-
"""
regen_greys_kai_fix.py -- builds the Grey's x KAI compatch in
`_greys/greys_kai_fix done` (GR.8, closing the last one of five keys not
already resolved elsewhere).

Load order: ... -> PSC -> KAI -> E&F -> ... -> Grey's pack -> aддон-Grey's.
Grey's loads after KAI, so a Grey's mod redeclaring a shared key full-body
wins outright.

Of GR.8's five original keys:
  * `building_construction_sector` [KAI vs grey_usu] -- already closed in
    `_greys/greys+psc done` (GR.2), which carries KAI's ai_value branch
    verbatim. Not here.
  * `NAI` [KAI vs _grey_soft_econ, grey_usu] -- both a `defines` category,
    which merges per field name across all mods regardless of load order
    (same class as GR.17's NEconomy/PRICE_RANGE, развилка №3). Checked: KAI's
    NAI fields (REFORM_GOVERNMENT_*, SUPPLY_SHIP_*, MONEY_SPENDING_*,
    PRODUCTION_*, GOVERNMENT_BUILDING_*, CONSUMPTION_TAX_INCOME_VALUE) share
    zero field names with soft_econ's (TRADE_CENTER_MINIMUM_GDP_*) or usu's
    (SUBSIDIZE_SHARE_OF_INFRA_FACTOR, OWNER_BUILDING_LOCATION_*). Purely
    additive, no file needed.
  * `ai_strategy_territorial_expansion` [KAI vs grey_subject] -- grey_subject's
    REPLACE_OR_CREATE: (MoG_diplomatic_strategies_SIS.txt) carries a comment
    "Cannot INJECT weights in the correct sequence" and its own
    undesirable_infamy_level/unacceptable_infamy_level values are byte-for-byte
    what KAI's INJECT: adds (50 / 100). The author already merged KAI's content
    in by hand. No file needed.
  * `foreign_investment_rights` [KAI vs grey_diplo] -- THE SECOND ONE THIS
    GENERATOR CLOSES, as of 27.08.2026. grey_diplo's TRY_REPLACE: is a
    deliberate, heavily-commented rebalance of KAI's own `ai` block (same
    accept_score structure, several values intentionally changed with reasoning
    -- e.g. law_isolationism penalty -300 -> -100, one KAI addition explicitly
    rejected with a "wtf is this" comment) -- that part is left untouched, it is
    grey_diplo's own design. One piece was not a rejected redesign though: KAI's
    own `wargoal_score_multiplier` carries a self-described vanilla bugfix
    ("Replaced target_country, which is actually the attacker, with
    source_country... Added a check against subjects, since the treaty will be
    broken immediately if a country does not have diplomatic autonomy") --
    grey_diplo's version silently reverted to the original (buggy)
    target_country reference and dropped the subject exemption, with no comment
    acknowledging it, unlike every other change in the same block. M confirmed:
    graft KAI's wargoal_score_multiplier onto grey_diplo's body, leave the rest
    of grey_diplo's rework alone. Implemented as a full TRY_REPLACE: of the
    whole record (grey_diplo's body verbatim, `ai.wargoal_score_multiplier`
    swapped for KAI's) rather than a TRY_INJECT:, because the two competing
    wargoal_score_multiplier bodies use the same field names with different
    logic -- an INJECT: would not resolve which one wins inside that sub-block,
    a full-record replace makes it unambiguous.
  * `building_government_administration` [KAI vs grey_usu] -- THE ONE THIS
    GENERATOR CLOSES. grey_usu's REPLACE_OR_CREATE: (yMoG_USU_government.txt)
    carries no `ai_value` at all; KAI's INJECT: adds the whole AI-construction-
    priority block (bureaucracy backlog scoring). Not a design dispute --
    grey_usu's body is missing the field entirely, no replacement logic of its
    own. The building's other known loss on this record (Morgenrote's
    pmg_panum_hospital group, GR.6) is a separate file
    (`_greys/greys+morg done`); this is additive to that, not instead of it.

Usage:
    python3 regen_greys_kai_fix.py            # write the fix
    python3 regen_greys_kai_fix.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

KAI = res("../../vic3_mods_out/TechRes+Kuromi/kai")
GREYS = res("../../vic3_mods_out/grey_add_alot_of_things")
KAI_BUILDINGS = os.path.join(KAI, "common/buildings/kai_buildings.txt")
USU_GOV_FILE = os.path.join(GREYS, "grey_usu/common/buildings/yMoG_USU_government.txt")
KAI_FIR = os.path.join(KAI, "common/treaty_articles/kai_foreign_investment_rights.txt")
DIPLO_FIR = os.path.join(GREYS, "grey_diplo/common/treaty_articles/z07_foreign_investment_rights.txt")
OUT = res("../_greys/greys_kai_fix done")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's x KAI compatch (GR.8) -- {what}
# Generated by tools/regen_greys_kai_fix.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: ... -> KAI -> ... -> Grey's pack -> THIS.
# Why this file exists: {why}
"""


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_gov_admin():
    key = "building_government_administration"
    kai_text = V.read(KAI_BUILDINGS)
    _decl, kai_body = V.entry(kai_text, key, "INJECT:")
    ai_value = V.sub(kai_body, "ai_value")
    assert ai_value, f"{key}: KAI no longer carries ai_value -- re-check GR.8, this fix may be stale"

    usu_text = V.read(USU_GOV_FILE)
    _decl2, usu_body = V.entry(usu_text, key, "REPLACE_OR_CREATE:")
    assert "ai_value" not in usu_body, (
        f"{key}: grey_usu's body now carries its own ai_value -- the author may have "
        f"caught up with KAI, re-check whether this fix is still needed")

    text = f"TRY_INJECT:{key} = {{\n\tai_value = {ai_value}\n}}"
    write("common/buildings/zz_greys_kai_fix_gov_admin.txt", text,
          "restore KAI's ai_value (bureaucracy-backlog construction priority) that grey_usu's REPLACE_OR_CREATE: drops",
          "grey_usu redeclares building_government_administration whole (REPLACE_OR_CREATE:) with "
          "no ai_value at all -- not a design dispute, the field is just absent. KAI's INJECT: "
          "(kai_buildings.txt) adds an ai_value block that makes the AI prioritise building "
          "administration where tax capacity is already short. Read live from KAI's own file. "
          "Separate from and additive to `_greys/greys+morg done` (GR.6), which restores this same "
          "building's pmg_panum_hospital production method group -- different sub-block, same key, "
          "no collision.")


def build_foreign_investment_rights():
    key = "foreign_investment_rights"
    kai_text = V.read(KAI_FIR)
    _decl, kai_body = V.entry(kai_text, key, "INJECT:")
    kai_ai_full = V.sub(kai_body, "ai")
    assert kai_ai_full, f"{key}: KAI no longer carries an ai block -- re-check GR.8, this fix may be stale"
    kai_wgs = V.sub(kai_ai_full[1:-1], "wargoal_score_multiplier")
    assert kai_wgs and "source_country" in kai_wgs and "is_subject = yes" in kai_wgs, (
        f"{key}: KAI's wargoal_score_multiplier no longer matches the expected shape "
        f"(source_country scope + subject exemption) -- re-check GR.8, this fix may be stale")

    diplo_text = V.read(DIPLO_FIR)
    _decl2, diplo_body = V.entry(diplo_text, key, "TRY_REPLACE:")
    diplo_ai_full = V.sub(diplo_body, "ai")
    assert diplo_ai_full, f"{key}: grey_diplo no longer carries an ai block -- re-check GR.8"
    diplo_ai_inner = diplo_ai_full[1:-1]
    diplo_wgs = V.sub(diplo_ai_inner, "wargoal_score_multiplier")
    assert diplo_wgs and "target_country" in diplo_wgs and "is_subject = yes" not in diplo_wgs, (
        f"{key}: grey_diplo's wargoal_score_multiplier no longer matches the expected (reverted) "
        f"shape -- the author may have fixed it themselves, re-check whether this fix is still needed")

    new_ai_inner = V.replace_sub(diplo_ai_inner, "wargoal_score_multiplier", kai_wgs)
    new_ai_full = "{" + new_ai_inner + "}"
    new_body = V.replace_sub(diplo_body, "ai", new_ai_full)

    write("common/treaty_articles/zz_greys_kai_fix_foreign_investment_rights.txt",
          f"TRY_REPLACE:{key} = {{{new_body}}}",
          "graft KAI's wargoal_score_multiplier (a scope bugfix + subject exemption) onto grey_diplo's foreign_investment_rights, keep the rest of grey_diplo's rework",
          "grey_diplo's TRY_REPLACE: is a deliberate rebalance of KAI's whole ai block, kept here "
          "verbatim except for one sub-block. KAI's own wargoal_score_multiplier fixes a vanilla bug "
          "(the wrong country was checked for an embargo pact -- 'target_country, which is actually "
          "the attacker') and adds an exemption so demanding investment rights from a subject doesn't "
          "immediately break the treaty (subjects lack diplomatic autonomy). grey_diplo's own copy of "
          "this sub-block silently reverted both -- no comment acknowledging it, unlike every other "
          "change in the same file. M confirmed (27.08.2026): keep grey_diplo's rebalance everywhere "
          "else, restore just this sub-block from KAI, read live from both sources rather than "
          "hand-copied. A full TRY_REPLACE: of the whole record, not a TRY_INJECT:, because both "
          "sides declare wargoal_score_multiplier with the same field names and different logic -- "
          "INJECT: cannot arbitrate which one wins inside a sub-block, only a full-record replace can.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        import re as _re
        doubled = _re.findall(r"^[A-Z_]+:[A-Z_]+:", text, _re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        empty_colon = _re.findall(r"^[A-Z_]+::", text, _re.M)
        if empty_colon:
            print(f"  FAIL {rel}: {len(empty_colon)} bad '::' prefix(es), e.g. {empty_colon[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = _re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_kai_fix.py -> {OUT}")
    for name, fn in (("gov_admin", build_gov_admin), ("foreign_investment_rights", build_foreign_investment_rights)):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current KAI / grey_usu sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
