# -*- coding: utf-8 -*-
"""
regen_greys_pbe.py -- builds the Grey's x PBE compatch in `_greys/greys+pbe done`.

Pair GR.3 of the Grey's addon. One shared record: `force_become_subject`.

grey_subject's `TRY_REPLACE:force_become_subject` and PBE's bare (prefix-less,
same strength as REPLACE:) `force_become_subject` both rewrite the same vanilla
power-bloc diplomatic action, and both diverge from vanilla and from each other
in two independent ways:

* PBE wraps three of vanilla's `possible` gates (rank, bloc cohesion, prestige)
  in `OR = { has_game_rule = vokaes_power_bloc_rule_diplo_action_changes_enabled,
  <vanilla gate> }` and adds a `create_incident` (infamy) effect to
  `accept_effect`, gated the same way. That game rule (PBE's own
  `common/game_rules/vokaes_power_bloc_game_rules.txt`) **defaults to
  enabled**, so this is live for most players out of the box, not an edge case.
* grey_subject adds one gate PBE does not have: a `custom_tooltip` requiring a
  land border with the target country (direct, or through a puppet/colony).

Grey's loads after PBE (`grey_subject` is the last file of the Grey's block;
PBE sits early in the common chain -- see `tools/blocks.json`, `load_order`),
and `TRY_REPLACE:` patches by named sub-block, and grey_subject names every
sub-block PBE does. So today grey_subject's version wins outright on
`possible` and `accept_effect`: PBE's game-rule gates and infamy incident are
gone, silently, and only grey_subject's border check survives. Everything
else in the record (`groups`, `show_in_lens`, `texture`, `selectable`,
`potential`, `ai`) is identical between the two mods already, so this file
re-issues PBE's full body with grey_subject's border check spliced into
`possible`.

Usage:
    python3 regen_greys_pbe.py            # write the compatch
    python3 regen_greys_pbe.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

PBE_FILE = res("../../vic3_mods_out/PowerBlocksExpanded/common/diplomatic_actions/vokaes_power_bloc_actions.txt")
GS_FILE = res("../../vic3_mods_out/grey_add_alot_of_things/grey_subject/common/diplomatic_actions/31_zower_bloc_force_become_subject.txt")
OUT = res("../_greys/greys+pbe done")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's x PBE compatch (GR.3) -- {what}
# Generated by tools/regen_greys_pbe.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: ... -> PBE -> ... -> Grey's pack (grey_subject last) -> THIS.
# Why this file exists: {why}
"""


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def skeleton(body: str) -> str:
    """`body` with `possible` and `accept_effect` cut out -- what has to match."""
    b = body
    for name in ("possible", "accept_effect"):
        span = V.sub_span(b, name)
        if span:
            b = b[:span[0]] + b[span[1]:]
    return b


def build_force_become_subject():
    pbe_text, gs_text = V.read(PBE_FILE), V.read(GS_FILE)

    pbe_decl, pbe_body = V.entry(pbe_text, "force_become_subject")
    assert re.match(r"^﻿?force_become_subject\s*=\s*\{", pbe_decl), (
        f"PBE now prefixes force_become_subject ({pbe_decl.splitlines()[0]!r}) -- re-check GR.3")

    gs_decl, gs_body = V.entry(gs_text, "force_become_subject", "TRY_REPLACE:")

    pbe_skel, gs_skel = skeleton(pbe_body), skeleton(gs_body)
    assert V.sha(pbe_skel) == V.sha(gs_skel), (
        "PBE and grey_subject now differ outside `possible`/`accept_effect` too "
        "(groups/show_in_lens/texture/selectable/potential/ai) -- re-read both bodies by "
        "hand, this merge only knows how to carry the two named blocks")

    # accept_effect: PBE's is a strict superset (grey_subject has no create_incident
    # and no dominion branch, same as PBE) -- take PBE's verbatim, nothing to splice.
    gs_accept = V.sub(gs_body, "accept_effect")
    pbe_accept = V.sub(pbe_body, "accept_effect")
    assert "create_incident" not in gs_accept, (
        "grey_subject's accept_effect now has its own create_incident -- re-check GR.3, "
        "this merge assumes only PBE adds it")
    assert "create_incident" in pbe_accept, "PBE dropped create_incident -- re-check GR.3"

    # possible: splice grey_subject's border custom_tooltip into PBE's possible.
    pbe_possible_full = V.sub(pbe_body, "possible")
    gs_possible_body = V.entry(gs_body, "possible")[1]
    gs_tooltip = V.sub(gs_possible_body, "custom_tooltip")
    assert gs_tooltip and "common_border1" in gs_tooltip, (
        "grey_subject's border check moved or changed shape -- re-check GR.3")
    pbe_possible_body = V.entry(pbe_body, "possible")[1]
    assert V.sub(pbe_possible_body, "custom_tooltip") is None, (
        "PBE's possible now has a custom_tooltip of its own at the top level -- "
        "re-check for a name clash before splicing grey_subject's in")

    close = pbe_possible_full.rindex("}")
    merged_possible = (
        pbe_possible_full[:close].rstrip() + "\n\n\t\tcustom_tooltip = " + gs_tooltip.rstrip()
        + "\n\t" + pbe_possible_full[close:]
    )
    merged_body = V.replace_sub(pbe_body, "possible", merged_possible)

    text = (
        "# Full body from PBE (common/diplomatic_actions/vokaes_power_bloc_actions.txt):\n"
        "#   game-rule-gated possible/accept_effect (live by default, see module docstring)\n"
        "# plus grey_subject's border check spliced into `possible`\n"
        "#   (common/diplomatic_actions/31_zower_bloc_force_become_subject.txt, custom_tooltip\n"
        "#   text = common_border1) -- the one thing PBE's body does not have.\n\n"
        f"REPLACE_OR_CREATE:force_become_subject = {{{merged_body}}}"
    )
    write("common/diplomatic_actions/zz_greys_pbe_force_become_subject.txt", text,
          "merge PBE's game-rule gates + infamy incident with grey_subject's border check "
          "on force_become_subject",
          "grey_subject's TRY_REPLACE: loads after PBE's bare full body and names every "
          "sub-block PBE does, so it wins outright: PBE's OR = { has_game_rule = "
          "vokaes_power_bloc_rule_diplo_action_changes_enabled, ... } gates on rank/cohesion/"
          "prestige and its create_incident (infamy) effect are gone, silently -- and that "
          "game rule defaults to enabled, so this is not an edge case. Only grey_subject's "
          "own addition, a common-border requirement in `possible`, survives. This file "
          "carries both: PBE's body as the base, grey_subject's custom_tooltip spliced into "
          "`possible`.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        stray_colon = re.findall(r"^[A-Z_]+::", text, re.M)
        if stray_colon:
            print(f"  FAIL {rel}: {len(stray_colon)} stray-colon prefix(es), e.g. {stray_colon[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_pbe.py -> {OUT}")
    for name, fn in (("force_become_subject", build_force_become_subject),):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current PBE / grey_subject sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
