#!/usr/bin/env python3
"""
EF.48 (the user, 1.10 night): E&F's currency interventions in our money's scale.

E&F (scripted_effects/01_economic_scripted_effects.txt) has one buy_<currency>_currency
effect per currency (95): a central bank buys an undervalued currency (value under 75% of
its parity) from its issuer for metal. The quantity is random, { 1000000 10000000 } units --
the scale of E&F's own money (~1 billion), while the money in circulation is now the engine's
(~25 times smaller: Britain's M2 15-40M). One deal moved the cover by tens of percent (run 16:
France 105%, Russia 2%). The quantity becomes zz_ef_fx_deal_size of the issuer -- a share of
its M2 (script_values/zz_ef_money_model_values.txt). The sell_* effects sell half of what a
bank holds -- proportional already, kept. M.5 (4.10): an AI buyer whose own metal cover is under
40% does not buy (quantity 0).

Writes _ef/ef hotfix 1.13/common/scripted_effects/zz_ef_fx_deals.txt: every buy_<currency>_currency
as E&F has it, key-level REPLACE_OR_CREATE, with the one line changed.

Usage:
    py tools/regen_ef_fx_deals.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, r"..\..\vic3_mods_out\E&F\common\scripted_effects\01_economic_scripted_effects.txt"))
OUT = os.path.normpath(os.path.join(HERE, r"..\_ef\ef hotfix 1.13\common\scripted_effects\zz_ef_fx_deals.txt"))

RANDOM = "value = { 1000000 10000000 }"
# M.5 (the user, 4.10): an AI central bank does not pay out metal for another currency while its
# own cover is under the norm (zz_ef_cover_normal, 40%) -- the deal's quantity is 0 then.
SCALED = ("value = { value = scope:undervalued_currency_country_owner.zz_ef_fx_deal_size "
          "if = { limit = { root = { is_ai = yes zz_ef_cb_cover < zz_ef_cover_normal } } value = 0 } }")


def blocks(text):
    """(name, body) of every top-level buy_<currency>_currency = { ... } (indented by one tab in E&F)."""
    for m in re.finditer(r"^\t?(buy_[a-z_]+_currency) = \{", text, re.M):
        start = m.start()
        i = text.index("{", m.start())
        depth = 0
        for j in range(i, len(text)):
            if text[j] == "{":
                depth += 1
            elif text[j] == "}":
                depth -= 1
                if depth == 0:
                    yield m.group(1), text[i:j + 1]
                    break


def main():
    text = open(SRC, encoding="utf-8-sig").read()
    out = ["# GENERATED by tools/regen_ef_fx_deals.py -- do not edit by hand.\n"
           "# EF.48: E&F's buy_<currency>_currency with the deal size in our money's scale\n"
           "# (zz_ef_fx_deal_size of the issuer) instead of a random 1-10 million units.\n"
           "# !! MAINTENANCE !! Key-level REPLACE_OR_CREATE of E&F's effects: regenerate after an E&F update.\n\n"]
    n = 0
    for name, body in blocks(text):
        if RANDOM not in body:
            continue
        assert body.count(RANDOM) == 1, name
        out.append(f"REPLACE_OR_CREATE:{name} = {body.replace(RANDOM, SCALED)}\n\n")
        n += 1
    assert n >= 90, n
    with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write("".join(out))
    print("ok", n, "effects ->", OUT)
    write_fx_reserves(sorted(set(re.findall(r"^\t?buy_([a-z_]+)_currency = \{", text, re.M))))


OUT_SV = os.path.normpath(os.path.join(HERE, r"..\_ef\ef hotfix 1.13\common\script_values\zz_ef_fx_reserves_values.txt"))


def write_fx_reserves(currencies):
    """Foreign currency in the CB's reserves, in gold: every currency but the country's own -- the stock
    the CB bought in E&F's interventions (var:stockpiling_<cur>_state_1 of its CB states, in our scale since
    c2ddc66) x money_value_<cur> (E&F's parity of the currency, gold per unit). Not E&F's
    stockpiling_<cur>_reserve_currency_state_1 (the reserve currency E&F credits for trade): it is in E&F's
    money scale -- run 20 (2.10): 10-65 million a state for the peseta, the franc, the Ottoman lira; in the
    cover it put Austria at 146% and its value at 3.6 times the parity within three months."""
    lines = ["# GENERATED by tools/regen_ef_fx_deals.py -- do not edit by hand.\n"
             "# EF.48 (the user, 1.10 night; night 2, 2.10): foreign currency in the CB's reserves, in gold --\n"
             "# the interventions' stocks only (the reserve currency E&F credits for trade is in E&F's scale).\n"
             "zz_ef_fx_reserves_metal = {\n\tvalue = 0\n"
             "\tevery_scope_state = {\n\t\tlimit = { has_modifier = central_bank_historic_place }\n"]
    for c in currencies:
        lines.append(f"\t\tif = {{ limit = {{ has_variable = stockpiling_{c}_state_1 "
                     f"NOT = {{ owner = {{ has_law = law_type:law_{c}_currency }} }} }} "
                     f"add = {{ value = var:stockpiling_{c}_state_1 multiply = money_value_{c} min = 0 }} }}\n")
    lines.append("\t}\n\tmin = 0\n}\n")
    with open(OUT_SV, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write("".join(lines))
    print("ok", len(currencies), "currencies ->", OUT_SV)
    write_stock_rescale(currencies)
    write_crisis(currencies)


OUT_RESCALE = os.path.normpath(os.path.join(HERE, r"..\_ef\ef hotfix 1.13\common\scripted_effects\zz_ef_fx_stock_rescale.txt"))


def write_stock_rescale(currencies):
    """Night 2, item 2 (2.10): E&F's currency-good stocks of a CB state (its own currency and the
    foreign ones, also the reserve-currency part) rescaled with the CB's metal at the start of a
    game (version 7) -- by owner.var:zz_ef_metal_rescale, STATE scope."""
    lines = ["# GENERATED by tools/regen_ef_fx_deals.py -- do not edit by hand.\n"
             "# EF.48, night 2 item 2 (2.10): E&F's currency stocks of a CB state in our money's scale,\n"
             "# the same factor as the metal (zz_ef_metal_rescale_step). STATE scope.\n"
             "zz_ef_fx_stock_rescale = {\n"]
    for c in currencies:
        for v in (f"stockpiling_{c}_state_1", f"stockpiling_{c}_reserve_currency_state_1"):
            lines.append(f"\tif = {{ limit = {{ has_variable = {v} }} "
                         f"change_variable = {{ name = {v} multiply = owner.var:zz_ef_metal_rescale }} }}\n")
    lines.append("}\n")
    with open(OUT_RESCALE, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write("".join(lines))
    print("ok", len(currencies), "currencies ->", OUT_RESCALE)


OUT_CRISIS = os.path.normpath(os.path.join(HERE, r"..\_ef\ef hotfix 1.13\common\scripted_effects\zz_ef_fx_crisis.txt"))

CRISIS = """REPLACE_OR_CREATE:sell_{c}_currency_crisis = {{
	scope:seller = {{
		save_scope_as = seller_root
		every_scope_state = {{
			limit = {{
				has_modifier = central_bank_historic_place
				is_capital = yes
			}}
			save_scope_as = central_bank_site_root
		}}
	}}
	scope:target_country = {{
		save_scope_as = overrated_currency_country_owner
		every_scope_state = {{
			limit = {{
				has_modifier = central_bank_historic_place
				is_capital = yes
			}}
			save_scope_as = central_bank_site_overrated_currency_owner
		}}
	}}
	if = {{
		limit = {{
			exists = scope:overrated_currency_country_owner
			exists = scope:central_bank_site_root
			exists = scope:central_bank_site_overrated_currency_owner
			scope:overrated_currency_country_owner = {{
				has_law = law_type:law_{c}_currency
				sell_currency_crisis_1 = yes
			}}
		}}
		scope:seller_root = {{
			# all of it, at the parity, as far as the issuer's metal goes
			set_variable = {{ name = stockpiling_overrated_quantity_var value = stockpiling_{c}_state }}
			set_variable = {{
				name = zz_ef_crisis_due
				value = {{
					value = var:stockpiling_overrated_quantity_var
					multiply = scope:overrated_currency_country_owner.money_value_target_real
					min = 0
				}}
			}}
			zz_ef_crisis_redeem = yes
			if = {{
				limit = {{
					has_variable = stockpiling_{c}_c_in_reserve_currency
					var:stockpiling_{c}_c_in_reserve_currency > 0
				}}
				set_variable = {{ name = stockpiling_{c}_c_in_reserve_currency value = 0 }}
			}}
			scope:central_bank_site_root = {{
				if = {{ limit = {{ has_variable = stockpiling_{c}_state_1 }} set_variable = {{ name = stockpiling_{c}_state_1 value = 0 }} }}
				if = {{ limit = {{ has_variable = stockpiling_{c}_reserve_currency_state_1 }} set_variable = {{ name = stockpiling_{c}_reserve_currency_state_1 value = 0 }} }}
			}}
		}}
		scope:overrated_currency_country_owner = {{
			reset_debt_in_national_currency = yes
		}}
	}}
}}

"""


def write_crisis(currencies):
    """Night 2, item 3 (2.10): E&F's currency crisis (money_value down 50% in half a year, or the CB
    bankrupt) makes every CB sell all of the currency -- and set the ISSUER's metal to 0 while the
    sellers get nothing: the metal left the game (run 18: Russia 125M -> 3.5M, 24.11-1.12.1836).
    Now the sellers redeem it: the issuer pays the holdings at its parity from its metal, as far as
    the metal goes (zz_ef_crisis_redeem, scripted_effects/zz_ef_money_model.txt)."""
    out = ["# GENERATED by tools/regen_ef_fx_deals.py -- do not edit by hand.\n"
           "# EF.48, night 2 item 3 (2.10): E&F's sell_<currency>_currency_crisis -- the sellers redeem the\n"
           "# currency for the issuer's metal (at most what it holds) instead of the issuer's metal set to 0.\n"
           "# !! MAINTENANCE !! Key-level REPLACE_OR_CREATE of E&F's effects: regenerate after an E&F update.\n\n"]
    for c in currencies:
        out.append(CRISIS.format(c=c))
    with open(OUT_CRISIS, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write("".join(out))
    print("ok", len(currencies), "crisis effects ->", OUT_CRISIS)


if __name__ == "__main__":
    main()
