#!/usr/bin/env python3
"""
regen_ef_cb_company_dividends.py -- the central bank's company pays its dividends
to the treasury (СТР.5, decided by the user 2026-10-02).

Why
---
The hotfix (EF.4) has the central bank born owned by a bank company, so the
company can mint the regime currencies as prestige goods. The bank's profit is
then the company's ownership income: dividends, and ~30% of it reinvested into
the investment pool. In the 2.10 run that made the central bank companies the
biggest single source of the pool (Bank of England: 32% of Britain's pool,
184k a week of ownership income), and the engine picks the owner of new private
construction in proportion to where the pool's money came from -- companies
took +1443..1698 productive levels in three years, pops -346..-534.

What it does
------------
The company holding the monopoly on building_bank is the central bank's
company (zz_ef_cm_bank_monopoly.txt grants it to the same company that owns
the bank). Monthly, its HQ building gets the static modifier
zz_ef_cb_company_dividends (building_company_government_dividends_add = 1):
all its dividends go to the treasury. The engine has no link from a company to
its HQ, but an HQ's building type is `building_` + the company key, so the
branches are generated, one per company, flat (first match wins, depth 1 --
see zz_ef_cm_bank_ownership.txt on why not an else_if chain).

Source of truth: the company list and order of
_ef/ef hotfix 1.13/common/scripted_effects/zz_ef_cm_bank_monopoly.txt.
Re-run after that file changes.

Usage:  python3 tools/regen_ef_cb_company_dividends.py [--check]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
HOTFIX = HERE.parent / "_ef" / "ef hotfix 1.13"
SRC = HOTFIX / "common/scripted_effects/zz_ef_cm_bank_monopoly.txt"
OUT_EFFECT = HOTFIX / "common/scripted_effects/zz_ef_cb_company_dividends.txt"

MODIFIER = "zz_ef_cb_company_dividends"

HEADER = f"""### GENERATED by tools/regen_ef_cb_company_dividends.py -- do not edit by hand.
### СТР.5 (2026-10-02): the central bank's company pays all its dividends to the
### treasury (static_modifiers/{MODIFIER}.txt, building_company_government_dividends_add = 1).
### Country scope, monthly (zz_ef_money_model_monthly_step). The company with the
### monopoly on building_bank is the central bank's company; its HQ building type
### is building_ + the company key. Company list and order: {SRC.name}.
### Flat branches, first match wins (one company per country holds the monopoly).

"""

LOC = {
    "english": (f'{MODIFIER}:0 "Central bank company: dividends to the treasury"',
                f'{MODIFIER}_desc:0 "This company holds the central bank to mint the currency, not to profit from it: all its dividends go to the treasury instead of its shareholders and the investment pool."'),
    "russian": (f'{MODIFIER}:0 "Компания центробанка: дивиденды в казну"',
                f'{MODIFIER}_desc:0 "Компания держит центробанк, чтобы чеканить валюту, а не ради прибыли: все её дивиденды идут в казну, а не акционерам и в инвестиционный пул."'),
}


def read(p: Path) -> str:
    return p.read_text(encoding="utf-8-sig")


def build_effect(keys: list[str]) -> str:
    out = [HEADER, "zz_ef_cb_company_dividends_step = {\n"]
    for k in keys:
        out.append(f"""\tif = {{
\t\tlimit = {{ has_company = company_type:{k} }}
\t\tif = {{
\t\t\tlimit = {{ company:{k} = {{ company_has_building_type_monopoly = bt:building_bank }} }}
\t\t\tevery_scope_building = {{
\t\t\t\tlimit = {{
\t\t\t\t\tis_building_type = building_{k}
\t\t\t\t\tNOT = {{ has_modifier = {MODIFIER} }}
\t\t\t\t}}
\t\t\t\tadd_modifier = {{ name = {MODIFIER} }}
\t\t\t}}
\t\t}}
\t}}
""")
    out.append("}\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report drift, write nothing")
    a = ap.parse_args()

    keys: list[str] = []
    for k in re.findall(r"\bcompany:([A-Za-z0-9_]+)\s*=\s*\{", read(SRC)):
        if k not in keys:
            keys.append(k)
    if not keys:
        print(f"ERROR: no company:<key> blocks in {SRC}", file=sys.stderr)
        return 1

    files = {OUT_EFFECT: build_effect(keys)}
    for lang_dir in sorted(p for p in (HOTFIX / "localization").iterdir() if p.is_dir()):
        lang = lang_dir.name
        name, desc = LOC.get(lang, LOC["english"])
        files[lang_dir / f"{MODIFIER}_l_{lang}.yml"] = (
            f"# GENERATED by tools/regen_ef_cb_company_dividends.py -- static_modifiers/{MODIFIER}.txt\n"
            f"l_{lang}:\n {name}\n {desc}\n")

    rc = 0
    for path, text in files.items():
        old = read(path) if path.exists() else ""
        changed = old != text
        depth = sum(l.split("#", 1)[0].count("{") - l.split("#", 1)[0].count("}") for l in text.split("\n"))
        print(f"[{'OK ' if depth == 0 else 'BAD'}] {path.relative_to(HOTFIX).as_posix():70} "
              f"{'changed' if changed else 'same'}")
        if depth:
            rc = 1
            continue
        if changed:
            if a.check:
                rc = 1
            else:
                path.write_text(text, encoding="utf-8-sig", newline="\n")
    print(f"{len(keys)} companies" + (" -- --check: nothing written" if a.check else ""))
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
