# -*- coding: utf-8 -*-
"""
regen_greys_usu_fix.py -- builds the grey_usu double-colon fix in
`_greys/greys_usu_fix done`.

GR.20 -- found while working GR.1 (Grey's x VC). Not a pair: purely internal
to grey_usu, unrelated to any other mod in the set.

`grey_usu/common/company_types/yMoG_USU_companies_ports_overwrite.txt` writes
three of its records with a typo'd prefix -- `TRY_INJECT::company_X` (two
colons) instead of `TRY_INJECT:company_X` (one). The engine does not
recognise `WORD::` as a valid prefix -- same failure class as the doubled
prefix `REPLACE:REPLACE:` that `Правила -- сборка.md` already warns about,
but a DIFFERENT pattern: `REPLACE:REPLACE:` is two valid prefixes stuck
together and IS caught by the standard self-check regex `^[A-Z_]+:[A-Z_]+:`;
`WORD::` is one valid prefix word followed directly by a second colon with
nothing between them, and that regex does NOT match it (the second
`[A-Z_]+` needs at least one character, and there is none between the two
colons). This generator's self-check adds a second regex, `^[A-Z_]+::`, to
catch this specific shape -- worth folding into the shared checklist in
`Правила -- сборка.md`, section 5.

Effect in game: the three records do not load at all, silently -- nothing in
error.log. `company_john_holt`, `company_lanfang_kongsi` and
`company_putilov_company` never get the `building_river_port` (and, for
Putilov, `building_usu_railway_line` prosperity modifier) that every other
company in the same file gets. Side effect noted in GR.1: this is also why
`company_putilov_company` did not show up as a seventh pair with VC there --
its record was never loading to begin with.

Usage:
    python3 regen_greys_usu_fix.py            # write the fix
    python3 regen_greys_usu_fix.py --check    # report only, exit 1 if source drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

SRC = res("../../vic3_mods_out/grey_add_alot_of_things/grey_usu/common/company_types/"
          "yMoG_USU_companies_ports_overwrite.txt")
OUT = res("../_greys/greys_usu_fix done")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

EXPECT_KEYS = {"company_john_holt", "company_lanfang_kongsi", "company_putilov_company"}

HEADER = """# grey_usu self-fix (GR.20) -- {what}
# Generated by tools/regen_greys_usu_fix.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: grey_usu -> ... -> THIS (anywhere after grey_usu; internal to
# grey_usu, no other mod involved).
# Why this file exists: {why}
"""


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_double_colon_fix():
    text = V.read(SRC)
    bad = re.findall(r"(?m)^([A-Z_]+)::([a-z][a-z0-9_]*)\s*=\s*\{", text)
    assert bad, (
        "no `WORD::key` records found in grey_usu's ports-overwrite file -- "
        "the author fixed it upstream, drop this compatch and close GR.20 as 'есть'")
    found = {key for _, key in bad}
    assert found == EXPECT_KEYS, (
        f"the set of broken records changed: file now has {sorted(found)}, "
        f"GR.20 in the plan says {sorted(EXPECT_KEYS)} -- re-read the plan and this generator")

    records, notes = [], []
    for prefix, key in bad:
        assert prefix == "TRY_INJECT", (
            f"{key}: broken prefix is {prefix}:: , not TRY_INJECT:: -- re-check GR.20, "
            f"the fix below assumes TRY_INJECT")
        decl, body = V.entry(text, key, prefix + "::")
        records.append(f"TRY_INJECT:{key} = {{{body}}}")
        notes.append(f"#   {key}")

    out_text = (
        "# Same three bodies as yMoG_USU_companies_ports_overwrite.txt, prefix fixed\n"
        "# from `TRY_INJECT::` (two colons, never loads) to `TRY_INJECT:` (one):\n"
        + "\n".join(notes) + "\n\n" + "\n\n".join(records)
    )
    write("common/company_types/zz_greys_usu_fix_double_colon.txt", out_text,
          "re-declare three USU port companies whose TRY_INJECT:: (two colons) prefix "
          "never loaded",
          "yMoG_USU_companies_ports_overwrite.txt has a typo'd prefix on three of its "
          "records -- `TRY_INJECT::company_X` (two colons) where every sibling record in "
          "the same file has `TRY_INJECT:company_X` (one). The engine does not recognise "
          "`WORD::` as a prefix at all, so these three records are not loaded -- not "
          "overridden, not skipped-with-a-warning, simply never parsed as the intended "
          "statement. Nothing in error.log. The three companies (John Holt and Company, "
          "Lanfang Kongsi, Society of Putilov Factories) end up missing the "
          "building_river_port (and, for Putilov, the building_usu_railway_line prosperity "
          "modifier) that every other company in the file gets. Internal to grey_usu, no "
          "other mod involved -- fixed here so the compatch does not have to wait on any "
          "particular pair, and reported to the author.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        stray_colon = re.findall(r"^[A-Z_]+::", text, re.M)
        if stray_colon:
            print(f"  FAIL {rel}: {len(stray_colon)} stray-colon prefix(es), e.g. {stray_colon[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_usu_fix.py -> {OUT}")
    for name, fn in (("double-colon fix", build_double_colon_fix),):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the source:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current grey_usu source")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
