#!/usr/bin/env python3
"""
regen_ef_stimulus_buttons.py -- СТР.4 (ночь Г, decision Д.13 of 2026-10-03): the stimulus
buttons 9-12 of E&F's Financial Stability Office journal change the factor of the
construction-sector limit instead of the base rate.

Before: each button cut the base rate by 1-4% for a +10..40 overbuilt-economy penalty;
switched off 2026-09-30, because under EF.30 the central bank walks any cut back within 1-4
quarters. The limit of construction sectors is urban centres x (1 - 5 x rate) (+ the STR.3
household part); the user's idea (30.09): the stimulus lowers the 5.

Now (Д.13): button 9 / 10 / 11 / 12 -> factor 4 / 3.5 / 3 / 2.5 for STIMULUS_MONTHS months
(var:zz_pb_ef_stimulus_mult, timed -- script_values/zz_pb_ef_overbuild_values.txt reads it),
+10 / 20 / 30 / 40 penalty (allowed while the penalty is below 90 / 80 / 70 / 60, so a press
never goes past 100), cooldown COOLDOWN_MONTHS (speculative_share_modifier_5, as E&F). A press
while a stimulus runs replaces it (new factor, 36 months from now) -- принято ночью, проверить.
No rate cut, no monetary expansion lock, no government fund lock: the button no longer
touches money. The bubble condition (E&F: bubble below 20) is dropped with them.

Writes common/scripted_guis/zz_pb_ef_speculative_pcs_sguis.txt and the button texts in
localization/<lang>/replace/zz_pb_ef_psc_l_<lang>.yml (english, russian; the other ten
languages get the English text, as the rest of that file).

Usage:  python3 tools/regen_ef_stimulus_buttons.py [--check]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
HOTFIX = REPO / "_ef" / "ef hotfix 1.13"
OUT_SGUI = HOTFIX / "common/scripted_guis/zz_pb_ef_speculative_pcs_sguis.txt"
LANGS = ["english", "russian", "braz_por", "french", "german", "japanese", "korean", "polish",
         "simp_chinese", "spanish", "turkish"]

STIMULUS_MONTHS = 36
COOLDOWN_MONTHS = 12
BUTTONS = [(9, 4, 10), (10, 3.5, 20), (11, 3, 30), (12, 2.5, 40)]  # button, factor, penalty

HEAD = f"""#############################################
# GENERATED by tools/regen_ef_stimulus_buttons.py -- do not edit by hand.
#
# pb+ef: player-side stimulus buttons 9-12 of E&F's Financial Stability
# Office journal (financial_center_je_2), clicked from
# gui/scripted_widgets/zz_pb_ef_fso_widgets.gui. E&F splits these in two:
# common/scripted_buttons/00_ef_buttons.txt is the AI branch (switched off here,
# scripted_buttons/zz_ef_buttons.txt), common/scripted_guis/00_financial_scripted_guis.txt
# the player branch.
#
# STR.4 (night G, 2026-10-03, decision D.13): a button lowers the factor of the
# construction-sector limit, urban centres x (1 - 5 x rate), for {STIMULUS_MONTHS} months:
#   button   factor   penalty   allowed while the penalty is below
""" + "".join(f"#    {b:2}      {m:<4}     +{p}        {100 - p}\n" for b, m, p in BUTTONS) + f"""# var:zz_pb_ef_stimulus_mult (timed), read by zz_pb_ef_css_rate_mult in
# script_values/zz_pb_ef_overbuild_values.txt. Cooldown {COOLDOWN_MONTHS} months
# (speculative_share_modifier_5, as E&F). A press while a stimulus runs replaces it.
# History: 2026-09-25 a pure rate cut with a price; 2026-09-30 switched off (under
# EF.30 the central bank walked the cut back); 2026-10-03 this.
# Texts: localization/*/replace/zz_pb_ef_psc_l_*.yml (same generator).
#############################################
"""


def sgui(b: int, m: float, p: int) -> str:
    return f"""
REPLACE_OR_CREATE:speculative_share_{b}_button = {{ ### stimulus: limit factor {m:g} for {STIMULUS_MONTHS} months, +{p} penalty
	name = "speculative_share_{b}_button"
	desc = "speculative_share_{b}_button_desc"

	is_valid = {{
		NOT = {{
			has_modifier = speculative_share_modifier_5
		}}
		has_modifier = has_financial_center
		custom_tooltip = {{
			text = speculative_share_{b}_button_tt_1
			var:speculative_share_2 < {100 - p}
		}}
	}}

	effect = {{
		add_modifier = {{
			name = speculative_share_modifier_5
			months = {COOLDOWN_MONTHS}
		}}
		custom_tooltip = {{
			text = speculative_share_{b}_button_tt_effect_1
		}}
		set_variable = {{
			name = zz_pb_ef_stimulus_mult
			value = {m:g}
			days = {STIMULUS_MONTHS * 30}
		}}
		change_variable = {{
			name = speculative_share_2
			add = {p}
		}}
		if = {{
			limit = {{ var:speculative_share_2 > 100 }}
			set_variable = {{
				name = speculative_share_2
				value = 100
			}}
		}}
	}}
}}
"""


def loc_lines(lang: str) -> list[str]:
    ru = lang == "russian"
    out = ["  # STR.4 (2026-10-03): stimulus buttons 9-12 change the sector limit factor -- tools/regen_ef_stimulus_buttons.py"]
    for b, m, p in BUTTONS:
        if ru:
            desc = (f"Правительство стимулирует частное строительство: на #b {STIMULUS_MONTHS} месяцев#! лимит "
                    f"строительных секторов меньше зависит от ключевой ставки — городские центры × (1 − #b {m:g}#! × ставка) "
                    f"вместо × (1 − 5 × ставка). Лишние частные секторы перегружают экономику: штраф избыточных "
                    f"строительных мощностей растёт на #b {p}#! пунктов и затем возвращается к цели. Повторное нажатие "
                    f"во время стимула заменяет его.")
            tt1 = (f"Штраф избыточных строительных мощностей ниже #b {100 - p}#! (сейчас: #b "
                   f"[GetPlayer.MakeScope.Var('speculative_share_2').GetValue|0]#!)")
            eff1 = f"Множитель ставки в лимите строительных секторов — #b {m:g}#! вместо 5 на #b {STIMULUS_MONTHS} месяцев#!."
            eff = (f"- $speculative_share_{b}_button_tt_effect_1$\\n- Штраф избыточных строительных мощностей #r +{p}#! "
                   f"(не выше 100)\\n- [GetPlayer.GetName] получает [GetStaticModifier('speculative_share_modifier_5').GetName|v] "
                   f"на {COOLDOWN_MONTHS} месяцев")
            tt = (f"$speculative_share_{b}_button$\\n\\n$speculative_share_{b}_button_desc$\\n\\nВозможно, если:\\n- Нет "
                  f"модификатора [GetStaticModifier('speculative_share_modifier_5').GetName|v]\\n- Есть модификатор "
                  f"[GetStaticModifier('has_financial_center').GetName|v]\\n- $speculative_share_{b}_button_tt_1$\\n\\n"
                  f"Эффект:\\n$speculative_share_{b}_button_tt_effect_1_1$")
        else:
            desc = (f"The government stimulates private construction: for #b {STIMULUS_MONTHS} months#! the limit of "
                    f"construction sectors depends less on the base rate -- urban centres × (1 − #b {m:g}#! × rate) instead "
                    f"of × (1 − 5 × rate). The extra private sectors overload the economy: the overbuilt economy penalty "
                    f"rises by #b {p}#! points and then returns to its target. Pressing again while a stimulus runs "
                    f"replaces it.")
            tt1 = (f"Overbuilt economy penalty below #b {100 - p}#! (current: #b "
                   f"[GetPlayer.MakeScope.Var('speculative_share_2').GetValue|0]#!)")
            eff1 = f"The rate factor in the construction sector limit is #b {m:g}#! instead of 5 for #b {STIMULUS_MONTHS} months#!."
            eff = (f"- $speculative_share_{b}_button_tt_effect_1$\\n- Overbuilt economy penalty #r +{p}#! (at most 100)"
                   f"\\n- [GetPlayer.GetName] gets [GetStaticModifier('speculative_share_modifier_5').GetName|v] for "
                   f"{COOLDOWN_MONTHS} months")
            tt = (f"$speculative_share_{b}_button$\\n\\n$speculative_share_{b}_button_desc$\\n\\nPossible:\\n- Not has "
                  f"[GetStaticModifier('speculative_share_modifier_5').GetName|v] modifier\\n- "
                  f"[GetStaticModifier('has_financial_center').GetName|v] modifier\\n- $speculative_share_{b}_button_tt_1$"
                  f"\\n\\nEffect:\\n$speculative_share_{b}_button_tt_effect_1_1$")
        out += [f'  speculative_share_{b}_button_desc: "{desc}"',
                f'  speculative_share_{b}_button_tt_1: "{tt1}"',
                f'  speculative_share_{b}_button_tt_effect_1: "{eff1}"',
                f'  speculative_share_{b}_button_tt_effect_1_1: "{eff}"',
                f'  speculative_share_{b}_button_tt: "{tt}"']
    return out


KEY_RE = re.compile(r"^\s*(?:# 2026-09-25: stimulus buttons|# STR\.4 \(2026-10-03\): stimulus buttons|"
                    r"speculative_share_(?:9|1[0-2])_button_(?:desc|tt_1|tt_effect_1|tt_effect_1_1|tt):)")


def patch_loc(lang: str, check: bool) -> bool:
    path = HOTFIX / f"localization/{lang}/replace/zz_pb_ef_psc_l_{lang}.yml"
    raw = path.read_bytes()
    text = raw.decode("utf-8-sig")
    lines = text.split("\n")
    idx = [i for i, l in enumerate(lines) if KEY_RE.match(l)]
    assert idx, f"{path}: no stimulus button lines"
    first = idx[0]
    kept = [l for i, l in enumerate(lines) if i not in set(idx)]
    new = kept[:first] + loc_lines(lang) + kept[first:]
    data = b"\xef\xbb\xbf" + "\n".join(new).encode("utf-8")
    if check:
        print(f"  {'SAME ' if data == raw else 'DRIFT'} {path.relative_to(REPO)}")
        return data == raw
    path.write_bytes(data)
    print(f"  wrote {path.relative_to(REPO)}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = HEAD + "".join(sgui(*x) for x in BUTTONS)
    assert text.count("{") == text.count("}")
    data = b"\xef\xbb\xbf" + text.encode("utf-8")
    ok = True
    if a.check:
        same = OUT_SGUI.read_bytes() == data
        print(f"  {'SAME ' if same else 'DRIFT'} {OUT_SGUI.relative_to(REPO)}")
        ok &= same
    else:
        OUT_SGUI.write_bytes(data)
        print(f"  wrote {OUT_SGUI.relative_to(REPO)}")
    for lang in LANGS:
        ok &= patch_loc(lang, a.check)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
