#!/usr/bin/env python3
"""
EF.48 (the user, 1.10 night): E&F's currency interventions in our money's scale.

E&F (scripted_effects/01_economic_scripted_effects.txt) has one buy_<currency>_currency
effect per currency (95): a central bank buys an undervalued currency (value under 75% of
its parity) from its issuer for metal. The quantity is random, { 1000000 10000000 } units --
the scale of E&F's own money (~1 billion), while the money in circulation is now the engine's
(~25 times smaller: Britain's M2 15-40M). One deal moved the cover by tens of percent (run 16:
France 105%, Russia 2%). The quantity becomes zz_ef_fx_deal_size of the issuer -- a share of
its M2 (script_values/zz_ef_money_model_values.txt). The sell_* effects sell half of what a
bank holds -- proportional already, kept.

Writes _ef/ef hotfix 1.13/common/scripted_effects/zz_ef_fx_deals.txt: every buy_<currency>_currency
as E&F has it, key-level REPLACE_OR_CREATE, with the one line changed.

Usage:
    py tools/regen_ef_fx_deals.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, r"..\..\vic3_mods_out\E&F\common\scripted_effects\01_economic_scripted_effects.txt"))
OUT = os.path.normpath(os.path.join(HERE, r"..\_ef\ef hotfix 1.13\common\scripted_effects\zz_ef_fx_deals.txt"))

RANDOM = "value = { 1000000 10000000 }"
SCALED = "value = scope:undervalued_currency_country_owner.zz_ef_fx_deal_size"


def blocks(text):
    """(name, body) of every top-level buy_<currency>_currency = { ... } (indented by one tab in E&F)."""
    for m in re.finditer(r"^\t?(buy_[a-z_]+_currency) = \{", text, re.M):
        start = m.start()
        i = text.index("{", m.start())
        depth = 0
        for j in range(i, len(text)):
            if text[j] == "{":
                depth += 1
            elif text[j] == "}":
                depth -= 1
                if depth == 0:
                    yield m.group(1), text[i:j + 1]
                    break


def main():
    text = open(SRC, encoding="utf-8-sig").read()
    out = ["# GENERATED by tools/regen_ef_fx_deals.py -- do not edit by hand.\n"
           "# EF.48: E&F's buy_<currency>_currency with the deal size in our money's scale\n"
           "# (zz_ef_fx_deal_size of the issuer) instead of a random 1-10 million units.\n"
           "# !! MAINTENANCE !! Key-level REPLACE_OR_CREATE of E&F's effects: regenerate after an E&F update.\n\n"]
    n = 0
    for name, body in blocks(text):
        if RANDOM not in body:
            continue
        assert body.count(RANDOM) == 1, name
        out.append(f"REPLACE_OR_CREATE:{name} = {body.replace(RANDOM, SCALED)}\n\n")
        n += 1
    assert n >= 90, n
    with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write("".join(out))
    print("ok", n, "effects ->", OUT)
    write_fx_reserves(sorted(set(re.findall(r"^\t?buy_([a-z_]+)_currency = \{", text, re.M))))


OUT_SV = os.path.normpath(os.path.join(HERE, r"..\_ef\ef hotfix 1.13\common\script_values\zz_ef_fx_reserves_values.txt"))


def write_fx_reserves(currencies):
    """Foreign currency in the CB's reserves, in metal: every currency but the country's own,
    E&F's stockpiling_<cur>_state (bought in interventions + earned by exports as reserve currency)
    x money_value_<cur> (E&F's value of the currency, metal per unit)."""
    lines = ["# GENERATED by tools/regen_ef_fx_deals.py -- do not edit by hand.\n"
             "# EF.48 (the user, 1.10 night): foreign currency in the CB's reserves, in metal.\n"
             "zz_ef_fx_reserves_metal = {\n\tvalue = 0\n"]
    for c in currencies:
        lines.append(f"\tif = {{ limit = {{ NOT = {{ has_law = law_type:law_{c}_currency }} stockpiling_{c}_state > 0 }} "
                     f"add = {{ value = stockpiling_{c}_state multiply = money_value_{c} }} }}\n")
    lines.append("\tmin = 0\n}\n")
    with open(OUT_SV, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write("".join(lines))
    print("ok", len(currencies), "currencies ->", OUT_SV)


if __name__ == "__main__":
    main()
