#!/usr/bin/env python3
"""
П.6 (the user, 4.10, decisions В.2 / В.3): the world clearing of payments with abroad.

Was (Hume, EF.48 item 6): each country's CB metal moved by its own net flow with abroad (zz_ef_ext_net_week)
with nobody on the other side -- the world's metal was not conserved, it piled up at the big exporters
(night 4.10: Britain x9, Russia x10) and Qing lost all. В2.1 (zz_ef_rc_step, monthly) swapped part of the
exporters' metal for the importers' currency pair by pair on top of it.

Now one clearing house for the world (global variables), in gold:
  * a country with a net OUTFLOW pays it in full into the clearing house: the share in metal by trust in its
    currency (zz_ef_clr_metal_share: 100% at strength to the reference < 0.75, 30% at >= 1.25, linear between),
    at most the metal its CB holds; the rest in its own currency (units of its money, E&F's
    stockpiling_<currency> scale). Fiat: currency only.
  * a country with a net INFLOW takes its inflow x the clearing ratio, at most what the house holds, as an equal
    slice of everything in it: metal into its CB, each foreign currency into its CB's stock
    (stockpiling_<currency>_state_1 on the CB capital state); its own currency coming home is redeemed
    (taken out of the house, a debt abroad gone).
  * the ratio: the countries' weekly steps are spread over the month (no common weekly tick), so the house
    works in windows of 7 days (global var zz_ef_clr_window; R1а.4: the fork's scheduler opens each window at the
    end of its week, the var lives 9 days as a fallback): at a window's start the ratio = what the
    house holds / the inflows claimed during the window before (at most 2); with world payments = world claims
    it is 1. Metal and currency only move between the CBs and the house: nothing appears from nowhere.

П.8 (В.5): E&F's table "currency in the trade balance" (its trade reserve, zeroed by В2.1 -- empty) shows the CB's
foreign currency by currency instead: units, in money, in gold, the week's change (zz_ef_cbfx_*; the list is
filled by our scripted GUI zz_ef_cbfx_update, the table re-issued by ld_economy_panel.gui форка, правится руками).

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys):
  common/scripted_effects/ld_clearing.txt, common/script_values/ld_clearing_values.txt,
  common/scripted_guis/ld_cbfx.txt, localization/{english,russian}/ld_cbfx_l_*.yml
Reads the list of currencies from ld_curdata (the fork's currency laws).

Usage:
    python3 tools/regen_ef_clearing.py [--check]
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ld_gen  # noqa: E402
from ld_curdata import currencies  # noqa: E402
from regen_ef_reserve_trade import chain  # noqa: E402

# hotfix paths; ld_gen writes into the fork (ld_clearing.txt, ld_clearing_values.txt, ld_cbfx.txt, ld_cbfx_l_*.yml)
OUT_EFF = "common/scripted_effects/zz_ef_clearing.txt"
OUT_SV = "common/script_values/zz_ef_clearing_values.txt"
OUT_SG = "common/scripted_guis/zz_ef_cbfx.txt"
LANGS = ["english", "russian", "braz_por", "french", "german", "japanese",
         "korean", "polish", "simp_chinese", "spanish", "turkish"]

HEAD = ("# GENERATED by tools/regen_ef_clearing.py -- do not edit by hand.\n"
        "# the world clearing of payments with abroad -- see the generator's docstring.\n")

STEP = """
# The window of the clearing house (7 days): at its start the ratio for the claims of the window.
zz_ef_clr_window_roll = {
	if = {
		limit = { NOT = { has_global_variable = zz_ef_clr_window } }
		set_global_variable = { name = zz_ef_clr_window value = yes days = 9 }
		if = {
			limit = { NOT = { has_global_variable = zz_ef_clr_in_acc } }
			set_global_variable = { name = zz_ef_clr_in_acc value = 0 }
		}
		if = {
			limit = { NOT = { has_global_variable = zz_ef_clr_out_acc } }
			set_global_variable = { name = zz_ef_clr_out_acc value = 0 }
		}
		# the world's net flows do not add up to zero (trade at different markets'
		# prices, countries without a CB), so both sides are scaled. Receivers take at most what the house holds
		# against last window's claims (up to 1.5); payers pay the share that keeps the house near twice a
		# window's claims: min(1, (2 x claims - held) / payments). On random flows (in = out) a receiver gets
		# ~0.8-0.9 of its inflow and the house stays bounded; was: receivers 20% (clr1), the house 187M (clr2).
		set_global_variable = { name = zz_ef_clr_ratio value = 1 }
		set_global_variable = { name = zz_ef_clr_pay_ratio value = 1 }
		if = {
			limit = { global_var:zz_ef_clr_in_acc > 0 }
			set_global_variable = {
				name = zz_ef_clr_ratio
				value = {
					value = zz_ef_clr_pot_value
					divide = global_var:zz_ef_clr_in_acc
					max = zz_ef_clr_take_max
					min = 0
				}
			}
		}
		if = {
			limit = { global_var:zz_ef_clr_out_acc > 0 }
			set_global_variable = {
				name = zz_ef_clr_pay_ratio
				value = {
					value = global_var:zz_ef_clr_in_acc
					multiply = zz_ef_clr_pot_target
					subtract = zz_ef_clr_pot_value
					divide = global_var:zz_ef_clr_out_acc
					max = 1
					min = 0
				}
			}
		}
		# the window just closed, for the tooltip
		set_global_variable = { name = zz_ef_clr_in_last value = global_var:zz_ef_clr_in_acc }
		set_global_variable = { name = zz_ef_clr_out_last value = global_var:zz_ef_clr_out_acc }
		set_global_variable = { name = zz_ef_clr_in_acc value = 0 }
		set_global_variable = { name = zz_ef_clr_out_acc value = 0 }
	}
}

# COUNTRY scope, from zz_ef_cb_hume_step: the week's net flow var:zz_ef_f_ext_net settled through the house.
# Leaves var:zz_ef_f_hume (the CB's metal, native, + in / - out), var:zz_ef_f_clr_cur_out (own currency paid,
# money), var:zz_ef_f_clr_fx_in (foreign currency received, gold), var:zz_ef_f_clr_own_back (own currency
# redeemed, money).
# В1.7 and В1.6 items 2-3: one position per pegged subject / market. A subject on the external exchange standard
# (pegged to its overlord, Д.R8а.3), and a country with no value of its own money in gold that
# does not own its market, do not settle themselves: the week's flow goes, in gold at the head's price
# (zz_ef_clr_gold_per_money), to the head -- the overlord / the market owner (var:zz_ef_clr_head) -- which settles
# it with its own next week (var:zz_ef_clr_sub_g, gold); otherwise their flows would be in neither the world's sum
# nor the clearing.
# var:zz_ef_f_clr_net -- what this country settles (its flow + its members', money; 0 for a member).
zz_ef_clr_step = {
	set_variable = { name = zz_ef_f_hume value = 0 }
	set_variable = { name = zz_ef_f_clr_cur_out value = 0 }
	set_variable = { name = zz_ef_f_clr_fx_in value = 0 }
	set_variable = { name = zz_ef_f_clr_own_back value = 0 }
	set_variable = { name = zz_ef_f_clr_net value = var:zz_ef_f_ext_net }
	set_variable = { name = zz_ef_f_clr_sub value = 0 }
	set_variable = { name = zz_ef_f_clr_sent value = 0 }
	# the head's price of gold per unit, one pass of the 95-branch chain for the whole step (and zz_ef_clr_pay / _receive):
	# nothing in the step changes its inputs (the laws, the parity, the currencies' values, the zone, the world's average)
	set_variable = { name = zz_ef_t_gpm value = zz_ef_clr_gold_per_money }
	# the members' flows sent since our last step
	if = {
		limit = { has_variable = zz_ef_clr_sub_g }
		set_variable = { name = zz_ef_f_clr_sub value = var:zz_ef_clr_sub_g }
		if = {
			limit = { var:zz_ef_t_gpm > 0 }
			change_variable = {
				name = zz_ef_f_clr_net
				add = {
					value = var:zz_ef_clr_sub_g
					divide = var:zz_ef_t_gpm
				}
			}
		}
		remove_variable = zz_ef_clr_sub_g
	}
	zz_ef_clr_head_find = yes
	if = {
		limit = { has_variable = zz_ef_clr_head }
		set_variable = { name = zz_ef_f_clr_sent value = var:zz_ef_f_clr_net }
		set_variable = {
			name = zz_ef_clr_send_g
			value = {
				value = var:zz_ef_f_clr_net
				multiply = var:zz_ef_t_gpm
			}
		}
		save_scope_as = clr_member
		var:zz_ef_clr_head = {
			if = {
				limit = { NOT = { has_variable = zz_ef_clr_sub_g } }
				set_variable = { name = zz_ef_clr_sub_g value = 0 }
			}
			change_variable = { name = zz_ef_clr_sub_g add = scope:clr_member.var:zz_ef_clr_send_g }
		}
		remove_variable = zz_ef_clr_send_g
		set_variable = { name = zz_ef_f_clr_net value = 0 }
	}
	else_if = {
		limit = {
			has_modifier = has_central_bank
			var:zz_ef_t_gpm > 0
			any_scope_state = {
				has_modifier = central_bank_historic_place
				is_capital = yes
			}
		}
		zz_ef_clr_window_roll = yes
		if = {
			limit = { var:zz_ef_f_clr_net < 0 }
			zz_ef_clr_pay = yes
		}
		else_if = {
			limit = { var:zz_ef_f_clr_net > 0 }
			zz_ef_clr_receive = yes
		}
	}
	# a country without a CB pays its outflow too -- in its currency only (no metal reserves);
	# it takes nothing (no CB to hold it). Its payments were counted as the receivers' inflow (subjects' tribute,
	# the East India Company -> Britain's diplomatic pacts +112K a week) with nothing paid into the house:
	# receivers got 15-40% of their claims. A subject on its overlord's currency pays in that currency, which
	# comes home to the overlord and is redeemed -- nothing out of nothing.
	else_if = {
		limit = {
			NOT = { has_modifier = has_central_bank }
			zz_ef_has_currency_value = yes
			var:zz_ef_f_clr_net < 0
		}
		zz_ef_clr_window_roll = yes
		zz_ef_clr_pay = yes
	}
}

# var:zz_ef_clr_head -- who settles for us (zz_ef_clr_step), or none: the overlord of a pegged subject; else, with
# no value of our money in gold, the market's owner if its money has one.
zz_ef_clr_head_find = {
	if = {
		limit = { has_variable = zz_ef_clr_head }
		remove_variable = zz_ef_clr_head
	}
	if = {
		limit = {
			has_law = law_type:law_external_exchange_standard
			is_subject = yes
		}
		set_variable = { name = zz_ef_clr_head value = overlord }
	}
	else_if = {
		limit = {
			NOT = { zz_ef_clr_gpm_own > 0 }
			exists = market
			NOT = { market.owner = this }
			market.owner = { zz_ef_clr_gpm_own > 0 }
		}
		market = { owner = { save_scope_as = clr_head_s } }
		set_variable = { name = zz_ef_clr_head value = scope:clr_head_s }
	}
}

zz_ef_clr_pay = {
	# the whole outflow in gold
	set_variable = {
		name = zz_ef_clr_due
		value = {
			value = var:zz_ef_f_clr_net
			multiply = -1
			multiply = var:zz_ef_t_gpm
		}
	}
	# the world's claims see the whole outflow; the payment is its share (П.6а)
	change_global_variable = { name = zz_ef_clr_out_acc add = var:zz_ef_clr_due }
	change_variable = { name = zz_ef_clr_due multiply = zz_ef_clr_pay_ratio_v }
	# the metal part, native (fiat: none), at most the CB's metal
	set_variable = { name = zz_ef_clr_metal value = 0 }
	if = {
		limit = {
			has_modifier = has_central_bank
			OR = {
				zz_ef_metal_gold = yes
				zz_ef_metal_silver = yes
				zz_ef_metal_bimet = yes
			}
			has_variable = money_value_target_1
			var:money_value_target_1 > 0
		}
		set_variable = {
			name = zz_ef_clr_metal
			value = {
				value = var:zz_ef_f_clr_net
				multiply = -1
				# the engine's money into the standard's metal at the fixed rate, not at the parity
				multiply = zz_ef_metal_per_money
				multiply = zz_ef_clr_metal_share
				multiply = zz_ef_clr_pay_ratio_v
				max = zz_ef_cb_metal
				min = 0
			}
		}
	}
	every_scope_state = {
		limit = {
			has_modifier = central_bank_historic_place
			is_capital = yes
		}
		if = {
			limit = { owner = { zz_ef_metal_silver = yes } }
			if = {
				limit = { NOT = { has_variable = silver_state_1 } }
				set_variable = { name = silver_state_1 value = 0 }
			}
			change_variable = { name = silver_state_1 subtract = owner.var:zz_ef_clr_metal }
		}
		else = {
			if = {
				limit = { NOT = { has_variable = gold_state_1 } }
				set_variable = { name = gold_state_1 value = 0 }
			}
			change_variable = { name = gold_state_1 subtract = owner.var:zz_ef_clr_metal }
		}
	}
	set_variable = { name = zz_ef_f_hume value = var:zz_ef_clr_metal }
	change_variable = { name = zz_ef_f_hume multiply = -1 }
	# the metal in gold into the house
	set_variable = { name = zz_ef_clr_mgold value = var:zz_ef_clr_metal }
	if = {
		limit = { zz_ef_metal_silver = yes }
		change_variable = { name = zz_ef_clr_mgold multiply = silver_to_gold_rate }
	}
	if = {
		limit = { NOT = { has_global_variable = zz_ef_clr_gold } }
		set_global_variable = { name = zz_ef_clr_gold value = 0 }
	}
	change_global_variable = { name = zz_ef_clr_gold add = var:zz_ef_clr_mgold }
	# the rest in the own currency, units of its engine money at its gold per unit (zz_ef_clr_gpm_own)
	set_variable = { name = zz_ef_clr_units value = 0 }
	if = {
		limit = {
			zz_ef_has_currency_value = yes
			var:zz_ef_clr_due > var:zz_ef_clr_mgold
		}
		set_variable = { name = zz_ef_clr_units value = var:zz_ef_clr_due }
		change_variable = { name = zz_ef_clr_units subtract = var:zz_ef_clr_mgold }
		change_variable = { name = zz_ef_clr_units divide = zz_ef_clr_gpm_own }
		zz_ef_clr_put_own = yes
	}
	set_variable = { name = zz_ef_f_clr_cur_out value = var:zz_ef_clr_units }
	remove_variable = zz_ef_clr_due
	remove_variable = zz_ef_clr_metal
	remove_variable = zz_ef_clr_mgold
	remove_variable = zz_ef_clr_units
}

zz_ef_clr_receive = {
	set_variable = {
		name = zz_ef_clr_claim
		value = {
			value = var:zz_ef_f_clr_net
			multiply = var:zz_ef_t_gpm
		}
	}
	change_global_variable = { name = zz_ef_clr_in_acc add = var:zz_ef_clr_claim }
	set_variable = { name = zz_ef_clr_pot value = zz_ef_clr_pot_value }
	if = {
		limit = { var:zz_ef_clr_pot > 0 }
		# the slice of everything in the house
		set_variable = {
			name = zz_ef_clr_g
			value = {
				value = var:zz_ef_clr_claim
				multiply = global_var:zz_ef_clr_ratio
				divide = var:zz_ef_clr_pot
				max = 1
				min = 0
			}
		}
		# metal: gold from the house, native into the CB
		set_variable = { name = zz_ef_clr_mgold value = 0 }
		if = {
			limit = { has_global_variable = zz_ef_clr_gold }
			set_variable = {
				name = zz_ef_clr_mgold
				value = {
					value = global_var:zz_ef_clr_gold
					multiply = var:zz_ef_clr_g
					min = 0
				}
			}
			change_global_variable = { name = zz_ef_clr_gold subtract = var:zz_ef_clr_mgold }
		}
		set_variable = { name = zz_ef_f_hume value = var:zz_ef_clr_mgold }
		if = {
			limit = { zz_ef_metal_silver = yes }
			change_variable = { name = zz_ef_f_hume multiply = gold_to_silver_rate }
		}
		every_scope_state = {
			limit = {
				has_modifier = central_bank_historic_place
				is_capital = yes
			}
			if = {
				limit = { owner = { zz_ef_metal_silver = yes } }
				if = {
					limit = { NOT = { has_variable = silver_state_1 } }
					set_variable = { name = silver_state_1 value = 0 }
				}
				change_variable = { name = silver_state_1 add = owner.var:zz_ef_f_hume }
			}
			else = {
				if = {
					limit = { NOT = { has_variable = gold_state_1 } }
					set_variable = { name = gold_state_1 value = 0 }
				}
				change_variable = { name = gold_state_1 add = owner.var:zz_ef_f_hume }
			}
			save_scope_as = clr_cb
		}
		# currencies
		save_scope_as = clr_rcv
		zz_ef_clr_take_all = yes
		remove_variable = zz_ef_clr_g
		remove_variable = zz_ef_clr_mgold
	}
	remove_variable = zz_ef_clr_claim
	remove_variable = zz_ef_clr_pot
}
"""


def effects(cur):
    out = [HEAD, STEP]
    out.append("\n# The payer's own currency into the house: var:zz_ef_clr_units of its money.\n"
               "zz_ef_clr_put_own = {\n")
    out.append(chain(cur, lambda c: (
        f"if = {{ limit = {{ NOT = {{ has_global_variable = zz_ef_clr_c_{c} }} }} "
        f"set_global_variable = {{ name = zz_ef_clr_c_{c} value = 0 }} }} "
        f"change_global_variable = {{ name = zz_ef_clr_c_{c} add = var:zz_ef_clr_units }}")))
    out.append("}\n")
    out.append("\n# scope:clr_rcv (the receiver), var:zz_ef_clr_g = its slice: each currency of the house -- its own\n"
               "# redeemed, a foreign one into its CB's stock (scope:clr_cb).\n"
               "zz_ef_clr_take_all = {\n")
    for c in cur:
        out.append(
            f"\tif = {{\n"
            f"\t\tlimit = {{ has_global_variable = zz_ef_clr_c_{c} global_var:zz_ef_clr_c_{c} > 0 }}\n"
            f"\t\tset_variable = {{ name = zz_ef_clr_u value = {{ value = global_var:zz_ef_clr_c_{c} multiply = var:zz_ef_clr_g }} }}\n"
            f"\t\tchange_global_variable = {{ name = zz_ef_clr_c_{c} subtract = var:zz_ef_clr_u }}\n"
            f"\t\tif = {{\n"
            f"\t\t\tlimit = {{ var:zz_ef_cur ?= flag:{c} }}\n"
            f"\t\t\tchange_variable = {{ name = zz_ef_f_clr_own_back add = var:zz_ef_clr_u }}\n"
            f"\t\t}}\n"
            f"\t\telse = {{\n"
            f"\t\t\tscope:clr_cb = {{\n"
            f"\t\t\t\tif = {{ limit = {{ NOT = {{ has_variable = stockpiling_{c}_state_1 }} }} set_variable = {{ name = stockpiling_{c}_state_1 value = 0 }} }}\n"
            f"\t\t\t\tchange_variable = {{ name = stockpiling_{c}_state_1 add = scope:clr_rcv.var:zz_ef_clr_u }}\n"
            f"\t\t\t}}\n"
            f"\t\t\tchange_variable = {{ name = zz_ef_f_clr_fx_in add = {{ value = var:zz_ef_clr_u multiply = zz_ef_fx_gold_{c} }} }}\n"
            f"\t\t}}\n"
            f"\t\tremove_variable = zz_ef_clr_u\n"
            f"\t}}\n")
    out.append("}\n")
    out.append("\n# the week's change of each foreign currency in the CB (country vars zz_ef_cbfx_d_<c>), from the\n"
               "# money model's weekly step.\n"
               "zz_ef_cbfx_week_step = {\n")
    for c in cur:
        out.append(f"\tif = {{ limit = {{ OR = {{ zz_ef_cbfx_{c} > 0 has_variable = zz_ef_cbfx_p_{c} }} }} "
                   f"set_variable = {{ name = zz_ef_cbfx_d_{c} value = zz_ef_cbfx_{c} }} "
                   f"if = {{ limit = {{ has_variable = zz_ef_cbfx_p_{c} }} change_variable = {{ name = zz_ef_cbfx_d_{c} subtract = var:zz_ef_cbfx_p_{c} }} }} "
                   f"set_variable = {{ name = zz_ef_cbfx_p_{c} value = zz_ef_cbfx_{c} }} }}\n")
    out.append("}\n")
    return "".join(out)


VALUES = """
# В.3: the payer's metal share by trust in its currency -- its strength against the reference
# (zz_ef_currency_strength): 100% under 0.75, 30% at 1.25 and over, linear between; the reference currency -- 30%.
zz_ef_clr_metal_share_low = 0.75
zz_ef_clr_metal_share_high = 1.25
zz_ef_clr_metal_share_min = 0.3
zz_ef_clr_metal_share = {
	value = zz_ef_currency_strength
	subtract = zz_ef_clr_metal_share_low
	divide = {
		value = zz_ef_clr_metal_share_high
		subtract = zz_ef_clr_metal_share_low
	}
	multiply = {
		value = 1
		subtract = zz_ef_clr_metal_share_min
	}
	multiply = -1
	add = 1
	max = 1
	min = zz_ef_clr_metal_share_min
	# the reference currency is taken abroad as it is -- the world holds pounds without asking the
	# Bank for gold at once: the reference pays the minimal metal share (its own strength is 1 by definition, it paid 65%,
	# and Britain's metal ran out in 1838 in run r1006_141714)
	if = {
		limit = { has_modifier = global_monetary_reference }
		value = zz_ef_clr_metal_share_min
	}
}
# Gold a unit of the scope country's money pays / claims abroad: its money against the parity (zz_ef_clr_gpm_own;
# a metal standard -- 1, as Hume settled). В1.6 items 2-3 (5.10): a country that settles through a
# head (zz_ef_clr_head_find) -- the head's: the zone's overlord, or, with no value of its own, its market's owner.
# The rest -- no price of its own nor its head's (a market with no currency, 121 of 269 countries in run s1e): the world's
# average, weighted by GDP.
zz_ef_clr_gold_per_money = {
	value = zz_ef_clr_gpm_head
	if = {
		limit = {
			NOT = { zz_ef_clr_gpm_head > 0 }
			has_global_variable = zz_ef_wld_gpm_avg
		}
		value = global_var:zz_ef_wld_gpm_avg
	}
	min = 0
}
zz_ef_clr_gpm_head = {
	value = zz_ef_clr_gpm_own
	if = {
		limit = {
			has_law = law_type:law_external_exchange_standard
			is_subject = yes
		}
		value = 0
		overlord = { add = zz_ef_clr_gpm_own }
	}
	else_if = {
		limit = {
			NOT = { zz_ef_clr_gpm_own > 0 }
			exists = market
			NOT = { market.owner = this }
		}
		value = 0
		market = { owner = { add = zz_ef_clr_gpm_own } }
	}
	min = 0
}
# ... the country's own
zz_ef_clr_gpm_own = {
	# gold per unit of the engine's money of the country: its money against the parity (Д.R8а.4; a metal standard -- 1);
	# no monetary system -- no money of its own, 0 (the market's owner's then)
	value = 0
	if = {
		limit = { zz_ef_has_currency_value = yes }
		value = zz_ef_value_to_parity
	}
}
# The week's results (0 if unset), for the cards and the log.
zz_ef_v_f_clr_cur_out = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_clr_cur_out } value = var:zz_ef_f_clr_cur_out }
}
zz_ef_v_f_clr_fx_in = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_clr_fx_in } value = var:zz_ef_f_clr_fx_in }
}
zz_ef_v_f_clr_own_back = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_clr_own_back } value = var:zz_ef_f_clr_own_back }
}
# the foreign currency received, in the receiver's money (gold / its gold a unit)
zz_ef_v_f_clr_fx_in_money = {
	value = 0
	if = {
		limit = { zz_ef_clr_gold_per_money > 0 }
		value = zz_ef_v_f_clr_fx_in
		divide = zz_ef_clr_gold_per_money
	}
}
# the house's limits -- receivers take at most 1.5 of their claim; payers keep the house near 2 windows' claims
zz_ef_clr_take_max = 1.5
zz_ef_clr_pot_target = 2
zz_ef_clr_pay_ratio_v = {
	value = 1
	if = { limit = { has_global_variable = zz_ef_clr_pay_ratio } value = global_var:zz_ef_clr_pay_ratio }
}
# this receiver's clearing, in money (the abroad card's reserve assets, П.17): metal at the parity, currency
zz_ef_v_f_clr_metal_money = {
	value = 0
	if = {
		limit = { has_variable = zz_ef_f_hume has_variable = money_value_target_1 var:money_value_target_1 > 0 }
		value = var:zz_ef_f_hume
		divide = zz_ef_cb_valuation
	}
}
zz_ef_v_f_clr_fx_money = {
	value = 0
	if = {
		limit = { zz_ef_clr_gold_per_money > 0 }
		value = zz_ef_v_f_clr_fx_in
		divide = zz_ef_clr_gold_per_money
	}
	subtract = zz_ef_v_f_clr_cur_out
	add = zz_ef_v_f_clr_own_back
}
# the reserves' change by the clearing and what the clearing did not settle this week (the BoP's errors and omissions)
zz_ef_v_f_clr_reserves_money = {
	value = zz_ef_v_f_clr_metal_money
	add = zz_ef_v_f_clr_fx_money
}
zz_ef_v_f_clr_unsettled = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_clr_net } value = var:zz_ef_f_clr_net }
	subtract = zz_ef_v_f_clr_reserves_money
}
zz_ef_clr_ratio_v = {
	value = 1
	if = { limit = { has_global_variable = zz_ef_clr_ratio } value = global_var:zz_ef_clr_ratio }
}
# the window just closed (world inflows claimed / payments made, gold), for the tooltip
zz_ef_clr_in_last_v = {
	value = 0
	if = { limit = { has_global_variable = zz_ef_clr_in_last } value = global_var:zz_ef_clr_in_last }
}
zz_ef_clr_out_last_v = {
	value = 0
	if = { limit = { has_global_variable = zz_ef_clr_out_last } value = global_var:zz_ef_clr_out_last }
}
# for the monthly log: 1 for a customs union member that settles with the market owner (В3.3)
zz_ef_cu_member_v = {
	value = 0
	if = { limit = { zz_ef_cu_member = yes } value = 1 }
}
# the amount of the player's currency on a holder (zz_ef_holders_update), for ordering the list
zz_ef_holds_pc_v = {
	value = 0
	if = { limit = { has_variable = zz_ef_holds_pc } value = var:zz_ef_holds_pc }
}
# the members' flows settled with ours (gold) / our flow sent to the head (money), for the log
zz_ef_v_f_clr_sub = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_clr_sub } value = var:zz_ef_f_clr_sub }
}
zz_ef_v_f_clr_sent = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_clr_sent } value = var:zz_ef_f_clr_sent }
}
zz_ef_clr_gold_v = {
	value = 0
	if = { limit = { has_global_variable = zz_ef_clr_gold } value = global_var:zz_ef_clr_gold }
}
"""


def values(cur):
    out = [HEAD, VALUES]
    out.append("# Everything the house holds, in gold: metal + each currency at its issuer's value (zz_ef_fx_gold_<cur>: the engine's\n"
               "# money against the parity, as the clearing's own unit zz_ef_clr_gpm_own, Д.R8а.4).\n"
               "zz_ef_clr_pot_value = {\n\tvalue = zz_ef_clr_gold_v\n")
    for c in cur:
        out.append(f"\tif = {{ limit = {{ has_global_variable = zz_ef_clr_c_{c} }} add = {{ value = global_var:zz_ef_clr_c_{c} "
                   f"multiply = zz_ef_fx_gold_{c} min = 0 }} }}\n")
    out.append("\tmin = 0\n}\n")
    out.append("# The scope country's own currency waiting in the house (its money): a debt abroad, as zz_ef_fx_liab.\n"
               "zz_ef_clr_own_in_pot = {\n\tvalue = 0\n")
    out.append(chain(cur, lambda c: f"if = {{ limit = {{ has_global_variable = zz_ef_clr_c_{c} }} value = global_var:zz_ef_clr_c_{c} }}"))
    out.append("\tmin = 0\n}\n")
    out.append("\n# the CB's stock of each foreign currency (the capital CB state, as the clearing and В2.1 keep it):\n"
               "# units, in gold (the issuer's value, zz_ef_fx_gold_<cur>), in the holder's money, the week's change.\n")
    for c in cur:
        out.append(f"zz_ef_cbfx_{c} = {{ value = 0 capital = {{ if = {{ limit = {{ has_variable = stockpiling_{c}_state_1 }} "
                   f"add = var:stockpiling_{c}_state_1 }} }} min = 0 }}\n"
                   f"zz_ef_cbfx_{c}_gold = {{ value = zz_ef_cbfx_{c} multiply = zz_ef_fx_gold_{c} }}\n"
                   f"zz_ef_cbfx_{c}_money = {{ value = 0 if = {{ limit = {{ zz_ef_clr_gold_per_money > 0 }} "
                   f"value = zz_ef_cbfx_{c}_gold divide = zz_ef_clr_gold_per_money }} }}\n"
                   f"zz_ef_cbfx_{c}_d = {{ value = 0 if = {{ limit = {{ has_variable = zz_ef_cbfx_d_{c} }} value = var:zz_ef_cbfx_d_{c} }} }}\n")
    return "".join(out)


def sguis(cur):
    out = [HEAD]
    # П.16: the same list sorted by the stock's value in gold, the biggest first (selection: the largest not yet
    # listed, again and again)
    out.append("\n# E&F's table sorted by value in gold, the biggest first.\n"
               "zz_ef_cbfx_update_sorted = {\n\teffect = {\n\t\tclear_global_variable_list = zz_ef_cbfx_list\n"
               "\t\tset_variable = { name = zz_ef_cbfx_n value = 0 }\n")
    for c in cur:
        out.append(f"\t\tif = {{ limit = {{ zz_ef_cbfx_{c}_gold > 0 NOT = {{ var:zz_ef_cur ?= flag:{c} }} }} "
                   f"change_variable = {{ name = zz_ef_cbfx_n add = 1 }} set_variable = {{ name = zz_ef_cbfx_left_{c} value = yes }} }}\n")
    out.append("\t\twhile = {\n\t\t\tlimit = { var:zz_ef_cbfx_n > 0 }\n"
               "\t\t\tset_variable = { name = zz_ef_cbfx_max value = -1 }\n")
    for c in cur:
        out.append(f"\t\t\tif = {{ limit = {{ has_variable = zz_ef_cbfx_left_{c} zz_ef_cbfx_{c}_gold > var:zz_ef_cbfx_max }} "
                   f"set_variable = {{ name = zz_ef_cbfx_max value = zz_ef_cbfx_{c}_gold }} }}\n")
    out.append("\t\t\tset_variable = { name = zz_ef_cbfx_done value = no }\n")
    for c in cur:
        out.append(f"\t\t\tif = {{ limit = {{ var:zz_ef_cbfx_done = no has_variable = zz_ef_cbfx_left_{c} zz_ef_cbfx_{c}_gold >= var:zz_ef_cbfx_max }} "
                   f"add_to_global_variable_list = {{ name = zz_ef_cbfx_list target = global_var:currency_import_export_value_{c}_03 }} "
                   f"remove_variable = zz_ef_cbfx_left_{c} set_variable = {{ name = zz_ef_cbfx_done value = yes }} }}\n")
    out.append("\t\t\tchange_variable = { name = zz_ef_cbfx_n subtract = 1 }\n\t\t}\n"
               "\t\tremove_variable = zz_ef_cbfx_n\n\t\tremove_variable = zz_ef_cbfx_max\n\t\tremove_variable = zz_ef_cbfx_done\n"
               "\t}\n}\n")
    # П.18: who holds our currency -- the other CBs' stocks of the player's currency, for a pie chart
    out.append("\n# the other CBs holding the player's currency (global list zz_ef_holders_list; the amount\n"
               "# in the player's money on each holder, var:zz_ef_holds_pc), for the pie chart in the trade balance.\n"
               "# biggest holder first -- the amounts are set first, then ordered_country fills the list.\n"
               "zz_ef_holders_update = {\n\teffect = {\n\t\tclear_global_variable_list = zz_ef_holders_list\n"
               "\t\tsave_scope_as = holders_root\n"
               "\t\tevery_country = { limit = { has_variable = zz_ef_holds_pc } remove_variable = zz_ef_holds_pc }\n")
    for i, c in enumerate(cur):
        kw = "if" if i == 0 else "else_if"
        out.append(f"\t\t{kw} = {{ limit = {{ var:zz_ef_cur ?= flag:{c} }} every_country = {{ limit = {{ NOT = {{ this = scope:holders_root }} "
                   f"NOT = {{ var:zz_ef_cur ?= flag:{c} }} has_modifier = has_central_bank capital = {{ has_variable = stockpiling_{c}_state_1 "
                   f"var:stockpiling_{c}_state_1 > 0 }} }} set_variable = {{ name = zz_ef_holds_pc value = capital.var:stockpiling_{c}_state_1 }} }} }}\n")
    out.append("\t\tordered_country = { limit = { has_variable = zz_ef_holds_pc } order_by = zz_ef_holds_pc_v max = 1000 check_range_bounds = no "
               "add_to_global_variable_list = { name = zz_ef_holders_list target = this } }\n")
    out.append("\t}\n}\n")
    return "".join(out)


def write_loc(cur):
    for lang in LANGS:
        ru = lang == "russian"
        w = "за неделю" if ru else "a week"
        sv = lambda n: f"[GetPlayer.MakeScope.ScriptValue('{n}')"
        lines = [f"l_{lang}:\n",
                 ' zz_ef_ep_cbfx_title:0 "%s"\n' % ("Резервы ЦБ по валютам" if ru else "CB reserves by currency"),
                 ' zz_ef_ep_cbfx_tt:0 "%s"\n' % (
                     "Чужая валюта в резервах ЦБ (мировой клиринг): количество, в наших деньгах, в золоте и изменение "
                     "за неделю. В подсказке денежной массы она в счёте «Заграница» и учтена в покрытии." if ru else
                     "Foreign currency in the CB's reserves (the world clearing): units, in our money, in gold and the "
                     "week's change. In the money supply tooltip it is in the 'Abroad' account and counts in the cover.")]
        for c in cur:
            lines.append(f' {c}_03_zz_cbfx_units:0 "#v {sv("zz_ef_cbfx_" + c)}|D]#! @{c}!"\n')
            lines.append(f' {c}_03_zz_cbfx_money:0 "{sv("zz_ef_cbfx_" + c + "_money")}|D] [GetPlayer.GetCustom(\'currency_symbol\')]"\n')
            lines.append(f' {c}_03_zz_cbfx_gold:0 "{sv("zz_ef_cbfx_" + c + "_gold")}|D] @gold! ({sv("zz_ef_cbfx_" + c + "_d")}|+D] {w})"\n')
        ld_gen.emit(f"localization/{lang}/zz_ef_cbfx_l_{lang}.yml", "".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    cur = currencies()
    write_loc(cur)
    for path, text in ((OUT_EFF, effects(cur)), (OUT_SV, values(cur)), (OUT_SG, sguis(cur))):
        assert text.count("{") == text.count("}"), path
        ld_gen.emit(path, text)
    ld_gen.report("regen_ef_clearing")


if __name__ == "__main__":
    main()
