#!/usr/bin/env python3
"""
A customs union member keeps its own currency (EF.48, В3.3).

The customs union member's own currency: money_value and money_value_in_gold (E&F, 00_economic_scripted_value.txt)
are edited in the fork's E&F file by hand, with the trigger zz_ef_currency_own in place of market_owner_is_root_4.
The trade of the countries of one market -- by their shares of it (Д.R8в.1, regen_ld_market_shares.py).

Generated:
  * zz_ef_cu_member / zz_ef_currency_own (scripted triggers): the country owns its market, or it is a member
    with a CB that is not a subject (is_subject_custom_trigger = no; subjects -- the suzerain's currency, В3.2).

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys): common/scripted_triggers/ld_customs_union_triggers.txt

Usage:
    python3 tools/regen_ef_customs_union.py [--check]
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

OUT_TR = "common/scripted_triggers/zz_ef_customs_union_triggers.txt"

HEAD = ("# GENERATED by tools/regen_ef_customs_union.py -- do not edit by hand.\n"
        "# a customs union member's own currency -- see the generator.\n")


TRIGGERS = HEAD + """
# A customs union member with a currency of its own: in a market it does not own, with a central bank,
# not a subject (subjects: the suzerain's currency, В3.2).
zz_ef_cu_member = {
	exists = market
	NOT = { market.owner = this }
	has_modifier = has_central_bank
	is_subject_custom_trigger = no
}
# The country's money is its own (E&F's money_value / money_value_in_gold): it owns its market or is
# such a member.
zz_ef_currency_own = {
	exists = market
	OR = {
		market.owner = this
		zz_ef_cu_member = yes
	}
}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    ld_gen.emit(OUT_TR, TRIGGERS)
    ld_gen.report("regen_ef_customs_union")


if __name__ == "__main__":
    main()
