# -*- coding: utf-8 -*-
"""
regen_greys_psc.py -- builds the Grey's x PSC compatch in `_greys/greys+psc done`.

Pair GR.2 of the Grey's addon, and the one the plan calls critical. PSC and
grey_usu are two different reworks of the SAME mechanic, and USU loads last:

* PSC turns the construction sector into a goods factory -- the four vanilla
  construction methods stop emitting `country_construction_add` and emit
  `goods_output_*_construction` instead, and a separate
  `building_construction_regulator` converts those goods into construction
  points. It also privatises the whole thing: `bg_construction` moves to
  `parent_group = bg_private_infrastructure`, `subsidized = no`,
  `ownership_type = self`, `can_build_private`.
* USU keeps the vanilla model (`country_construction_add` straight off the
  method) and rebalances it: sectors at 2/5 size, `construction_cost_consec`
  = 20, `has_max_level = yes` capped by its urban-synergy modifier, and
  `bg_construction` back to `bg_public_infrastructure` / `is_government_funded`.

There is no line-level merge between those two: whoever wins, wins the model.
Decision 27.08.2026: **PSC (and the megapack body on top of it) wins.** This
compatch re-issues the winning bodies after the Grey's pack and switches USU's
construction layer off.

What the restored bodies carry, and why this file is allowed to serve more
than one pair (Правила -- сборка, section 3, "исключение"): the record
`building_construction_sector` is written by PSC, KAI, E&F (through the
megapack merge) and USU, and the four methods by PSC, the megapack (E&F stock)
and VC. Two compatches must never REPLACE one record, so all of it lives here,
in one body, and the plan's GR.17 / GR.8 / GR.1 entries for these keys are
closed by this file rather than by files of their own.

Usage:
    python3 regen_greys_psc.py            # write the compatch
    python3 regen_greys_psc.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

PSC = res("../../vic3_mods_out/PSC")
VC = res("../../vic3_mods_out/VC")
GREYS = res("../../vic3_mods_out/grey_add_alot_of_things")
MEGA = res("../__megapacks/megapack no t&r")
OUT = res("../_greys/greys+psc done")

MEGA_SECTOR = os.path.join(MEGA, "common/buildings/zz_pb_ef_construction_sector.txt")
MEGA_PM = os.path.join(MEGA, "common/production_methods/zz_pb_ef_construction_pm.txt")
PSC_BG = os.path.join(PSC, "common/building_groups/zz_PSC_building_groups.txt")
VC_PM = os.path.join(VC, "common/production_methods/joi_methods.txt")
USU_BLD = os.path.join(GREYS, "grey_usu/common/buildings/yMoG_USU_construction.txt")
USU_PM = os.path.join(GREYS, "grey_usu/common/production_methods/yMoG_USU_construction.txt")
USU_BG = os.path.join(GREYS, "grey_usu/common/building_groups/yMoG_USU_building_groups.txt")
USU_BALANCER = "common/history/buildings/MoG_consec_balancer.txt"
GVC_PM = res("../_greys/greys+vc done/common/production_methods/zz_gvc_methods.txt")

GUARD = """	# Guard, not PSC's line. grey_usu's body puts vanilla's country_construction_add
	# back into country_modifiers, and PSC's chain replaces construction points with
	# goods output -- both together would count construction twice. Under "REPLACE:
	# replaces the record" this block is a no-op; under "REPLACE: patches the named
	# sub-blocks" (the question still open in the rules) it is what clears USU's.
	country_modifiers = { workforce_scaled = { } }
"""

PMS = ["pm_wooden_buildings", "pm_iron_frame_buildings",
       "pm_steel_frame_buildings", "pm_arc_welded_buildings"]

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's x PSC compatch (GR.2) -- {what}
# Generated by tools/regen_greys_psc.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: TGR -> PSC -> KAI -> E&F -> ... -> megapack -> [VC] -> ... -> Grey's pack -> THIS.
# Why this file exists: {why}
"""

def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    WRITTEN[rel] = (("﻿" if bom else "") + body).encode("utf-8")
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == WRITTEN[rel] else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def verify_sources():
    """Everything this merge assumes, asserted against the live files."""
    for path in (MEGA_SECTOR, MEGA_PM, PSC_BG, VC_PM, USU_BLD, USU_PM, USU_BG):
        assert os.path.isfile(path), f"source gone: {path}"
    # the four things USU does that this compatch is here to undo
    usu_bld = V.read(USU_BLD)
    _, body = V.entry(usu_bld, "building_construction_sector", "REPLACE_OR_CREATE:")
    assert "pmg_market_liquidity" not in body, (
        "USU now keeps pmg_market_liquidity on the construction sector -- re-read GR.2")
    assert re.search(r"has_max_level\s*=\s*yes", body), (
        "USU no longer sets has_max_level on the sector -- the `no` below may be unnecessary now")
    usu_bg = V.read(USU_BG)
    _, bg = V.entry(usu_bg, "bg_construction", "REPLACE_OR_CREATE:")
    assert "bg_public_infrastructure" in bg, (
        "USU no longer moves bg_construction back to public infrastructure -- re-read GR.2")
    usu_pm = V.read(USU_PM)
    for pm in PMS:
        _, pmb = V.entry(usu_pm, pm, "REPLACE_OR_CREATE:")
        assert "country_construction_add" in pmb, (
            f"USU's {pm} no longer emits country_construction_add -- re-read GR.2, the two "
            f"construction models may no longer be mutually exclusive")
    assert os.path.isfile(os.path.join(GREYS, "grey_usu", USU_BALANCER)), (
        "USU's MoG_consec_balancer.txt is gone -- the path override below now shadows nothing, "
        "delete it")


def build_sector():
    text = V.read(MEGA_SECTOR)
    decl, body = V.entry(text, "building_construction_sector", "REPLACE:")
    assert "pmg_market_liquidity" in body and "ai_construction_sector_price_pressure_bonus" in body, (
        "the megapack's construction sector body lost E&F's liquidity group or the AI bonus -- "
        "re-read it before copying")
    # USU sets has_max_level = yes; the megapack body never names the field at all, so under the
    # "REPLACE patches by named sub-blocks" reading USU's cap would survive our own REPLACE.
    # Naming it explicitly is correct under both readings of the open question in the rules.
    lines = body.split("\n")
    for i, ln in enumerate(lines):
        if re.match(r"\s*levels_per_mesh\s*=", ln):
            lines.insert(i + 1, "\thas_max_level = no\t# USU sets yes; PSC's sector has no cap")
            break
    else:
        raise AssertionError("no levels_per_mesh line in the megapack body -- insert has_max_level by hand")
    write("common/buildings/zz_greys_psc_construction_sector.txt",
          "REPLACE:building_construction_sector = {" + "\n".join(lines) + "}",
          "the winning construction sector body, re-issued after grey_usu",
          "grey_usu REPLACE_OR_CREATEs building_construction_sector with a body that is vanilla "
          "plus its own sizing, and loads after everything. That silently drops: E&F's "
          "pmg_market_liquidity, the whole scripted ai_value (PSC's base, KAI's iron clause, "
          "the capital kickstart and the construction-price pressure bonus), ownership_type = "
          "self, can_build_private and ai_nationalization_desire -- i.e. the entire "
          "PSC+E&F+KAI construction sector. Body copied verbatim from the megapack's "
          "zz_pb_ef_construction_sector.txt, plus one explicit has_max_level = no. "
          "!! MAINTENANCE !! re-run this generator whenever that megapack file changes.")


def build_construction_pms():
    """The four construction methods, PSC's bodies with E&F's stock line.

    Deliberately WITHOUT Victorian Century's layer. VC `INJECT:`s extra goods
    inputs and a state_construction_mult into all four, grey_usu eats those
    injects with everything else, and GR.1 restores them by re-issuing VC's own
    inject verbatim in `_greys/greys+vc done`. Two restorations of one inject
    would add VC's numbers twice, so this file carries the base body only.

    Load order that makes the split work: this REPLACE: has to come BEFORE that
    INJECT:. Inside the assembled addon the file names sort that way on their own
    (`zz_greys_...` < `zz_gvc_...`, 'r' < 'v'); as separate mods, the PSC compatch
    must stand before the VC one in the playset.
    """
    mega = V.read(MEGA_PM)
    gvc = V.read(GVC_PM) if os.path.isfile(GVC_PM) else None
    assert gvc is not None, (
        "_greys/greys+vc done/common/production_methods/zz_gvc_methods.txt is gone -- it is "
        "what puts VC's injects back on these four methods (GR.1). Either restore it or add "
        "VC's layer here by hand")
    records = []
    for pm in PMS:
        _, body = V.entry(mega, pm, "REPLACE:")
        assert "goods_output_" in body and "_construction_add" in body, (
            f"{pm}: the megapack body no longer emits PSC's construction goods -- re-read GR.2")
        assert re.search(r"(?m)^INJECT:" + pm + r"\s*=\s*\{", gvc), (
            f"{pm}: greys+vc done no longer re-issues VC's inject for it -- VC's goods inputs "
            f"would be lost, add the layer here or fix GR.1")
        assert "country_modifiers" not in body, (
            f"{pm}: the megapack body now has its own country_modifiers -- the guard below "
            f"would wipe it, merge by hand")
        records.append(f"REPLACE:{pm} = {{{body.rstrip()}\n\n{GUARD}}}")
    head = ("# PSC's construction chain (goods out, no country_construction_add) with E&F's stock\n"
            "# line, from the megapack merge. Victorian Century's layer is NOT here: GR.1 puts it\n"
            "# back by re-issuing VC's own INJECT: in _greys/greys+vc done/common/\n"
            "# production_methods/zz_gvc_methods.txt, which loads after this file (zz_greys_ < zz_gvc_).\n")
    write("common/production_methods/zz_greys_psc_construction_pm.txt",
          head + "\n" + "\n\n".join(records),
          "the four construction methods, re-issued after grey_usu",
          "grey_usu REPLACE_OR_CREATEs all four vanilla construction methods with bodies "
          "that put country_construction_add back and drop PSC's goods_output_*_construction "
          "-- which decouples the whole PSC chain: the construction regulator loses its input "
          "and PSC's four construction goods lose their only producer. It also eats E&F's "
          "stock line. Bodies copied from the megapack's zz_pb_ef_construction_pm.txt. "
          "!! MAINTENANCE !! re-run whenever that file changes.")


def build_bg_construction():
    decl, body = V.entry(V.read(PSC_BG), "bg_construction", "REPLACE:")
    assert "bg_private_infrastructure" in body, (
        "PSC no longer privatises bg_construction -- re-read GR.2 before copying")
    write("common/building_groups/zz_greys_psc_bg_construction.txt",
          "REPLACE:bg_construction = {" + body + "}",
          "PSC's building group for construction, re-issued after grey_usu",
          "grey_usu REPLACE_OR_CREATEs bg_construction back to parent_group = "
          "bg_public_infrastructure with is_government_funded = yes, urbanization = 2 and "
          "infrastructure_usage_per_level = 0.8. That undoes PSC's privatised construction "
          "(bg_private_infrastructure, subsidized = no, economy_of_scale, should_auto_expand) "
          "and leaves the sector's own ownership_type = self fighting a government-funded "
          "group. Body verbatim from PSC's zz_PSC_building_groups.txt.")


def build_balancer_override():
    text = ("# This file deliberately has no BUILDINGS block: it exists to shadow, by path,\n"
            "# grey_usu/common/history/buildings/MoG_consec_balancer.txt.\n"
            "#\n"
            "# USU's version hands +1 construction sector at game start to every incorporated,\n"
            "# non-treaty-port state with iron potential, to compensate for ITS OWN sectors being\n"
            "# 2/5 of vanilla size. With PSC's model restored (see the other files here) that\n"
            "# compensation is for a shrink that never happened: a PSC sector is a full goods\n"
            "# factory (1000 pops and 100 construction cost per level), PSC already places the\n"
            "# starting sectors it wants in its own common/history/buildings/PSC_buildings.txt,\n"
            "# and history containers are additive -- there is no prefix that can cancel another\n"
            "# mod's BUILDINGS block, only a file at the same path.\n"
            "#\n"
            "# !! MAINTENANCE !! this override also swallows anything the Grey's author adds to\n"
            "# this file later. Re-read it on every Grey's update.\n"
            "#\n"
            "# USU's mog_construction_max_level_adjustment modifier is deliberately NOT touched:\n"
            "# with has_max_level = no on the sector it has nothing to cap and does nothing.")
    write(USU_BALANCER, text,
          "shadow USU's starting-sector top-up, which only makes sense with USU's own sizing",
          "see the body -- a path override is the only way to cancel another mod's additive "
          "history block.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_psc.py -> {OUT}")
    verify_sources()
    for name, fn in (("construction sector", build_sector),
                     ("construction methods", build_construction_pms),
                     ("bg_construction", build_bg_construction),
                     ("consec balancer override", build_balancer_override)):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current PSC / megapack / VC / Grey's sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
