# -*- coding: utf-8 -*-
"""
regen_greys_diplo_fix.py -- builds an internal Grey's fix in
`_greys/greys_diplo_fix done` (GR.11).

Not a pair -- a single-mod bug in grey_diplo, the same class CMF's own rules
file already documents as the canonical example (`Правила работы с модами
Victoria 3.md`, "CMF держит реестр флагов *_is_active"): CMF registers
`Grey_DIS_is_active = { always = no }` for other mods to detect grey_diplo's
presence. A mod that wants its own flag to read `yes` must override CMF's
bare declaration with `REPLACE_OR_CREATE:` -- a bare key of the same name does
NOT override for scripted_triggers, it is simply a second, later, ignored
declaration. grey_diplo's own file declares the flag bare:

    Grey_DIS_is_active = { # Diplomatic Interaction Suite
        always = yes
    }

CMF's "no" wins. Checked: nothing in the current set actually gates on this
flag today (no foreign compat layer for grey_diplo exists in this set yet),
so there is no silent breakage to point at right now -- but any future mod
that adds one (the whole point of the registry) would silently fail to detect
grey_diplo, exactly the way `is_usfp_active`/Hail Columbia! did for real
elsewhere in this pack. Three-line fix.

Usage:
    python3 regen_greys_diplo_fix.py            # write the fix
    python3 regen_greys_diplo_fix.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

GREYS = res("../../vic3_mods_out/grey_add_alot_of_things")
DIPLO_FILE = os.path.join(GREYS, "grey_diplo/common/scripted_triggers/zz_MoG_DIS_mod_compatibility_triggers.txt")
OUT = res("../_greys/greys_diplo_fix done")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """# Grey's internal fix (GR.11) -- {what}
# Generated by tools/regen_greys_diplo_fix.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: CMF -> ... -> grey_diplo -> THIS (anywhere after grey_diplo).
# Why this file exists: {why}
"""


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: brace balance {V.brace_balance(body)}"
    if bom is None:
        bom = any(ord(ch) > 127 for line in body.split("\n") for ch in line.split("#")[0])
    blob = (("﻿" if bom else "") + body).encode("utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    V.write(path, body, bom=bom)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_flag():
    key = "Grey_DIS_is_active"
    diplo_text = V.read(DIPLO_FILE)
    _decl, body = V.entry(diplo_text, key)
    assert "always" in body and "yes" in body, (
        f"{key}: grey_diplo's own declaration no longer reads 'always = yes' -- "
        f"re-check GR.11, this fix may need a different body")

    text = f"REPLACE_OR_CREATE:{key} = {{\n\talways = yes\n}}"
    write("common/scripted_triggers/zz_greys_diplo_fix_dis_flag.txt", text,
          "make Grey_DIS_is_active actually override CMF's registry default",
          "grey_diplo declares Grey_DIS_is_active bare (no prefix). CMF's own registry "
          "(0_community_mod_triggers.txt) already declares the same flag bare as "
          "'always = no' for other mods to detect grey_diplo's presence -- a bare "
          "redeclaration does not override for scripted_triggers, only REPLACE_OR_CREATE: "
          "does, so CMF's 'no' silently wins and the flag never reads yes. This is the "
          "exact case the project's own rules file already cites as the canonical example "
          "of the *_is_active pattern. Nothing in the current set gates on this flag yet, "
          "so there is no visible breakage today -- but any future compat layer for "
          "grey_diplo would silently fail to detect it, same as is_usfp_active did for "
          "Hail Columbia! elsewhere in this pack. Three lines, REPLACE_OR_CREATE: this time.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if V.brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {V.brace_balance(text)}")
            bad += 1
        non_ascii = any(ord(ch) > 127 for line in text.split("\n") for ch in line.split("#")[0])
        if non_ascii and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        import re as _re
        doubled = _re.findall(r"^[A-Z_]+:[A-Z_]+:", text, _re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        empty_colon = _re.findall(r"^[A-Z_]+::", text, _re.M)
        if empty_colon:
            print(f"  FAIL {rel}: {len(empty_colon)} bad '::' prefix(es), e.g. {empty_colon[0]}")
            bad += 1
        category, depth = os.path.dirname(rel), 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = _re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, {bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_greys_diplo_fix.py -> {OUT}")
    for name, fn in (("dis_flag", build_flag),):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current grey_diplo source")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
