"""
regen_llwa_companies.py -- builds `_llwa/llwa+companies done`: gives LLWA's
transport buildings to the natural-candidate historical companies across the
set, as extension_building_types.

Not a two-mod pair. LLWA closes its own four companies over its own seven
buildings (LLWA_companies.txt) -- turnpike (roadway/waterway/riverway),
ship_line (waterway/riverway/port), railroad (railway), airline (airway).
llwa_building_freight_depot, llwa_building_exchange, and
LLWA_building_logistics_hub are deliberately not on any company anywhere
(logistics_hub is `no_ownership`; the other two look like a deliberate
"one per state, not a company holding" choice by LLWA's own author -- not
touched here).

Everyone ELSE's historical companies -- Orient Express, GWR, Suez, Panama,
Prussian State Railways, Mantetsu, and ~50 more across vanilla, TGR, VC, HC,
MoH -- know nothing about LLWA, because LLWA didn't exist when they were
written. Checked live (index of all `common/company_types` in the set):
zero of them mention any LLWA building. This isn't a conflict (nothing is
overwritten, nothing is silently dropped) -- it's LLWA's new transport
network sitting invisible to every company whose whole point is building
exactly that kind of infrastructure.

E&F's ~100 banks also carry building_railway (diversified financial
companies, not transport companies -- railway is one of 7-10 holdings each),
but were left out of the FIRST pass here on purpose -- a separate, then-
undecided question. Follow-up (user question, same day): decided yes, give
them llwa_building_exchange -- see EF_BANKS below. Grey's/USU's ~70 railway
companies stay excluded: addon-Grey's own territory (GR.9).

Rule, applied uniformly, not by hand-picking companies:
  * company_types with building_railway in building_types
      -> extension_building_types += LLWA_building_roadway
  * company_types with building_port in building_types
      -> extension_building_types += LLWA_building_waterway, LLWA_building_riverway
  * E&F company_types with a building_financial_centre_* building
      -> extension_building_types += llwa_building_exchange
Two companies (company_hbc, company_yasuda) have both building_railway and
building_port and get all three transport additions; the bank rule is a
disjoint set (E&F's own company names, CamelCase, don't collide with the
snake_case historical-company keys above -- checked, zero overlap).

extension_building_types is confirmed present (declared, possibly empty) on
every single company record checked across all six source mods -- this is
INJECT: adding list items to an existing field, not creating a new one.

A company defined by more than one source mod in this list (e.g.
company_orient_express: vanilla AND VC) is emitted ONCE -- this addon loads
last in the chain, so one INJECT: lands on whichever definition is final at
merge time regardless of how many earlier mods touched the same key.

Usage:
    python3 regen_llwa_companies.py            # write the compatch
    python3 regen_llwa_companies.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

OUT = res("../_llwa/llwa+companies done")

# Order matters: find_company() below keeps overwriting its result as it
# walks this dict, so the LAST entry that defines a given key wins -- this
# must match the REAL target chain's load order (rules file's own chain:
# ...TGR -> PSC -> Kuromi's AI -> E&F -> E&F Hotfix -> Morgenroete -> PBE ->
# ...megapack -> Victorian Century -> addon-VC -> HC+GoB+MoH -> addon-HC...),
# not insertion-convenience order. E&F loads BEFORE Victorian Century, not
# after -- getting this wrong once already produced a wrong "final" building_types
# for company_standard_oil (E&F's own empty stub instead of VC's real one).
SOURCES = {
    "VANILLA": res("../../vic3_mods_out/.vanillaVIC3/common/company_types"),
    "TGR": res("../../vic3_mods_out/TheGreatRevision/common/company_types"),
    "EF": res("../../vic3_mods_out/E&F/common/company_types"),
    "VC": res("../../vic3_mods_out/VC/common/company_types"),
    "HC": res("../../vic3_mods_out/for addon/hailcolumbia/common/company_types"),
    "MoH": res("../../vic3_mods_out/for addon/mandateofheaven/common/company_types"),
}

HEADER = """# LLWA x historical companies -- {what}
# Generated by tools/regen_llwa_companies.py on {date}. Do not hand-edit: the
# next run overwrites this file. Change the generator instead.
#
# Load order: vanilla/TGR/VC/HC/MoH/E&F company_types -> ... -> LLWA -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

# Rail candidates -- have building_railway in building_types in the FINAL
# (last-mod-wins) definition, verified live by find_company() below, not just
# in whichever mod first coined the name. 11 companies were dropped from an
# earlier draft of this list for exactly that reason: TGR defines them as
# railway companies, but VC's own REPLACE_OR_CREATE: on the same key (VC
# loads after TGR) turns them into something else entirely with a different
# building_types (e.g. company_krupp -> arms/steel, company_east_india_company
# -> plantations) -- adding LLWA_building_roadway to VC's redesigned version
# would be thematically wrong. The generator's own assert catches this class
# of drift on every future re-run, not just this one.
# -> get LLWA_building_roadway.
RAIL = [
    "company_altos_hornos_de_vizcaya", "company_cfr", "company_cordoba_railway", "company_csfa",
    "company_dmc", "company_egyptian_rail", "company_franco_belge",
    "company_great_indian_railway", "company_gwr", "company_hbc",
    "company_imperial_ethiopian_railways", "company_iranian_state_railway",
    "company_kaiping_mining", "company_lkab", "company_mantero_seta",
    "company_mantero_seta_two_sicilies", "company_mantetsu", "company_massey_harris",
    "company_ong_lung_sheng_tea_company_heaven_kingdom", "company_orient_express",
    "company_prussian_state_railways", "company_sao_paulo_railway", "company_sherkate_eslamiya",
    "company_siemens_and_halske", "company_standard_oil", "company_tashkent_railroad",
    "company_united_fruit", "company_usfp_union_pacific", "company_yasuda"
]

# Port candidates -- have building_port in building_types somewhere in the
# chain -> get LLWA_building_waterway + LLWA_building_riverway.
PORT = [
    "company_a_markwald_and_company", "company_admiralty_rijkswerf", "company_ap_moller",
    "company_caribbean_petroleum", "company_david_sassoon", "company_hbc", "company_john_holt",
    "company_lanfang_kongsi", "company_panama_company", "company_russian_american_company",
    "company_societe_francaise_charbonnages_du_tonkin", "company_stt", "company_sudamericana_de_vapores",
    "company_suez_company", "company_uragadockcompany", "company_white_star_line", "company_yasuda",
    "company_ynchausti_y_compania",
]

# E&F's diversified banks -- decided separately from the vanilla/TGR/VC/HC/MoH
# rule above (user question, follow-up to LLWA.8): every E&F company whose
# building_types carries a building_financial_centre_* variant (the country-
# specific suffix E&F uses, not the bare key -- checked with a prefix match,
# not exact membership) gets llwa_building_exchange added to
# extension_building_types. 97 of E&F's 103 companies qualify; the six that
# don't are utility-only entries with no financial_centre building at all
# (company_private_construction, three basic mining companies, the plain
# company_PennsylvaniaRailroad, and company_standard_oil, which E&F itself
# leaves with an empty building_types here). llwa_building_exchange is a
# MAPI-communications building despite its name (LLWA_pmg_exchange_base +
# LLWA_pmg_mapi_comms -- telegraph/telephone/press reducing market access
# price impact), not a literal stock exchange, but the theme -- banks
# investing in the infrastructure that moves markets -- fits the same way
# railways do.
EF_BANKS = [
    "company_BasicBank", "company_BankJPMorgan", "company_BankGoldmanSachs",
    "company_ChaseBank", "company_BankWellsFargo", "company_BankAmericanExpress",
    "company_DeNederlandscheBank", "company_amsterdamschebank",
    "company_RotterdamscheBankvereeniging", "company_BanqueNationaleDeBelgique",
    "company_SocieteGeneraledeBelgique", "company_BanqueDeBruxelles", "company_Bankenverein",
    "company_HandelsBanken", "company_LandmandsBanken", "company_ChristianiaBank",
    "company_BankofSpain", "company_BancoDeBilbao", "company_BancoHispanoColonial",
    "company_BancoDePortugal", "company_BancoCommercialPortugues", "company_Bank_Ultramarino",
    "company_Rothschild_Bank_ita", "company_BancaDItalia", "company_BancaCommercialeItaliana",
    "company_CassaDiRisparmioDiTorino", "company_BankofEngland", "company_LloydsBank",
    "company_barclaysBank", "company_NationalWestminsterBank", "company_RoyalBankOfScotland",
    "company_Rothschild_Bank_gbr", "company_BanqueDeFrance", "company_BankCreditLyonnais",
    "company_SocieteGenerale", "company_BanqueDeParisEtDesPaysBas",
    "company_Rothschild_Bank_fra", "company_StateBankRussianEmpire", "company_DeutscheBank",
    "company_Reichsbank", "company_PreussischeSeehandlung", "company_Rothschild_Bank_ger",
    "company_BayerischeHypothekenUndWechselBank", "company_OesterreichischeNationalbank",
    "company_OesterreichischeCreditAnstalt", "company_WienerBankverein",
    "company_Rothschild_Bank_aus", "company_bankofgreec", "company_OttomanBank",
    "company_TurkishZiraatBankasi", "company_BanqueImperialeOttomane",
    "company_ImperialBankofPersia", "company_BankMelliIran", "company_BankTejaratPersia",
    "company_BankAngloPersian", "company_BanqueEgyptienne", "company_ChohungBank",
    "company_BankHSBC", "company_BankIBC", "company_BankBOCOM", "company_DaQingBank",
    "company_Mitsubishiexchangehousebank", "company_BankOfJapan", "company_SumitomoBank",
    "company_ImperialBankofIndia", "company_BankOfIndiaCompany", "company_BankOfBombay",
    "company_RoyalBankofCanada", "company_BankOfMontreal",
    "company_CanadianImperialBankOfCommerce", "company_BankDesjardins",
    "company_ColonialBankOfAustralia", "company_NationalBankOfAustralia",
    "company_SouthAustralianBank", "company_BancoDeMexico", "company_bancodelondresmexico",
    "company_BancoMercantilMexicano", "company_BancoCentralDeCostaRica",
    "company_BancoCentralDeGuatemala", "company_BancoCentralDeHonduras",
    "company_BancoNacionalDePanama", "company_BancoDoBrasil", "company_BancoMercantil",
    "company_BancoCommercialDoBrasil", "company_BancoNacionArgentina",
    "company_BancoHipotecarioNacional", "company_BancoProvincia", "company_BancoDeChile",
    "company_BancoEstado", "company_BancoDeValparaiso", "company_BancoNacionalDeBolivia",
    "company_BancoRepublicaColombia", "company_BancoCentralDeVenezuela",
    "company_BancoEspanolDeLaHabana", "company_BancoCentralDelUruguay",
    "company_BancoNacionalDelParaguay", "company_BankSBoBSA"
]


def find_company(key: str) -> tuple[str, list[str]] | None:
    """Search all six source mods for `key`; return (mod label, its
    building_types list) from the LAST (highest-priority) source that
    defines it, or None if nobody defines it any more."""
    found = None
    for label, base in SOURCES.items():
        if not os.path.isdir(base):
            continue
        for f in sorted(os.listdir(base)):
            if not f.endswith(".txt"):
                continue
            text = "\n".join(read_lines(os.path.join(base, f)))
            m = re.search(r"(?m)^(?:[A-Z_]+:)?" + re.escape(key) + r"\s*=\s*\{", text)
            if not m:
                continue
            i = text.index("{", m.start())
            d = 0
            for j in range(i, len(text)):
                if text[j] == "{":
                    d += 1
                elif text[j] == "}":
                    d -= 1
                    if d == 0:
                        break
            body = text[i + 1:j]
            bt = re.search(r"building_types\s*=\s*\{([^}]*)\}", body)
            found = (label, bt.group(1).split() if bt else [])
    return found


def verify_and_collect() -> dict[str, list[str]]:
    additions: dict[str, set[str]] = {}
    missing = []
    wrong = []
    for key in RAIL:
        hit = find_company(key)
        if not hit:
            missing.append(key)
            continue
        label, bt = hit
        if "building_railway" not in bt:
            wrong.append((key, label, "no longer has building_railway"))
            continue
        additions.setdefault(key, set()).add("LLWA_building_roadway")
    for key in PORT:
        hit = find_company(key)
        if not hit:
            missing.append(key)
            continue
        label, bt = hit
        if "building_port" not in bt:
            wrong.append((key, label, "no longer has building_port"))
            continue
        additions.setdefault(key, set()).update(
            {"LLWA_building_waterway", "LLWA_building_riverway"})
    for key in EF_BANKS:
        hit = find_company(key)
        if not hit:
            missing.append(key)
            continue
        label, bt = hit
        if not any(b.startswith("building_financial_centre") for b in bt):
            wrong.append((key, label, "no longer has a building_financial_centre* building"))
            continue
        additions.setdefault(key, set()).add("llwa_building_exchange")
    assert not missing, f"{len(missing)} companies no longer found anywhere: {missing[:5]}..."
    assert not wrong, f"{len(wrong)} companies drifted: {wrong[:5]}"
    return {k: sorted(v) for k, v in additions.items()}


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build():
    additions = verify_and_collect()
    out_records = []
    for key in sorted(additions):
        items = "\n".join(f"\t\t{it}" for it in additions[key])
        out_records.append(
            f"INJECT:{key} = {{\n\textension_building_types = {{\n{items}\n\t}}\n}}"
        )
    write("common/company_types/zz_llwa_companies_extensions.txt",
          "\n\n".join(out_records),
          f"add LLWA transport buildings to {len(additions)} companies "
          f"as extension buildings",
          "Every historical railway/port company across vanilla, TGR, VC, HC, and "
          "MoH predates LLWA and knows nothing about its roads/canals/rivers -- same "
          "for E&F's diversified banks and llwa_building_exchange. "
          "extension_building_types is additive and declared (even if empty) on "
          "every company record checked, so this is a pure INJECT: -- nothing "
          "overwritten, no company's own design touched. Grey's/USU's ~70 railway "
          "companies are deliberately not here -- see the generator's module docstring.")
    roadway = sum(1 for v in additions.values() if 'LLWA_building_roadway' in v)
    waterway = sum(1 for v in additions.values() if 'LLWA_building_waterway' in v)
    exchange = sum(1 for v in additions.values() if 'llwa_building_exchange' in v)
    both_rail_port = sum(1 for v in additions.values()
                          if 'LLWA_building_roadway' in v and 'LLWA_building_waterway' in v)
    print(f"  {len(additions)} companies: {roadway} get roadway, {waterway} get "
          f"waterway/riverway ({both_rail_port} get both), {exchange} banks get exchange")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        # duplicate-INJECT-target check (different rule than the buildings
        # generators: here EVERY record is INJECT:, so "duplicate" means the
        # same company key appears twice in this file, which would be a
        # generator bug, not a cross-mod layering pattern)
        keys = re.findall(r"(?m)^INJECT:([A-Za-z0-9_]+)\s*=\s*\{", text)
        for k in keys:
            where = ("common/company_types", k)
            if where in seen:
                print(f"  FAIL duplicate INJECT target {k} in {rel}")
                bad += 1
            seen[where] = rel
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} INJECT targets, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_llwa_companies.py -> {OUT}")
    build()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
