#!/usr/bin/env python3
"""
Д2.30 / Д2.31 (the user, 6.10 day): a country's currency held by other CBs lies as deposits in ITS banks.

Was: the clearing paid an outflow partly in the payer's own currency (the reference 70%, В1); the engine had already
taken the importers' money, so that currency left the payer's M2 for good -- the holders' stocks
(stockpiling_<currency>_state_1 on their CB capitals) only grew. Run r1006_154528: 21.6M pounds abroad by 1838.3,
Britain's M2 41 -> 36M, prices -10% a year, GDP -9%.

Now (Д2.30, (a)): the issuer's banks hold it. Хвост R1 (the user, 8.10): our currency held by another CB is a deposit
in our banks that comes only with a counter-posting; the register var:zz_ef_nr_dep is the truth, the holders' stocks
(stockpiling_<currency>_state_1) its mirror. Weekly, at the receiver after the clearing:
  * the clearing -- our own currency paid out (var:zz_ef_f_clr_cur_out) less the one redeemed (var:zz_ef_f_clr_own_back):
    money the engine already took for the imports -- into / out of the issuer's pool as deposits (var:zz_ef_f_nr_dep,
    at most the pool on the way out);
  * any other change of zz_ef_fx_liab_all (E&F's monthly stockpiling, E&F's forex, a crisis reset) -- no money moves:
    the register follows the stocks (var:zz_ef_f_nr_oth) and the reconciliation shows it as «прочее» (the pool less the
    book) until those writers post (R2, Ф9).

The start (Хвост R1, 8.10): no CB holds a foreign currency -- E&F's history gave every CB 2.5-10M of each in E&F's scale
(_archive/ef_start_fx_reserves/ of the fork); the deposits start at 0, no cut, nothing out of the banks' capital.

Д2.33 (the user, 6.10 day, after run r1006_162423: Britain's deficit 0.15 -> 0.6M a week, pounds abroad 66% of GDP,
nothing closing it): (a) the issuer's banks pay the holders interest at the deposit rate -- weekly every holder's
stock x (1 + zz_ef_deposit_rate / 52), credited as more deposits (the pool unchanged, the banks' liabilities up, their capital down --
R1б, В8: var:zz_ef_f_nr_int); (b) the holders spend the currency on the issuer's goods -- the engine's lever, an export
advantage for the issuer by its currency held abroad: static modifier zz_ef_fx_holders_demand (+1% per unit),
multiplier = zz_ef_fx_holders_demand_m (+1 per 3% of GDP held abroad, at most 20). More exports -> an inflow in the
clearing -> the holders pay with its own currency coming home, the debt falls by itself.

The issuer: a country with a CB outside an overlord's currency zone (zz_ef_nr_issuer) -- a zone member shares the
overlord's zz_ef_fx_liab and must not count it twice.

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys): common/scripted_effects/ld_nr_deposits.txt,
common/script_values/ld_nr_deposits_values.txt, common/scripted_triggers/ld_nr_deposits_triggers.txt,
common/static_modifiers/ld_fx_holders_demand.txt (localization by hand). Reads the currencies from zz_ef_fx_liab's
branches (the fork's common/script_values/ld_reserve_trade_values.txt).

Usage:
    python3 tools/regen_ef_nr_deposits.py [--check]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

SRC = os.path.join(ld_gen.FORK, "common", "script_values", "ld_reserve_trade_values.txt")
# hotfix paths; ld_gen writes into the fork (ld_nr_deposits*.txt, ld_fx_holders_demand.txt)
OUT_EFF = "common/scripted_effects/zz_ef_nr_deposits.txt"
OUT_SV = "common/script_values/zz_ef_nr_deposits_values.txt"
OUT_TR = "common/scripted_triggers/zz_ef_nr_deposits_triggers.txt"
OUT_SM = "common/static_modifiers/zz_ef_fx_holders_demand.txt"

HEAD = ("# GENERATED by tools/regen_ef_nr_deposits.py -- do not edit by hand.\n"
        "# Д2.30 (6.10), Хвост R1 (8.10): our currency held by other CBs = deposits in our banks, by a posting only;\n"
        "# the start holds none -- see the generator's docstring.\n")


def currencies():
    text = open(SRC, encoding="utf-8-sig").read()
    block = text[text.index("\nzz_ef_fx_liab = {"):]
    block = block[:block.index("\n}\n")]
    cur = re.findall(r"has_law = law_type:law_([a-z_]+)_currency \}", block)
    cur = list(dict.fromkeys(cur))
    assert len(cur) >= 90, len(cur)
    return cur


def trim_chain(cur, var="zz_ef_fxt_k"):
    out = []
    for i, c in enumerate(cur):
        kw = "if" if i == 0 else "else_if"
        out.append(
            f"\t\t\t{kw} = {{ limit = {{ has_law = law_type:law_{c}_currency }} every_country = {{ limit = {{ "
            f"NOT = {{ this = scope:zz_fxt_issuer }} NOT = {{ has_law = law_type:law_{c}_currency }} "
            f"has_modifier = has_central_bank }} capital = {{ if = {{ limit = {{ has_variable = stockpiling_{c}_state_1 }} "
            f"change_variable = {{ name = stockpiling_{c}_state_1 multiply = scope:zz_fxt_issuer.var:{var} }} }} }} }} }}\n")
    return "".join(out)


def effects(cur):
    return HEAD + """
# COUNTRY scope, weekly at the receiver after the clearing (zz_ef_cb_hume_step). Хвост R1 (8.10): the deposits start at
# 0 once the country is an issuer (no CB holds a foreign currency at the start); they move by the clearing's posting,
# the rest of the holders' stocks is mirrored into «прочее» (var:zz_ef_f_nr_oth).
zz_ef_nr_dep_step = {
	set_variable = { name = zz_ef_f_nr_dep value = 0 }
	set_variable = { name = zz_ef_f_nr_oth value = 0 }
	if = {
		limit = {
			zz_ef_nr_issuer = yes
			NOT = { has_variable = zz_ef_nr_started }
			has_variable = zz_ef_parity_version
		}
		set_variable = { name = zz_ef_nr_started value = yes }
		if = { limit = { NOT = { has_variable = zz_ef_nr_dep } } set_variable = { name = zz_ef_nr_dep value = 0 } }
	}
	if = {
		limit = {
			zz_ef_nr_issuer = yes
			has_variable = zz_ef_nr_started
		}
		# Д2.33 (a): interest to the holders at the deposit rate, credited as more deposits (the pool unchanged);
		# R1б (В8, 8.10): paid out of the banks' capital, like the pops' deposit interest (zz_ef_post)
		set_variable = { name = zz_ef_f_nr_int value = 0 }
		set_variable = { name = zz_ef_nri_liab value = zz_ef_fx_liab }
		if = {
			limit = {
				var:zz_ef_nri_liab > 0
				zz_ef_nr_int_week > 0
			}
			set_variable = { name = zz_ef_f_nr_int value = zz_ef_nr_int_week }
			set_variable = { name = zz_ef_nri_k value = var:zz_ef_f_nr_int }
			change_variable = { name = zz_ef_nri_k divide = var:zz_ef_nri_liab }
			change_variable = { name = zz_ef_nri_k add = 1 }
			save_scope_as = zz_fxt_issuer
""" + trim_chain(cur, "zz_ef_nri_k") + """			set_variable = { name = zz_ef_nr_dep value = zz_ef_nr_dep_v }
			zz_ef_post = { FROM = zz_ef_bank_capital TO = zz_ef_nr_dep V = var:zz_ef_f_nr_int }
		}
		# the holders' stock is final for the week here (the interest above was its last change): one pass of
		# zz_ef_fx_liab_all, read by the deposits below and by zz_ef_fx_holders_demand_m
		set_variable = { name = zz_ef_t_liab_all value = zz_ef_fx_liab_all }
		# the clearing's posting: our currency paid out less the one redeemed this week (zz_ef_clr_step), money;
		# withdrawn -- at most what the pool holds
		set_variable = { name = zz_ef_f_nr_dep value = 0 }
		if = { limit = { has_variable = zz_ef_f_clr_cur_out } change_variable = { name = zz_ef_f_nr_dep add = var:zz_ef_f_clr_cur_out } }
		if = { limit = { has_variable = zz_ef_f_clr_own_back } change_variable = { name = zz_ef_f_nr_dep subtract = var:zz_ef_f_clr_own_back } }
		if = {
			limit = { var:zz_ef_f_nr_dep < 0 }
			set_variable = {
				name = zz_ef_f_nr_dep
				value = {
					value = var:zz_ef_f_nr_dep
					min = {
						value = investment_pool
						min = 0
						multiply = -1
					}
				}
			}
		}
		add_investment_pool = var:zz_ef_f_nr_dep
		set_variable = { name = zz_ef_nr_dep value = zz_ef_nr_dep_v }
		change_variable = { name = zz_ef_nr_dep add = var:zz_ef_f_nr_dep }
		# the rest of the stocks' change, with no money behind it: the register follows the stocks, the pool does not --
		# «прочее» of the reconciliation (the pool less the book) shows it
		set_variable = { name = zz_ef_f_nr_oth value = var:zz_ef_t_liab_all }
		change_variable = { name = zz_ef_f_nr_oth subtract = var:zz_ef_nr_dep }
		set_variable = { name = zz_ef_nr_dep value = var:zz_ef_t_liab_all }
	}
	# Д2.33 (b): the holders' demand for the issuer's goods -- an export advantage by its currency held abroad
	if = {
		limit = { has_modifier = zz_ef_fx_holders_demand }
		remove_modifier = zz_ef_fx_holders_demand
	}
	if = {
		limit = {
			zz_ef_nr_issuer = yes
			has_variable = zz_ef_nr_started
			zz_ef_fx_holders_demand_m > 0
		}
		add_modifier = {
			name = zz_ef_fx_holders_demand
			multiplier = zz_ef_fx_holders_demand_m
		}
	}
}
"""


def values():
    return HEAD + """
# the deposits of other CBs in our banks (our currency they hold), money
zz_ef_nr_dep_v = {
	value = 0
	if = { limit = { has_variable = zz_ef_nr_dep } value = var:zz_ef_nr_dep }
}
# put into (+) / drawn out of (-) the pool this receiver / last window
zz_ef_v_f_nr_dep = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_nr_dep } value = var:zz_ef_f_nr_dep }
}
zz_ef_v_w_nr_dep = {
	value = 0
	if = { limit = { has_variable = zz_ef_w_nr_dep } value = var:zz_ef_w_nr_dep }
}
# Хвост R1: the change of the holders' stocks this receiver with no posting behind it (E&F's writers), money
zz_ef_v_f_nr_oth = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_nr_oth } value = var:zz_ef_f_nr_oth }
}

# Д2.33 (a): the week's interest to the holders: the deposits x the deposit rate / 52
zz_ef_nr_int_week = {
	value = zz_ef_nr_dep_v
	multiply = zz_ef_deposit_rate
	divide = 52
	min = 0
}
zz_ef_v_f_nr_int = {
	value = 0
	if = { limit = { has_variable = zz_ef_f_nr_int } value = var:zz_ef_f_nr_int }
}
# Д2.33 (b): the export advantage's multiplier, +1 (= +1%) per 3% of GDP held abroad, at most 20
# (only inside zz_ef_nr_dep_step, after zz_ef_t_liab_all is set: the same guards as the step's second block)
zz_ef_fx_holders_demand_m = {
	value = 0
	if = {
		limit = {
			has_variable = zz_ef_t_liab_all
			zz_ef_raw_gdp > 0
		}
		value = var:zz_ef_t_liab_all
		divide = zz_ef_raw_gdp
		multiply = 100
		divide = 3
	}
	max = 20
	min = 0
}
"""


def triggers():
    return HEAD + """
# The issuer of its currency: a CB, not a member of an overlord's currency zone (В3.2)
zz_ef_nr_issuer = {
	has_modifier = has_central_bank
	NOT = { has_variable = zz_ef_cur_zone }
}
"""


def modifiers():
    return HEAD + """
# Д2.33 (b): the holders of our currency spend it on our goods -- +1% export advantage per unit; the multiplier
# zz_ef_fx_holders_demand_m (script_values/zz_ef_nr_deposits_values.txt), set weekly by zz_ef_nr_dep_step
zz_ef_fx_holders_demand = {
	icon = gfx/interface/icons/timed_modifier_icons/strong_currency.dds
	state_export_advantage_mult = 0.01
}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    cur = currencies()
    for path, text in ((OUT_EFF, effects(cur)), (OUT_SV, values()), (OUT_TR, triggers()), (OUT_SM, modifiers())):
        ld_gen.emit(path, text)
    ld_gen.report("regen_ef_nr_deposits")


if __name__ == "__main__":
    main()
