"""
regen_vc_morg.py -- builds the VC x Morgenrote compatch in `_vc/morg+vc`.

The pair: Morgenrote (+ requires CMF) loads early in the main pack, Victorian
Century loads last. Machine matrix: 101 shared keys, 1 shared path (VC.3 in
`План проекта.md`). Analysis: `_vc/morg+vc/conflicts_vc_vs_morgenrote_report.md`.

Same shape as the E&F x VC pair (regen_vc_ef.py): Morgenrote loads first, so
every fix here is a plain TRY_INJECT/INJECT re-applying Morgenrote's own lines
-- lifted live from Morgenrote's current files, never hand-copied -- on top of
VC's REPLACE_OR_CREATE body. Source of truth is Morgenrote's own file at
generation time (rule from `Правила работы...`, section 9).

What's real out of the 101 shared keys, 1 shared path:
  * common/buy_packages -- 90 keys (wealth_10..wealth_99), all real. VC's
    REPLACE_OR_CREATE:wealth_N never mentions popneed_entertainment (Morgenrote's
    own good), so Morgenrote's TRY_INJECT is a clean re-apply -- same mechanism
    as the old T&R x VC compatch (`_vc/kai+vc outdate/.../zz_vc_tr_buy_packages.txt`),
    and the two turned out to carry byte-identical popneed_entertainment values
    (common non-vanilla source, see rules section 279 -- not copied from one
    into the other by this generator, each is read from its own mod).
  * common/pop_needs -- 3 keys, all real. VC's REPLACE_OR_CREATE:popneed_free_movement
    / _leisure / _luxury_items wipes Morgenrote's TRY_INJECT entries (air_travel,
    elgar_instruments, rubber -- Morgenrote's own goods plus one vanilla good).
    None of these goods already appear in VC's replacement bodies.
  * common/character_templates -- 2 keys, both real. VC's REPLACE_OR_CREATE on
    gbr_charles_dickens_character_template and swe_karl_johan_bernadotte_template
    wipes Morgenrote's INJECT (role, extra traits, on_created for Dickens; one
    extra trait for Bernadotte). No field-name collisions: every field
    Morgenrote adds is absent from VC's body, and the trait lists are lists
    (INJECT appends, per the company_standard_oil precedent in regen_vc_ef.py).
  * common/mobilization_options -- 3 keys, NOT real conflicts needing a file.
    aerial_recon / balloon_recon: Morgenrote's TRY_INJECT sets `group`, VC's
    INJECT sets `upkeep_modifier` -- disjoint fields on the same vanilla
    record, both additive prefixes, nothing to patch (same shape as the
    mutual_funds finding in VC.2). chemical_weapons: Morgenrote's TRY_REPLACE
    sets upkeep_modifier.goods_input_fertilizer_add = 2, VC's INJECT sets the
    same field to 0.5 (plus two fields Morgenrote doesn't touch) in the SAME
    named sub-block. Whether repeated `_add` keys inside one object's own
    modifier block sum (like the base_values case, which is a country-wide
    static-modifier pool -- confirmed by verified precedent) or the second
    declaration silently wins is NOT established for this kind of single-
    object sub-block, and guessing wrong either loses Morgenrote's fertilizer
    cost or double-counts it if duplicates already sum. No file is written for
    this one; see the report for the open in-game check.
  * common/technology/technologies -- 2 keys, NOT real conflicts. civilizing_mission:
    Morgenrote's TRY_INJECT touches `modifier`, VC's INJECT touches `on_researched`
    -- disjoint. organized_sports: both touch `modifier` but disjoint field
    names (country_prestige_mult vs country_authority_mult/country_influence_mult/
    building_group_bg_service_employee_mult) -- same shape as mutual_funds in
    VC.2, modifier blocks accumulate.
  * common/dna_data/ecchi_ger_hitler.txt (path) + ecchi_dna_adolf_hitler (key)
    -- NOT a real conflict. Byte-for-byte the same portrait gene-by-gene, just
    reformatted (Morgenrote: 4 values per line; VC: 1 value per line). Only
    two differences: VC's body has one extra gene (`coats`) Morgenrote's
    lacks, and `gene_stubble` differs (Morgenrote 0/0, VC 127/127) -- a single
    cosmetic value, not a design decision either author would defend. VC wins
    the path outright (loads last); nothing of Morgenrote's own is lost
    because there is no Morgenrote-only content here -- both drew from the
    same third-party DNA source (rules section 279).

Usage:
    python3 regen_vc_morg.py            # write the compatch
    python3 regen_vc_morg.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

MORG = res("../../vic3_mods_out/Morgenrote")
VC = res("../../vic3_mods_out/VC")
OUT = res("../_vc/morg+vc done")

HEADER = """# Morgenrote x VC compatch -- {what}
# Generated by tools/regen_vc_morg.py on {date}. Do not hand-edit: the next run
# overwrites this file. Change the generator instead.
#
# Load order: Morgenrote -> ... -> Victorian Century -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}


def block(lines: list[str], i: int) -> tuple[list[str], int]:
    """Given lines[i] is the opening `key = {` line, return (block_lines, j_next)."""
    depth = 0
    started = False
    for j in range(i, len(lines)):
        code = lines[j].split("#", 1)[0]
        depth += code.count("{") - code.count("}")
        if "{" in code:
            started = True
        if started and depth <= 0:
            return lines[i:j + 1], j + 1
    return lines[i:], len(lines)


def record(path: str, key: str) -> list[str] | None:
    """Lines of one top-level record, key line included, prefix stripped off."""
    lines = read_lines(path)
    pat = re.compile(r"^(?:[A-Z_]+:)?" + re.escape(key) + r"\s*=\s*\{")
    for i, raw in enumerate(lines):
        if pat.match(raw.split("#", 1)[0].lstrip("﻿")):
            body, _ = block(lines, i)
            body[0] = re.sub(r"^﻿?(?:[A-Z_]+:)?", "", body[0])
            return body
    return None


def find_file(root: str, category: str, key: str) -> str | None:
    directory = os.path.join(root, category)
    if not os.path.isdir(directory):
        return None
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".txt"):
            continue
        full = os.path.join(directory, name)
        if record(full, key) is not None:
            return full
    return None


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


# ------------------------------------------------------------------- the pieces

def build_buy_packages():
    morg_f = find_file(MORG, "common/buy_packages", "wealth_10")
    assert morg_f, "Morgenrote wealth_10 not found -- did the buy_packages file move?"
    lines = read_lines(morg_f)

    vc_f = find_file(VC, "common/buy_packages", "wealth_1")
    assert vc_f, "VC wealth_1 not found"
    vc_text = "\n".join(read_lines(vc_f))
    assert "popneed_entertainment" not in vc_text, (
        "VC's buy_packages now mentions popneed_entertainment -- re-check the "
        "merge, a blind re-inject would double it up")

    pat = re.compile(r"^(?:TRY_INJECT:|INJECT:)?wealth_(\d+)\s*=\s*\{")
    blocks: dict[int, list[str]] = {}
    i = 0
    while i < len(lines):
        m = pat.match(lines[i].split("#", 1)[0].lstrip("﻿"))
        if m:
            body, nxt = block(lines, i)
            body[0] = re.sub(r"^﻿?", "", body[0])
            if not body[0].startswith("TRY_INJECT:") and not body[0].startswith("INJECT:"):
                body[0] = "TRY_INJECT:" + body[0]
            blocks[int(m.group(1))] = body
            i = nxt
        else:
            i += 1

    assert len(blocks) == 90, f"expected 90 wealth_* TRY_INJECTs in Morgenrote, found {len(blocks)}"
    assert set(blocks) == set(range(10, 100)), (
        f"expected wealth_10..wealth_99, got {sorted(blocks)}")

    out_lines: list[str] = []
    for n in sorted(blocks):
        out_lines.extend(blocks[n])
        out_lines.append("")

    write("common/buy_packages/zz_vc_morg_buy_packages.txt",
          "\n".join(out_lines),
          "re-apply Morgenrote's popneed_entertainment demand on wealth_10..99",
          "VC's REPLACE_OR_CREATE:wealth_* wipes Morgenrote's TRY_INJECT "
          "(popneed_entertainment, Morgenrote's own good) on all 90 tiers it "
          "touches. VC never sets that need itself, so this is a clean "
          "re-apply of Morgenrote's own lines, read live from its "
          "buy_packages file -- not a re-balance. Values happen to match the "
          "old T&R x VC compatch byte-for-byte (both took the same "
          "third-party base, see the plan section 279), but this generator "
          "reads Morgenrote's file directly, not that old compatch.")


def build_pop_needs():
    src = {}
    for key in ("popneed_free_movement", "popneed_leisure", "popneed_luxury_items"):
        f = find_file(MORG, "common/pop_needs", key)
        assert f, f"Morgenrote {key} not found"
        src[key] = record(f, key)

    vc_f = find_file(VC, "common/pop_needs", "popneed_free_movement")
    assert vc_f, "VC popneed_free_movement not found"

    out_lines: list[str] = []
    for key, body in src.items():
        vc_body = "\n".join(record(vc_f, key) or [])
        goods = [ln.strip() for ln in body if re.match(r"^\s*goods\s*=", ln)]
        for g in goods:
            assert g not in vc_body, (
                f"VC's {key} now has {g} -- re-check before re-injecting")
        text = "\n".join(body)
        text = re.sub(r"^(?:TRY_INJECT:|INJECT:)?" + re.escape(key), "TRY_INJECT:" + key, text, count=1)
        out_lines.append(text)
        out_lines.append("")

    write("common/pop_needs/zz_vc_morg_pop_needs.txt",
          "\n".join(out_lines),
          "re-apply Morgenrote's entries on three vanilla pop needs",
          "VC's REPLACE_OR_CREATE:popneed_free_movement / _leisure / "
          "_luxury_items wipes Morgenrote's TRY_INJECT entries (air_travel, "
          "elgar_instruments, rubber) on all three. None of these goods "
          "already appear in VC's replacement bodies, so this is a clean "
          "re-apply, read live from Morgenrote's pop_needs file.")


def build_character_templates():
    dickens_f = find_file(MORG, "common/character_templates", "gbr_charles_dickens_character_template")
    assert dickens_f, "Morgenrote Dickens template not found"
    dickens_body = record(dickens_f, "gbr_charles_dickens_character_template")

    bern_f = find_file(MORG, "common/character_templates", "swe_karl_johan_bernadotte_template")
    assert bern_f, "Morgenrote Bernadotte template not found"
    bern_body = record(bern_f, "swe_karl_johan_bernadotte_template")

    vc_dickens_f = find_file(VC, "common/character_templates", "gbr_charles_dickens_character_template")
    assert vc_dickens_f, "VC Dickens template not found"
    vc_dickens = "\n".join(record(vc_dickens_f, "gbr_charles_dickens_character_template") or [])
    assert "role" not in vc_dickens, "VC's Dickens now has its own role -- re-check"
    assert "on_created" not in vc_dickens, "VC's Dickens now has on_created -- re-check"

    vc_bern_f = find_file(VC, "common/character_templates", "swe_karl_johan_bernadotte_template")
    assert vc_bern_f, "VC Bernadotte template not found"
    vc_bern = "\n".join(record(vc_bern_f, "swe_karl_johan_bernadotte_template") or [])
    assert "mr_ruler_trait_karl_xiv" not in vc_bern, (
        "VC's Bernadotte now has mr_ruler_trait_karl_xiv -- re-check")

    out = []
    text = "\n".join(dickens_body)
    text = re.sub(r"^(?:INJECT:|TRY_INJECT:)?gbr_charles_dickens_character_template",
                  "INJECT:gbr_charles_dickens_character_template", text, count=1)
    out.append(text)
    out.append("")
    text = "\n".join(bern_body)
    text = re.sub(r"^(?:INJECT:|TRY_INJECT:)?swe_karl_johan_bernadotte_template",
                  "INJECT:swe_karl_johan_bernadotte_template", text, count=1)
    out.append(text)

    write("common/character_templates/zz_vc_morg_character_templates.txt",
          "\n".join(out),
          "re-apply Morgenrote's additions on two character templates VC rebuilds",
          "VC's REPLACE_OR_CREATE on gbr_charles_dickens_character_template and "
          "swe_karl_johan_bernadotte_template wipes Morgenrote's INJECT (role, "
          "two extra traits, on_created for Dickens; one extra trait for "
          "Bernadotte). No field-name collisions -- every field Morgenrote "
          "adds is absent from VC's body -- and the trait lists are lists, so "
          "INJECT appends rather than duplicating (same as the "
          "company_standard_oil precedent in regen_vc_ef.py).")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category = os.path.dirname(rel)
        depth = 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_vc_morg.py -> {OUT}")
    for name, fn in (
        ("buy_packages", build_buy_packages),
        ("pop_needs", build_pop_needs),
        ("character_templates", build_character_templates),
    ):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current Morgenrote / VC sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
