#!/usr/bin/env python3
"""
EF.48, В2.1 (decided 2.10): trade reserve currency as a real flow.

The trade reserve currency as a real flow (E&F's trade_balance itself is edited in the fork's E&F file by hand).

Generated:
  * zz_ef_rc_step (our monthly step, every metal-standard market owner with a CB): for every other
    market owner with a CB and a currency, the week's exports both ways (market_exports, units, by a
    binary search -- 19 checks instead of up to 5000) x the average export price per unit of each
    market; if the exporter's side is bigger, the importer pays zz_ef_rc_share (25% for the test,
    the user 2.10) of the net in its currency instead of metal: first it hands back the exporter's
    own currency it holds, the rest the exporter's CB takes in the importer's currency. Metal: the
    exporter's CB gives up what Hume brought in for that part, valued at its parity (not today's value:
    a value that grows with the metal fed back on itself). The importer gets no metal back (run 23: it
    made reserves out of nothing, Prussia's value 24 -> 1401 in five years) -- its currency held
    abroad is its debt (zz_ef_fx_liab).
  * zz_ef_fx_liab: the country's currency held by other CBs (its debt abroad), for the log and M3.

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys):
  common/scripted_effects/ld_reserve_trade.txt, common/script_values/ld_reserve_trade_values.txt
Reads the fork's common/scripted_effects/01_economic_scripted_effects.txt (the list of currencies).

Usage:
    python3 tools/regen_ef_reserve_trade.py [--check]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_gen  # noqa: E402

SRC = os.path.join(ld_gen.FORK, "common", "scripted_effects", "01_economic_scripted_effects.txt")
# hotfix paths; ld_gen writes into the fork (ld_reserve_trade.txt, ld_reserve_trade_values.txt)
OUT_EFF = "common/scripted_effects/zz_ef_reserve_trade.txt"
OUT_SV = "common/script_values/zz_ef_reserve_trade_values.txt"

HEAD = ("# GENERATED by tools/regen_ef_reserve_trade.py -- do not edit by hand.\n"
        "# EF.48, В2.1 (2.10): trade reserve currency as a flow -- see the generator's docstring.\n")

SEARCH_BITS = 18  # up to 2^19 - 1 units a week between two markets


def currencies():
    text = open(SRC, encoding="utf-8-sig").read()
    cur = sorted(set(re.findall(r"^\t?buy_([a-z_]+)_currency = \{", text, re.M)))
    assert len(cur) >= 90, len(cur)
    return cur


def chain(cur, body):
    """if / else_if over the currency laws of the scope country; body(c) is the branch's effect."""
    out = []
    for i, c in enumerate(cur):
        kw = "if" if i == 0 else "else_if"
        out.append(f"\t{kw} = {{ limit = {{ has_law = law_type:law_{c}_currency }} {body(c)} }}\n")
    return "".join(out)


def search_effect():
    lines = ["# Units a week FROM's market exports to TO's (market_exports), into var:$VAR$ of the\n"
             "# scope country, by a binary search (E&F stepped by 1 up to 5000 times). Saved scopes:\n"
             "# scope:$FROM$ / scope:$TO$ -- markets.\n"
             "zz_ef_rc_search = {\n"
             "\tset_variable = { name = $VAR$ value = 0 }\n"
             "\tif = {\n"
             "\t\tlimit = { scope:$FROM$ = { market_exports = { target = scope:$TO$ value >= 1 } } }\n"]
    for k in range(SEARCH_BITS, -1, -1):
        lines.append(f"\t\tset_variable = {{ name = zz_ef_rc_try value = var:$VAR$ }}\n"
                     f"\t\tchange_variable = {{ name = zz_ef_rc_try add = {2 ** k} }}\n"
                     f"\t\tif = {{ limit = {{ scope:$FROM$ = {{ market_exports = {{ target = scope:$TO$ "
                     f"value >= scope:rc_exp.var:zz_ef_rc_try }} }} }} "
                     f"set_variable = {{ name = $VAR$ value = var:zz_ef_rc_try }} }}\n")
    lines.append("\t\tremove_variable = zz_ef_rc_try\n\t}\n}\n\n")
    return "".join(lines)


STEP = """# Monthly, from zz_ef_money_model_monthly_step. COUNTRY scope (the exporter).
zz_ef_rc_step = {
	set_variable = { name = zz_ef_rc_fx_in value = 0 }
	set_variable = { name = zz_ef_rc_back value = 0 }
	set_variable = { name = zz_ef_rc_metal_out value = 0 }
	if = {
		limit = {
			has_modifier = has_central_bank
			market.owner = this
			OR = {
				has_law = law_type:law_gold_standard
				has_law = law_type:law_silver_standard
				has_law = law_type:law_bimetallism_standard
			}
			NOT = { has_modifier = currency_crisis_country }
			NOT = { has_modifier = central_bank_bankruptcy_country }
			has_variable = money_value_target_1
			var:money_value_target_1 > 0
			zz_ef_rc_unit_price > 0
			any_scope_state = {
				has_modifier = central_bank_historic_place
				is_capital = yes
			}
		}
		save_scope_as = rc_exp
		market = { save_scope_as = rc_exp_market }
		every_scope_state = {
			limit = {
				has_modifier = central_bank_historic_place
				is_capital = yes
			}
			save_scope_as = rc_exp_cb
		}
		set_variable = { name = zz_ef_rc_price value = zz_ef_rc_unit_price }
		# the metal the CB can swap this month (its standard's metal; bimetallism -- gold, as Hume)
		set_variable = { name = zz_ef_rc_metal_left value = 0 }
		if = {
			limit = {
				has_law = law_type:law_silver_standard
				scope:rc_exp_cb = { has_variable = silver_state_1 }
			}
			set_variable = { name = zz_ef_rc_metal_left value = scope:rc_exp_cb.var:silver_state_1 }
		}
		else_if = {
			limit = {
				NOT = { has_law = law_type:law_silver_standard }
				scope:rc_exp_cb = { has_variable = gold_state_1 }
			}
			set_variable = { name = zz_ef_rc_metal_left value = scope:rc_exp_cb.var:gold_state_1 }
		}
		every_country = {
			limit = {
				NOT = { this = scope:rc_exp }
				has_modifier = has_central_bank
				market.owner = this
				NOT = { has_modifier = currency_crisis_country }
				NOT = { has_modifier = central_bank_bankruptcy_country }
				zz_ef_rc_currency_value > 0.0002
				any_scope_state = {
					has_modifier = central_bank_historic_place
					is_capital = yes
				}
			}
			save_scope_as = rc_imp
			market = { save_scope_as = rc_imp_market }
			every_scope_state = {
				limit = {
					has_modifier = central_bank_historic_place
					is_capital = yes
				}
				save_scope_as = rc_imp_cb
			}
			scope:rc_exp = { zz_ef_rc_pair = yes }
		}
		remove_variable = zz_ef_rc_metal_left
		remove_variable = zz_ef_rc_price
	}
}

# One pair, scope:rc_exp. The net exports of the week x 52/12 x the share = what the importer
# pays in currency this month (the exporter's money); in metal at the exporter's value.
zz_ef_rc_pair = {
	if = { limit = { has_variable = zz_ef_rc_q_in } remove_variable = zz_ef_rc_q_in }
	zz_ef_rc_search = { FROM = rc_exp_market TO = rc_imp_market VAR = zz_ef_rc_q_out }
	set_variable = { name = zz_ef_rc_due value = zz_ef_rc_pair_net }
	if = {
		limit = { var:zz_ef_rc_due > 0 }
		zz_ef_rc_search = { FROM = rc_imp_market TO = rc_exp_market VAR = zz_ef_rc_q_in }
		set_variable = { name = zz_ef_rc_due value = zz_ef_rc_pair_net }
	}
	if = {
		limit = { var:zz_ef_rc_due > 0 }
		# the exporter's metal given up (native), at most what is left this month
		set_variable = {
			name = zz_ef_rc_metal
			value = {
				value = var:zz_ef_rc_due
				multiply = zz_ef_rc_share_month
				multiply = var:money_value_target_1
				max = var:zz_ef_rc_metal_left
				min = 0
			}
		}
	}
	else = {
		set_variable = { name = zz_ef_rc_metal value = 0 }
	}
	if = {
		limit = { var:zz_ef_rc_metal > 0 }
		# in the exporter's money and in gold
		set_variable = { name = zz_ef_rc_money value = var:zz_ef_rc_metal }
		change_variable = { name = zz_ef_rc_money divide = var:money_value_target_1 }
		set_variable = { name = zz_ef_rc_gold value = var:zz_ef_rc_metal }
		if = {
			limit = { has_law = law_type:law_silver_standard }
			change_variable = { name = zz_ef_rc_gold multiply = silver_to_gold_rate }
		}
		# 1. the importer hands back the exporter's currency it holds
		set_variable = { name = zz_ef_rc_held value = 0 }
		zz_ef_rc_read_held = yes
		set_variable = {
			name = zz_ef_rc_back_now
			value = {
				value = var:zz_ef_rc_held
				max = var:zz_ef_rc_money
				min = 0
			}
		}
		zz_ef_rc_take_held = yes
		# 2. the rest in the importer's currency, at its parity in gold
		set_variable = { name = zz_ef_rc_rest_gold value = var:zz_ef_rc_money }
		change_variable = { name = zz_ef_rc_rest_gold subtract = var:zz_ef_rc_back_now }
		change_variable = { name = zz_ef_rc_rest_gold divide = var:zz_ef_rc_money }
		change_variable = { name = zz_ef_rc_rest_gold multiply = var:zz_ef_rc_gold }
		set_variable = { name = zz_ef_rc_units value = var:zz_ef_rc_rest_gold }
		change_variable = { name = zz_ef_rc_units divide = scope:rc_imp.zz_ef_rc_currency_value }
		scope:rc_imp = { zz_ef_rc_add_units = yes }
		# metal: out of the exporter's CB. Not into the importer's (run 23, 2.10: that made reserves out
		# of nothing -- the importer kept the metal and owed only currency nobody counted against it;
		# Prussia's value 24 -> 1401 in five years): the importer's currency abroad is its debt.
		scope:rc_exp_cb = {
			if = {
				limit = { owner = { has_law = law_type:law_silver_standard } }
				change_variable = { name = silver_state_1 subtract = scope:rc_exp.var:zz_ef_rc_metal }
			}
			else = {
				change_variable = { name = gold_state_1 subtract = scope:rc_exp.var:zz_ef_rc_metal }
			}
		}
		change_variable = { name = zz_ef_rc_metal_left subtract = var:zz_ef_rc_metal }
		# the month, for the log
		change_variable = { name = zz_ef_rc_fx_in add = var:zz_ef_rc_rest_gold }
		change_variable = { name = zz_ef_rc_back add = var:zz_ef_rc_back_now }
		change_variable = { name = zz_ef_rc_metal_out add = var:zz_ef_rc_metal }
		remove_variable = zz_ef_rc_money
		remove_variable = zz_ef_rc_gold
		remove_variable = zz_ef_rc_held
		remove_variable = zz_ef_rc_back_now
		remove_variable = zz_ef_rc_rest_gold
		remove_variable = zz_ef_rc_units
	}
	remove_variable = zz_ef_rc_metal
	remove_variable = zz_ef_rc_due
	remove_variable = zz_ef_rc_q_out
	if = { limit = { has_variable = zz_ef_rc_q_in } remove_variable = zz_ef_rc_q_in }
}

"""


def effects(cur):
    out = [HEAD]
    out.append(STEP)
    out.append(search_effect())
    # 1. the importer's stock of the exporter's currency (rc_exp's law decides)
    out.append("# scope:rc_exp: var:zz_ef_rc_held = the exporter's currency in the importer's CB (scope:rc_imp_cb).\n"
               "zz_ef_rc_read_held = {\n")
    out.append(chain(cur, lambda c: f"if = {{ limit = {{ scope:rc_imp_cb = {{ has_variable = stockpiling_{c}_state_1 }} }} "
                                    f"set_variable = {{ name = zz_ef_rc_held value = scope:rc_imp_cb.var:stockpiling_{c}_state_1 }} }}"))
    out.append("}\n")
    out.append("# scope:rc_exp: the importer's CB gives back var:zz_ef_rc_back_now of the exporter's currency.\n"
               "zz_ef_rc_take_held = {\n")
    out.append(chain(cur, lambda c: f"if = {{ limit = {{ scope:rc_imp_cb = {{ has_variable = stockpiling_{c}_state_1 }} }} "
                                    f"scope:rc_imp_cb = {{ change_variable = {{ name = stockpiling_{c}_state_1 "
                                    f"subtract = scope:rc_exp.var:zz_ef_rc_back_now }} }} }}"))
    out.append("}\n")
    # 2. the exporter's CB takes the importer's currency (rc_imp's law decides)
    out.append("# scope:rc_imp: the exporter's CB (scope:rc_exp_cb) takes scope:rc_exp.var:zz_ef_rc_units of\n"
               "# the importer's currency.\n"
               "zz_ef_rc_add_units = {\n")
    out.append(chain(cur, lambda c: f"scope:rc_exp_cb = {{ if = {{ limit = {{ NOT = {{ has_variable = stockpiling_{c}_state_1 }} }} "
                                    f"set_variable = {{ name = stockpiling_{c}_state_1 value = 0 }} }} "
                                    f"change_variable = {{ name = stockpiling_{c}_state_1 add = scope:rc_exp.var:zz_ef_rc_units }} }}"))
    out.append("}\n")
    return "".join(out)


VALUES = """# The importer pays this share of the net exports in its currency instead of metal (В2.1: 25% for
# everyone in the test, the user 2.10; by the importer's currency strength -- after the run).
zz_ef_rc_share = 0.25
# The searched flows are a week's; the step is monthly.
zz_ef_rc_share_month = {
	value = zz_ef_rc_share
	multiply = 4.33
}
# Average export price per unit of the scope country's market (engine money a unit; E&F prices
# the bilateral units the same way: export value / export units).
zz_ef_rc_unit_price = {
	value = 0
	if = {
		limit = { market.owner = this }
		value = zz_ef_rc_export_value
		divide = {
			value = zz_ef_rc_export_units
			min = 1
		}
	}
}
zz_ef_rc_export_value = {
	value = 0
	market = {
		every_market_goods = {
			add = {
				value = market_goods_exports
				multiply = {
					value = market_goods_pricier
					add = 1
				}
				multiply = goods.base_price
			}
		}
	}
}
zz_ef_rc_export_units = {
	value = 0
	market = {
		every_market_goods = {
			add = market_goods_exports
		}
	}
}
# scope:rc_exp, inside zz_ef_rc_pair: the week's net exports to scope:rc_imp, engine money
# (var:zz_ef_rc_q_in is 0 until searched -- the exporter's side is checked first).
zz_ef_rc_pair_net = {
	value = var:zz_ef_rc_q_out
	multiply = var:zz_ef_rc_price
	if = {
		limit = { has_variable = zz_ef_rc_q_in }
		subtract = {
			value = var:zz_ef_rc_q_in
			multiply = scope:rc_imp.zz_ef_rc_unit_price
		}
	}
}
# Log helpers (0 if unset).
zz_ef_v_rc_fx_in = {
	value = 0
	if = { limit = { has_variable = zz_ef_rc_fx_in } value = var:zz_ef_rc_fx_in }
}
zz_ef_v_rc_back = {
	value = 0
	if = { limit = { has_variable = zz_ef_rc_back } value = var:zz_ef_rc_back }
}
zz_ef_v_rc_metal_out = {
	value = 0
	if = { limit = { has_variable = zz_ef_rc_metal_out } value = var:zz_ef_rc_metal_out }
}
"""


def values(cur):
    out = [HEAD, VALUES]
    out.append("# The scope country's currency at its parity in gold (E&F's money_value_<currency>: the leading\n"
               "# country's money_value_target_real_in_gold).\n"
               "zz_ef_rc_currency_value = {\n\tvalue = 0\n")
    out.append(chain(cur, lambda c: f"value = money_value_{c}"))
    out.append("}\n")
    out.append("# The scope country's currency held by the other countries' CBs (capital CB states), in its own\n"
               "# money: its debt abroad (В2.1). Countries on the same currency law are not foreigners here.\n"
               "zz_ef_fx_liab = {\n\tvalue = 0\n")
    out.append(chain(cur, lambda c: f"every_country = {{ limit = {{ NOT = {{ this = root }} NOT = {{ has_law = law_type:law_{c}_currency }} "
                                    f"has_modifier = has_central_bank }} capital = {{ if = {{ limit = {{ has_variable = stockpiling_{c}_state_1 }} "
                                    f"add = {{ value = var:stockpiling_{c}_state_1 min = 0 }} }} }} }}"))
    out.append("\tmin = 0\n}\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    cur = currencies()
    ld_gen.emit(OUT_EFF, effects(cur))
    ld_gen.emit(OUT_SV, values(cur))
    ld_gen.report("regen_ef_reserve_trade")


if __name__ == "__main__":
    main()
