"""
regen_vc_tgr.py -- builds the TGR x VC compatch in `_vc/tgr+vc done`.

The pair: The Great Revision loads early, Victorian Century loads last, and VC
wins every hard overwrite -- 172 shared keys and 14 shared file paths. Full
analysis: `_vc/tgr+vc done/conflicts_tgr_vs_vc_report.md`.

Vanilla is the common ancestor of both mods for every record here, so the merge
is three-way (see vic3merge3.py) rather than hand-written bodies. What the two
authors did to different lines is kept from both; what they did to the SAME lines
is a conflict, and every conflict is either resolved by a declared winner below
or printed for a human. Nothing is resolved silently.

Decisions taken 25.08.2026 (recorded in `План проекта.md`, fork 8):
  * buy_packages -- VC's numbers are the base, TGR's own headline multipliers
    (+25% from wealth_10, +50% from wealth_21 on basic_food / luxury_food /
    luxury_drinks) are re-applied on top. Both economies survive.
  * German unification -- stitched: VC's state list and Frankfurt gate, TGR's
    buttons, Bismarck pulse and 21-state annexation.
  * Parties -- VC wins the "three or more members" multiplier; TGR's other two
    adjustments (no marginal-IG gate, +50 for the party's natural IG) are kept.

Usage:
    python3 regen_vc_tgr.py            # write the compatch
    python3 regen_vc_tgr.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, merge3, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

VAN = res("../../vic3_mods_out/.vanillaVIC3")
TGR = res("../../vic3_mods_out/TheGreatRevision")
VC = res("../../vic3_mods_out/VC")
OUT = res("../_vc/tgr+vc done")

HEADER = """# TGR x VC compatch -- {what}
# Generated by tools/regen_vc_tgr.py on {date}. Do not hand-edit: the next run
# overwrites this file. Change the generator instead.
#
# Load order: The Great Revision -> ... -> Victorian Century -> THIS.
# Why this file exists: {why}
#
# !! MAINTENANCE !! Bodies are a three-way merge with vanilla 1.13.11 as the
# common ancestor. After either mod updates, re-run the generator and read the
# conflict list it prints -- a new conflict means the authors started fighting
# over a line they used to leave alone.
"""

DATE = "2026-08-26"
CHECK_ONLY = False


# ---------------------------------------------------------------- record access

def record(path: str, key: str) -> list[str] | None:
    """Lines of one top-level record, key line included, prefix stripped off."""
    lines = read_lines(path)
    pat = re.compile(r"^(?:[A-Z_]+:)?" + re.escape(key) + r"\s*=\s*\{")
    for i, raw in enumerate(lines):
        if pat.match(raw.split("#", 1)[0].lstrip("﻿")):
            depth = 0
            started = False
            for j in range(i, len(lines)):
                code = lines[j].split("#", 1)[0]
                depth += code.count("{") - code.count("}")
                if "{" in code:
                    started = True
                if started and depth <= 0:
                    body = lines[i:j + 1]
                    body[0] = re.sub(r"^﻿?(?:[A-Z_]+:)?", "", body[0])
                    return body
            return lines[i:]
    return None


def find_file(root: str, category: str, key: str) -> str | None:
    directory = os.path.join(root, category)
    if not os.path.isdir(directory):
        return None
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".txt"):
            continue
        full = os.path.join(directory, name)
        if record(full, key) is not None:
            return full
    return None


def merged_record(category: str, key: str, prefer: str, report: list):
    van_f, tgr_f, vc_f = (find_file(r, category, key) for r in (VAN, TGR, VC))
    assert van_f and tgr_f and vc_f, f"missing source for {category}/{key}: {van_f} {tgr_f} {vc_f}"
    base, a, b = record(van_f, key), record(tgr_f, key), record(vc_f, key)
    out, conflicts = merge3(base, a, b, prefer=prefer)
    for lo, hi, atxt, btxt, how in conflicts:
        report.append((f"{category}/{key}", lo, hi, atxt, btxt, how))
    return out


WRITTEN: dict[str, bytes] = {}


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"                       # never open the real file for write:
    with open(tmp, "wb") as fh:               # a bad open() truncates before it validates
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


# ------------------------------------------------------------------- the pieces

def build_base_values():
    """VC REPLACE_OR_CREATEs base_values with a 103-line body and eats three TGR
    INJECTs. Re-issuing the same INJECTs after VC restores them exactly: repeated
    keys inside a modifier block ADD, so the result is "VC value + TGR delta" --
    the same delta TGR applies to vanilla. Do not try to write final numbers here;
    TGR's figures are addends, not totals."""
    inner, sources = [], 0
    for name in sorted(os.listdir(os.path.join(TGR, "common/static_modifiers"))):
        body = record(os.path.join(TGR, "common/static_modifiers", name), "base_values")
        if not body:
            continue
        sources += 1
        inner.append(f"\t# from TheGreatRevision/common/static_modifiers/{name}")
        for line in body[1:-1]:               # drop TGR's own `base_values = {` and `}`
            if line.strip():
                inner.append(line)
        inner.append("")
    assert sources == 3, f"expected 3 TGR base_values injects, got {sources}"
    # One INJECT block, not three: TGR splits them across three files only because
    # they belong to three of his subsystems. Their keys are disjoint, and repeated
    # keys in a modifier block add anyway, so folding them into one block is
    # equivalent and avoids re-declaring the same key three times in one file.
    out = ["INJECT:base_values = {", *inner, "}"]
    write("common/static_modifiers/zz_vc_tgr_base_values.txt", "\n".join(out),
          "static modifier base_values",
          "VC's REPLACE_OR_CREATE:base_values wipes TGR's three INJECTs "
          "(loan interest, bureaucracy/authority/influence, officer and soldier\n"
          "#   political strength, company construction efficiency, trade advantage). "
          "Silent: no log line.")


def build_canada_australia():
    """Neither vanilla nor either mod invented this file: both carry the same
    third-party file that turns the vanilla canada/australia JOURNAL entries into
    decisions. VC carries it unmodified; TGR carries it plus his own adjustments.
    The whole TGR-vs-VC diff IS those adjustments, so TGR's file is the merge."""
    rel = "common/decisions/canada_australia.txt"
    src = os.path.join(TGR, rel)
    dst = os.path.join(OUT, rel)
    blob = open(src, "rb").read()
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(dst, "rb").read() if os.path.isfile(dst) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copyfile(src, dst)                 # byte copy: no header of ours, no BOM change
    print(f"  wrote {rel}  (byte copy of TGR's file)")


def build_history(report):
    """Path overlap, so the compatch must own the path: a second file with the
    same COUNTRIES container would ADD, and every country would get its companies
    and journal entries twice."""
    files = ["aus - austria", "chi - china", "fra - france", "gbr - great britain",
             "jap - japan", "net - netherlands", "spa - spain", "tur - ottoman empire"]
    for name in files:
        rel = f"common/history/countries/{name}.txt"
        base, a, b = (read_lines(os.path.join(r, rel)) for r in (VAN, TGR, VC))
        out, conflicts = merge3(base, a, b, prefer="both")
        for lo, hi, atxt, btxt, how in conflicts:
            report.append((rel, lo, hi, atxt, btxt, how))
        write(rel, "\n".join(out), f"country history: {name}",
              "VC overwrites TGR's file by path. TGR's companies and law changes "
              "would vanish; VC's amendments,\n#   journal entries and modifiers are "
              "kept from VC's side of the merge.")


def build_records(category, keys, rel, what, why, prefer, report):
    """One file per category: every shared record re-declared REPLACE_OR_CREATE:
    after VC, carrying the merge."""
    out = []
    for key in keys:
        out.append("REPLACE_OR_CREATE:" + "\n".join(merged_record(category, key, prefer, report)))
        out.append("")
    write(rel, "\n".join(out), what, why)


IGS = ["ig_armed_forces", "ig_devout", "ig_industrialists", "ig_intelligentsia",
       "ig_landowners", "ig_petty_bourgeoisie", "ig_rural_folk", "ig_trade_unions"]
PARTIES = ["conservative_party", "liberal_party", "radical_party", "religious_party"]
GOVS = ["gov_presidential_democracy", "gov_presidential_dictatorship"]
COMPANIES = ["company_compania_sansinena_de_carnes_congeladas", "company_east_india_company",
             "company_gebruder_thonet", "company_imperial_arsenal", "company_kablin",
             "company_krupp", "company_mitsui", "company_ong_lung_sheng_tea_company",
             "company_philips", "company_russian_american_company", "company_united_fruit",
             "company_william_cramp"]
POPNEEDS = ["popneed_basic_food", "popneed_crude_items", "popneed_heating",
            "popneed_household_items", "popneed_intoxicants", "popneed_luxury_drinks",
            "popneed_luxury_food", "popneed_simple_clothing"]


def build_interest_groups(report):
    """Both REPLACE_OR_CREATE full bodies, VC wins. There is no fork here despite
    what the plan feared: VC rewrites the IGs wholesale (141-395 changed lines vs
    vanilla) while TGR only tweaks them (8-79), and every TGR tweak is fenced with
    `##### TGR CHANGES #####`. The sweeping one is `multiply = 0.0025 -> 0.030`
    inside `scope:interest_group`, which is the core of TGR's IG-membership rework."""
    build_records("common/interest_groups", IGS,
                  "common/interest_groups/zz_vc_tgr_interest_groups.txt",
                  "the eight interest groups",
                  "VC's REPLACE_OR_CREATE bodies eat TGR's tweaks whole -- the 0.030 "
                  "membership multiplier, the raised base\n#   weights, the "
                  "law_appointed_bureaucrats and law_dedicated_police blocks, the "
                  "trade-union tech multipliers.", "both", report)


def build_parties(report):
    """Path overlap AND key overlap on four of the thirteen party files.

    TGR and VC share a non-vanilla base here (both add the same `exists = c:XXX`
    guards, both drop the same Japanese taikunate/ezo descriptions), so only the
    two authors' own deltas get merged.

    Fork settled 25.08.2026: VC wins the "three or more members" multiplier.
    TGR zeroes it (max 2 IGs per party), VC splits it into `= 3` and `> 3`; both
    edited that exact block, and the decision was to keep three-IG coalitions
    possible but expensive. TGR's other two adjustments -- dropping the
    non-marginal-IG gate and +50 for the party's natural IG -- are kept, they sit
    on lines VC never touched. prefer="b" is what implements that."""
    build_records("common/parties", PARTIES,
                  "common/parties/zz_vc_tgr_parties.txt",
                  "the four contested parties",
                  "VC overwrites conservative/liberal/radical/religious by path AND by "
                  "key, so TGR's marked\n#   ADJUSTMENTS blocks disappear.", "both", report)


def build_government_types(report):
    """TGR gates both on the franchise; VC gates on culture and on being a
    monarchy's subject. Orthogonal, so both survive. Both authors independently
    deleted vanilla's je_peru_bolivia / ezo_republic_var NANDs -- not restored:
    a compatch that puts back what both authors removed is inventing behaviour
    neither of them wants."""
    build_records("common/government_types", GOVS,
                  "common/government_types/zz_vc_tgr_government_types.txt",
                  "the two presidential government types",
                  "both REPLACE_OR_CREATE, VC wins, and TGR's franchise requirement "
                  "disappears with it.", "both", report)


def build_companies(report):
    """The one category where TGR changes more than VC (25-58 changed lines against
    4-17): he rewrites building_types, drops vanilla's prerequisites and sets
    ai_weight = 9999 so the AI actually founds flavoured companies. VC brings its
    own prosperity modifiers and categories."""
    build_records("common/company_types", COMPANIES,
                  "common/company_types/zz_vc_tgr_company_types.txt",
                  "the twelve contested companies",
                  "both REPLACE_OR_CREATE, VC wins, and TGR's ai_weight 9999 plus his "
                  "relaxed prerequisites vanish.", "both", report)


# ------------------------------------------------------------------- pop_needs

FIELD_RE = re.compile(r"^(\s*)(weight|max_supply_share|min_supply_share|default"
                      r"|obsession_demand_min|obsession_demand_mult"
                      r"|prestige_goods_demand_increase)(\s*=\s*)([0-9.]+)(.*)$")
GOODS_RE = re.compile(r"^\s*goods\s*=\s*([A-Za-z0-9_]+)")


def _entries(lines):
    """Split a popneed body into (head, [entry_blocks]) keyed by goods name."""
    head, entries, cur, name = [], [], None, None
    depth = 0
    for line in lines:
        code = line.split("#", 1)[0]
        if cur is None and re.match(r"^\s*entry\s*=\s*\{", code):
            cur, name, depth = [line], None, code.count("{") - code.count("}")
            continue
        if cur is None:
            head.append(line)
            continue
        cur.append(line)
        m = GOODS_RE.match(code)
        if m:
            name = m.group(1)
        depth += code.count("{") - code.count("}")
        if depth <= 0:
            entries.append((name, cur))
            cur = None
    if cur is not None:
        entries.append((name, cur))
    return head, entries


def _fields(block):
    out = {}
    for line in block:
        m = FIELD_RE.match(line.split("#", 1)[0])
        if m:
            out[m.group(2)] = m.group(4)
    return out


def build_pop_needs(report):
    """Field-level merge, not line-level, because the two designs are orthogonal
    per field and a line diff would cluster them:

      * TGR reworks `max_supply_share` / `min_supply_share` -- narrow the ceiling
        (0.75-1.0 -> 0.3-0.5), raise the floor (0.0 -> 0.2-0.3). That is his
        "pops must consume a mix" system, and it is the whole point of the record.
      * VC reworks `weight` -- how much a good counts inside the need.

    Rule: supply shares from TGR, weight from VC where VC moved it off vanilla,
    otherwise from TGR. Entries only TGR has (he adds `fish` to luxury food) are
    carried over."""
    out = []
    for key in POPNEEDS:
        base = record(find_file(VAN, "common/pop_needs", key), key)
        a = record(find_file(TGR, "common/pop_needs", key), key)
        b = record(find_file(VC, "common/pop_needs", key), key)
        vh, ve = _entries(base)
        ah, ae = _entries(a)
        bh, be = _entries(b)
        av = {n: _fields(bl) for n, bl in ae}
        bv = {n: _fields(bl) for n, bl in be}
        vv = {n: _fields(bl) for n, bl in ve}
        merged = list(bh)                       # head: VC's (default, obsession_*, ...)
        # head fields TGR moved and VC did not
        for i, line in enumerate(merged):
            m = FIELD_RE.match(line.split("#", 1)[0])
            if not m:
                continue
            f = m.group(2)
            hv, ha_, hb = (_fields(vh).get(f), _fields(ah).get(f), _fields(bh).get(f))
            if ha_ is not None and ha_ != hv and hb == hv:
                merged[i] = f"{m.group(1)}{f}{m.group(3)}{ha_}\t# TGR"
        body = []
        for name, block in be:                  # entries in VC's order
            new = []
            for line in block:
                m = FIELD_RE.match(line.split("#", 1)[0])
                if not m:
                    new.append(line)
                    continue
                f = m.group(2)
                van_v = vv.get(name, {}).get(f)
                tgr_v = av.get(name, {}).get(f)
                vc_v = m.group(4)
                if f in ("max_supply_share", "min_supply_share") and tgr_v is not None:
                    pick, who = tgr_v, "TGR"
                elif vc_v != van_v or tgr_v is None or tgr_v == van_v:
                    pick, who = vc_v, "VC"
                else:
                    pick, who = tgr_v, "TGR"
                mark = "" if pick == vc_v and who == "VC" else f"\t# {who} ({van_v} vanilla)"
                new.append(f"{m.group(1)}{f}{m.group(3)}{pick}{mark}")
            body.extend(new)
        for name, block in ae:                  # entries only TGR has
            if name not in bv:
                body.append("\t# entry added by TGR, absent from vanilla and VC")
                body.extend(block)
                report.append((f"common/pop_needs/{key}", -1, -1,
                               [f"extra entry: {name}"], ["(absent)"], "a"))
        out.append("REPLACE_OR_CREATE:" + "\n".join(merged[:-1] + body + [merged[-1]]))
        out.append("")
    write("common/pop_needs/zz_vc_tgr_pop_needs.txt", "\n".join(out),
          "the eight contested pop needs",
          "both REPLACE_OR_CREATE, VC wins, and TGR's whole supply-share rework "
          "disappears silently.")


# ----------------------------------------------------------------- buy_packages

MULT_GOODS = ("popneed_basic_food", "popneed_luxury_food", "popneed_luxury_drinks")


def _packages(path):
    lines = read_lines(path)
    out, cur, name = {}, None, None
    depth = 0
    for line in lines:
        code = line.split("#", 1)[0]
        m = re.match(r"^﻿?(?:REPLACE_OR_CREATE:)?(wealth_\d+)\s*=\s*\{", code)
        if m and cur is None:
            name, cur, depth = m.group(1), [line], code.count("{") - code.count("}")
            continue
        if cur is None:
            continue
        cur.append(line)
        depth += code.count("{") - code.count("}")
        if depth <= 0:
            out[name] = cur
            cur = None
    return out


def build_buy_packages(report):
    """99 packages, and the loudest fork in the pair.

    TGR ships his rebalance at the vanilla path `common/buy_packages/00_buy_packages.txt`
    with bare bodies; VC REPLACE_OR_CREATEs all 99 from `joi_buy_packages.txt` and
    takes the lot.

    The two share a non-vanilla base (wealth_7 basic_food: vanilla 115, both 118),
    so most cells are not actually in dispute. Decision 25.08.2026: VC's numbers
    are the base, and TGR's own headline multipliers -- stated in the header of his
    file, +25% from wealth_10 and +50% from wealth_21 on basic food, luxury food and
    luxury drinks -- are re-applied on top. Both rebalances then live: VC keeps its
    services / leisure / communication curve, TGR keeps "the rich eat more".

    Where only TGR moved a good off vanilla (intoxicants and stimulants low down the
    ladder), TGR's number is taken as is.

    The multiplier is derived, not copied, so it stays right when VC updates its
    numbers. The run prints how far the derived value lands from TGR's own -- a
    residual above a rounding step means TGR changed his formula and the header
    has to be re-read."""
    van = _packages(os.path.join(VAN, "common/buy_packages/00_buy_packages.txt"))
    tgr = _packages(os.path.join(TGR, "common/buy_packages/00_buy_packages.txt"))
    vc = _packages(os.path.join(VC, "common/buy_packages/joi_buy_packages.txt"))
    assert len(van) == len(tgr) == len(vc) == 99, (len(van), len(tgr), len(vc))

    def values(block):
        out = {}
        for line in block:
            m = re.match(r"^\s*(popneed_[a-z_]+)\s*=\s*([0-9]+)", line.split("#", 1)[0])
            if m:
                out[m.group(1)] = int(m.group(2))
        return out

    out, residuals, taken_tgr = [], [], 0
    for n in range(1, 100):
        key = f"wealth_{n}"
        mult = 1.5 if n >= 21 else (1.25 if n >= 10 else 1.0)
        v, t, c = values(van[key]), values(tgr[key]), values(vc[key])
        new = []
        for line in vc[key]:
            m = re.match(r"^(\s*)(popneed_[a-z_]+)(\s*=\s*)([0-9]+)(.*)$", line.split("#", 1)[0])
            if not m:
                new.append(line)
                continue
            good = m.group(2)
            val = int(m.group(4))
            note = ""
            tgr_moved = good in t and good in v and t[good] != v[good]
            vc_moved = c.get(good) != v.get(good)
            if tgr_moved and not vc_moved:
                # Only TGR touched this cell -- his number already carries whatever
                # multiplier he meant. Re-deriving it from vanilla would be worse,
                # not better: his luxury-food ladder is not vanilla x1.25.
                note = f"\t# TGR ({v[good]} vanilla)"
                val = t[good]
                taken_tgr += 1
            elif tgr_moved and vc_moved and good in MULT_GOODS and mult != 1.0:
                # Both moved it, and it is one of the three needs TGR's own header
                # names. Derive from VC's number so the multiplier follows VC if VC
                # rebalances again.
                scaled = int(round(val * mult))
                residuals.append((key, good, t[good], scaled))
                note = f"\t# {val} x{mult} TGR"
                val = scaled
            new.append(f"{m.group(1)}{good}{m.group(3)}{val}{note}")
        # Strip VC's own prefix first. Gluing one on top of another produces
        # REPLACE_OR_CREATE:REPLACE_OR_CREATE:wealth_1 and the record silently
        # does not load -- no error, the packages just stay vanilla.
        new[0] = "REPLACE_OR_CREATE:" + re.sub(r"^﻿?(?:[A-Z_]+:)?", "", new[0])
        out.extend(new)
        out.append("")
    off = [r for r in residuals if abs(r[2] - r[3]) > 1]
    print(f"  buy_packages: {len(residuals)} multiplied cells, {len(off)} off TGR's own "
          f"value by more than a rounding step; {taken_tgr} cells taken from TGR outright")
    for key, good, tgr_v, ours in off[:12]:
        print(f"    {key:>10} {good:<26} TGR={tgr_v:<5} ours={ours}")
    if off:
        report.append(("common/buy_packages", -1, -1,
                       [f"{len(off)} cells differ from TGR's own numbers by >1"],
                       ["VC base x TGR multiplier"], "b"))
    write("common/buy_packages/zz_vc_tgr_buy_packages.txt", "\n".join(out),
          "all 99 wealth_* buy packages",
          "VC REPLACE_OR_CREATEs all 99 and TGR's whole consumption rebalance "
          "disappears. See the decision above.")


GERMAN_JES = ["je_german_unification", "je_north_german_unification",
              "je_schleswig_holstein_question"]


def build_german_unification(report):
    """The one place in this pair where the two mods carry two different machines
    for the same event, and they do not add up.

    TGR rebuilds German unification: his own JE group, two scripted buttons, a
    monthly pulse firing `german_unification.3` (Bismarck), a hidden effect that
    annexes 21 German states and `change_infamy = -60`, and a
    `great_revision_german_unification.6` broadcast. VC's edits to the same three
    journal entries are two lines: `c:PRU ?= THIS` instead of `c:PRU = THIS`, and
    `any_country` instead of `any_country_in_german_confederation` -- the same
    widening TGR made independently.

    Right now VC wins and the whole TGR machine is dead: the events are never
    called, the buttons never drawn, no state is ever annexed. No log line.

    Decision 25.08.2026 -- stitch, not pick a side:
      * journal entries: TGR's bodies win (prefer="a"), VC's `?=` safety is kept
        where it does not collide -- it is strictly safer than a bare `=`;
      * `country_formation/GER`: VC's explicit 31-state list and its Frankfurt
        parliament gate stay, TGR's `required_states_fraction` and his removal of
        the candidate caps come back on top (prefer="both").

    VC's state list includes Bohemia, Moravia, Austria, Tyrol, Styria, Slovenia and
    Istria, so a Greater-German formation stays possible -- TGR's `use_culture_states`
    would have decided that differently, and the state list is the more explicit of
    the two."""
    ger = merged_record("common/country_formation", "GER", "both", report)
    # `use_culture_states = yes` (TGR) and an explicit `states = { ... }` (VC) are
    # two ways of saying the same thing, and the union emits both because they are
    # different keys. The stitch keeps VC's explicit list, so TGR's switch has to go
    # -- a formable with both would be deciding its own territory twice.
    before = len(ger)
    ger = [ln for ln in ger if "use_culture_states" not in ln.split("#", 1)[0]]
    assert len(ger) == before - 1, "TGR's use_culture_states line moved or vanished"
    out = ["REPLACE_OR_CREATE:" + "\n".join(ger), ""]
    write("common/country_formation/zz_vc_tgr_country_formation.txt", "\n".join(out),
          "formable GER",
          "both REPLACE_OR_CREATE. VC's state list wins, TGR's formation rules come "
          "back on top of it.")

    out = []
    for key in GERMAN_JES:
        out.append("REPLACE_OR_CREATE:" + "\n".join(
            merged_record("common/journal_entries", key, "a", report)))
        out.append("")
    write("common/journal_entries/zz_vc_tgr_german_unification.txt", "\n".join(out),
          "the three German unification journal entries",
          "VC re-declares all three from the vanilla path and TGR's entire German "
          "rework stops being called.\n#   TGR's bodies win here; VC's two edits are "
          "kept where they do not collide.")


def self_check() -> int:
    """Run at the end of every generation, because a compatch that loads but is
    wrong is the expensive kind. Checks: brace balance, BOM where a non-comment
    line needs one, and -- the one that actually catches mistakes -- the same
    top-level key defined twice anywhere in the mod."""
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        # A prefix glued on top of a prefix. The record does not load and nothing
        # is logged; it happened once here, on all 99 buy packages at once.
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category = os.path.dirname(rel)
        depth = 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                # INJECT:/TRY_INJECT: are additive by definition -- the same key
                # appearing twice there is a stack, not a redefinition.
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, "
          f"{bad} problem(s)")
    return bad


# ------------------------------------------------------------ позиции идеологий

STANCES = ("strongly_approve", "approve", "neutral", "disapprove", "strongly_disapprove")
GRID = os.path.join(OUT, "vc_tgr_ideology_grid.xlsx")


def _read_grid():
    """The stances are hand-authored, not derived, and the workbook next to the
    compatch is the source. Neither author wrote them: TGR gives no opinion on
    VC's ten new laws and VC gives none on TGR's thirteen new law groups, and
    nothing in either mod lets a generator infer one. So a human filled the grid
    and this only transcribes it -- but it transcribes it from the file that was
    filled, so re-editing the workbook and re-running is the whole update path."""
    from openpyxl import load_workbook
    wb = load_workbook(GRID, data_only=True)

    ws = wb["Позиции"]
    nmeta = 5
    laws = [(ws.cell(1, c).value, ws.cell(2, c).value) for c in range(nmeta + 1, ws.max_column + 1)]
    group_of, order = {}, []
    cur = None
    for grp, law in laws:
        if grp:
            cur = grp
        group_of[law] = "lawgroup_" + cur
        order.append(law)
    vc_side = {}
    for r in range(5, ws.max_row + 1):                 # 4 -- строка-пример
        ide = ws.cell(r, 1).value
        if not ide:
            continue
        row = {}
        for j, c in enumerate(range(nmeta + 1, ws.max_column + 1)):
            v = ws.cell(r, c).value
            if v is not None and str(v).strip():
                row[order[j]] = str(v).strip()
        if row:
            vc_side[ide] = row

    ws = wb["Обратно"]
    rlaws = [ws.cell(3, c).value for c in range(3, ws.max_column + 1)]
    rgroups = ["lawgroup_" + (ws.cell(4, c).value or "") for c in range(3, ws.max_column + 1)]
    tgr_side = {}
    for r in range(5, ws.max_row + 1):
        ide = ws.cell(r, 1).value
        if not ide:
            continue
        row = {}
        for j, c in enumerate(range(3, ws.max_column + 1)):
            v = ws.cell(r, c).value
            if v is not None and str(v).strip():
                row[rlaws[j]] = str(v).strip()
        if row:
            tgr_side[ide] = row
    rgroup_of = dict(zip(rlaws, rgroups))
    return vc_side, group_of, order, tgr_side, rgroup_of, rlaws


def _record_prefix(path: str, key: str) -> str:
    """The database prefix a file uses for one record: "", "INJECT:", "REPLACE:"..."""
    pat = re.compile(r"^﻿?([A-Z_]+:)?" + re.escape(key) + r"\s*=\s*\{")
    for raw in read_lines(path):
        m = pat.match(raw.split("#", 1)[0])
        if m:
            return m.group(1) or ""
    return ""


def _group_blocks(body: list[str] | None) -> dict[str, list[tuple[str, str]]]:
    """`lawgroup_x = { law_y = stance ... }` sub-blocks of one ideology, in order."""
    out: dict[str, list[tuple[str, str]]] = {}
    cur, depth = None, 0
    for raw in body or []:
        code = raw.split("#", 1)[0]
        line = code.strip()
        if depth == 1:
            m = re.match(r"(lawgroup_[a-z_0-9]+)\s*=\s*\{", line)
            if m:
                cur = m.group(1)
                out.setdefault(cur, [])
                for lm in re.finditer(r"(law_[a-z_0-9]+)\s*=\s*([a-z_]+)", line[m.end():]):
                    out[cur].append((lm.group(1), lm.group(2)))
        elif depth >= 2 and cur:
            m = re.match(r"(law_[a-z_0-9]+)\s*=\s*([a-z_]+)", line)
            if m:
                out[cur].append((m.group(1), m.group(2)))
        depth += code.count("{") - code.count("}")
        if depth <= 1:
            cur = None
    return out


_GROUP_CACHE: dict[str, dict[str, tuple[list[tuple[str, str]], str]]] = {}


def _effective_groups(ideology: str) -> dict[str, tuple[list[tuple[str, str]], str]]:
    """What lawgroup blocks the ideology already carries when our addon loads.

    Walked in load order vanilla -> TGR -> VC. A body without a prefix (or with
    REPLACE:/REPLACE_OR_CREATE:/TRY_REPLACE:) drops everything declared earlier;
    INJECT: keeps what it does not name and replaces what it does. That last
    clause is the whole reason this function exists -- see _stance_block."""
    if ideology in _GROUP_CACHE:
        return _GROUP_CACHE[ideology]
    state: dict[str, tuple[list[tuple[str, str]], str]] = {}
    for root, label in ((VAN, "vanilla"), (TGR, "TGR"), (VC, "VC")):
        path = find_file(root, "common/ideologies", ideology)
        if not path:
            continue
        groups = {g: (v, label) for g, v in _group_blocks(record(path, ideology)).items()}
        if _record_prefix(path, ideology) in ("INJECT:", "TRY_INJECT:"):
            state.update(groups)
        else:
            state = groups
    _GROUP_CACHE[ideology] = state
    return state


def _plural_pos(n: int) -> str:
    if n % 10 == 1 and n % 100 != 11:
        return "позиция"
    if n % 10 in (2, 3, 4) and n % 100 not in (12, 13, 14):
        return "позиции"
    return "позиций"


MERGED_BLOCKS: list[tuple[str, str, str, int]] = []


def _stance_block(ideology, row, group_of, order):
    """One INJECT: record with our stances, one sub-block per law group.

    A lawgroup block is a NAMED entry, so an injected `lawgroup_taxation = { ... }`
    REPLACES the ideology's existing block of that name instead of adding a line to
    it (правило 50). Found the hard way 26.08.2026: the one-line form silently wiped
    73 blocks and with them the interest-group stances on the laws screen -- VC.1k.
    So where the group is already taken, the block is re-issued WHOLE: the earlier
    author's positions first, ours appended, ours winning on the same law. Where the
    group is free (all 13 TGR groups against VC's ideologies) nothing is copied."""
    by_group = {}
    for law in order:
        if law in row:
            by_group.setdefault(group_of[law], []).append((law, row[law]))
    have = _effective_groups(ideology)
    out = ["INJECT:%s = {" % ideology]
    for grp, items in by_group.items():
        existing = have.get(grp)
        if existing:
            pairs, label = existing
            merged = list(pairs)
            at = {law: i for i, (law, _) in enumerate(merged)}
            for law, st in items:
                if law in at:
                    merged[at[law]] = (law, st)
                else:
                    merged.append((law, st))
            MERGED_BLOCKS.append((ideology, grp, label, len(pairs)))
            out.append("\t%s = {\t# тело блока целиком: %d %s %s + наши; "
                       "инжект именованного блока заменяет его, а не дополняет"
                       % (grp, len(pairs), _plural_pos(len(pairs)), label))
        else:
            merged = items
            out.append("\t%s = {" % grp)
        width = max(len(law) for law, _ in merged)
        for law, st in merged:
            out.append("\t\t%-*s = %s" % (width, law, st))
        out.append("\t}")
    out.append("}")
    return "\n".join(out), sum(len(v) for v in by_group.values())


def build_ideology_stances(report):
    """Two files, one per direction, because the two are independently droppable.

    INJECT: and not REPLACE_OR_CREATE: -- the point is to ADD stances to ideologies
    whose bodies belong to someone else. But an injected lawgroup block REPLACES the
    same-named block instead of merging into it, so `_stance_block` re-issues that
    one block whole wherever it is already taken (73 of them, all in the VC-laws
    direction). Copying stays bounded to those blocks: the 13 TGR groups are free on
    VC's ideologies, and no full ideology body is ever re-declared."""
    vc_side, group_of, order, tgr_side, rgroup_of, rlaws = _read_grid()

    bad = [(i, l, v) for i, row in list(vc_side.items()) + list(tgr_side.items())
           for l, v in row.items() if v not in STANCES]
    assert not bad, "недопустимые значения позиций: %s" % bad[:5]

    blocks, n = [], 0
    for ide in vc_side:
        b, cnt = _stance_block(ide, vc_side[ide], group_of, order)
        blocks.append(b)
        n += cnt
    write("common/ideologies/zz_vc_tgr_stances_on_tgr_laws.txt",
          "\n\n".join(blocks),
          "%d Victorian Century ideologies, %d stances on The Great Revision's laws" % (len(vc_side), n),
          "TGR adds 13 law groups and 60 laws; not one of VC's 56 new ideologies had an\n"
          "#   opinion on any of them, so every interest group led by VC flavour was neutral\n"
          "#   on TGR's entire political layer. Hand-authored, see the workbook beside this file.",
          bom=True)

    blocks, n2 = [], 0
    rorder = [l for l in rlaws]
    for ide in tgr_side:
        b, cnt = _stance_block(ide, tgr_side[ide], rgroup_of, rorder)
        blocks.append(b)
        n2 += cnt
    write("common/ideologies/zz_vc_tgr_stances_on_vc_laws.txt",
          "\n\n".join(blocks),
          "%d The Great Revision ideologies, %d stances on Victorian Century's laws" % (len(tgr_side), n2),
          "the other direction: VC adds 10 laws into vanilla law groups and no TGR\n"
          "#   ideology had an opinion on any of them. 73 блока из восьми групп\n#   переизданы целиком -- иначе инжект сносит чужие позиции, см. VC.1k.",
          bom=True)

    # ideology_jacksonian_democrat -- Hail Columbia REPLACE_OR_CREATEs it and loads
    # later, so this injection does not survive a set that includes HC. The stance
    # has to be folded into the addon's zz_hct_jacksonian_democrat.txt instead.
    # Asserting rather than commenting: if HC ever stops doing that, this fires and
    # the note gets deleted instead of quietly outliving its reason.
    hc = os.path.join(res("../../vic3_mods_out/for addon/hailcolumbia"),
                      "common/ideologies")
    clash = "ideology_jacksonian_democrat" in tgr_side and any(
        "ideology_jacksonian_democrat" in open(os.path.join(hc, f), encoding="utf-8-sig",
                                               errors="ignore").read()
        for f in os.listdir(hc) if f.endswith(".txt"))
    if clash:
        report.append(("common/ideologies/ideology_jacksonian_democrat", -1, -1,
                       ["наши позиции по законам VC"],
                       ["Hail Columbia REPLACE_OR_CREATE поверх, грузится позже — "
                        "переносить в аддон-HC, zz_hct_jacksonian_democrat.txt"], "b"))


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    ap.add_argument("--only", default=None, help="run one section")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    report: list = []
    print(f"regen_vc_tgr.py -> {OUT}")

    sections = {
        "base_values": build_base_values,
        "canada": build_canada_australia,
        "history": lambda: build_history(report),
        "interest_groups": lambda: build_interest_groups(report),
        "parties": lambda: build_parties(report),
        "government_types": lambda: build_government_types(report),
        "companies": lambda: build_companies(report),
        "pop_needs": lambda: build_pop_needs(report),
        "buy_packages": lambda: build_buy_packages(report),
        "german_unification": lambda: build_german_unification(report),
        "ideology_stances": lambda: build_ideology_stances(report),
    }
    for name, fn in sections.items():
        if args.only and args.only != name:
            continue
        print(f"[{name}]")
        fn()

    if report:
        print(f"\n=== {len(report)} conflict cluster(s): both mods edited the same lines ===")
        for where, lo, hi, atxt, btxt, prefer in report:
            who = {"a": "TGR", "b": "VC", "both": "both (union)"}[prefer]
            print(f"\n--- {where}  base lines {lo}..{hi}   winner: {who}")
            print("    TGR:")
            for line in atxt:
                print("      | " + line)
            print("    VC:")
            for line in btxt:
                print("      | " + line)
    else:
        print("\nno conflicts: every hunk was touched by only one mod")

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current TGR / VC / vanilla sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
