"""
regen_vc_kai.py -- builds the VC x Kuromi's AI compatch in `_vc/kai+vc done`.

The pair: Kuromi's AI (KAI) loads early in the main pack, Victorian Century
(VC) loads last, right after the megapack. Machine matrix: 9 shared keys, 0
shared paths (VC.4 in `План проекта.md`). Analysis:
`conflicts_vc_vs_kai_report.md` in the output folder.

Three categories of the 9 keys, three different outcomes:

  * common/ship_types -- 5 keys (ship_type_monitor, _coastal_defense_ship,
    _troop_ship, _seaplane_tender, _aircraft_carrier). KAI's file is 100%
    INJECT:, always into `ai_weight` only. VC's file is 100% INJECT: too,
    always into `modifier` / `construction_goods` (troop_ship also
    `materiel_goods`). Disjoint sub-blocks on every one of the 5 shared
    records -- both apply, nothing to merge. NOT a real conflict.

  * common/defines -- NAI (1 key). KAI's kai_ai.txt sets 30-ish AI-tuning
    constants (REFORM_GOVERNMENT_*, MONEY_SPENDING_*, PRODUCTION_METHOD_*,
    MILITARY_UNITS_PER_FORMATION_ARMY...). VC's joi_ai.txt sets two
    completely different constants (BUILDING_PRIVATIZATION_CHANCE,
    CONSTRUCTION_MAX_NUM_PRODUCTION_BUILDING_CONSTRUCTIONS_SCALED_MAX).
    Defines merge per-key, not per-block (rules section 3) -- zero shared
    constant names. NOT a real conflict.

  * common/ai_strategies -- 3 keys, ALL real, because VC's REPLACE_OR_CREATE
    (loading after KAI) wipes KAI's earlier contribution on all three:

    - ai_strategy_great_reforms, ai_strategy_tanzimat_reforms: KAI only
      INJECT:s `revolution_aversion = { value = 67.5 }` into each. VC's
      REPLACE_OR_CREATE body for both turns out to be byte-identical to
      vanilla except for `possible` (VC swaps in its own journal-entry
      trigger; vanilla's revolution_aversion values -- 10 and 25 -- are
      carried over UNCHANGED, not a VC design choice). Same shape as the
      TGR restores in VC.1: KAI's INJECT is reissued verbatim on top of VC's
      later body.

    - ai_strategy_meiji_restoration: KAI does not INJECT here, it REPLACEs
      the whole record. Comparing all three bodies (vanilla / KAI / VC)
      against each other (Анализ 5 three-way merge):
        * VC's own delta from vanilla is ONLY `possible` (VC's Meiji
          Restoration is a full rework with its own journal entries --
          `meiji_restoration`, `meiji_restoration_mil/dip/eco/law/lad/ray`,
          group `je_group_meiji_restoration` REPLACE_OR_CREATE'd -- vanilla's
          `je_meiji_main` is left untouched by VC and MAY still fire from
          the untouched vanilla event `meiji.1`, but VC never checks it and
          the interaction between VC's parallel system and the old one is
          not established).
        * KAI's own delta from vanilla is FOUR things: revolution_aversion
          10->67.5, max_regressiveness 25->50, drops ig_armed_forces from
          anti_interest_groups, and adds an interest_group_government_weight
          block conditioned on `has_journal_entry = je_meiji_army` (a
          vanilla-only journal entry VC does not add -- VC's own military
          track uses journal type `meiji_restoration_mil`, and VC merely
          reuses the *variable name* `completed_je_meiji_army` for its own
          bookkeeping, it never adds the je_meiji_army journal entry itself).
      revolution_aversion and max_regressiveness are safe standalone numeric
      tweaks -- restored here. anti_interest_groups / interest_group_
      government_weight / possible are a bundled three-way design question
      that depends on whether je_meiji_army and je_meiji_main ever fire
      under VC's own Meiji rework, which is NOT established from the files
      alone -- left OPEN, see the report and README.

Usage:
    python3 regen_vc_kai.py            # write the compatch
    python3 regen_vc_kai.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

KAI = res("../../vic3_mods_out/TechRes+Kuromi/kai")
VC = res("../../vic3_mods_out/VC")
OUT = res("../_vc/kai+vc done")

HEADER = """# Kuromi's AI x VC compatch -- {what}
# Generated by tools/regen_vc_kai.py on {date}. Do not hand-edit: the next run
# overwrites this file. Change the generator instead.
#
# Load order: Kuromi's AI -> ... -> Victorian Century -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}


def block(lines: list[str], i: int) -> tuple[list[str], int]:
    """Given lines[i] is the opening `key = {` line, return (block_lines, j_next)."""
    depth = 0
    started = False
    for j in range(i, len(lines)):
        code = lines[j].split("#", 1)[0]
        depth += code.count("{") - code.count("}")
        if "{" in code:
            started = True
        if started and depth <= 0:
            return lines[i:j + 1], j + 1
    return lines[i:], len(lines)


def record(path: str, key: str) -> list[str] | None:
    """Lines of one top-level record, key line included, prefix stripped off."""
    lines = read_lines(path)
    pat = re.compile(r"^(?:[A-Z_]+:)?" + re.escape(key) + r"\s*=\s*\{")
    for i, raw in enumerate(lines):
        if pat.match(raw.split("#", 1)[0].lstrip("﻿")):
            body, _ = block(lines, i)
            body[0] = re.sub(r"^﻿?(?:[A-Z_]+:)?", "", body[0])
            return body
    return None


def find_file(root: str, category: str, key: str) -> str | None:
    directory = os.path.join(root, category)
    if not os.path.isdir(directory):
        return None
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".txt"):
            continue
        full = os.path.join(directory, name)
        if record(full, key) is not None:
            return full
    return None


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


# ------------------------------------------------------------------- the pieces

def build_ai_strategies():
    out_lines: list[str] = []

    # -- great_reforms / tanzimat_reforms: KAI's INJECT is a clean re-apply,
    #    VC's body carries vanilla's own revolution_aversion value forward
    #    unchanged, so nothing of VC's own is touched.
    for key in ("ai_strategy_great_reforms", "ai_strategy_tanzimat_reforms"):
        kai_f = find_file(KAI, "common/ai_strategies", key)
        assert kai_f, f"KAI {key} not found -- did the political strategies file move?"
        body = record(kai_f, key)
        text = "\n".join(body)
        assert re.sub(r"\s+", "", "\n".join(body[1:-1])) == "revolution_aversion={value=67.5}", (
            f"KAI's {key} INJECT is no longer just revolution_aversion=67.5 -- "
            f"re-check the merge, got: {body[1:-1]!r}")

        vc_f = find_file(VC, "common/ai_strategies", key)
        assert vc_f, f"VC {key} not found"
        vc_body = "\n".join(record(vc_f, key) or [])
        vc_rev = re.search(r"revolution_aversion\s*=\s*\{\s*value\s*=\s*([\d.]+)", vc_body)
        assert vc_rev, f"VC's {key} has no revolution_aversion -- re-check"
        assert vc_rev.group(1) != "67.5", (
            f"VC's {key} revolution_aversion is now 67.5 -- KAI's value may "
            f"already be present, re-check before re-injecting")

        text = re.sub(r"^(?:INJECT:|TRY_INJECT:)?" + re.escape(key), "INJECT:" + key, text, count=1)
        out_lines.append(text)
        out_lines.append("")

    # -- meiji_restoration: KAI REPLACEs the whole record, VC REPLACE_OR_CREATEs
    #    the whole record. Three-way merge against vanilla (Анализ 5): VC's own
    #    delta is only `possible`; KAI's own delta is revolution_aversion,
    #    max_regressiveness, anti_interest_groups and interest_group_government_
    #    weight. Only the two plain numeric fields are restored here -- see the
    #    module docstring and the README for why the other two are left open.
    key = "ai_strategy_meiji_restoration"
    vc_f = find_file(VC, "common/ai_strategies", key)
    assert vc_f, "VC ai_strategy_meiji_restoration not found"
    vc_body = record(vc_f, key)
    text = "\n".join(vc_body)

    assert "ig_armed_forces" in text, (
        "VC's meiji_restoration no longer lists ig_armed_forces in "
        "anti_interest_groups -- re-check the open item before regenerating")
    assert "interest_group_government_weight" not in text, (
        "VC's meiji_restoration now has its own interest_group_government_weight "
        "-- re-check before leaving KAI's version out")

    rev_pat = re.compile(r"(revolution_aversion\s*=\s*\{\s*value\s*=\s*)10(\s*\})")
    assert rev_pat.search(text), "VC's meiji_restoration revolution_aversion is not 10 -- re-check"
    text = rev_pat.sub(r"\g<1>67.5\g<2>", text, count=1)

    regr_pat = re.compile(r"(max_regressiveness\s*=\s*\{\s*value\s*=\s*)25(\s*\})")
    assert regr_pat.search(text), "VC's meiji_restoration max_regressiveness is not 25 -- re-check"
    text = regr_pat.sub(r"\g<1>50\g<2>", text, count=1)

    text = re.sub(r"^(?:REPLACE_OR_CREATE:|REPLACE:)?" + re.escape(key),
                  "REPLACE_OR_CREATE:" + key, text, count=1)
    out_lines.append(text)

    write("common/ai_strategies/zz_vc_kai_ai_strategies.txt",
          "\n".join(out_lines),
          "restore KAI's AI-competence tweaks on three political AI strategies",
          "VC's REPLACE_OR_CREATE wipes KAI's earlier contribution on all "
          "three shared ai_strategies records. great_reforms/tanzimat_reforms: "
          "KAI's revolution_aversion INJECT re-applied verbatim (VC's own body "
          "just carries vanilla's value forward, no VC design choice touched). "
          "meiji_restoration: three-way merge against vanilla -- VC's only own "
          "change is `possible` (kept as-is), KAI's revolution_aversion and "
          "max_regressiveness are restored as plain numeric tweaks. KAI's "
          "anti_interest_groups / interest_group_government_weight change is "
          "NOT included -- see README, it depends on journal entries "
          "(je_meiji_army, je_meiji_main) whose reachability under VC's own "
          "Meiji rework is not established from the files alone.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category = os.path.dirname(rel)
        depth = 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_vc_kai.py -> {OUT}")
    for name, fn in (
        ("ai_strategies", build_ai_strategies),
    ):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current KAI / VC sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
