"""
regen_llwa_tgr.py -- builds the LLWA x TGR compatch in `_llwa/llwa+tgr done`.

The pair: TGR loads early in the main pack, LLWA loads last in the target
chain (after VC, addon-VC, HC+GoB+MoH, addon-HC). Machine matrix: 11 shared
keys (LLWA.1/plan). 10 in common/production_methods, 1 (ai_strategy_default)
in common/ai_strategies -- see README for why the latter is NOT included here
(it's noneed: LLWA only ever touches ai_strategy_default via a separate
INJECT:subsidies file, additive, safe regardless of load order).

The 10 production_methods keys are all ten LLWA_rails.txt records. Three of
them (pm_no_passenger_trains, pm_steel_passenger_carriages,
pm_wooden_passenger_carriages) are ALSO shared with VC -- per the plan
("один файл на обе пары не делать") that restoration lives in
`_llwa/llwa+vc done`, not here, so this generator only covers the other
seven.

What's actually lost, and what is NOT restored:

  * TGR's own numeric rebalance (higher state_infrastructure_add, different
    goods_output_transportation_add, etc.) is NOT restored. LLWA loads last
    in the target chain, so LLWA's own numbers are the legitimate winner --
    restoring TGR's numbers back on top would silently overrule LLWA's own
    design choice, which is not what "LLWA loses something" means here.

  * What IS silently lost: TGR adds a `state_modifiers.unscaled = {
    state_market_access_price_impact = 0.05 }` sub-block on six of the seven
    (pm_early_trains, pm_steam_trains(+ptc3), pm_electric_trains(+ptc3),
    pm_diesel_trains) that LLWA's REPLACE: does not declare at all -- LLWA's
    body has no `unscaled` key anywhere in these records, so this is a pure
    addition, not two authors touching the same field. On the seventh
    (pm_diesel_trains_principle_transport_3) TGR's own file puts this same
    block under `building_modifiers.unscaled` instead of `state_modifiers.
    unscaled` -- almost certainly a copy-paste slip in TGR's own file (every
    other entry uses state_modifiers), but per "не чинить чужой замысел, не
    разобравшись" this generator reproduces TGR's actual placement exactly,
    not the "obviously intended" one.

  * Per the still-open REPLACE: sub-block question (rules file, section 3),
    any new REPLACE: written here is a FULL body, not a partial patch --
    correct under either reading of that question.

Usage:
    python3 regen_llwa_tgr.py            # write the compatch
    python3 regen_llwa_tgr.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3merge3 import brace_balance, needs_bom, read_lines  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

LLWA = res("../../vic3_mods_out/llwa")
TGR = res("../../vic3_mods_out/TheGreatRevision")
OUT = res("../_llwa/llwa+tgr done")

HEADER = """# LLWA x TGR compatch -- {what}
# Generated by tools/regen_llwa_tgr.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: TGR -> ... -> LLWA -> THIS.
# Why this file exists: {why}
"""

DATE = "2026-08-26"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

# The seven keys handled here. The other three (shared with VC too) live in
# _llwa/llwa+vc done.
KEYS = [
    "pm_early_trains",
    "pm_steam_trains",
    "pm_steam_trains_principle_transport_3",
    "pm_electric_trains",
    "pm_electric_trains_principle_transport_3",
    "pm_diesel_trains",
    "pm_diesel_trains_principle_transport_3",
]


def block(lines: list[str], i: int) -> tuple[list[str], int]:
    depth = 0
    started = False
    for j in range(i, len(lines)):
        code = lines[j].split("#", 1)[0]
        depth += code.count("{") - code.count("}")
        if "{" in code:
            started = True
        if started and depth <= 0:
            return lines[i:j + 1], j + 1
    return lines[i:], len(lines)


def record(path: str, key: str) -> list[str] | None:
    lines = read_lines(path)
    pat = re.compile(r"^(?:[A-Z_]+:)?" + re.escape(key) + r"\s*=\s*\{")
    for i, raw in enumerate(lines):
        if pat.match(raw.split("#", 1)[0].lstrip("﻿")):
            body, _ = block(lines, i)
            body[0] = re.sub(r"^﻿?(?:[A-Z_]+:)?", "", body[0])
            return body
    return None


def top_subblocks(body: list[str]) -> dict[str, tuple[int, int]]:
    """Map sub-block name -> (start, end) indices (inclusive) at depth 1
    within body. body[0] is the `key = {` line (depth 0 -> 1)."""
    out: dict[str, tuple[int, int]] = {}
    depth = 0
    i = 0
    n = len(body)
    while i < n:
        code = body[i].split("#", 1)[0]
        if i == 0:
            depth += code.count("{") - code.count("}")
            i += 1
            continue
        if depth == 1:
            m = re.match(r"^\s*([A-Za-z0-9_]+)\s*=\s*\{", code)
            if m:
                sub, j = block(body, i)
                out[m.group(1)] = (i, j - 1)
                depth += sum(c.count("{") - c.count("}") for c in
                             [x.split("#", 1)[0] for x in body[i:j]])
                i = j
                continue
        depth += code.count("{") - code.count("}")
        i += 1
    return out


def extract_nested(body: list[str], parent: str, nested: str) -> list[str] | None:
    subs = top_subblocks(body)
    if parent not in subs:
        return None
    lo, hi = subs[parent]
    parent_body = body[lo:hi + 1]
    inner = top_subblocks(parent_body)
    if nested not in inner:
        return None
    ilo, ihi = inner[nested]
    # inner block includes the `nested = {` line and its closing `}`; strip both
    return parent_body[ilo + 1:ihi]


def dedent(lines: list[str]) -> list[str]:
    """Strip the common leading-tab depth so callers can re-indent extracted
    source lines to a new target depth without doubling up."""
    non_empty = [l for l in lines if l.strip()]
    if not non_empty:
        return lines
    base = min(len(l) - len(l.lstrip("\t")) for l in non_empty)
    return [l[base:] if l.startswith("\t" * base) else l for l in lines]


def insert_nested(body: list[str], parent: str, nested: str, nested_lines: list[str]) -> list[str]:
    """Return a new body with `parent.nested = { nested_lines }` appended
    just before parent's closing brace. Creates `parent` if it doesn't
    exist (appended before the record's own closing brace, at depth-1
    indent). `nested_lines` is dedented first so it doesn't matter what
    absolute depth it was extracted from."""
    nested_lines = dedent(nested_lines)
    subs = top_subblocks(body)
    out = list(body)
    if parent in subs:
        lo, hi = subs[parent]
        assert "\t\t" + nested + " = {" not in [l.rstrip() for l in out[lo:hi + 1]], (
            f"{parent}.{nested} already present -- would duplicate")
        insertion = ["\t\t" + nested + " = {"] + ["\t\t\t" + l for l in nested_lines] + ["\t\t}"]
        out = out[:hi] + insertion + out[hi:]
    else:
        # insert a whole new parent block before the record's closing brace
        insertion = ["\t" + parent + " = {", "\t\t" + nested + " = {"] + \
                    ["\t\t\t" + l for l in nested_lines] + ["\t\t}", "\t}"]
        out = out[:-1] + insertion + out[-1:]
    return out


def write(rel: str, text: str, what: str, why: str, bom: bool | None = None):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip("\n") + "\n"
    balance = brace_balance(body)
    assert balance == 0, f"{rel}: brace balance {balance}"
    if bom is None:
        bom = needs_bom(body)
    blob = body.encode("utf-8-sig" if bom else "utf-8")
    WRITTEN[rel] = blob
    if CHECK_ONLY:
        old = open(path, "rb").read() if os.path.isfile(path) else None
        print(f"  {'SAME  ' if old == blob else 'DRIFT '} {rel}")
        return
    tmp = path + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(blob)
    os.replace(tmp, path)
    print(f"  wrote {rel}  ({len(body.splitlines())} lines, bom={bom})")


def build_rails():
    llwa_f = os.path.join(LLWA, "common/production_methods/LLWA_rails.txt")
    tgr_f = os.path.join(TGR, "common/production_methods/TGR_TRADE_private_infrastructure_railway.txt")
    assert os.path.isfile(llwa_f), "LLWA_rails.txt not found -- did LLWA rename it?"
    assert os.path.isfile(tgr_f), "TGR's rail PM file not found -- did TGR rename it?"

    out_records: list[str] = []
    for key in KEYS:
        llwa_body = record(llwa_f, key)
        assert llwa_body, f"LLWA has no {key} in LLWA_rails.txt -- re-check the key list"
        tgr_body = record(tgr_f, key)
        assert tgr_body, f"TGR has no {key} -- re-check the key list"

        # Find which top-level sub-block TGR nests `unscaled` under -- don't
        # assume, some entries put it under state_modifiers, one under
        # building_modifiers (see module docstring).
        tgr_subs = top_subblocks(tgr_body)
        parent = None
        for cand in ("state_modifiers", "building_modifiers"):
            if extract_nested(tgr_body, cand, "unscaled") is not None:
                parent = cand
                break
        assert parent, (
            f"TGR's {key} no longer has an `unscaled` sub-block anywhere -- "
            f"the thing this compatch restores may already be gone, re-check")

        unscaled_lines = extract_nested(tgr_body, parent, "unscaled")
        joined = " ".join(l.split("#", 1)[0].strip() for l in unscaled_lines if l.strip())
        assert re.sub(r"\s+", "", joined) == "state_market_access_price_impact=0.05", (
            f"TGR's {key} unscaled block is no longer just "
            f"state_market_access_price_impact=0.05, got: {unscaled_lines!r} -- re-check the merge")

        llwa_subs = top_subblocks(llwa_body)
        if parent in llwa_subs:
            existing = extract_nested(llwa_body, parent, "unscaled")
            assert existing is None, (
                f"LLWA's {key}.{parent} already has an unscaled sub-block -- "
                f"this generator assumes a pure addition, re-check before merging")

        new_body = insert_nested(llwa_body, parent, "unscaled", unscaled_lines)
        text = "REPLACE_OR_CREATE:" + "\n".join(new_body)
        out_records.append(text)

    write("common/production_methods/zz_llwa_tgr_rails.txt",
          "\n\n".join(out_records),
          "restore TGR's market-access modifier on seven rail production methods",
          "LLWA's REPLACE: on these seven records (loading last in the target "
          "chain) is a bare full body with no `unscaled` sub-block at all, so "
          "TGR's `state_market_access_price_impact = 0.05` addition (six under "
          "state_modifiers, one -- pm_diesel_trains_principle_transport_3 -- "
          "under building_modifiers in TGR's own file, reproduced as-is) is "
          "silently dropped. LLWA's own numeric rebalance is NOT touched: "
          "LLWA loads last, its numbers are the legitimate winner, restoring "
          "TGR's numbers on top would overrule LLWA's own design. The other "
          "three rail PMs LLWA shares with TGR (pm_no_passenger_trains, "
          "pm_steel_passenger_carriages, pm_wooden_passenger_carriages) are "
          "ALSO shared with VC -- that restoration lives in "
          "_llwa/llwa+vc done, not here, so one record isn't written twice.")


def self_check() -> int:
    bad = 0
    seen: dict[tuple[str, str], str] = {}
    for rel, blob in sorted(WRITTEN.items()):
        text = blob.decode("utf-8-sig")
        if brace_balance(text) != 0:
            print(f"  FAIL {rel}: brace balance {brace_balance(text)}")
            bad += 1
        if needs_bom(text) and not blob.startswith(b"\xef\xbb\xbf"):
            print(f"  FAIL {rel}: non-ASCII outside a comment, needs a BOM")
            bad += 1
        doubled = re.findall(r"^[A-Z_]+:[A-Z_]+:", text, re.M)
        if doubled:
            print(f"  FAIL {rel}: {len(doubled)} doubled prefix(es), e.g. {doubled[0]}")
            bad += 1
        category = os.path.dirname(rel)
        depth = 0
        for raw in text.split("\n"):
            code = raw.split("#", 1)[0]
            if depth == 0:
                m = re.match(r"^﻿?([A-Z_]+:)?([A-Za-z0-9_.\-]+)\s*=\s*\{", code)
                if m and (m.group(1) or "").rstrip(":") in ("INJECT", "TRY_INJECT"):
                    m = None
                if m and m.group(2) not in ("COUNTRIES", "GLOBAL", "BUILDINGS", "POPS"):
                    where = (category, m.group(2))
                    if where in seen:
                        print(f"  FAIL duplicate key {m.group(2)} in {category}: "
                              f"{seen[where]} and {rel}")
                        bad += 1
                    seen[where] = rel
            depth += code.count("{") - code.count("}")
    print(f"  self-check: {len(WRITTEN)} files, {len(seen)} top-level keys, "
          f"{bad} problem(s)")
    return bad


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    print(f"regen_llwa_tgr.py -> {OUT}")
    for name, fn in (
        ("rails", build_rails),
    ):
        print(f"[{name}]")
        fn()

    print()
    bad = self_check()
    if args.check:
        drifted = [r for r, blob in WRITTEN.items()
                   if (open(os.path.join(OUT, r), "rb").read()
                       if os.path.isfile(os.path.join(OUT, r)) else None) != blob]
        if drifted:
            print(f"\n{len(drifted)} file(s) on disk no longer match the sources:")
            for r in drifted:
                print("  " + r)
            return 1
        print("\nall files match the current LLWA / TGR sources")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
