#!/usr/bin/env python3
"""Финансовые центры форка «E&F: Ledgerdemain» (R8б, шаг 4; Д.R8.7, Д.R8б.1, Д.R8б.14): одна биржа на страну.

    python3 tools/regen_ld_financial_centres.py [--check]

Таблица `VARIANTS` — 38 вариантов E&F: суффикс типа, тег страны, чей это вариант, область (state region) и иконка;
общий финцентр (`building_financial_centre`) — у остальных. Вариант — оформление (название, иконка, область), правило
одно: здание финцентра можно расширять только в штате биржи своей страны (`zz_ef_fc_possible`, переменная страны
`zz_ef_fc_state`); новую биржу учреждает запись дневника «Учреждение биржи» (`financial_center_je_1`).

Пишет:
- `common/buildings/ef_16_financial_centre.txt` — типы по одному шаблону (общий + 38 вариантов);
- `common/scripted_effects/ld_fc_types.txt` — всё, что требует перечня типов: `zz_ef_fc_activate_pm` (метод во всех
  финцентрах штата), `zz_ef_fc_remove` (снести финцентр штата), `zz_ef_fc_expand` (частная стройка уровней биржи),
  `zz_ef_fc_variant_set` (вариант биржи страны — флаг `var:zz_ef_fc_variant`), `zz_ef_fc_found` (учредить биржу:
  вариант своей области или общий в столице);
- в `common/customizable_localization/00_ef_localization_ custom.txt` — `stock_exchange_name` (название биржи по
  варианту страны).

Манчестер (`gbr_2`), Чикаго (`usa_2`), Гонконг (`hkh`) — в `_archive/ef_fc_second_variants/` форка: вторая биржа
страны (Д.R8.7).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ld_gen  # noqa: E402

OUT_BLD = "common/buildings/ef_16_financial_centre.txt"
OUT_EFF = "common/scripted_effects/ld_fc_types.txt"
OUT_CUSTOM = "common/customizable_localization/00_ef_localization_ custom.txt"
ICONS = "gfx/interface/icons/building_icons/financial_centre/"
HEAD = "# GENERATED by tools/regen_ld_financial_centres.py -- do not edit by hand.\n"

# (suffix, tag, state region, icon)
VARIANTS = [
    ("arg", "ARG", "BUENOS_AIRES", "financial_centre_arg.dds"),
    ("aus", "AUS", "AUSTRIA", "financial_centre_aus.dds"),
    ("bav", "BAV", "BAVARIA", "financial_centre_bav.dds"),
    ("bel", "BEL", "FLANDERS", "financial_centre_bel.dds"),
    ("bic", "BIC", "BOMBAY", "financial_centre_bic.dds"),
    ("brz", "BRZ", "RIO_DE_JANEIRO", "financial_centre_brz.dds"),
    ("chi", "CHI", "SUZHOU", "financial_centre_chi.dds"),
    ("chl", "CHL", "SANTIAGO", "financial_centre_chl.dds"),
    ("den", "DEN", "ZEALAND", "financial_centre_den.dds"),
    ("dei", "DEI", "WEST_JAVA", "financial_centre_dei.dds"),
    ("egy", "EGY", "LOWER_EGYPT", "financial_centre_egy.dds"),
    ("fra", "FRA", "ILE_DE_FRANCE", "financial_centre_fra.dds"),
    ("frm", "FRM", "HESSE", "financial_centre_frm.dds"),
    ("gbr", "GBR", "HOME_COUNTIES", "financial_centre_gbr.dds"),
    ("gre", "GRE", "ATTICA", "financial_centre_gre.dds"),
    ("han", "HAN", "HANNOVER", "financial_centre_han.dds"),
    ("ita", "ITA", "LOMBARDY", "financial_centre_ita.dds"),
    ("jap", "JAP", "KANTO", "financial_centre_jap.dds"),
    ("mex", "MEX", "MEXICO", "financial_centre_mex.dds"),
    ("net", "NET", "HOLLAND", "financial_centre_net.dds"),
    ("nsw", "NSW", "NEW_SOUTH_WALES", "financial_centre_nsw.dds"),
    ("ont", "ONT", "ONTARIO", "financial_centre_ont.dds"),
    ("peu", "PEU", "LIMA", "financial_centre_peu.dds"),
    ("por", "POR", "ESTREMADURA", "financial_centre_por.dds"),
    ("pru", "PRU", "BRANDENBURG", "financial_centre_pru.dds"),
    ("que", "QUE", "QUEBEC", "financial_centre_que.dds"),
    ("rus", "RUS", "INGRIA", "financial_centre_rus.dds"),
    ("saf", "SAF", "CAPE_COLONY", "financial_centre_saf.dds"),
    ("sar", "SAR", "PIEDMONT", "financial_centre_sar.dds"),
    ("sic", "SIC", "CAMPANIA", "financial_centre_sic.dds"),
    ("spa", "SPA", "NEW_CASTILE", "financial_centre_spa.dds"),
    ("swe", "SWE", "SVEALAND", "financial_centre_swe.dds"),
    ("swi", "SWI", "WEST_SWITZERLAND", "financial_centre_swi.dds"),
    ("tus", "TUS", "TUSCANY", "financial_centre_tus.dds"),
    ("tur", "TUR", "EASTERN_THRACE", "financial_centre_tur.dds"),
    ("uru", "URU", "URUGUAY", "financial_centre_uru.dds"),
    ("usa", "USA", "NEW_YORK", "financial_centre_usa.dds"),
    ("sax", "SAX", "SAXONY", "financial_centre_sax.dds"),
]
TYPES = ["building_financial_centre"] + [f"building_financial_centre_{v[0]}" for v in VARIANTS]


def building(key, icon, region):
    pot = f"\tpotential = {{\n\t\tstate_region = s:STATE_{region}\n\t}}\n" if region else ""
    tech = "\tunlocking_technologies = {\n\t\tfinancial_center\n\t}\n\n" if not region else ""
    return (f"{key} = {{\n"
            "\tbuilding_group = bg_financial_centre\n"
            f"\ticon = \"{ICONS}{icon}\"\n"
            "\tcity_type = city\n"
            "\trequired_construction = construction_cost_very_low\n"
            "\tresidence_points_per_level = 0\n"
            "\tlevels_per_mesh = 10\n\n"
            "\tai_nationalization_desire = -1\n\n"
            f"{tech}"
            "\tproduction_method_groups = {\n"
            "\t\tpmg_manufacture_stock_exchange\n"
            "\t\tpmg_agricultural_stock_exchange\n"
            "\t\tpmg_mining_stock_exchange\n"
            "\t\tpmg_railroad_stock_exchange\n"
            "\t}\n\n"
            f"{pot}"
            "\t# only the country's own exchange grows (ld_fc_types.txt)\n"
            "\tpossible = {\n\t\tzz_ef_fc_possible = yes\n\t}\n\n"
            "\tcan_build_government = {\n\t\talways = no\n\t}\n"
            "\tcan_build_private = {\n\t\talways = yes\n\t}\n"
            "\thas_max_level = yes\n"
            "\tdownsizeable = no\n\n"
            "\townership_type = self\n"
            "\tbackground = \"gfx/interface/icons/building_icons/backgrounds/building_panel_bg_monuments.dds\"\n"
            "}\n")


def buildings():
    out = [HEAD, "# The financial centres (R8б.4): one exchange per country; the variants differ in name, icon and state region\n"
                 "# only -- see the generator's docstring.\n"]
    out.append(building("building_financial_centre", "financial_centre.dds", None))
    for suf, tag, region, icon in VARIANTS:
        out.append(f"# {tag}\n" + building(f"building_financial_centre_{suf}", icon, region))
    return "".join(out)


def effects():
    L = [HEAD, "# What needs the list of the financial centre's types (R8б.4) -- see the generator's docstring.\n"]
    L.append("\n# State scope: production method $PM$ in every financial centre of the state.\nzz_ef_fc_activate_pm = {\n")
    for t in TYPES:
        L.append(f"\tif = {{ limit = {{ has_building = {t} }} activate_production_method = {{ building_type = {t} production_method = $PM$ }} }}\n")
    L.append("}\n")
    L.append("\n# State scope: the state's financial centre removed (a financial crash, E&F).\nzz_ef_fc_remove = {\n")
    for t in TYPES:
        L.append(f"\tif = {{ limit = {{ has_building = {t} }} remove_building = {t} }}\n")
    L.append("}\n")
    L.append("\n# Country scope: $N$ levels of the country's exchange (var:zz_ef_fc_state), privately funded -- the journal's buttons\n"
             "# speculative_share_5..8_button (scripted_buttons/00_ef_buttons.txt, scripted_guis/00_financial_scripted_guis.txt).\n"
             "zz_ef_fc_expand = {\n\tif = {\n\t\tlimit = { has_variable = zz_ef_fc_state }\n\t\tvar:zz_ef_fc_state = {\n")
    for t in TYPES:
        L.append(f"\t\t\tif = {{ limit = {{ has_building = {t} can_construct_building = {t} }} "
                 f"while = {{ count = $N$ start_privately_funded_building_construction = {t} }} }}\n")
    L.append("\t\t}\n\t}\n}\n")
    L.append("\n# State scope (the exchange's state): its variant on the owner -- var:zz_ef_fc_variant = flag:<suffix>, none for the\n"
             "# common one (the name stock_exchange_name, the icon).\nzz_ef_fc_variant_set = {\n"
             "\towner = { if = { limit = { has_variable = zz_ef_fc_variant } remove_variable = zz_ef_fc_variant } }\n")
    for suf, tag, region, icon in VARIANTS:
        L.append(f"\tif = {{ limit = {{ has_building = building_financial_centre_{suf} }} owner = {{ set_variable = {{ name = zz_ef_fc_variant value = flag:{suf} }} }} }}\n")
    L.append("}\n")
    L.append("\n# Country scope: a new exchange (the journal «Учреждение биржи», Д.R8б.1) -- the country's variant in its state region\n"
             "# if the country holds a state there, else the common one in the capital; var:zz_ef_fc_state set first (the\n"
             "# buildings' possible reads it).\nzz_ef_fc_found = {\n\tif = { limit = { has_variable = zz_ef_fc_state } remove_variable = zz_ef_fc_state }\n")
    first = True
    for suf, tag, region, icon in VARIANTS:
        kw = "if" if first else "else_if"
        first = False
        L.append(f"\t{kw} = {{\n\t\tlimit = {{ c:{tag} ?= this any_scope_state = {{ state_region = s:STATE_{region} }} }}\n"
                 f"\t\trandom_scope_state = {{\n\t\t\tlimit = {{ state_region = s:STATE_{region} }}\n"
                 f"\t\t\towner = {{ set_variable = {{ name = zz_ef_fc_state value = prev }} }}\n"
                 f"\t\t\tcreate_building = {{ building = building_financial_centre_{suf} level = 1 }}\n\t\t}}\n\t}}\n")
    L.append("\telse_if = {\n\t\tlimit = { exists = capital }\n"
             "\t\tcapital = {\n\t\t\towner = { set_variable = { name = zz_ef_fc_state value = prev } }\n"
             "\t\t\tcreate_building = { building = building_financial_centre level = 1 }\n\t\t}\n\t}\n"
             "\tif = { limit = { has_variable = zz_ef_fc_state } var:zz_ef_fc_state = { zz_ef_fc_variant_set = yes } }\n"
             "\t# the exchange's investment fund (scripted_effects/ld_investment_fund.txt)\n\tzz_ef_fund_found = yes\n}\n")
    return "".join(L)


def custom():
    L = ["stock_exchange_name = {", "\ttype = country", "\tlog_loc_errors = no", "",
         "\t# the exchange's name by the country's variant (var:zz_ef_fc_variant, scripted_effects/ld_fc_types.txt);",
         "\t# the common one -- its generic name",
         "\ttext = {", "\t\ttrigger = { NOT = { has_variable = zz_ef_fc_variant } }",
         "\t\tlocalization_key = building_financial_centre_scripted", "\t}"]
    for suf, tag, region, icon in VARIANTS:
        L += ["\ttext = {", f"\t\ttrigger = {{ var:zz_ef_fc_variant ?= flag:{suf} }}",
              f"\t\tlocalization_key = building_financial_centre_{suf}", "\t}"]
    L.append("}")
    return "\n".join(L) + "\n"


def main():
    for path, text in ((OUT_BLD, buildings()), (OUT_EFF, effects())):
        assert text.count("{") == text.count("}"), path
        _put(path, text)
    ld_gen.emit(OUT_CUSTOM, custom())
    ld_gen.report("regen_ld_financial_centres")
    if ld_gen.CHECK and _changed:
        sys.exit(1)


_changed = []


def _put(rel, text):
    """A whole generated file (every entry is the generator's)."""
    import ld_pdx
    dst = os.path.join(ld_gen.FORK, rel)
    old, bom, eol = ld_pdx.read(dst) if os.path.exists(dst) else (None, True, "\n")
    if old is not None and old.replace("\r\n", "\n").lstrip("﻿") == text:
        return
    _changed.append(rel)
    print(f"  {'differs' if ld_gen.CHECK else 'written'}: {rel}")
    if not ld_gen.CHECK:
        ld_pdx.write(dst, text, bom=True if old is None else bom, eol=eol)


if __name__ == "__main__":
    main()
