#!/usr/bin/env python3
"""
В5.5 (decided by the user 5.10; with EF.37, Ф.10): a bond is a part of the engine's government debt.

The engine's debt (principal) is the treasury's loan from its own economy: the interest goes to the pops whose
privately owned cash reserves back the loans (vanilla concept_budget_interest_desc; the nationally owned part lowers
the government dividends). The engine takes and repays it alone. E&F's treasury bonds (ai_buy_bond_1..10: the buyer's
treasury pays the price, the seller gets nothing; the buyer's interest is E&F's income modifier from nobody, since
Е.5 / Д.2 the seller paid it as an expense line; at maturity the buyer gets the price back from nobody) become a
record of WHO HOLDS A PART of the seller's principal:

  1. purchase  -- the price goes into the seller's bank pool (not its treasury), at most the seller's principal minus
                  the parts already held; the rest goes back to the buyer's treasury;
  2. interest  -- the seller pays the engine as usual; the holder gets (its part / principal) x the week's interest
                  (the bridge's GetInterestPayment, var:zz_ef_g_ipay), out of the seller's pool (the pool took the
                  price: it sold part of its claim). E&F's income modifier and our Д.2 expense line go;
  3. repayment -- the engine repays alone; the principal under the parts held -> each holder gets the difference back
                  from the seller's pool; E&F's maturity -> the part is bought back from the seller's pool (E&F's
                  payout from nobody removed);
  4. default   -- the principal falls by more than half in a week (clear_debt, bankruptcy): the parts over it are
                  written off, nobody pays (accepted 5.10, check).
Weekly, in the money model's step: the holder walks its 10 slots; the seller's side is summed in var:zz_ef_bl_acc_*
and rolled into var:zz_ef_f_bl_* at its own step (at most a week late). Private banks' bonds
(ai_privat_bank_bond_value_N, 25 global bank slots) -- stage 2 (В7.1), not here. The bond tables (Е.6) -- later.

Writes (_ef/ef hotfix 1.13/common/):
  scripted_effects/zz_ef_bond_ledger.txt          -- the ledger (generated slots);
  scripted_effects/zz_ef_bond_maturity_no_payout.txt -- E&F's ai_bond_maturity_1..10 without the payout, and
                                                       interest_per_month_from_foreign_debt_investment reduced to
                                                       removing its modifier (key-level REPLACE_OR_CREATE: regenerate
                                                       after an E&F update; counts asserted).

Usage:
    py tools/regen_ef_bond_ledger.py [--check]
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))
SRC = res(r"..\..\vic3_mods_out\E&F\common\scripted_effects\01_financial_scripted_effects.txt")
HOT = res(r"..\_ef\ef hotfix 1.13\common")
OUT_LEDGER = os.path.join(HOT, "scripted_effects", "zz_ef_bond_ledger.txt")
OUT_MAT = os.path.join(HOT, "scripted_effects", "zz_ef_bond_maturity_no_payout.txt")
SLOTS = range(1, 11)
HEAD = "# GENERATED by tools/regen_ef_bond_ledger.py -- do not edit by hand.\n"


def match(text, i):
    d = 0
    for j in range(i, len(text)):
        d += {"{": 1, "}": -1}.get(text[j], 0)
        if d == 0:
            return j
    raise AssertionError


def block(t, name):
    m = re.search(rf"^{name} = \{{", t, re.M)
    assert m, f"{name} not found"
    i = t.index("{", m.start())
    return t[i + 1:match(t, i)]


def slot(n):
    return f"""
# slot {n}: E&F's ai_buy_bond_{n}_on / ai_seller_country_general_{n} / ai_total_bond_value_{n}
zz_ef_bl_slot_{n} = {{
	if = {{
		limit = {{
			has_variable = ai_buy_bond_{n}_on
			var:ai_buy_bond_{n}_on = 1
			NOT = {{ has_variable = zz_ef_bh_{n} }}
			has_variable = ai_seller_country_general_{n}
			has_variable = ai_total_bond_value_{n}
			exists = var:ai_seller_country_general_{n}
			var:ai_seller_country_general_{n} = {{ is_country_type = recognized }}
		}}
		set_variable = {{ name = zz_ef_bs_{n} value = var:ai_seller_country_general_{n} }}
		set_variable = {{ name = zz_ef_bh_{n} value = var:ai_total_bond_value_{n} }}
		zz_ef_bl_register = {{ N = {n} }}
	}}
	else_if = {{
		limit = {{
			has_variable = zz_ef_bh_{n}
			has_variable = ai_buy_bond_{n}_on
			var:ai_buy_bond_{n}_on = 1
			has_variable = zz_ef_bs_{n}
			exists = var:zz_ef_bs_{n}
		}}
		zz_ef_bl_hold = {{ N = {n} }}
	}}
	else_if = {{
		limit = {{ has_variable = zz_ef_bh_{n} }}
		zz_ef_bl_end = {{ N = {n} }}
	}}
}}
"""


def ledger():
    slots = "".join(slot(n) for n in SLOTS)
    calls = "".join(f"\tzz_ef_bl_slot_{n} = yes\n" for n in SLOTS)
    return HEAD + f"""# В5.5 (5.10): E&F's treasury bonds as parts of the seller's engine debt -- see the generator's docstring.
# Values: script_values/zz_ef_bond_ledger_values.txt (generated with this file).

# Country scope, weekly (zz_ef_money_model_step): the seller's side first (roll last week's sums, the ratio of the
# principal to the parts held), then this country's slots as a holder.
zz_ef_bond_ledger_step = {{
	# E&F's income modifier and our Д.2 expense line are gone (the holder is paid by the ledger)
	if = {{ limit = {{ has_modifier = zz_ef_foreign_bond_interest }} remove_modifier = zz_ef_foreign_bond_interest }}
	if = {{ limit = {{ has_modifier = interest_from_foreign_debt_investment }} remove_modifier = interest_from_foreign_debt_investment }}
	set_variable = {{ name = zz_ef_f_bond_int value = 0 }}
	# --- as a seller ---
	zz_ef_bl_roll = {{ F = sold }}
	zz_ef_bl_roll = {{ F = int_out }}
	zz_ef_bl_roll = {{ F = redeem }}
	zz_ef_bl_roll = {{ F = woff }}
	set_variable = {{ name = zz_ef_bl_ratio value = 1 }}
	if = {{ limit = {{ has_variable = zz_ef_bl_woff_now }} remove_variable = zz_ef_bl_woff_now }}
	if = {{
		limit = {{
			has_variable = zz_ef_bl_held
			var:zz_ef_bl_held > 0
			zz_ef_bl_principal < var:zz_ef_bl_held
		}}
		set_variable = {{ name = zz_ef_bl_ratio value = zz_ef_bl_principal }}
		change_variable = {{ name = zz_ef_bl_ratio divide = var:zz_ef_bl_held }}
		# default: the principal more than halved in a week -> the parts over it are written off
		if = {{
			limit = {{
				has_variable = zz_ef_bl_prev_principal
				zz_ef_bl_principal < zz_ef_bl_half_prev
			}}
			set_variable = {{ name = zz_ef_bl_woff_now value = yes }}
		}}
	}}
	set_variable = {{ name = zz_ef_bl_prev_principal value = zz_ef_bl_principal }}
	# --- as a holder ---
	set_variable = {{ name = zz_ef_f_bl_buy value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_refund value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_int_in value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_back value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_lost value = 0 }}
	set_variable = {{ name = zz_ef_f_bl_int_short value = 0 }}
{calls}	if = {{
		limit = {{
			OR = {{
				is_player = yes
				gdp > 20000000
				zz_ef_bl_held_v > 0
				zz_ef_bl_parts > 0
			}}
		}}
		debug_log = "EFB|[TimeKeeper.GetCurrentDate.GetString]|[THIS.GetCountry.GetNameNoFormatting]|principal [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_bl_principal')|0]|held [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_bl_held_v')|0]|ratio [THIS.GetCountry.MakeScope.Var('zz_ef_bl_ratio').GetValue|3]|ipay [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_g_ipay')|0]|sold [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_sold')|0]|int_out [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_int_out')|0]|redeem [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_redeem')|0]|woff [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_v_f_bl_woff')|0]|parts [THIS.GetCountry.MakeScope.ScriptValue('zz_ef_treasury_bonds')|0]|buy [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_buy').GetValue|0]|refund [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_refund').GetValue|0]|int_in [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_int_in').GetValue|0]|back [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_back').GetValue|0]|lost [THIS.GetCountry.MakeScope.Var('zz_ef_f_bl_lost').GetValue|0]"
	}}
}}

# var:zz_ef_f_bl_$F$ = var:zz_ef_bl_acc_$F$ (summed by the holders since our last step); the sum restarts.
zz_ef_bl_roll = {{
	set_variable = {{ name = zz_ef_f_bl_$F$ value = 0 }}
	if = {{
		limit = {{ has_variable = zz_ef_bl_acc_$F$ }}
		set_variable = {{ name = zz_ef_f_bl_$F$ value = var:zz_ef_bl_acc_$F$ }}
	}}
	set_variable = {{ name = zz_ef_bl_acc_$F$ value = 0 }}
}}

# Holder scope, slot $N$ just bought: var:zz_ef_bh_$N$ = E&F's price, var:zz_ef_bs_$N$ = the seller. The part is at
# most the seller's room (principal - the parts held); the rest back to our treasury; the part's price into the
# seller's pool.
zz_ef_bl_register = {{
	var:zz_ef_bs_$N$ = {{ save_scope_as = zz_ef_bl_seller }}
	set_variable = {{ name = zz_ef_bl_x value = scope:zz_ef_bl_seller.zz_ef_bl_room }}
	if = {{
		limit = {{ var:zz_ef_bh_$N$ > var:zz_ef_bl_x }}
		set_variable = {{ name = zz_ef_bl_y value = var:zz_ef_bh_$N$ }}
		change_variable = {{ name = zz_ef_bl_y subtract = var:zz_ef_bl_x }}
		add_treasury = var:zz_ef_bl_y
		change_variable = {{ name = zz_ef_f_bl_refund add = var:zz_ef_bl_y }}
		set_variable = {{ name = zz_ef_bh_$N$ value = var:zz_ef_bl_x }}
	}}
	change_variable = {{ name = zz_ef_f_bl_buy add = var:zz_ef_bh_$N$ }}
	scope:zz_ef_bl_seller = {{
		if = {{ limit = {{ NOT = {{ has_variable = zz_ef_bl_held }} }} set_variable = {{ name = zz_ef_bl_held value = 0 }} }}
		change_variable = {{ name = zz_ef_bl_held add = root.var:zz_ef_bh_$N$ }}
		zz_ef_bl_acc_add = {{ F = sold V = root.var:zz_ef_bh_$N$ }}
		add_investment_pool = root.var:zz_ef_bh_$N$
	}}
	remove_variable = zz_ef_bl_x
	if = {{ limit = {{ has_variable = zz_ef_bl_y }} remove_variable = zz_ef_bl_y }}
}}

# Holder scope, slot $N$ live: the seller's principal under the parts -> our part cut (paid back from its pool, or
# written off in a default); then the week's interest on what is left, from its pool.
zz_ef_bl_hold = {{
	var:zz_ef_bs_$N$ = {{ save_scope_as = zz_ef_bl_seller }}
	if = {{
		limit = {{
			scope:zz_ef_bl_seller = {{
				has_variable = zz_ef_bl_ratio
				var:zz_ef_bl_ratio < 1
			}}
		}}
		set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_bh_$N$ }}
		change_variable = {{ name = zz_ef_bl_x multiply = {{ value = 1 subtract = scope:zz_ef_bl_seller.var:zz_ef_bl_ratio }} }}
		change_variable = {{ name = zz_ef_bh_$N$ subtract = var:zz_ef_bl_x }}
		scope:zz_ef_bl_seller = {{ change_variable = {{ name = zz_ef_bl_held subtract = root.var:zz_ef_bl_x }} }}
		if = {{
			limit = {{ scope:zz_ef_bl_seller = {{ has_variable = zz_ef_bl_woff_now }} }}
			change_variable = {{ name = zz_ef_f_bl_lost add = var:zz_ef_bl_x }}
			scope:zz_ef_bl_seller = {{ zz_ef_bl_acc_add = {{ F = woff V = root.var:zz_ef_bl_x }} }}
		}}
		else = {{
			zz_ef_bl_pay = {{ F = redeem TO = zz_ef_f_bl_back SHORT = zz_ef_f_bl_lost }}
		}}
	}}
	set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_bh_$N$ }}
	change_variable = {{ name = zz_ef_bl_x multiply = scope:zz_ef_bl_seller.zz_ef_bl_int_per_part }}
	zz_ef_bl_pay = {{ F = int_out TO = zz_ef_f_bl_int_in SHORT = zz_ef_f_bl_int_short }}
	remove_variable = zz_ef_bl_x
}}

# Holder scope, slot $N$ ended (E&F's maturity, its payout removed): the seller's pool buys the part back.
zz_ef_bl_end = {{
	if = {{
		limit = {{
			has_variable = zz_ef_bs_$N$
			exists = var:zz_ef_bs_$N$
			var:zz_ef_bs_$N$ = {{ is_country_type = recognized }}
		}}
		var:zz_ef_bs_$N$ = {{ save_scope_as = zz_ef_bl_seller }}
		set_variable = {{ name = zz_ef_bl_x value = var:zz_ef_bh_$N$ }}
		scope:zz_ef_bl_seller = {{ change_variable = {{ name = zz_ef_bl_held subtract = root.var:zz_ef_bl_x }} }}
		zz_ef_bl_pay = {{ F = redeem TO = zz_ef_f_bl_back SHORT = zz_ef_f_bl_lost }}
		remove_variable = zz_ef_bl_x
	}}
	else = {{
		change_variable = {{ name = zz_ef_f_bl_lost add = var:zz_ef_bh_$N$ }}
	}}
	remove_variable = zz_ef_bh_$N$
	if = {{ limit = {{ has_variable = zz_ef_bs_$N$ }} remove_variable = zz_ef_bs_$N$ }}
}}

# Holder scope: var:zz_ef_bl_x from scope:zz_ef_bl_seller's pool (at most what it holds) to our treasury;
# the seller sums it under $F$, we under var:$TO$; what its pool could not pay -- under var:$SHORT$.
zz_ef_bl_pay = {{
	change_variable = {{ name = $SHORT$ add = var:zz_ef_bl_x }}
	set_variable = {{
		name = zz_ef_bl_x
		value = {{
			value = var:zz_ef_bl_x
			max = {{
				value = scope:zz_ef_bl_seller.investment_pool
				min = 0
			}}
			min = 0
		}}
	}}
	scope:zz_ef_bl_seller = {{
		add_investment_pool = {{
			value = root.var:zz_ef_bl_x
			multiply = -1
		}}
		zz_ef_bl_acc_add = {{ F = $F$ V = root.var:zz_ef_bl_x }}
	}}
	add_treasury = var:zz_ef_bl_x
	change_variable = {{ name = $TO$ add = var:zz_ef_bl_x }}
	change_variable = {{ name = $SHORT$ subtract = var:zz_ef_bl_x }}
}}

# Seller scope: var:zz_ef_bl_acc_$F$ += $V$.
zz_ef_bl_acc_add = {{
	if = {{ limit = {{ NOT = {{ has_variable = zz_ef_bl_acc_$F$ }} }} set_variable = {{ name = zz_ef_bl_acc_$F$ value = 0 }} }}
	change_variable = {{ name = zz_ef_bl_acc_$F$ add = $V$ }}
}}
{slots}"""


def values():
    held = "".join(f"\tif = {{ limit = {{ has_variable = zz_ef_bh_{n} }} add = var:zz_ef_bh_{n} }}\n" for n in SLOTS)
    vf = "".join(f"zz_ef_v_f_bl_{k} = {{\n\tvalue = 0\n\tif = {{ limit = {{ has_variable = zz_ef_f_bl_{k} }} value = var:zz_ef_f_bl_{k} }}\n}}\n"
                 for k in ("sold", "int_out", "redeem", "woff", "buy", "refund", "int_in", "back", "lost", "int_short"))
    return HEAD + f"""# В5.5 (5.10): values of the bond ledger (scripted_effects/zz_ef_bond_ledger.txt) -- see the generator's docstring.

# the engine's debt
zz_ef_bl_principal = {{
	value = principal
	min = 0
}}
zz_ef_bl_half_prev = {{
	value = 0
	if = {{ limit = {{ has_variable = zz_ef_bl_prev_principal }} value = var:zz_ef_bl_prev_principal }}
	multiply = 0.5
}}
# the parts of our principal held abroad
zz_ef_bl_held_v = {{
	value = 0
	if = {{ limit = {{ has_variable = zz_ef_bl_held }} value = var:zz_ef_bl_held }}
	min = 0
}}
# room for new parts
zz_ef_bl_room = {{
	value = zz_ef_bl_principal
	subtract = zz_ef_bl_held_v
	min = 0
}}
# the week's interest per unit of principal (the bridge's GetInterestPayment / principal)
zz_ef_bl_int_per_part = {{
	value = 0
	if = {{
		limit = {{ zz_ef_bl_principal > 0 }}
		value = zz_ef_v_g_ipay
		divide = zz_ef_bl_principal
		min = 0
		max = 0.01
	}}
}}
# our parts of other countries' debt (the treasury's foreign bonds, replaces E&F's prices in zz_ef_treasury_bonds)
zz_ef_bl_parts = {{
	value = 0
{held}}}
# the week's results (0 if unset)
{vf}"""


def maturity():
    t = open(SRC, encoding="utf-8-sig").read()
    out = [HEAD, "# В5.5 (5.10): E&F's bond maturity without its payout from nobody; the buyer's income modifier off -- see\n"
           "# tools/regen_ef_bond_ledger.py. !! MAINTENANCE !! Key-level REPLACE_OR_CREATE: regenerate after an E&F update.\n"]
    for n in SLOTS:
        body = block(t, f"ai_bond_maturity_{n}")
        pat = re.compile(r"\n[ \t]*if = \{\s*limit = \{\s*ai_no_longer_exists_%d = 1\s*\}\s*add_treasury = \{\s*add = "
                         r"var:ai_total_bond_value_%d\s*\}\s*\}" % (n, n))
        body, k = pat.subn("\n\t\t# В5.5: the payout from nobody removed -- the ledger buys the part back", body)
        assert k == 1, f"ai_bond_maturity_{n}: payout {k}"
        assert "add_treasury" not in body
        out.append(f"\nREPLACE_OR_CREATE:ai_bond_maturity_{n} = {{{body}}}\n")
    body = block(t, "interest_per_month_from_foreign_debt_investment")
    assert "add_modifier" in body and "interest_from_foreign_debt_investment" in body, "E&F's interest effect changed"
    out.append("\nREPLACE_OR_CREATE:interest_per_month_from_foreign_debt_investment = {\n"
               "\tremove_modifier = interest_from_foreign_debt_investment\n}\n")
    return "".join(out)


def main():
    outs = [(OUT_LEDGER, ledger()), (OUT_MAT, maturity()),
            (os.path.join(HOT, "script_values", "zz_ef_bond_ledger_values.txt"), values())]
    bad = 0
    for path, text in outs:
        assert text.count("{") == text.count("}"), path
        if "--check" in sys.argv:
            cur = open(path, encoding="utf-8-sig").read() if os.path.exists(path) else ""
            print("ok" if cur == text else "DIFFERS", path)
            bad += cur != text
            continue
        with open(path, "w", encoding="utf-8-sig", newline="\n") as f:
            f.write(text)
        print("ok", path)
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
