#!/usr/bin/env python3
"""
TGR.1 + TGR.3 -- TGR records written before game 1.13, brought up to 1.13.

TGR re-issues many vanilla records with full bodies written against an older
vanilla. Fields game 1.13 added to those records silently disappear. Two parts:

  1. Country ranks (TGR.1) -- full re-issue, see below.
  2. Plain 1.13 fields TGR's bodies lack (TGR.3), put back with INJECT:
     (adds fields, wipes nothing), each read from vanilla 1.13:
       treaty_articles  military_assistance, foreign_investment_rights --
                        max_target_involvement / target_involvement_applies_to
                        (the involvement cap), military_assistance's
                        non_fulfillment;
       company_types    category (1.13 company categories) on four companies,
                        prestige_goods_trigger on five;
       goods            obsession_chance on fish and groceries;
       buildings        aliases on nine industry buildings (save compatibility).
     Everything else the scan finds (TGR's laws, taxation, journal entries,
     GER formation, trade-center and refrigeration methods) is TGR's own
     redesign or shadowed by a later mod -- classified in the plan (TGR.3).

Country ranks
-------------
TGR's `common/country_ranks/TGR_POLITICS_country_ranks.txt` REPLACE_OR_CREATEs all
eight ranks with bodies written against an older vanilla. Game 1.13 added fields
to those records that TGR's bodies simply do not have:

    top level   treaty_article_cost, ai_pool_character_multiplier,
                ai_innovation_critical_threshold
    modifier    country_max_unassigned_generals_add,
                country_max_unassigned_admirals_add

so under TGR every rank loses them silently. With the Grey's pack this repairs
itself (soft_pop re-issues 1.13 bodies, `_greys/greys+tgr done` puts TGR's fields
back on top); without Grey's nothing did, until this file.

What is TGR's and is kept
-------------------------
Read live from TGR's files, never hand-copied:
  * every modifier field TGR adds or sets to a different value than vanilla
    1.13 -- today country_construction_add (+30 great, +20 major) and the
    lower country_support_independence_weekly_liberty_desire_add;
  * TGR_TRADE_country_ranks.txt's INJECT of state_export_advantage_mult /
    state_import_advantage_mult -- a REPLACE_OR_CREATE loading after TGR would
    otherwise wipe it;
  * country_loan_interest_rate_mult stays OUT: decision 27.08.2026 (GR.7a),
    TGR's loan system drops rank-dependent interest on purpose.

Anything else TGR drops from a vanilla body makes the generator stop -- a new
difference must be classified by a human (1.13 addition or TGR's intent).

Output: `_tgr/tgr 1.13 fix done/common/country_ranks/zz_tgr_ranks_fix.txt` and
`common/<category>/zz_tgr_113_fields.txt`, copied into the megapacks that carry
TGR (`megapack`, `megapack no t&r`). With the Grey's pack, grey_diplo re-issues
foreign_investment_rights later -- `_greys/greys_kai_fix done` carries the same
two fields there.

Usage:
    py tools/regen_tgr_113_fix.py            # write
    py tools/regen_tgr_113_fix.py --check    # report only, exit 1 if sources drifted
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

VAN = res("../../vic3_mods_out/.vanillaVIC3")
TGR = res("../../vic3_mods_out/TheGreatRevision")
OUT = res("../_tgr/tgr 1.13 fix done")
MEGAPACKS = [res("../__megapacks/megapack"), res("../__megapacks/megapack no t&r")]
REL = "common/country_ranks/zz_tgr_ranks_fix.txt"
DATE = "2026-09-25"

RANKS = [
    "great_power", "major_power", "minor_power", "insignificant_power",
    "unrecognized_major_power", "unrecognized_regional_power", "unrecognized_power",
    "decentralized_power",
]
# Fields vanilla 1.13 has and TGR's older bodies lack -- restored from vanilla.
NEW_IN_113_TOP = {"treaty_article_cost", "ai_pool_character_multiplier", "ai_innovation_critical_threshold"}
NEW_IN_113_MOD = {"country_max_unassigned_generals_add", "country_max_unassigned_admirals_add"}
# Dropped by TGR on purpose (GR.7a).
TGR_DROPS = {"country_loan_interest_rate_mult"}

FIELD = re.compile(r'(?m)^([ \t]*)([a-z_]+)[ \t]*=[ \t]*(-?[\d.]+|yes|no)[ \t]*(#[^\n]*)?$')

HEADER = """# TGR.1 -- country ranks: vanilla 1.13 bodies + TGR's own changes
# Generated by tools/regen_tgr_113_fix.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: TGR -> ... -> THIS (megapack). With the Grey's pack,
# _greys/greys+tgr done loads later and re-issues these ranks on soft_pop's bodies.
# Why: TGR's REPLACE_OR_CREATE bodies predate 1.13 and silently drop
# treaty_article_cost, ai_pool_character_multiplier,
# ai_innovation_critical_threshold and country_max_unassigned_generals/admirals_add.
# TGR's own fields are kept (marked "# TGR"): country_construction_add, the lower
# independence support, the trade-advantage INJECT; rank-dependent loan interest
# stays out (decision 27.08.2026, GR.7a).
"""


def fields(block: str) -> dict[str, str]:
    """Depth-1 scalar fields of a `{ ... }` block (sub-blocks skipped)."""
    out, depth = {}, 0
    for line in block.split("\n"):
        code = line.split("#", 1)[0]
        if depth == 1:
            m = re.match(r'^\s*([a-z_]+)\s*=\s*(-?[\d.]+|yes|no)\s*$', code)
            if m:
                out[m.group(1)] = m.group(2)
        depth += code.count("{") - code.count("}")
    return out


def build() -> str:
    van_text = V.read(os.path.join(VAN, "common/country_ranks/00_country_ranks.txt"))
    pol_text = V.read(os.path.join(TGR, "common/country_ranks/TGR_POLITICS_country_ranks.txt"))
    trd_text = V.read(os.path.join(TGR, "common/country_ranks/TGR_TRADE_country_ranks.txt"))
    records = []
    for rank in RANKS:
        _, vbody = V.entry(van_text, rank, None)
        _, tbody = V.entry(pol_text, rank, "REPLACE_OR_CREATE:")

        # top level: TGR may only lack 1.13 additions, never differ
        vtop, ttop = fields("{" + vbody + "}"), fields("{" + tbody + "}")
        for k, v in vtop.items():
            if k not in ttop:
                assert k in NEW_IN_113_TOP, f"{rank}: TGR drops top-level {k} -- classify it"
            else:
                assert ttop[k] == v, f"{rank}: TGR changes top-level {k} {v}->{ttop[k]} -- classify it"
        for k in ttop:
            assert k in vtop, f"{rank}: TGR adds top-level {k} -- classify it"

        # sub-blocks other than modifier (valid_country_types, ...) are taken from
        # vanilla: TGR must not have changed them
        norm = lambda s: re.sub(r"\s+", " ", re.sub(r"#[^\n]*", "", s or "")).strip()
        for s in (set(V.sub_names(vbody)) | set(V.sub_names(tbody))) - {"modifier"}:
            assert norm(V.sub(vbody, s)) == norm(V.sub(tbody, s)), f"{rank}: TGR changes sub-block {s} -- classify it"

        vmod, tmod = V.sub(vbody, "modifier"), V.sub(tbody, "modifier")
        assert vmod is not None and tmod is not None, f"{rank}: no modifier block"
        vf, tf = fields(vmod), fields(tmod)
        new_mod = vmod
        for k in vf:
            if k in tf:
                continue
            if k in TGR_DROPS:
                new_mod = FIELD.sub(lambda m: (f"{m.group(1)}# {m.group(2)} = {m.group(3)}  # dropped by TGR's loan system (GR.7a)"
                                               if m.group(2) == k else m.group(0)), new_mod)
            else:
                assert k in NEW_IN_113_MOD, f"{rank}: TGR drops modifier {k} -- classify it"
        extra = []
        for k, tv in tf.items():
            if k not in vf:
                extra.append(f"{k} = {tv}  # TGR, not in vanilla")
            elif vf[k] != tv:
                new_mod = FIELD.sub(lambda m: (f"{m.group(1)}{k} = {tv}  # TGR (vanilla {vf[k]})"
                                               if m.group(2) == k else m.group(0)), new_mod)
        try:
            _, ibody = V.entry(trd_text, rank, "INJECT:")
            imod = V.sub(ibody, "modifier")
            for k, v in fields(imod).items():
                assert k not in vf and k not in tf, f"{rank}: TGR_TRADE injects {k} over an existing field"
                extra.append(f"{k} = {v}  # TGR_TRADE inject")
        except KeyError:
            pass
        if extra:
            close = new_mod.rstrip().rfind("}")
            new_mod = new_mod[:close].rstrip() + "\n\t\t" + "\n\t\t".join(extra) + "\n\t}"
        new_body = V.replace_sub(vbody, "modifier", new_mod)
        records.append(f"REPLACE_OR_CREATE:{rank} = {{{new_body}}}")
    return HEADER.format(date=DATE) + "\n" + "\n\n".join(records) + "\n"


# ---------------------------------------------------------------------------
# TGR.3 -- INJECT the 1.13 fields TGR's bodies lack
# ---------------------------------------------------------------------------

# (category, record, [fields]) -- each field must exist in vanilla 1.13 and be
# absent from every TGR body of that record, else the generator stops.
INJECTS = [
    ("treaty_articles", "military_assistance", ["max_target_involvement", "target_involvement_applies_to", "non_fulfillment"]),
    ("treaty_articles", "foreign_investment_rights", ["max_target_involvement", "target_involvement_applies_to"]),
    ("company_types", "company_east_india_company", ["category"]),
    ("company_types", "company_russian_american_company", ["category", "prestige_goods_trigger"]),
    ("company_types", "company_imperial_arsenal", ["category"]),
    ("company_types", "company_lkab", ["category"]),
    ("company_types", "company_dmc", ["prestige_goods_trigger"]),
    ("company_types", "company_hbc", ["prestige_goods_trigger"]),
    ("company_types", "company_altos_hornos_de_vizcaya", ["prestige_goods_trigger"]),
    ("company_types", "company_sherkate_eslamiya", ["prestige_goods_trigger"]),
    ("goods", "fish", ["obsession_chance"]),
    ("goods", "groceries", ["obsession_chance"]),
    # laws: 1.13 DLC content TGR's older bodies never had -- Japan's sakoku / Edo
    # system, Austria's manorialism, anarchy / factory councils, law variants
    # (`parent`), the opening of Japan. NOT here: tax_modifier_* (TGR's tax panel
    # replaces them on purpose) and `modifier` on law_no_colonial_affairs /
    # law_commercialized_agriculture (a removed modifier may be TGR's balance).
    ("laws", "law_peasant_levies", ["is_visible"]),
    ("laws", "law_professional_army", ["disallowing_laws"]),
    ("laws", "law_national_militia", ["disallowing_laws"]),
    ("laws", "law_mass_conscription", ["disallowing_laws"]),
    ("laws", "law_hereditary_bureaucrats", ["is_visible"]),
    ("laws", "law_frontier_colonization", ["disallowing_laws"]),
    ("laws", "law_colonial_resettlement", ["disallowing_laws"]),
    ("laws", "law_colonial_exploitation", ["disallowing_laws"]),
    ("laws", "law_industry_banned", ["disallowing_laws"]),
    ("laws", "law_extraction_economy", ["disallowing_laws"]),
    ("laws", "law_private_schools", ["is_visible"]),
    ("laws", "law_serfdom", ["is_visible"]),
    ("laws", "law_tenant_farmers", ["is_visible"]),
    ("laws", "law_homesteading", ["is_visible", "parent"]),
    ("laws", "law_no_migration_controls", ["disallowing_laws"]),
    ("laws", "law_migration_controls", ["disallowing_laws"]),
    ("laws", "law_closed_borders", ["on_deactivate"]),
    ("laws", "law_no_womens_rights", ["is_visible"]),
    ("laws", "law_no_social_security", ["is_visible"]),
    ("production_methods", "pm_simple_organization", ["ai_value"]),
    ("journal_entries", "je_schleswig_holstein_question", ["is_shown_in_lobby"]),
    ("journal_entries", "je_german_unification", ["is_shown_in_lobby"]),
    ("journal_entries", "je_risorgimento", ["is_shown_in_lobby"]),
] + [("buildings", b, ["aliases"]) for b in (
    "building_textile_mill", "building_furniture_manufactory", "building_tooling_workshop",
    "building_paper_mill", "building_chemical_plant", "building_synthetics_plant",
    "building_steel_mill", "building_arms_industry", "building_munition_plant")]

INJECT_HEADER = """# TGR.3 -- 1.13 fields TGR's older bodies lack, put back with INJECT:
# Generated by tools/regen_tgr_113_fix.py on {date}. Do not hand-edit: the next
# run overwrites this file. Change the generator instead.
#
# Load order: TGR -> ... -> THIS (megapack). TGR re-issues these records with
# bodies written before game 1.13; the fields below are 1.13's, read verbatim
# from vanilla. INJECT: adds them and wipes nothing of TGR's.
"""


def _find(root: str, cat: str, key: str, prefixes=None) -> list[str]:
    out = []
    for dp, dn, fn in os.walk(os.path.join(root, "common", cat)):
        for f in sorted(fn):
            if not f.endswith(".txt"):
                continue
            text = V.read(os.path.join(dp, f))
            for m in re.finditer(r"(?m)^((?:[A-Z_]+:)?)" + re.escape(key) + r"\s*=\s*\{", text):
                if prefixes is not None and m.group(1) not in prefixes:
                    continue
                i = text.index("{", m.start())
                j = V._match_brace(text, i)
                out.append(text[i + 1:j])
    return out


def _field(body: str, name: str) -> str | None:
    """The whole depth-0 statement `name = ...` of a body, or None."""
    span = V.sub_span(body, name)
    if span:
        return body[span[0]:span[1]].strip()
    depth = 0
    for line in body.split("\n"):
        code = line.split("#", 1)[0]
        if depth == 0:
            m = re.match(r"^\s*(" + re.escape(name) + r"\s*=\s*\S+)\s*$", code)
            if m:
                return m.group(1)
        depth += code.count("{") - code.count("}")
    return None


def build_injects() -> dict[str, str]:
    per_cat: dict[str, list[str]] = {}
    for cat, key, fields in INJECTS:
        van = _find(VAN, cat, key)
        assert len(van) == 1, f"{cat}/{key}: {len(van)} vanilla bodies -- re-check"
        tgr = _find(TGR, cat, key, prefixes=("", "REPLACE:", "REPLACE_OR_CREATE:"))
        assert tgr, f"{cat}/{key}: TGR no longer re-issues it -- drop it from INJECTS"
        stmts = []
        for fld in fields:
            v = _field(van[0], fld)
            assert v, f"{cat}/{key}: vanilla has no {fld} -- re-check"
            for b in tgr:
                assert _field(b, fld) is None, f"{cat}/{key}: TGR now has {fld} -- drop it from INJECTS"
            stmts.append(v)
        per_cat.setdefault(cat, []).append(
            f"INJECT:{key} = {{\n\t" + "\n\t".join(s.replace("\n", "\n\t") for s in stmts) + "\n}")
    return {f"common/{cat}/zz_tgr_113_fields.txt": INJECT_HEADER.format(date=DATE) + "\n" + "\n\n".join(recs) + "\n"
            for cat, recs in per_cat.items()}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    files = {REL: build()}
    files.update(build_injects())
    targets = [OUT] + MEGAPACKS
    drift = []
    for root in targets:
      for rel, text in files.items():
        assert V.brace_balance(text) == 0, rel
        blob = text.encode("utf-8")
        p = os.path.join(root, rel)
        old = open(p, "rb").read() if os.path.isfile(p) else None
        if old != blob:
            drift.append(p)
            if not a.check:
                os.makedirs(os.path.dirname(p), exist_ok=True)
                open(p, "wb").write(blob)
                print(f"  wrote {p}")
    if a.check:
        for p in drift:
            print(f"  DRIFT {p}")
        print("all files match the current vanilla / TGR sources" if not drift else f"{len(drift)} file(s) drifted")
        return 1 if drift else 0
    print(f"  {len(files)} files x {len(targets)} places, {len(drift)} written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
