#!/usr/bin/env python3
"""
EF.48, В3.3 (decided 2.10): a customs union member keeps its own currency, with a trade account.

E&F's money_value (00_economic_scripted_value.txt:5292) gives every country that does not own its market
(market_owner_is_root_4 = no) the market owner's value -- a subject and a customs union member alike;
money_value_in_gold converts it by the owner's standard. A member with its own central bank and metal
(the Zollverein's states) had no currency of its own. And the engine counts no exports inside a common
market, so our Hume step (zz_ef_trade_net_week: the market's exports - imports, market owners only) saw
nothing of a member's trade.

Here:
  * zz_ef_currency_own (scripted trigger): the country owns its market, or it is a member with a CB that
    is not a subject (is_subject_custom_trigger = no; subjects -- the suzerain's currency, В3.2);
    money_value and money_value_in_gold are re-issued with it in place of market_owner_is_root_4;
  * zz_ef_member_goods_net: a member's trade account -- what its states produce beyond what they consume,
    good by good (state_goods_production - state_goods_consumption), at the market's price; the 53
    vanilla goods (sg: takes a fixed key only; the goods of other mods -- Morgenroete, PSC -- are a small
    share of trade and are left out);
  * zz_ef_members_trade_sum: the market owner's side -- the members' accounts it pays (used in
    zz_ef_trade_net_week, values file of the money model).

Writes (_ef/ef hotfix 1.13/common/): script_values/zz_ef_customs_union_values.txt,
scripted_triggers/zz_ef_customs_union_triggers.txt

Usage:
    py tools/regen_ef_customs_union.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))
VANILLA_GOODS = res(r"..\..\vic3_mods_out\.vanillaVIC3\common\goods\00_goods.txt")
EF_SV = res(r"..\..\vic3_mods_out\E&F\common\script_values\00_economic_scripted_value.txt")
HOTFIX = res(r"..\_ef\ef hotfix 1.13\common")

HEAD = ("# GENERATED by tools/regen_ef_customs_union.py -- do not edit by hand.\n"
        "# EF.48, В3.3 (2.10): a customs union member's own currency and trade account -- see the generator.\n")


def block(text, name):
    m = re.search(rf"^{re.escape(name)} = \{{", text, re.M)
    assert m, name
    i = text.index("{", m.start())
    d = 0
    for j in range(i, len(text)):
        d += {"{": 1, "}": -1}.get(text[j], 0)
        if d == 0:
            return text[i:j + 1]
    raise AssertionError(name)


def goods():
    t = open(VANILLA_GOODS, encoding="utf-8-sig").read()
    g = re.findall(r"^([a-z_]+) = \{", t, re.M)
    assert len(g) == 53, len(g)
    return g


def values():
    ef = open(EF_SV, encoding="utf-8-sig").read()
    out = [HEAD, "# !! MAINTENANCE !! Key-level REPLACE_OR_CREATE of E&F's money_value and money_value_in_gold:\n"
                 "# regenerate after an E&F update.\n\n"]
    for name, n_expected in (("money_value", 1), ("money_value_in_gold", 4)):
        body = block(ef, name)
        # the live checks only (the commented-out ones stay as they are)
        live = re.findall(r"^(?![ \t]*#).*market_owner_is_root_4\s*=\s*(?:yes|no)", body, re.M)
        assert len(live) == n_expected, (name, live)
        body = re.sub(r"^((?![ \t]*#).*?)market_owner_is_root_4(\s*)=(\s*)(yes|no)",
                      lambda m: f"{m.group(1)}zz_ef_currency_own{m.group(2)}={m.group(3)}{m.group(4)}",
                      body, flags=re.M)
        out.append(f"REPLACE_OR_CREATE:{name} = {body}\n\n")
    out.append("# A member's trade account for the week: its states' production beyond their consumption, at the\n"
               "# market's price (engine money; + it sells into the common market). 0 for others.\n"
               "zz_ef_member_goods_net = {\n\tvalue = 0\n\tif = {\n\t\tlimit = { zz_ef_cu_member = yes }\n")
    for g in goods():
        out.append(f"\t\tadd = {{\n\t\t\tvalue = 0\n"
                   f"\t\t\tevery_scope_state = {{ add = sg:{g}.state_goods_production subtract = sg:{g}.state_goods_consumption }}\n"
                   f"\t\t\tmultiply = {{ value = market.mg:{g}.market_goods_pricier add = 1 }}\n"
                   f"\t\t\tmultiply = g:{g}.base_price\n\t\t}}\n")
    out.append("\t}\n}\n")
    out.append("# The market owner's side: the members' accounts of the week (stored by each member's receiver).\n"
               "zz_ef_members_trade_sum = {\n\tvalue = 0\n"
               "\tevery_country = {\n\t\tlimit = {\n\t\t\tNOT = { this = root }\n\t\t\tmarket.owner = root\n"
               "\t\t\tzz_ef_cu_member = yes\n\t\t\thas_variable = zz_ef_member_trade\n\t\t}\n"
               "\t\tadd = var:zz_ef_member_trade\n\t}\n}\n")
    return "".join(out)


TRIGGERS = HEAD + """
# A customs union member with a currency of its own: in a market it does not own, with a central bank,
# not a subject (subjects: the suzerain's currency, В3.2).
zz_ef_cu_member = {
	NOT = { market.owner = this }
	has_modifier = has_central_bank
	is_subject_custom_trigger = no
}
# The country's money is its own (E&F's money_value / money_value_in_gold): it owns its market or is
# such a member.
zz_ef_currency_own = {
	OR = {
		market.owner = this
		zz_ef_cu_member = yes
	}
}
"""


def write(path, text):
    with open(path, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write(text)
    print("ok", path)


def main():
    write(os.path.join(HOTFIX, "script_values", "zz_ef_customs_union_values.txt"), values())
    write(os.path.join(HOTFIX, "scripted_triggers", "zz_ef_customs_union_triggers.txt"), TRIGGERS)


if __name__ == "__main__":
    main()
