#!/usr/bin/env python3
"""
regen_ef_metal_hoard.py -- stage 2, night 6.10, step 4: pops buy gold and silver (Д2.21, Д2.24).

Why
---
Metal is a good (М, the user 6.10): every unit on any account was bought on the market. The pops are one of its
buyers: their metal is part of their savings, held out of distrust (Д3.4) -- in the XIX century the hoard was the
peasants' and workers' savings, the rich held paper.
  * wealth 15+: gold and silver are two more choices in E&F's popneed_financial_products (bonds, stocks, mutual
    funds) -- pops take what is cheaper, the weight follows the market's sell orders (Д2.21);
  * wealth 5-14: a new need, popneed_metal_hoard -- metals only (Д2.24 б: metals from wealth 5, paper from 15).
The money pops spend on them leaves their income through the market (the leak to their savings falls by as much),
the metal goes to their account var:zz_ef_popm_gold / _silver (scripted_effects/zz_ef_metal_accounts.txt: the
states' consumption minus the banks' buildings' input, x 100 / x 775 units a good).

What it writes (through ld_gen.emit, by entry keys, into the fork «E&F: Ledgerdemain»)
--------------
1. common/pop_needs/ld_metal_hoard.txt -- popneed_metal_hoard (silver default, gold).
2. localization/{english,russian}/ld_metal_hoard_l_<lang>.yml.
The INJECT of gold and silver into popneed_financial_products (wealth 15+) and the wealth_5..wealth_14 packages
are merged into the fork's E&F / buy-package files by hand and are not generated. Reads nothing.

!! TUNING !! (accepted at night 6.10, check): the entries' weight and max_supply_share
(pops must not buy the market out from under the CBs: max_supply_share 0.5).

Usage:  python3 tools/regen_ef_metal_hoard.py [--check]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ld_gen  # noqa: E402

NEED = "popneed_metal_hoard"
WEIGHT, MAX_SHARE = 0.5, 0.5

OUT_NEED = "common/pop_needs/zz_ef_metal_hoard.txt"   # hotfix path; ld_gen maps it into the fork

LOC = {
    "english": {
        NEED: "Hoarded Metal",
        NEED + "_desc": "Gold and silver coin kept at home: the savings of those who trust neither banks nor paper.",
    },
    "russian": {
        NEED: "Металл в кубышке",
        NEED + "_desc": "Золотая и серебряная монета дома: сбережения тех, кто не доверяет ни банкам, ни бумагам.",
    },
}

HEAD = """### GENERATED by tools/regen_ef_metal_hoard.py -- do not edit by hand.
### Stage 2, night 6.10 (Д2.21, Д2.24): pops buy gold and silver -- metals from wealth 5, paper from wealth 15.
"""


def entry(good: str) -> str:
    return f"""
	entry = {{
		goods = {good}

		weight = {WEIGHT:g}
		max_supply_share = {MAX_SHARE:g}
		min_supply_share = 0.0
	}}
"""


def build_need() -> str:
    return HEAD + f"""### The hoard: metals only, silver by default (the small saver's coin). Weight by the market's sell orders.

{NEED} = {{
	default = silver
{entry("silver")}{entry("gold")}}}
"""


def build_loc(lang: str) -> str:
    lines = [f"l_{lang}:"] + [f' {k}:0 "{v}"' for k, v in LOC[lang].items()]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    files = [(OUT_NEED, build_need())]
    for lang in LOC:
        files.append((f"localization/{lang}/zz_ef_metal_hoard_l_{lang}.yml", build_loc(lang)))
    for path, text in files:
        assert text.count("{") == text.count("}"), path
        ld_gen.emit(path, text)
    ld_gen.report("regen_ef_metal_hoard")
    return 0


if __name__ == "__main__":
    sys.exit(main())
