#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
regen_greys_llwa.py -- builds the Grey's x addon-LLWA compatch in `_greys/greys+llwa`.

Task GR.16, 41 shared keys total (see the plan). This script covers the two
pieces that are pure silent losses with nothing to dispute -- grey_usu simply
does not know LLWA's building types exist, there is no competing design to
weigh against:

  * Eight railway companies: grey_usu's TRY_REPLACE: on each is a full body
    that pre-dates LLWA and has its own extension_building_types list, so
    addon-LLWA's earlier TRY_INJECT: of LLWA_building_roadway is silently gone
    (classic full-body-after-additive-inject loss). Re-issued as a plain
    TRY_INJECT: after the whole Grey's pack -- additive, so it does not matter
    that grey_usu's REPLACE already ran.

  * Three rail production methods (pm_no_passenger_trains,
    pm_steel_passenger_carriages, pm_wooden_passenger_carriages): the exact
    same shape, `building_modifiers.unscaled.building_job_attractiveness_mult
    = 2` (originally VC's, already restored against LLWA's own body in
    `_llwa/llwa+vc done`) is missing from grey_usu's REPLACE_OR_CREATE bodies
    for these three. grey_usu's own numbers on every other field are kept
    untouched -- this is the same "keep the later mod's design, restore only
    the narrow missing field" rule already applied in llwa+tgr done /
    llwa+vc done.

NOT in this patch (see the plan's GR.16 bullet for the reasoning):
  * The other seven rail production methods -- grey_usu has its own
    progressively-scaled state_market_access_price_impact design on all
    seven, a genuine numeric dispute, not a silent loss. No file.
  * building_railway / building_airport -- shared with GR.9/GR.17, one body,
    handled there.
  * The six railway companies that ALSO collide with Victorian Century
    (company_great_indian_railway, company_mantetsu, company_orient_express,
    company_panama_company, company_prussian_state_railways,
    company_suez_company) -- these already get a full-body REPLACE_OR_CREATE
    from `_greys/greys+vc done/common/company_types/zz_gvc_companies.txt`.
    Writing a second, separate TRY_INJECT: for them here would do nothing:
    that file's REPLACE_OR_CREATE loads at the same position (after the whole
    Grey's pack) and a full body always wins over an earlier additive INJECT.
    The LLWA fix for those six is folded directly into that file instead --
    see tools/regen_greys_vc.py and its own README section.

Usage:
    python3 regen_greys_llwa.py            # write the compatch
    python3 regen_greys_llwa.py --check    # report only, exit 1 if sources drifted
"""
from __future__ import annotations
import argparse, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vic3lib as V  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
res = lambda p: os.path.normpath(os.path.join(HERE, p))

GREYS = res("../../vic3_mods_out/grey_add_alot_of_things")
USU = os.path.join(GREYS, "grey_usu")
ADDON_LLWA = res("../__addon/addon llwa")
OUT = res("../_greys/greys+llwa")

DATE = "2026-08-27"
CHECK_ONLY = False
WRITTEN: dict[str, bytes] = {}

HEADER = """### ComPatch Grey's x addon-LLWA -- {what}
###
{why}
### Generated by tools/regen_greys_llwa.py on {date}. Do not hand-edit: the
### next run overwrites this file. Change the generator instead.
### Load order: ... -> addon-LLWA -> ... -> the whole Grey's pack -> THIS.
"""


def write(rel: str, text: str, what: str, why: str):
    body = HEADER.format(what=what, why=why, date=DATE) + "\n" + text.rstrip() + "\n"
    assert V.brace_balance(body) == 0, f"{rel}: unbalanced braces"
    path = os.path.join(OUT, rel)
    if CHECK_ONLY:
        old = V.read(path) if os.path.exists(path) else None
        if old != body:
            print(f"DRIFT: {rel} would change")
            WRITTEN["__drift__"] = b"1"
        return
    V.write(path, body)
    print(f"  wrote {rel} ({len(text.splitlines())} lines)")


# --------------------------------------------------------------------------
# 1. Eight railway companies -- LLWA_building_roadway silently dropped
# --------------------------------------------------------------------------

COMPANIES_ROADWAY = [
    "company_cfr", "company_cordoba_railway", "company_egyptian_rail",
    "company_gwr", "company_imperial_ethiopian_railways",
    "company_iranian_state_railway", "company_sao_paulo_railway",
    "company_tashkent_railroad",
]

RAIL_OVERWRITE_FILES = [
    os.path.join(USU, "common/company_types/yMoG_USU_companies_rail_overwrite.txt"),
    os.path.join(USU, "common/company_types/yMoG_USU_panama_suez.txt"),
]
LLWA_EXT_FILE = os.path.join(ADDON_LLWA, "common/company_types/zz_llwa_companies_extensions.txt")


def build_companies():
    ext_text = V.read(LLWA_EXT_FILE)
    usu_text = "\n".join(V.read(p) for p in RAIL_OVERWRITE_FILES)

    blocks = []
    for k in COMPANIES_ROADWAY:
        # 1. addon-LLWA really does inject exactly LLWA_building_roadway here.
        _decl, ext_body = V.entry(ext_text, k, prefix="TRY_INJECT:")
        ext_list = V.sub(ext_body, "extension_building_types")
        assert ext_list is not None, f"{k}: addon-LLWA no longer injects extension_building_types"
        assert "LLWA_building_roadway" in ext_list, \
            f"{k}: addon-LLWA's inject changed, no longer LLWA_building_roadway: {ext_list}"

        # 2. grey_usu really does re-issue the whole record with its own list,
        #    and that list really does not carry LLWA_building_roadway (else
        #    there is nothing to restore -- fail loudly instead of duplicating).
        _decl, usu_body = V.entry(usu_text, k, prefix="TRY_REPLACE:")
        usu_ext = V.sub(usu_body, "extension_building_types")
        assert usu_ext is not None, f"{k}: grey_usu no longer has extension_building_types at all"
        assert "LLWA_building_roadway" not in usu_ext, \
            f"{k}: grey_usu's own body already carries LLWA_building_roadway -- nothing to restore"

        blocks.append(
            f"# {k} -- grey_usu's TRY_REPLACE: (own extension_building_types list, "
            f"no LLWA_building_roadway) silently drops addon-LLWA's earlier TRY_INJECT:.\n"
            f"# Re-issued additively: does not touch any of grey_usu's own list items.\n"
            f"TRY_INJECT:{k} = {{\n\textension_building_types = {{ LLWA_building_roadway }}\n}}"
        )

    write("common/company_types/zz_greys_llwa_companies.txt", "\n\n".join(blocks),
          "8 railway companies, addon-LLWA's extension_building_types restored",
          "### grey_usu's TRY_REPLACE: on each of these eight companies is a full body\n"
          "### written before addon-LLWA existed. Re-issuing addon-LLWA's own\n"
          "### TRY_INJECT: after the whole Grey's pack restores it additively -- grey_usu's\n"
          "### own extension_building_types items are untouched either way.\n"
          "### The other six railway companies that also collide with Victorian Century\n"
          "### (company_great_indian_railway, company_mantetsu, company_orient_express,\n"
          "### company_panama_company, company_prussian_state_railways,\n"
          "### company_suez_company) are NOT here -- see zz_gvc_companies.txt in\n"
          "### _greys/greys+vc done, which now also carries the LLWA layer for those six.")


# --------------------------------------------------------------------------
# 2. Three rail production methods -- building_job_attractiveness_mult lost
# --------------------------------------------------------------------------

RAIL_PMS = ["pm_no_passenger_trains", "pm_steel_passenger_carriages", "pm_wooden_passenger_carriages"]
RAIL_PM_FILE = os.path.join(USU, "common/production_methods/yMoG_USU_rail_other_pms.txt")


def build_rails():
    text = V.read(RAIL_PM_FILE)
    blocks = []
    for k in RAIL_PMS:
        _decl, body = V.entry(text, k, prefix="REPLACE_OR_CREATE:")
        bm_stmt = V.sub(body, "building_modifiers")
        assert bm_stmt is not None, f"{k}: grey_usu no longer has building_modifiers"
        bm_inner = bm_stmt[bm_stmt.index("{") + 1:-1]
        assert V.sub(bm_inner, "unscaled") is None, \
            f"{k}: grey_usu already has an unscaled sub-block -- check by hand, do not blindly append"

        new_bm_inner = bm_inner.rstrip() + "\n\tunscaled = {\n\t\tbuilding_job_attractiveness_mult = 2\n\t}\n"
        new_bm = "{" + new_bm_inner + "}"
        new_body = V.replace_sub(body, "building_modifiers", new_bm)

        blocks.append(
            f"# {k} -- grey_usu's REPLACE_OR_CREATE:, own numbers kept verbatim,\n"
            f"# only building_modifiers.unscaled.building_job_attractiveness_mult = 2 restored\n"
            f"# (originally VC's; already restored against LLWA's own body in llwa+vc done --\n"
            f"# same field, same value, this time against grey_usu's later body).\n"
            f"REPLACE_OR_CREATE:{k} = {{{new_body}}}"
        )

    write("common/production_methods/zz_greys_llwa_rails.txt", "\n\n".join(blocks),
          "3 rail production methods, building_job_attractiveness_mult restored",
          "### grey_usu's REPLACE_OR_CREATE: on these three keeps its own numbers on every\n"
          "### field it touches -- this restores only the one field it never had:\n"
          "### building_modifiers.unscaled.building_job_attractiveness_mult = 2, originally\n"
          "### VC's, silently dropped the same way on every full-body rewrite since.\n"
          "### The other seven rail production methods are NOT here on purpose: grey_usu has\n"
          "### its own progressively-scaled state_market_access_price_impact design on all\n"
          "### seven (0.02..0.05) -- a genuine numeric dispute, not a silent loss. See the\n"
          "### plan, GR.16.")


def self_check() -> int:
    problems = 0
    for rel in sorted(WRITTEN):
        pass
    n_files = 0
    n_keys = 0
    for dp, _dn, fs in os.walk(OUT):
        for fn in sorted(fs):
            if not fn.endswith(".txt"):
                continue
            p = os.path.join(dp, fn)
            text = V.read(p)
            n_files += 1
            keys = V.sub_names(text) if False else None
            # top-level key count: count top-level '<PREFIX>:name = {' occurrences
            import re as _re
            n_keys += len(_re.findall(r'(?m)^(?:[A-Z_]+:)?[A-Za-z0-9_]+\s*=\s*\{', text))
            if V.brace_balance(text) != 0:
                print(f"  PROBLEM: {p}: brace imbalance"); problems += 1
            with open(p, 'rb') as f:
                raw = f.read()
            has_bom = raw[:3] == b'\xef\xbb\xbf'
            non_ascii = any(ord(c) > 127 for line in text.split('\n') for c in line.split('#')[0])
            if non_ascii and not has_bom:
                print(f"  PROBLEM: {p}: has non-ASCII but no BOM"); problems += 1
            if re.search(r'\b([A-Z_]+):\1:', text):
                print(f"  PROBLEM: {p}: doubled prefix"); problems += 1
            if re.search(r'\b(\w+)\s*=\s*\1\s*=\s*\{', text):
                print(f"  PROBLEM: {p}: doubled field name (a = a = {{)"); problems += 1
    print(f"self-check: {n_files} files, {n_keys} top-level keys, {problems} problems")
    return problems


def main() -> int:
    global CHECK_ONLY
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    CHECK_ONLY = args.check

    steps = (("companies", build_companies), ("rails", build_rails))
    for name, fn in steps:
        print(f"-- {name}")
        fn()

    if CHECK_ONLY:
        return 1 if WRITTEN.get("__drift__") else 0
    return self_check()


if __name__ == "__main__":
    sys.exit(main())
