#!/usr/bin/env python3
"""
EF.48, В2.1 (decided 2.10): trade reserve currency as a real flow.

The trade reserve currency as a real flow (E&F's trade_balance itself is edited in the fork's E&F file by hand).

Generated:
  * zz_ef_fx_liab: the country's currency held by other CBs (its debt abroad), for the log and M3.
The monthly trade-reserve step zz_ef_rc_step (its call was commented out) is in the fork's
_archive/ef_reserve_trade_step/ (ФК2, 6.10).

Output (fork «E&F: Ledgerdemain», via ld_gen, by entry keys):
  common/script_values/ld_reserve_trade_values.txt
Reads the list of currencies from ld_curdata (the fork's currency laws).

Usage:
    python3 tools/regen_ef_reserve_trade.py [--check]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ld_curdata  # noqa: E402
import ld_gen  # noqa: E402

OUT_SV = "common/script_values/ld_reserve_trade_values.txt"

HEAD = ("# GENERATED by tools/regen_ef_reserve_trade.py -- do not edit by hand.\n"
        "# trade reserve currency as a flow -- see the generator's docstring.\n")



def currencies():
    return ld_curdata.currencies()


def chain(cur, body):
    """if / else_if over the scope country's currency (var:zz_ef_cur, its currency law); body(c) is the branch's effect."""
    out = []
    for i, c in enumerate(cur):
        kw = "if" if i == 0 else "else_if"
        out.append(f"\t{kw} = {{ limit = {{ var:zz_ef_cur ?= flag:{c} }} {body(c)} }}\n")
    return "".join(out)


VALUES = ""  # the EFX fields zz_ef_v_rc_* -- nothing set their variables (fork _archive/ld_dead_readers/, 8.10)


def values(cur):
    out = [HEAD, VALUES]
    out.append("# The scope country's currency held by the other countries' CBs (capital CB states), in its own\n"
               "# money: its debt abroad (В2.1). Countries on the same currency (var:zz_ef_cur) are not foreigners here.\n"
               "zz_ef_fx_liab = {\n\tvalue = 0\n")
    out.append(chain(cur, lambda c: f"every_country = {{ limit = {{ NOT = {{ this = root }} NOT = {{ var:zz_ef_cur ?= flag:{c} }} "
                                    f"has_modifier = has_central_bank }} capital = {{ if = {{ limit = {{ has_variable = stockpiling_{c}_state_1 }} "
                                    f"add = {{ value = var:stockpiling_{c}_state_1 min = 0 }} }} }} }}"))
    out.append("\tmin = 0\n}\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.parse_args()
    cur = currencies()
    ld_gen.emit(OUT_SV, values(cur))
    ld_gen.report("regen_ef_reserve_trade")


if __name__ == "__main__":
    main()
